### ISSUE TITLE
Un lien direct vers un récit fait sauter la vidéo 

### ISSUE THREAD

**Issue by gheleguen** [l-atelier-des-chercheurs/dodoc#1001]
Bonjour,
J’ai réalisé un récit sur mon dodoc, et j’aimerai envoyer un lien direct vers le récit et non vers le projet. J’ai trouvé dans les « options » un outil pour générer un lien direct.

Cependant mon récit contient une vidéo, qui n’apparait pas (chrome et firefox) avec le lien direct : [Documentator](https://dodoc.guillaumeleguen.xyz/+ateliers-collectifs/cartographie-participative-des-mobilites/publications/a-sotteville-les-rouen?display=section)

Comment faire ?

Guillaume

**Comment by Spiderwan01** [comment]
Salut Guillaume,
 bein moi sur firefox, je la vois bien ta vidéo ?!
tu as des photos un peu lourde je crois sur le carroussel, certaines 4 Go.
mais sur chrome la vidéo a aussi fini par se déclencher après un petit moment.

ps  : chouette ce projet !!

**Comment by gheleguen** [comment]
Salut @Spiderwan01 !
Oui on a traficoté un truc. En clair j'ai supprimé la vidéo et je l'ai remise et là comme par magie, elle est revenue : https://forum.latelier-des-chercheurs.fr/t/un-lien-direct-vers-un-recit-fait-sauter-la-video/553/7
J'avais compris que dodoc compressait les fichiers et images ? 
A++

**Comment by Spiderwan01** [comment]
Et bien tu peux après  avoir déposé  une image, l’ouvrir et accéder à
l’option d’optimisation qui va la réduit si nécessaire.

**Comment by gheleguen** [comment]
Ohh super ! Je ne savais pas ! 
Comment tu as eu l'information de la taille de l'image ?

**Comment by Spiderwan01** [comment]
J’ai fait la manipulation d’optimisation puis observé les méta-données,
qui montrent bien comment l’optimisation à influer sur le format

**Comment by Spiderwan01** [comment]
![01 (1)](https://github.com/user-attachments/assets/f00e4ccf-f812-4d6e-9247-6854faced54b)
![01 (2)](https://github.com/user-attachments/assets/579b952e-ab51-4411-ba79-37f690438cc9)

**Comment by gheleguen** [comment]
Ahhh mais oui ! Super cet outil interne de réduction des images ! Merci @Spiderwan01

**Comment by jubonhomme** [comment]
Non seulement ça réduit si tu le souhaites mais ça réutilise surtout un format standard plus lisible par les navigateurs.
Par exemple on avait pas mal de soucis avec des imports de photos depuis des iphone ou ipad en HEIC... on les passent maintenant à la moulinette et hop ça ressort en jpeg. 
Idem pour les fichiers vidéos ou sons avec des codecs qui ne passent pas bien sur un navigateur web... on peut presque tout passer en format standard par ce bouton "convertir" en plus de réduire le poids.

**Comment by Spiderwan01** [comment]
Yes je pense

Le lun. 16 déc. 2024, 13:10, Louis Eveillard ***@***.***> a
écrit :
