### ISSUE TITLE
Grille capture

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1002]
Quand on active la grille on a la possibilité de choisir différents modes (moitiés / tiers / quarts.

![image](https://github.com/user-attachments/assets/a8d78853-ff0a-4f21-8691-6fd8507895ee)

Est-ce qu'on pourrait avoir ce choix dans une fenêtre modale pour ne pas laisser afficher toujours les trois options sur l'écran ?
On aurait un bouton pour activer ou désactiver la grille et un petit onglet pour choisir le mode dans une modale. Si on active juste la grille le bouton se colore en vert et reprends le dernier mode sélectionné mais n'affiche pas forcément les choix en continu

**Comment by louis-ev** [comment]
Ok !
Le soucis avec une modal, c'est qu'on ne voit pas directement les lignes apparaitre sur l'image – pas pratique pour la découvrabilité. Je propose plutôt un sélecteur : 

<img width="266" alt="image" src="https://github.com/user-attachments/assets/5f73760b-9936-4828-b467-853999275d73">

<img width="254" alt="image" src="https://github.com/user-attachments/assets/6228d438-8be7-4c53-95c3-9b124a401c42">

Qu'en penses-tu ?

**Comment by louis-ev** [comment]
(-- grille --  = off, mais ça faisait bizarre d'afficher "aucune grille" la première fois qu'on ouvre la capture, ça me semblait assez clair comme ça)

**Comment by jubonhomme** [comment]
Ok pour moi 

Je ferme ici
