### ISSUE TITLE
Localisation capture

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1003]
Si on active la localisation dans la capture on ne peut plus la désactiver... ou alors je n'ai pas trouvé (à part supprimer la localisation sur la carte mais le bouton reste en vert et c'est trompeur)

**Comment by louis-ev** [comment]
Résolu. À retester :)

**Comment by jubonhomme** [comment]
Je viens de faire un test après mise à jour.

On peut maintenant enlever la localisation dans la capture mais uniquement en supprimant la localisation.
On ne peut pas activer ou désactiver la localisation sans à chaque fois supprimer et redéfinir la localisation. Il faudrait que ça conserve l'emplacement et juste arrêter d'ajouter la métadonnée dans la capture si on désactive.

**Comment by louis-ev** [comment]
Ha ! est-ce que je peux te demander pourquoi tu voudrais conserver la localisation ? j'ai du mal à imaginer un scénario ?

**Comment by jubonhomme** [comment]
On imagine que si on active sur appareil mobile c'est avec le GPS en priorité et si on l'active sur un PC fixe on ne la change pas tous les jours.
On ferme donc ici et on voit à l'usage si il y a des ajustements à faire
