### ISSUE TITLE
Fonds Carto et Photo IGN ne fonctionnent plus

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1007]
Je viens de voir que les fonds carto et photo de l'IGN sont HS dans les publications carto.

On dirait que ça ne fait plus le lien vers les tuiles.

**Comment by louis-ev** [comment]
Visiblement il y a eu migration : https://geoservices.ign.fr/bascule-vers-la-geoplateforme
J'ai pas le temps de creuser mais possible qu'il s'agisse juste de trouver la bonne URL, qui remplace `https://wxs.ign.fr/decouverte/geoportail/wmts` ici : https://github.com/l-atelier-des-chercheurs/dodoc/blob/2ac2857ba470715dc9ad230e6e55a7e8b6fd843a/client/src/adc-core/fields/DisplayOnMap.vue#L1032

**Comment by jubonhomme** [comment]
De ce que j'ai vu c'est effectivement une bascule de géoservices de l'IGN vers géoplateforme qui par défaut est en opensource.
Voir les serveurs de diffusions de tuiles ici :
https://geoservices.ign.fr/services-geoplateforme-diffusion
