### ISSUE TITLE
Pouvoir réorganiser l'ordre des images dans un carrousel 

### ISSUE THREAD

**Issue by Pixflowave** [l-atelier-des-chercheurs/dodoc#1008]
Peut-on avoir la possibilité de modifier l'ordre des images d'un carrousel ?

**Comment by jubonhomme** [comment]
Il y a une astuce qui permet déjà de réorganiser les images dans un carrousel ou dans une mosaïque.
![image](https://github.com/user-attachments/assets/87f028e7-90e9-4038-8d21-c31368d7defc)



En basculant sur un affichage "Liste de fichiers" il y a une petite main devant chaque ligne qui permet de réorganiser les fichiers par un glisser/déposer.
![image](https://github.com/user-attachments/assets/66e86224-a182-4ce4-af0e-601a232f8ae5)

On ajuste l'ordre souhaité et on repasse à l'affichage Carrousel ou Mosaïque...
Magique non ?
![image](https://github.com/user-attachments/assets/2f7f8cbf-3b7c-4697-981e-ffcfabb4b538)
![image](https://github.com/user-attachments/assets/c05f1b11-13c6-46f7-a790-fc03a3fd491b)

Proposition pour rendre ça plus évident : 
Il faudrait juste ajouter un bouton "changer l'ordre"  dans le menu des options qui basculerait l'affichage dans une vue identique à la liste de fichiers et qui permettrait de changer l'ordre (comme les chapitres du récit) et quand on validerait ça retournerait à l'affichage sélectionné mosaïque ou carrousel.

**Comment by Pixflowave** [comment]
La liste de fichiers ne permet pas de pouvoir se repérer facilement dans un carrousel de plusieurs images proches en couleur et sujet. (vignette trop petite)

**Comment by louis-ev** [comment]
Je viens d'implémenter une solution, à priori le meilleur des deux mondes : 

- un ptit bouton en haut à droite, qui reprends le picto pour réordonner les chapitres
<img width="329" alt="image" src="https://github.com/user-attachments/assets/e7ca0abd-346d-4a8f-aebf-0cb0ae8f3c21">

- qui ouvre une modale qui utilise le champ fichiers
<img width="553" alt="image" src="https://github.com/user-attachments/assets/bc44a68e-1589-4c84-82ac-712329a2a546">

Avec des aperçus un chouia plus grand.
Possibilité de supprimer/ajouter des médias ici.

**Comment by louis-ev** [comment]
On pourrait imaginer qu'on puisse ouvrir individuellement en grand les médias (ici comme sur le menu fichiers source) pour pouvoir mieux les distinguer – t'en penses quoi @Pixflowave ?

**Comment by Pixflowave** [comment]
un mode grand serait idéal ou mosaïque comme sur la recette image par image de la V9

**Comment by louis-ev** [comment]
<img width="564" alt="image" src="https://github.com/user-attachments/assets/8ed94254-749f-4dcf-aa55-b6ef79798fb7">

T'en penses quoi ?

**Comment by Pixflowave** [comment]
> <img alt="image" width="564" src="https://private-user-images.githubusercontent.com/1948417/394014363-8ed94254-749f-4dcf-aa55-b6ef79798fb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NzM1OTEsIm5iZiI6MTczMzg3MzI5MSwicGF0aCI6Ii8xOTQ4NDE3LzM5NDAxNDM2My04ZWQ5NDI1NC03NDlmLTRkY2YtYWE1NS1iNmVmNzk3OThmYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMjMyODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQ5NzlmNjI4M2M2NGMyOWViOThiNjBjNGM0Zjg1ZWI5NDI3Yzk0NWY4YWZiNzAyYjE5MzgwNjdmMjFmNDZjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NDsrDD6ant2KdqTKte0RrjxlO0YvQplR-BGa7rnT96w">
> T'en penses quoi ?

en mode aperçu puis on referme pour modifier l'ordre ?

**Comment by louis-ev** [comment]
> Est-ce qu'il serait possible de reprendre l'idée de la modale de collecter ? En changeant la couleur jaune pour ne pas confondre mais avoir les médias alignés à l'horizontale avec la possibilité de choisir l'affichage 

Je suis pas certain, ça me semble important que ça ressemble à une liste de fichiers et que ça se démarque des autres modules. Vous avez testé en l'état ? ça remplit bien le cahier des charges du premier post je trouve

**Comment by jubonhomme** [comment]
ça marche effectivement très bien comme ça
Par contre il n'y a pas de bouton de validation ça se fait tout seul mais on a un doute avant de cliquer à l'extérieur pour fermer cette modale
Ce serait pas mal d'avoir une confirmation qui ferme la fenêtre je pense

**Comment by louis-ev** [comment]
<img width="509" alt="image" src="https://github.com/user-attachments/assets/964ba0df-eec7-4a58-855d-675021c3a0af">

Comme ça ? Bien qu'en vrai, il ne fasse que fermer la fenêtre – je n'ai pas la possibilité d'en faire un élément "annulable", tout est enregistré en live.

**Comment by jubonhomme** [comment]
Oui je pense que c'est mieux même si le bouton n'est là que pour rassurer en vrai
Mais j'avoue que si on déplace les médias pour tout réorganiser on cherche quand même un bouton pour sortir en étant certain que le choix soit bien conservé.

**Comment by jubonhomme** [comment]
Tout semble en place et fonctionnel de mon côté

A fermer ?
