### ISSUE TITLE
Sélection de la caméra arrière par défaut à la place de la caméra frontale sur appareil mobile

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1009]
Est-il possible de lancer la caméra arrière d'un appareil mobile (tablette ou smartphone) à la place de la caméra avant ?
C'est souvent la caméra qu'on utilise par défaut pour les captures dans dodoc et ça éviterait de passer par les paramètres. 
Il y aurait toujours la possibilité de passer sur la caméra avant mais comme choix secondaire.

**Comment by louis-ev** [comment]
Et par rapport à une webcam ? Est-ce qu'on fait un ordre de priorité ?

**Comment by jubonhomme** [comment]
Pourquoi pas une caméra USB en premier choix si disponible.

Après sur un ordinateur c'est assez facile de modifier la caméra, sur un téléphone avec un affichage réduit c'est moins évident
