### ISSUE TITLE
léger bug aléatoire affichage carrouselle en mode carto

### ISSUE THREAD

**Issue by Spiderwan01** [l-atelier-des-chercheurs/dodoc#1012]
En mode cartographie, sur un carrousel de photos, j’ai remarqué un problème d’affiche des images si on joue avec le volet qui permet de donner plus de place à la carte ou au contenu. Mais cela est aléatoire.
![image](https://github.com/user-attachments/assets/6df2b7f9-ce82-421d-a887-d5bf1825072d)

**Comment by louis-ev** [comment]
Résolu, dispo bientôt sur ton instance :)

**Comment by Spiderwan01** [comment]
Merci !
