### ISSUE TITLE
Dupliquer des chapitres

### ISSUE THREAD

**Issue by Spiderwan01** [l-atelier-des-chercheurs/dodoc#1013]
Hello, petite réflexion en pleine réalisation de contenu avec ma classe.

Nous avions déjà vu que traiter plusieurs médias en même temps était délicat. ( Les copier coller ensemble par exemple...) 

Mais peut imaginer pouvoir dans un mode récit, dupliquer un chapitre/onglet, afin de répercuter un gabarit de présentation de contenu, qui est ensuite reproduit sur d'autres onglets, sans avoir à tout refaire.

Super utile pour des projets de publication de projets de classe qui s'organise autour d'un gabarit commun initialement réalisé en classe et faisant parti d'une même publication.

**Comment by louis-ev** [comment]
Hello !
Si je reformule : 
- dans une même publication, pouvoir dupliquer l'ensemble d'un chapitre – ce qui créerait un nouveau chapitre juste après celui dupliqué, qui contiendrait tous les contenus en double.
- le nouveau chapitre s'appelle "copie de Nom du chapitre dupliqué"

C'est bien ça ?

**Comment by Spiderwan01** [comment]
exactement ! 
et cela résonne avec l'issus sur l'histoire des récits carto, avec une carte qui peut représentés des contenus non pas que du chapitre en cours, mais de plusieurs car les médias carto-localisés, ne sont pas intégrés à la suite sur le même chapitre mais répartis dans des chapitres distincts, préalablement préparés avec un gabarit vierge grâce à la copie de chapitre ....

**Comment by jubonhomme** [comment]
Comme le dupliquer une page dans la publication page à page, ça permet aussi de faire des modèles rapidement pour chaque groupe

**Comment by louis-ev** [comment]
En place ! à tester, ça a demandé pas mal de prise de tête alors je veux bien des tests poussés (a base d'ajout de média/suppression/ajout de texte/déplacement/duplication de la section, suppression de son contenu, vérification que tout est resté en place sur l'original, notamment !).

J'en ai profité pour améliorer l'affichage du haut des chapitres : 

<img width="690" alt="image" src="https://github.com/user-attachments/assets/0f89b9be-42c4-4250-9881-71ab815e42e5" />

<img width="194" alt="image" src="https://github.com/user-attachments/assets/b7fa9d1e-e60c-4d11-81ab-b501b8509077" />

J'espère que c'est plus lisible comme ça !

**Comment by jubonhomme** [comment]
Un petit détail que je viens de voir sur les boutons 
Quand on prévisualise le récit ou que l'on partage le récit il reste le bouton avec l'oeil pour afficher / masquer le titre qui reste présent.

**Comment by louis-ev** [comment]
Je pensais le déplacer vers le menu OPTIONS, ça a du sens ?

**Comment by jubonhomme** [comment]
Pas évident à comprendre si c'est dans les options on pourrait comprendre que ça masque le chapitre en entier comme dupliquer ou supprimer

**Comment by Spiderwan01** [comment]
Sur l'espace test, ça marche bien.
Lorsque tu pourras actualiser cette option sur mon instance de classe, je ferai des test avec des contenus plus charger pour voir si cela fonctionne bien. Merci en tout cas !!
