### ISSUE TITLE
Lecture en boucle "animation"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1015]
J'ajoute une dernière demande sur le Stop motion qui est déjà parfait ;)

La possibilité de lire en boucle une animation

Une fois qu'on est dans le mode capture et qu'on prévisualise l'animation on pourrait ajouter un mode pour lire en boucle l'animation ?
![image](https://github.com/user-attachments/assets/80399709-c481-4eaa-b950-a6b53a23d26e)

Comme ici :
![image](https://github.com/user-attachments/assets/4b391a92-a452-4765-82e8-5731d806dd60)

**Comment by louis-ev** [comment]
Ok ! mais même si on ne peut pas encoder dans le fichier vidéo résultat qu'il doit lire en boucle ?
Tu peux détailler ton utilisation ?

**Comment by jubonhomme** [comment]
Oui, je trouve que c'est deux choses différentes même si c'est lié.

Quand on fait une séquence de stop motion avec quelques dizaines de photos on peut déjà obtenir une boucle mais à la lecture ça ne dure que quelques secondes. Donc on clique et on voit 4 ou 5 secondes et ça stop.
L'idée est de pouvoir prévisualiser avec une lecture en boucle pour revoir plusieurs fois la séquence et vérifier un certain nombre de point (éclairage / main qui traine...) sans forcément enregistrer en boucle.

Pour l'enregistrement ça pourrait aussi être utile sous forme de gif (#249 )

Par exemple Victor Haegelin travaille beaucoup en stop motion à base de boucle
https://www.tiktok.com/@patagraph/video/7330261762744388897

**Comment by louis-ev** [comment]
Ok ! je comprends mieux.
Par contre je le mettrai plutôt à côté du réglage de la vitesse de lecture ? Une case à cocher "Lire en boucle" ? ça me semble être un réglage, qui perdure sur la page de visualisation qui s'affiche après.

<img width="335" alt="image" src="https://github.com/user-attachments/assets/6c6aa139-ae2a-47e6-ba71-55d220b15824">

Non ?
bon par contre on a pas une place illimité, ça risque de déplacer le bbouton de capture vers la gauche.

**Comment by louis-ev** [comment]
Tu as raison oui, absolument.
Et du coup, à tester : 
<img width="494" alt="image" src="https://github.com/user-attachments/assets/5e78e65b-b281-4a13-8698-f91d87fe40eb">

Et proposition graphique pour l'export GIF / en boucle, sur la page de prévisualisation qui suit : 
<img width="350" alt="image" src="https://github.com/user-attachments/assets/ba64abf1-dc1e-4fbe-a152-0370d56fc0f3">

**Comment by louis-ev** [comment]
En fait je me demande si ça a de l'intérêt un gif pas bouclé… Ok pour le faire d'office ? ça simplifie l'interface

**Comment by jubonhomme** [comment]
Oui pour si boucle => format gif

**Comment by louis-ev** [comment]
En place ! je ferme, si soucis tu peux rouvrir bien sur.
