### ISSUE TITLE
les contributeurs d'un projet peuvent modifier les épingles de publication

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#1016]

**Comment by louis-ev** [comment]
@jubonhomme je n'arrive pas à reproduire le bug, tu peux le reproduire sur test11 ?

Se peut-il que tu sois référent d'un espace, ce qui te donne tous les droits sur tous les projets qu'il contient ? Faut-il changer cette logique, ou l'indiquer dans l'interface ?

**Comment by jubonhomme** [comment]
Je viens de refaire un test ici
https://test11.dodoc.fr/+stop-motion/tutoriel-stop-motion?projectpanes=%5B%7B%22type%22%3A%22publish%22,%22size%22%3A100%7D%5D

J'ai ouvert les contributions à tous et je me déconnecte.
En fait je n'arrive effectivement pas à épingler ou changer l'ordre, ce qui m'a trompé c'est qu'on voit la vue comme si on le pouvait. On peut rafraichir la vignette mais les boutons épingles et flèches sont bien inactifs même si présents.
![image](https://github.com/user-attachments/assets/3e5f471a-815c-4e48-8211-df44e31a96a6)

**Comment by louis-ev** [comment]
Oui ok, c'est plus clair ! je regarde.

Autre chose : si notre compte est Référent d'un espace, ou que tout ça est réglé sur Tout le monde, on peut tout faire quels que soient les permissions du projet. Est-ce qu'on change ça ? Ou on l'indique qqpart ?

**Comment by louis-ev** [comment]
> En fait je n'arrive effectivement pas à épingler ou changer l'ordre

Je crois que c'est lié à un bug au niveau de la déconnexion d'un compte : le token côté client n'est pas effacé correctement, donc dodoc client croit qu'on a toujours les droits du compte avec lequel on était login, mais dodoc server a bien effacé le token. Tu pourrais enquêter de ton côté pour confirmer ma théorie ? te délogger d'un compte admin, voir si l'interface suggère que tu peux faire des choses que tu ne devrais pas pouvoir faire en étant anonyme ?

**Comment by jubonhomme** [comment]
Je viens tout juste de mettre à jour avec tes dernières modifications et ça fait pareil sur ma machine.
Je suis connecté en référent j'ouvre à tous les contributions. Je me déconnecte, je vois toujours les épingles et flèches mais non autorisé

**Comment by louis-ev** [comment]
Quand tu te déconnectes, tu vois bien la page se recharger ?
Et si tu recharges manuellement (ctrl + r), les icones disparaissent ?

**Comment by jubonhomme** [comment]
Même si je me déconnecte et ferme dodoc et quand je le relance et que je suis pas connecté je vois quand même les boutons
