### ISSUE TITLE
revoir le menu ajuster

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#1017]
<img width="246" alt="image" src="https://github.com/user-attachments/assets/cac265c5-0f9a-4b62-9b75-4c41260b61fa">

- le renommer "retoucher" ?
- pouvoir dessiner les zones ou s'applique une retouche, comme le flou ou la saturation (logique de masque), ou appliquer à toute l'image. Un mode "simplifié", un mode "avancé" ?

**Comment by jubonhomme** [comment]
Ok pour retoucher

Est-ce qu'on pourrait en profiter pour ajouter un bouton pour "réinitialiser les paramètres" aussi sur cette fenêtre ?
 Comme celui pour "réinitialiser le cadrage"

Sur mon poste j'ai shotwell qui propose "Ajuster"
![image](https://github.com/user-attachments/assets/bc1f7759-58aa-41e4-9f4a-2a666d215cd3)

Et simplement annuler / Réinitialiser / Valider
![image](https://github.com/user-attachments/assets/2bed9002-1899-4026-ad96-1402101d4b49)

**Comment by jubonhomme** [comment]
Je viens de tester sur mon téléphone pour voir sur petit écran et la différence entre recadrer et ajuster est assez importante.
Le bandeau de bouton en haut pour recadrer permet d'avoir une image assez grande même sur un téléphone. Par contre pour Ajuster les curseurs dans le volet de gauche réduisent l'affichage de l'image. Est-ce qu'il y a un moyen de la faire passer en dessous ?
![image](https://github.com/user-attachments/assets/3d551596-36d1-4035-9269-590fa572fea3)
![image](https://github.com/user-attachments/assets/9a65d7af-385e-495f-8b57-f3d7a20b5c69)

**Comment by jubonhomme** [comment]
Sur cet écran les titres et boutons prennent beaucoup de place et coupent l'affichage de l'image.
Est-ce qu'il y a moyen de gagner un peu de place ?
![image](https://github.com/user-attachments/assets/5ce2a9e0-8fe2-4c99-b449-db6f304ae4f6)

**Comment by JeFabrique-MaterielPeda** [comment]
Désolée d'arriver après la bataille mais Retoucher n'est pas factuellement correct et c'est bien ajuster qui désigne l'opération. Retoucher implique une action localisée à certains endroits choisis du média (doit à la main avec un cache ou un pinceau, soit par l'IA), ce que cette fonction ne permet pas encore. Ajuster désigne des modifications sur l'ensemble de l'image.

**Comment by louis-ev** [comment]
> Désolée d'arriver après la bataille mais Retoucher n'est pas factuellement correct […]

Absolument ! Mais on tends vers ça :)
Après, on pourrait dissocier Recadrer de Retoucher/ajuster, mais ça veut dire que c'est un peu laborieux de reprendre un média (il faut l'écraser ou en enregistrer un autre, puis rouvrir le menu, et on perds un peu de qualité avec ce double enregistrement).

**Comment by louis-ev** [comment]
Amélioration de la fenêtre recadré en petite taille, avec un minimum de hauteur de 240px au lieu de 100px : 
<img width="377" alt="image" src="https://github.com/user-attachments/assets/c12893cd-830d-4096-92e8-61293ccb2891">
<img width="382" alt="image" src="https://github.com/user-attachments/assets/386cd6f4-2120-4cc0-aa6d-b3cf0b236e6b">
