### ISSUE TITLE
reprise choix résolution caméra

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#1019]
<img width="269" alt="image" src="https://github.com/user-attachments/assets/066860a5-1fb7-400e-9877-fc4804c5fd59">

<img width="280" alt="image" src="https://github.com/user-attachments/assets/8de10575-560e-474c-a209-b420ad7a9e15">

J'ai essayé de simplifier un peu, typo plus grande, ajout de "pixels" quand on choisir une résolution personnalisé.
Mais je pense que les choix sont pas clairs, trop complexes.
Dans le menu Optimiser, j'indique juste Qualité : Maximale, Élevée, Moyenne, Basse, Personnalisée
Peut-être repartir là-dessus, et indiquer en sélectionnant la résolution choisie ? Maximale = 4K (3840x2160 pixels), Élevée = Full HD (1920x1080 pixels), etc.

**Comment by louis-ev** [comment]
Proposition : 

<img width="277" alt="image" src="https://github.com/user-attachments/assets/ee55087e-2c85-4608-b213-9cb70c644357">

**Comment by louis-ev** [comment]
Le terme Résolutions est-il le plus explicite ? D'un point de vue technique/précision, oui, mais peut-être qu'il y a mieux ?

**Comment by JeFabrique-MaterielPeda** [comment]
Pour le coup maintenant je trouve ça trop simplifié. La plupart des gens ne comprennent pas à quoi correspondent les pixels. Je trouvais sympa que tu puisse mettre la correspondance 4k, HD... et le ratio. Tu pourrais peut-être ajouter ces infos entre parenthèses après ta nouvelle formulation ?

**Comment by JeFabrique-MaterielPeda** [comment]
> mieux ?

Pour moi c'est résolution au singulier. Puisqu'il n'y qu'une résolution par image.

**Comment by louis-ev** [comment]
> Pour moi c'est résolution au singulier. Puisqu'il n'y qu'une résolution par image.

Ou "Résolution de l’image" ? vu que le média existe pas encore ?

> Peut-être préciser : Résolution du Media ?

Oui ça me fait bizarre aussi… Résolution au singulier, ça marche.

> Je trouvais sympa que tu puisse mettre la correspondance 4k, HD... et le ratio. Tu pourrais peut-être ajouter ces infos entre parenthèses après ta nouvelle formulation ?

Mon objectif était surtout d'alléger, pas d'enlever de l'information ! Une autre approche :
<img width="274" alt="image" src="https://github.com/user-attachments/assets/25fc85b0-f5f2-4df2-94bf-88bd40d2dd8a">

<img width="273" alt="image" src="https://github.com/user-attachments/assets/0345c5ba-6c4b-4678-ae7a-69d960ad7900">

Qu'en pensez-vous ?

**Comment by louis-ev** [comment]
La résolution > Personnalisé**e** ?
