### ISSUE TITLE
Prévisualisation image  dans vignette projet

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1023]
Quand on sélectionne une image pour la vignette du projet, elle est affichée en format carré comme pour l'espace, ensuite elle est à la bonne dimension dans la vignette du projet en format paysage.
Est-ce qu'il est possible d'avoir la prévisualisation au bon format avant de l'ajouter ?

**Comment by louis-ev** [comment]
On pourrait réutiliser vue-advanced-cropper, pour pouvoir faire ça bien !

**Comment by jubonhomme** [comment]
Je viens de tester.
Deux petits détails : 
si je clique sur réinitialiser le cadrage ça déverrouille le ratio qui semble avoir été ajusté pour que l'image corresponde à la taille de la vignette
Une fois qu'on sélectionne l'image avec le bon cadrage pour la vignette projet, elle s'affiche encore en carré pour l'aperçu avant de se mettre en vignette paysage dans le projet. Est-ce possible de l'avoir directement l'aperçu en format paysage et non carré ?

**Comment by jubonhomme** [comment]
Mais sinon le reste est Top !

**Comment by louis-ev** [comment]
Good catch! Résolu :)

**Comment by jubonhomme** [comment]
Je ferme aussi !
