### ISSUE TITLE
Ajout visuel accueil

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1024]
Quand on essaie d'ajouter la première fois une image en page d'accueil et qu'on a rien importé, il n'y a pas de message d'indication. On voit juste le texte "visuel page d'accueil" mais rien d'autre.Il faut refermer et importer une image avant. 
C'est logique quand on le sait mais pas si évident si on découvre.
Ce serait utile d'avoir un message ou un bouton pour importer une image comme il y a dans les vignettes projets ou espaces.
On ne la change pas toutes les 5 min mais qd on n'a jamais vu la console admin "logo et images" on cherche un peu.

![image](https://github.com/user-attachments/assets/49dc33f5-3254-472f-bd0f-46c59f0b477a)

Idem pour le petit clic à faire en bas de la fenêtre pour rafraîchir : j'ai redémarré plusieurs fois dodoc avant de voir qu'il y avait ce "bouton"
On pourrait le rendre plus visible

![image](https://github.com/user-attachments/assets/98e18e1f-84a9-493b-8fb1-4a51ca13ff9c)

**Comment by louis-ev** [comment]
Je vois oui, tu as raison. J'aimais bien l'idée que tous les réglages soient centralisés, mais je conçois que c'est pas le plus fluide/pratique. Je peux mettre des raccourcis.

En fait c'est pas "Rafraîchir la fenêtre pour appliquer" mais "Rafraîchir la fenêtre pour voir les changements"

**Comment by louis-ev** [comment]
À court terme : des crayons, que pour les admins d'instance, qui amènent directement sur le bon panneau dans les règlages d'admin : 
![Uploading image.png…]()

**Comment by jubonhomme** [comment]
Je vois bien l'idée de rassembler tous les paramétrages admin au même endroit. Ça me va parfaitement pour la gestion des accès / sécurité / stockage et le reste.
Par contre pour le visuel de la page d'accueil je trouve ça plus évident de le gérer comme on gère ensuite les espaces et les projets. 
J'installe dodoc, je m'identifie avec le compte admin par défaut et j'arrive sur la page d'accueil. Je clique sur le crayon et je modifie le bandeau, le titre de la plateforme... Je crée un premier espace (idem), je crée un projet (idem).
Pour les accès et le reste ça se passe dans la modale admin comme avec les modales pour gérer les espaces et les projets.

**Comment by jubonhomme** [comment]
Juste un détail encore :
Si on choisit un fond vert, on ne voit plus le crayon vert :D 
Est-ce que tu as un bouton crayon avec un détourage sous la main pour qu'on le voit dans tous les cas ?
Par exemple ici en bas à droite...
![image](https://github.com/user-attachments/assets/a9ea25ee-4c83-41cf-ae91-d379be7872b0)

**Comment by jubonhomme** [comment]
Tout y est !
Je ferme ici
