### ISSUE TITLE
bug blocs texte multiples ouverts - saisie qui bascule dans celui qui s'actualise

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1025]
Avec l'astuce de déplacer un bloc de texte dans un bloc média on peut avoir un texte sur plusieurs colonnes. En fait plusieurs blocs côte à côte.

Cas un peu extrême j'avoue mais c'est plus pour garder une trace du fonctionnement.

Si on a plusieurs blocs et que l'on saisi du texte dans le premier et que le deuxième s'actualise, la saisie bascule dans ce deuxième bloc. A chaque fois qu'un bloc s'actualise il prend la main sur la saisie qui bascule automatiquement dans ce bloc.

**Comment by louis-ev** [comment]
J'ai fais des petits tests et j'ai pas réussi à reproduire ce soucis (si je l'ai bien compris) : 
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/913ffcc4-f12e-412e-afc4-eff2c13450db">

Tu peux préciser ?

**Comment by jubonhomme** [comment]
Voici la démo en vidéo... c'est plus parlant même sans son 
https://test11.dodoc.fr/_previewmedia?path_to_meta=spaces/hello-test/projects/test-11/video-1733921434969-5ar.webm.meta.txt

**Comment by Spiderwan01** [comment]
c'est pas déjà quelque chose qui fait doublon avec le tableau ?

**Comment by louis-ev** [comment]
J'ai compris. C'est embêtant.
Si qqun modifie un bloc collaboratif qui est ouvert ailleurs, il est "focus" automatiquement lorsque la modif parvient aux utilisateurs. Pas gênant si plusieurs personnes le modifient en même temps, mais si un autre utilisateur fait autre chose sur la page en le laissant ouvert son curseur y reviendra direct.

**Comment by louis-ev** [comment]
J'ai trouvé le code que j'ai écrit qui déclenchait ça – il a des effets secondaires imprévues dans quill…
Bref, je corrige, merci pour l'aide pour identifier le soucis !
