### ISSUE TITLE
Bouton supprimer la page dans publication

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1028]
Quand on est dans une publication Récit le bouton avec la corbeille pour supprimer un chapitre affiche "supprimer le chapitre" au survol
![image](https://github.com/user-attachments/assets/fb826dcc-c719-4951-aaff-d9662d52e542)

Est ce qu'on pourrait faire la même chose avec la corbeille dans le page à page et avoir "supprimer la page" au survol ?
Et avoir "Dupliquer la page" sur l'autre picto.
![image](https://github.com/user-attachments/assets/11fc3902-ea38-4849-9467-e7048b36111c)

**Comment by louis-ev** [comment]
Comme ça ? 
<img width="175" alt="image" src="https://github.com/user-attachments/assets/6f5a3938-6ef4-4a01-ba08-fa509364ad28">
<img width="194" alt="image" src="https://github.com/user-attachments/assets/2580377f-8e89-4f8a-b37c-46157a037dea">
<img width="214" alt="image" src="https://github.com/user-attachments/assets/d584a83d-75a4-410e-8f12-ad3adcb65a4f">

Y a un boulot à faire pour homogénéiser les codes graphiques partout, simplifier au max…
D'ailleurs à ce sujet, je remplacerai bien le bouton "options" par trois petits points, qui pourrait être la convention "plus d'options pour cet élément" partout :

<img width="277" alt="image" src="https://github.com/user-attachments/assets/d5dad6a1-54dc-4a6b-b377-01c42e1e635a">

<img width="274" alt="image" src="https://github.com/user-attachments/assets/49c38f73-f02a-45cf-afb1-2112d69e1261">
<img width="718" alt="image" src="https://github.com/user-attachments/assets/d16e9481-f20f-4679-a725-9f5173061550">

**Comment by jubonhomme** [comment]
Top pour les boutons dupliquer et supprimer

Pourquoi pas aussi un bouton "..." à la place du bouton "option" mais il faudrait le mettre en évidence avec un détourage ou quelque chose qui le rende bien visible.

**Comment by jubonhomme** [comment]
Tout y est !
Je ferme
