### ISSUE TITLE
redimensionner une image

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#1029]
Pour pouvoir plus précisément redimensionner une image, pouvoir choisir une résolution spécifique.
Question : est-ce qu'on peut indiquer une résolution exacte, ou uniquement une largeur ou une hauteur et la conversion se charge d'en déduire l'autre dimension de manière homothétique ? Parce que si on choisit précisément une résolution qui correspond pas au ratio, on étire l'image.

<img width="506" alt="image" src="https://github.com/user-attachments/assets/e8842f01-ae1c-4f63-9fa1-862eaea4a1bc">

**Comment by Pixflowave** [comment]
Hello, ça éviterait d'avoir à ajouter le bouton - petite chaine - qui permet de choisir, conserver ou non le ratio ?

**Comment by louis-ev** [comment]
Bonne idée ! À tester sur next :
<img width="338" alt="image" src="https://github.com/user-attachments/assets/5973ca8c-6091-40bf-87bb-3fc1b62762f7">

**Comment by louis-ev** [comment]
Effectivement, c'est clairement pas le plus utile mais il y a des cas de figure ou ça peut l'être (je pense). Donc autant avoir l'option :)
Coché par défaut, oui !

**Comment by louis-ev** [comment]
Je ferme
