### ISSUE TITLE
bug affichage référents contributeurs

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1036]
Sur la V11.1.10 

Si j'ouvre la fenêtre pour ajouter des référents ou contributeurs ça n'affiche plus ceux qui sont déjà dans la liste.
Si je modifie la liste et que j'enregistre, je re ouvre tout de suite ça affiche les noms.
Si j'enregistre et je ferme la fenêtre -> si je ré ouvre et modifie la liste  mais les noms n'y sont plus affichés

voir ici en vidéo
https://test11.dodoc.fr/_previewmedia?path_to_meta=spaces/hello-test/projects/test-11/video-1734561589189-2l7.webm.meta.txt

**Comment by louis-ev** [comment]
J'ai pas compris… ni dans la vidéo ni dans le texte…

**Comment by louis-ev** [comment]
Tu peux me faire des screenshots légendés plutôt ? Dans ta vidéo tout me semble normal…

**Comment by jubonhomme** [comment]
https://test11.dodoc.fr/+hello-test/test-referents-contributeurs?projectpanes=%5B%7B%22type%22%3A%22publish%22,%22size%22%3A100%7D%5D

https://test11.dodoc.fr/+hello-test/test-2-referents
[10:58](https://framateam.org/latelier-des-chercheurs/pl/pe1ahx3n9trjxn771y394hr9by)

Dans ces 2 projets... si tu ouvres "Plus d'informations" pour changer ajouter un nouveau référent ou contributeur la liste des contributeurs déjà ajouté est vide... on peut en ajouter et valider mais à chaque fois qu'on ouvre cette fenêtre c'est remis à zéro à l'ouverture. 
Le fonctionnement d'avant : on ouvre, on voit ceux qui y sont déjà et on peut en ajouter ou en enlever et on enregistre. Quand on ré ouvre la fenêtre on voit la liste de ceux qui y sont déjà

Fonctionnement actuel : A chaque fois qu'on ouvre la liste des personnes déjà référentes est toujours vide.

**Comment by jubonhomme** [comment]
Si je créé un projet je suis référent
![image](https://github.com/user-attachments/assets/143cc50b-347d-4434-84f1-4c73bb88de67)


Je clique sur le crayon pour en ajouter un autre et à l'ouverture je n'y suis plus comme référent, je peux me rajouter mais la liste est vide.
![image](https://github.com/user-attachments/assets/2467157f-97f2-4467-aa30-ed71f5af9369)

Alors qu'à l'ouverture AVANT on avait ça
![image](https://github.com/user-attachments/assets/50695484-e731-4220-87e2-0cfe1717aa8f)
Et on pouvait en ajouter ou supprimer et enregistrer.

Là si on ne se rajoute pas à chaque fois on perd la main dessus... et donc on est bloqué
