### ISSUE TITLE
Filtre "Mes projets"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#1038]
Filtre  "Mes projets" 

![image](https://github.com/user-attachments/assets/5dde9fb0-5dd7-40c0-9d90-735475f810fd)

Cette liste affiche tous les projets dont vous êtes référent ou contributeur, mais affiche aussi par défaut tous les projets avec Référents : Tout le monde ou Contributeurs : Tout le monde.

Le problème remonté est que sur une instance avec de très nombreux projets ouverts à "Tout le monde" on ne retrouve plus vraiment les projets pour lesquels on est ajouté directement en tant qu'auteur.
Une collègue documentaliste m'a rappelé qu'en documentation on appelle cela le "bruit documentaire" 

Est-ce qu'il serait possible de régler le filtrage de façon plus stricte et ne pas afficher dans ce volet les projets pour lesquels "Tout le monde" est référent ou contributeur ?

Ce serait plus évident que "MES PROJETS" affiche uniquement ceux là et non des projets complètement inconnus.

**Comment by louis-ev** [comment]
Ok, je change la logique : affiche uniquement les projets pour lesquels on est soit référent, soit contributeur.
