### ISSUE TITLE
soucis création vidéo montage

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#1040]
Si on fait un montage avec des images particulièrement grandes (par exemple, photo de 3000x2000 pixels), la résolution choisie par défaut sera très importante – trop pour un ordinateur ou serveur normal : 

![image](https://github.com/user-attachments/assets/a256ae7d-8588-449a-97bc-9aad6d570393)

Du coup, ça aurait du sens de mettre un choix plus judicieux (peut-être 1920x1080pixels) par défaut – ou au moins d'afficher un message d'alerte si on risque de dépasser les capacités du serveur.

**Comment by jubonhomme** [comment]
C'est aussi bien pour une question de sobriété numérique de faire un peu plus light que ce que produisent les capteurs actuels

**Comment by louis-ev** [comment]
Oui :)
Du coup, les stopmotion et les montage image/vidéo utiliseront par défaut le règlage "qualité haute".
623d9477396d981df6a54626cb585e293da0b889
