### ISSUE TITLE
Installation sur Raspberry Pi 3

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#121]

**Comment by lrault2** [comment]
Un petit "up"...

**Comment by louis-ev** [comment]
Nous avons testé cela il y a quelques mois, malheureusement il semble que la puissance du raspberry est trop limite pour faire tourner l'interface correctement. 
Par contre je dois re-tester en essayant uniquement de s'en servir comme un serveur qui héberge dodoc et les contenus et sur lequel smartphones, tablettes et autres ordinateurs peuvent se connecter. Je vous tiens au courant de tout ça.

**Comment by lrault2** [comment]
Un prof a développé un serveur local avec une série d'outil conséquent : owncloud, blog, pad, ... donc assez lour et ça tourne sous raspberry 3 [http://entbox.ticedu.fr/forums/discussion/3/telechargement-et-installation-dentbox]. Le système est totalement différent mais si ça peut vous aider...

**Comment by louis-ev** [comment]
Merci ! On regarde EntBox, c'est une chouette idée !
Pour le raspberry : https://github.com/l-atelier-des-chercheurs/dodoc/issues/275

**Comment by louis-ev** [comment]
La version 6 à venir facilite l’installation sous Raspberry Pi.
À retester quand la béta sera publiée !

**Comment by louis-ev** [comment]
Une version de test est à retrouver ici : http://forum.latelier-des-chercheurs.fr/t/mobilite-dodoc-sur-rpi3/112/5?u=louis

**Comment by louis-ev** [comment]
Note pour plus tard : https://gist.github.com/enzanki-ars/7d67996a90883e928bc1dd2db7ef0351

**Comment by jubonhomme** [comment]
Issue à fermer ?
