### ISSUE TITLE
retours test dodoc 05-05-2016

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#138]
QUESTION IMPORTANTE  SUR LES FORMATS DE MEDIAS
Les formats ne sont pas contraints et il y a des comportements différents en fonction des sources.
<br>
Capture en général sur ordi : 4/3 
Un format qui prend en compte que les médias seront en plein écran dans les publi seraient pas mal ?
Si import ordi : Formats portraits automatiquement pivotés à 90° (photos et vidéos). 
Si téléphone/capture via DoDoc: format portrait [photos+stop-mo] écrasé, vidéo ok 
Si téléphone/import: format portrait pivoté mais vidéo lues ensuite dans le bon sens (rotation s'effectue dans le média lui-même, très chelou)
Quoi faire ?
Suggestion : 
Crop dans la bibli > aperçu de l'image avec un format défini (ratio 16/9 ?)
Antony suggérait de refaire ce que tu avais fait pour la "publi des chercheurs" > rotation et resize. <br>
Quand on ouvre un média, dans son pop-up : options de rotation, de crop, et pourquoi pas à terme, de placement d'éléments géométriques simples (cercles, carrés) ?) Il faut revoir la taille du pop-up alors car là quand les éléments sont en portrait, on ne voit pas tout d'un coup.
Vous en pensez quoi ?
### Bugs

RIEN ! YOUPI !
### BUGS
- stop-motion encore un peu bancal<br>
  ok pour ne pas effacer les images précédentes si pas de validation - par contre quand on revient sur la page, le visualiseur est d'abord caché sous le flux > ensuite ok.
  Là tu as un delay entre les prises de vue du stop-motion et c'est pas top quand tu dois shooter 10 fois une image pour ralentir un mouvement. 
  > Est-ce qu'on attend un gros retravail global sur le stop-mo pour régler la question? Sinon, est-ce que tu peux avoir un delay dans les autres modes mais pas dans celui-là ?
- navigation dans les mp4 impossible: il faut lire toute la vidéo avant de pouvoir naviguer dedans (et le refaire à chaque ouverture)
### général

Je trouve le bouton supprimer partout un peu gros et souvent plus visible que le valider alors que c'est une exception la suppression. La solution trouvée pour la capture image et vidéo est bien je trouve (animation)
#### Page Capture
- Sur mon 13 pouces le flux video (à gauche) est trop en bas (tjs, ça touche)
#### Page Bibli
- Agrandir l'endroit du drop à la taille de la fenêtre (au départ quand il n'y a rien). 
- Designer les sliders / controllers (idem dans la page bibli) -- cf. ceux sur téléphone.
- le placement de l'onde sonore est trop à gauche > agrandir ou centrer
#### Page publi
- Design du print css (export pdf)
- Design de la page web publi css
#### Page de bibli
- dans l’upload de fichiers, est ce qu’on autorise plus de format ? (au moins png, jpg, mp4, mp3, m4v, avi ? les formats de base des 4 médias type non ?)  En tout cas, éditer la légende actuelle dans le pop-up (jpg, jpeg, png, mp4)
- variation dans la qualité de capture (par exemple vidéo avec la webcam de mon ordi , pendant la même vidéo, grosse variation - pas pixellisé à très pixellisé) Une idée de pourquoi ?
#### Projets
- dans les bandeaux, en bas dans les infos, on pourrait mettre le nombre d'éléments.
- sur l'icône publi > rajouter le nbre de publi ? (comme avant le +1 de capture / cf.mock-up)
#### Page capture
- Bug "moche" si on capture trop vite les stop motions, l'encart supprimer l'image et le count d'image clignote en haut à gauche de l'image. 
- Dans audio, mettre le player en autoplay 
#### Page Projets
- Fenêtre de confirmation de suppression à designer comme sur la page dossier
#### Page capture
- design du bouton supprimer (à harmoniser > son et stop-motion pas pareils que img et vidéo)
- Mettre un loader quand le stop motion se compile (là c'est moche)
- Dans les instructions > problème d'anti-slash
#### Page bibliothèque
- fenêtre publi, je suis pas fan non plus de l’espèce d’ombre quand c’est un média highlighté.
#### Page publi
- designer le bouton de retour au projet (mais c’est une très bonne idée)
- je suis pas fan de l’encadré autour du texte > pas grave = css à refaire entièrement
## Pour plus tard
- le statut terminé, ne fonctionne pas vraiment puisqu’on peut toujours éditer les dossiers /les projets quand ils sont en statut terminé. il faut qu’on puisse seulement voir les dossiers et les projets mais ne pas pouvoir ajouter un nouveau projet ou capturer des médias ou créer une publi. Mais ça c’est pour plus tard je pense.
- Upload d’images dans projets. > compresser ?

**Comment by louis-ev** [comment]
c0bdd9de25dab4cd82e45796f116cbaa57155a9d

Il est maintenant possible d'ajouter plusieurs fois le même média à une publi

**Comment by louis-ev** [comment]
a3f164213b1378a3c4c7f395270b181ab873d37d

Résolu tous les bugs "Très Important"

**Comment by louis-ev** [comment]
Je reprend la todo pour pouvoir répondre et barrer ce qui est fait !


> Très Important
> 
> Bugs
> 
> Page bibli
> 
> la fenêtre d'alerte "ce média existe déja" apparait à chaque action à partir du moment où elle est apparu une fois. Et du coup ça fait planter le panneau publication.

Résolu. On peut mettre plusieurs fois le même média.

> Page capture
> 
> Bug quand on prend une image et une vidéo et qu'on passe ensuite en stop motion. La fenêtre de droite avec les instructions disparait. Du coup on n'a aucune visualisation du stop motion.

C'est changé. Bon ?

> Dans stop motion, enlever l'icône valider dans l'écran 

Done.

> Important
> 
> BUGS
> 
> Page publi
> 
> l’icône svg de média apparait et la position des images est étrange

Supprimé l'icone. La position a quoi de problématique ? screenshot ?

> design
> 
> Page Capture
> 
> Sur mon 13 pouces le flux video (à gauche) est coupé en bas, ce qui fait que je dois scrollé pour atteindre le bouton de capture (c'est pas très grave hein)

Modifié. À tester

> Sur mon 13 pouces, en plein écran le flux vidéo est coupé en bas, le bouton de capture aussi. #### Page Bibli

La même, modifié. Ça devrait être ok. Y a un feedback visuel à la capture de photo aussi.

> Agrandir l'endroit du drop à la taille de la fenêtre (au départ quand il n'y a rien). #### Page publi

Done.

> Design du print css (export pdf)

Faudrait, oui. Des idées de quoi faire au juste ? On pourrait se faire un print.scss, ce serait bien. Sarah, tu veux t'en charger ? Je maitrise pas bien...

> Questions
> 
> Page de bibli
> 
> dans l’upload de fichiers, est ce qu’on autorise plus de format ?

Pour l'instant les .jpeg, .jpg et .png sont acceptés pour faire des images.
Les .mp4 et les .webm font des vidéos.

> fenêtre publi - est ce qu’on laisse le message quand on met 2 fois le même élément dans la publi ? Si oui (je vote oui pour ma part), il faut changer le message et ne pas demander de supprimer le média (on peut imaginer qu’il y a des cas ou on a besoin de mettre plusieurs fois le meme média)

Il est supprimé, c'est maintenant possible. On peut néanmoins afficher un petit message d'alerte pour prévenir, au cas où ça n'est pas voulu ?

> Moyen important
> 
> bugs
> 
> Home
> 
> dans les tuiles, en bas dans les infos y a juste marqué “projet”, avant on mettait le nombre de projets. #### Page capture

Modifié. C'est pas parfait mais ça fera l'affaire.

> Temps de latence entre la création de la vidéo et l'envoie de l'icone feeback dans l'icone bibliotheque. Il faut envoyer l'anim de l'icone après que le média soit apparu.

L'icone-feedback a lieu immédiatement pour dire "c'est parti". Le média s'affiche quand il est prêt. Mettre un loader, peut-être ? qui dit que c'est en préparation ? Ça vous paraît bien ?

> Bug "moche" si on capture trop vite les stop motions, l'encart supprimer l'image et le count d'image clignote en haut à gauche de l'image.

Oké...

> Dans audio, mettre le player en autoplay ?

En capture ? C'est pas gênant ?

> Désactiver le plein écran pour l'audio ?

Fait.

> Design
> 
> Page Projets
> 
> Fenêtre de confirmation de suppression à designer comme sur la page dossier #### Page projet

todo

> la liste des publication, c’est un peu bizarre la largeur de chaque élément. On pourrait pas avoir une largeur du même acajou que celle dans le panneau de publi dans bibli ? #### Page capture

todo

> design du boutton supprimer

lequel ?

> Mettre un loader quand le stop motion se compile (là c'est moche) #### Page bibliothèque

page capture tu veux dire ? On le voit pas se compiler page bibli, si ?

> Je préférais quand le flag encadrait les médias

todo

> fenêtre publi, je suis pas hyper fan de l’encadré en gros pointillé gris

le survol est important... Pauline ?

> fenêtre publi, je suis pas fan non plus de l’espèce d’ombre quand c’est un média highlighté. #### Page publi

oui, bug, todo

> designer le bouton de retour au projet (mais c’est une très bonne idée)

todo

> je suis pas fan de l’encadré autour du texte

oké, todo

> Pour plus tard
> 
> le statut terminé, ne fonctionne pas vraiment puisqu’on peut toujours édité les dossiers les projets quand ils sont en statut terminé. il faut qu’on puisse seulement voir les dossiers et les projets mais ne pas pouvoir ajouter un nouveau projet ou capturer des médias ou créer une publi. Mais ça c’est pour plus tard je pense.

oké. Le plus simple serait d'ajouter une classe au body et de masquer ces éléments en CSS (comme ça on touche pas au js, mais on cache les fonctions qu'on veut pas.

> Upload d’images dans projets. Quand on met une image assez lourde (plus de 3MB), ça a tendance à faire ramer un peu dodoc. Peut être ajouter une limite de 1 MB pour les images uploadées ?

En affichage, après l'upload ? Peut-être la redimensionner à l'arrivée sinon ? Les profs vont se retrouver coincé si ils veulent mettre une photo d'un smartphone…
