### ISSUE TITLE
finir la traduction des jade

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#139]
avec des  
`| #{dodoc.lang.audio}`

**Comment by louis-ev** [comment]
La trad est prête à être faite pour l'anglais ! Tout le français est encodé, il suffit de copier les chaînes dans dodoc.js

**Comment by paulinegourlet** [comment]
rrrrrégnial :)
je m'y mets dès demain !
Je suis sur le texte de la journée du 15... avec un angle nettement mieux
je crois. J'enchaîne ensuite avec les textes en retard pour l'atelier des
chercheurs avec une architecture de dossiers d'images triées pour le site !

Tu vas voir ! Épatés que vous allez être :)
Bisous

2016-05-08 0:32 GMT+02:00 Louis Eveillard <notifications@github.com>:

**Comment by louis-ev** [comment]
Gourlette ? tu t'en charges ?
