### ISSUE TITLE
Page publi - On ne peut pas naviguer dans les vidéos 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#145]
Impossible de naviguer dans les vidéos (d'aller à un moment précis de la vidéo). 
Par contre une fois qu'on a regardé la vidéo en entier, on peut.

**Comment by louis-ev** [comment]
Lié à l'encodage des vidéos. Voir la branche capture-for-firefox

**Comment by louis-ev** [comment]
Tester d'autres paramètres pour générer les vidéos avec ffmpeg : 

`
file=`basename $1`
file="${file%.*}"

# low quality MP4
ffmpeg -i $1 -acodec libfaac -vcodec libx264 -vb 2000k -vf scale=iw/2:ih/2 -f mp4 $file.lq.mp4
# high quality MP4
ffmpeg -i $1 -acodec libfaac -vcodec libx264 -vb 8000k -f mp4 $file.hq.mp4

# low quality WebM
ffmpeg -i $1 -acodec libvorbis -vcodec libvpx -vb 2000k -vf scale=iw/2:ih/2 -f webm $file.lq.webm
# high quality WebM
ffmpeg -i $1 -acodec libvorbis -vcodec libvpx -vb 8000k -f webm $file.hq.webm

# low quality OGV
ffmpeg -i $1 -acodec libvorbis -vcodec libtheora -vb 2000k -vf scale=iw/2:ih/2 -f ogv $file.lq.ogv
# high quality OGV
ffmpeg -i $1 -acodec libvorbis -vcodec libtheora -vb 8000k -f ogv $file.hq.ogv
`
