### ISSUE TITLE
EDITION MEDIA : Rotation media (pop-up media)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#178]

**Comment by louis-ev** [comment]
En cours d’implémentation (ça fonctionne déjà en fait, mais pas idéal).

**Comment by louis-ev** [comment]
Comme indiqué, déjà en place mais à revoir pour plus de fluidité (en lien avec #181 )

**Comment by sarahgarcin** [comment]
je ferme cette issue et la merge avec la #181
