### ISSUE TITLE
EDITION MEDIA : retouche image minimale (contraste / lumière / température ?)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#181]

**Comment by louis-ev** [comment]
Je repousse au futur :)

**Comment by jubonhomme** [comment]
Un lien vers une appli web... pas libre malheureusement mais qui correspond bien dans l'idée.
Interface simple et efficace.
Si on peut avoir les mêmes outils (sauf Markup qui est déjà dans la marmite) ce serait top !

https://doka.photo/

**Comment by louis-ev** [comment]
C’est pas mal oui. On va commencer doucement avec le crop et on voit :)
L’idéal serait de trouver une lib js (basée sur vue.js c’est encore mieux) qui fait ça.

**Comment by jubonhomme** [comment]
https://pqina.nl/doka/docs/

Comme leur module pour Vue
https://pqina.nl/doka/docs/patterns/adapters/vue/

C'est bien ça qu'il faut rechercher mais en libre ? 
J'ai pas l'impression que celui ci soit libre. Mais c'est das cette direction c'est bien ça ?

**Comment by jubonhomme** [comment]
Vue js Crop Image
Licence MIT
https://agontuk.github.io/vue-cropperjs/
https://www.npmjs.com/package/vue-cropperjs

**Comment by jubonhomme** [comment]
Je reprends ce fil au vue des possibilités de la version 2 de capture.

Est-il possible d'utiliser les filtres de l'outil capture ?
![image](https://user-images.githubusercontent.com/29262866/106947047-30cd9980-672a-11eb-87a2-4c10d8cfcf1f.png)


pour les utiliser dans une recette unique "effet video/image" dans laquelle on pourrait utiliser des vidéos ou des images pour appliquer ces filtres. 
![image](https://user-images.githubusercontent.com/29262866/106947650-f0225000-672a-11eb-993a-f67ac5796a2e.png)

**Comment by sarahgarcin** [comment]
Je suis d'accord avec @jubonhomme, avec options de rotation de l'image et de crop
Je passe cette fonctionnalité en to do pour la version 10

**Comment by jubonhomme** [comment]
Un exemple pour le recadrage :
https://github.com/advanced-cropper/vue-advanced-cropper

**Comment by jubonhomme** [comment]
Il ne manquerait plus que la rotation dans les options, et peut-être un effet miroir vertical ou horizontal.

Et il y a aussi en lien la possibilité de pouvoir flouter une partie de l'image #326 
C'est un peu un mix entre le filtre Blur et la zone de sélection pour le recadrage mais juste pour le filtre.

On va bientôt pouvoir fermer cette issue ;)

**Comment by jubonhomme** [comment]
Je reprends cet exemple qui est assez efficace
https://advanced-cropper.github.io/vue-advanced-cropper/guides/advanced-recipes.html#rotate-flip-image

**Comment by louis-ev** [comment]
Soucis flou : pas identique entre l'apercu et la sortie (surtout depuis que la résolution de crop est maximale, s'appuie sur celle de l'image source). Normal vu que le réglage est en **pixels** et pas en **%** – il faudrait utiliser une valeur qui ne varie pas en fonction de la taille de l'image de base.

**Comment by louis-ev** [comment]
Du coup, j'implémente la rotation d'image et le miroir vertical/horizontal, et je reporte à 10.1 pour ça.

**Comment by louis-ev** [comment]
Malheureusement après quelques tentatives je dois laisser de côté, je n'ai pas le temps ni le projet qui justifie d'y passer le temps qu'il faudrait pour que ça marche bien. Je reporte tout ça à 10.1 du coup, désolé pour le faux espoir !

**Comment by louis-ev** [comment]
(sauf si quelqu'un veut reprendre le chantier ?)

**Comment by jubonhomme** [comment]
Yes !
La modification des images est accessible directement dans le volet à droite dans la visualisation des médias dans Collecter

A fermer ?

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/e41cfb7a-c184-42f6-be6b-a88389052c38)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/e533e6d2-7a46-40a8-8390-b2f290bad34f)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/5dc41ddd-2f24-4796-b74f-ad470ba32727)
