### ISSUE TITLE
EDITION MEDIA : Annotations sur média (dessins)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#182]

**Comment by louis-ev** [comment]
Une référence intéressante : https://www.excalidraw.com/#W3sidHlwZSI6InJlY3RhbmdsZSIsIngiOjEyNCwieSI6ODcsIndpZHRoIjo2ODMsImhlaWdodCI6NjAzLCJpc1NlbGVjdGVkIjpmYWxzZSwic3Ryb2tlQ29sb3IiOiIjMDAwMDAwIiwiYmFja2dyb3VuZENvbG9yIjoiI2ZmNjkwMCIsImZpbGxTdHlsZSI6ImNyb3NzLWhhdGNoIiwic3Ryb2tlV2lkdGgiOjEsInJvdWdobmVzcyI6MSwib3BhY2l0eSI6MTAwLCJzZWVkIjoxMTAzNDIyMDAwfSx7InR5cGUiOiJlbGxpcHNlIiwieCI6ODQ2LCJ5IjoyMTAsIndpZHRoIjoyMDEsImhlaWdodCI6MTg5LCJpc1NlbGVjdGVkIjpmYWxzZSwic3Ryb2tlQ29sb3IiOiIjMDAwMDAwIiwiYmFja2dyb3VuZENvbG9yIjoiI2ZmNjkwMCIsImZpbGxTdHlsZSI6ImhhY2h1cmUiLCJzdHJva2VXaWR0aCI6MSwicm91Z2huZXNzIjoxLCJvcGFjaXR5IjoxMDAsInNlZWQiOjExMDkwNDQ1Njh9LHsidHlwZSI6ImFycm93IiwieCI6NjU0LCJ5IjozODYsIndpZHRoIjozMTIsImhlaWdodCI6LTEzOSwiaXNTZWxlY3RlZCI6dHJ1ZSwic3Ryb2tlQ29sb3IiOiIjMDAwMDAwIiwiYmFja2dyb3VuZENvbG9yIjoiI2ZmNjkwMCIsImZpbGxTdHlsZSI6ImhhY2h1cmUiLCJzdHJva2VXaWR0aCI6MSwicm91Z2huZXNzIjoxLCJvcGFjaXR5IjoxMDAsInNlZWQiOjEwMDIwNzEyNzZ9XQ==:eyJkcmFnZ2luZ0VsZW1lbnQiOm51bGwsInJlc2l6aW5nRWxlbWVudCI6bnVsbCwiZWxlbWVudFR5cGUiOiJzZWxlY3Rpb24iLCJleHBvcnRCYWNrZ3JvdW5kIjp0cnVlLCJjdXJyZW50SXRlbVN0cm9rZUNvbG9yIjoiIzAwMDAwMCIsImN1cnJlbnRJdGVtQmFja2dyb3VuZENvbG9yIjoiI2ZmNjkwMCIsInZpZXdCYWNrZ3JvdW5kQ29sb3IiOiIjZmZmZmZmIiwic2Nyb2xsWCI6MCwic2Nyb2xsWSI6MCwibmFtZSI6ImV4Y2FsaWRyYXctMjAyMDE3OTE5MjcifQ==

**Comment by louis-ev** [comment]
Note perso : aller fouiller dans Plateau

**Comment by louis-ev** [comment]
https://www.thinglink.com/fr/

**Comment by jubonhomme** [comment]
Il y a aussi H5P qui est libre et basé sur du HTML5 
https://h5p.org/content-types-and-applications

**Comment by louis-ev** [comment]
Première implémentation en place, avec fabric.js.
Les options sont très rudimentaires pour l’instant (possibilité seulement de tracer des traits) mais c’est facile d’ajouter des options : 

http://fabricjs.com/freedrawing
<img width="913" alt="image" src="https://user-images.githubusercontent.com/1948417/75623499-cbcd0380-5baa-11ea-9955-85d5f5162964.png">

https://www.postermaker.com/
<img width="987" alt="image" src="https://user-images.githubusercontent.com/1948417/75623565-72190900-5bab-11ea-9e6c-279ca90ac95e.png">

**Comment by louis-ev** [comment]
Celui ci est intéressant et open-source (licence MIT) : https://carstenschaefer.github.io/DrawerJs/examples/standalone/

code source : 
https://github.com/carstenschaefer/DrawerJs

**Comment by louis-ev** [comment]
La recette "bloc dessin" remplie t’elle cette fonction ? Est-elle assez aboutie ?

**Comment by jubonhomme** [comment]
Comme : 

- les outils médias / formes / lignes / flèches ... sont déjà dans la recette page à page, 
- on peut exporter une seule page en png de page à page ou plusieurs en pdf
- page à page gère très bien les calques, et toutes les options opacité / couleurs / verrouillage ...
- page à page est collaboratif en synchrone à plusieurs
- on peut choisir le format de la page
....

Je trouve effectivement que la recette bloc dessin n'apporte pas grand chose à part un outil basique de tracé à la souris... et comme je ne suis pas doué pour dessiner à la souris...
Si cet outil peut se rajouter à la recette page à page je pense que ce serait beaucoup plus simple.
Pour annoter simplement un média en arrière plan ou réaliser quelques schémas c'est suffisant à mon avis.

ça permettrai aussi d'unifier les cadres de sélection qui sont différents pour les outils formes (comme les médias) et les dessins

![image](https://user-images.githubusercontent.com/29262866/98299681-61315a80-1fb8-11eb-98d4-9f3b61cc5e3c.png)
![image](https://user-images.githubusercontent.com/29262866/98299752-7b6b3880-1fb8-11eb-9e40-b53912bd49a8.png)

Et de régler les soucis de cadrage du bloc dessin (décalé en bas à droite) et du menu tout en bas qui passe sur le bloc dessin
Je trouve le fonctionnement des menus et de la gestion des pages bien mieux dans la recette page à page... surtout depuis toutes les modifications récentes.
![image](https://user-images.githubusercontent.com/29262866/98300003-f16f9f80-1fb8-11eb-89ee-610d6fa69f96.png)

**Comment by louis-ev** [comment]
@paulinegourlet un avis là-dessus ?
@PixnWave ?
Christophe ?

**Comment by PixnWave** [comment]
Bonjour,
le regroupement me semble intéressent sauf si tu as la possibilité de développer un Gimp ou un krita sur do.doc ;-)

**Comment by chrisnoullez** [comment]
Je suis d'accord que cette outil est très bien quand il est intégré au document page à page. Il est plus fonctionnel sans sortir de la production.

**Comment by PixnWave** [comment]
je viens de voir ça https://addons.mozilla.org/es/firefox/addon/gimp-online-editor/
c'est compatible ?

**Comment by louis-ev** [comment]
Waouh c’est bien bourrin cette extension : d’après ce que je vois ça fait un partage d’écran vers une machine sous Linux qui fait tourner gimp. Pas du tout propre ou optimisé (y a un délai, vu la techno utilisée) mais ça fonctionne à peu près.
Pas question de faire ça dans do•doc par contre :)

**Comment by sarahgarcin** [comment]
à voir ce qu'on fait pour la sortie de la version 9: enlève-t-on la recette bloc dessin ?

côté outil d'annotation dans le page à page, il faudrait : 
- ajouter un picto à l'option "bloc dessin"
- avoir la possibilité de choisir la couleur et l'épaisseur du trait dans bloc dessin 
- traduire la mention sous le mode de fusion "Use at your own risk: medias can become invisible in some cases."
- possible de remplace les phrases d'aide comme "Plus cette valeur est haute et plus le bloc sera au premier "  par un point d'interrogation ça allégerait le panneau ?

vous voyez d'autres choses ?

**Comment by jubonhomme** [comment]
#571 pour le tracé qui ne suit pas la souris et le picto

**Comment by PixnWave** [comment]
pour info j'ai eu "besoin" du bloc dessin pour faire le générique de fin d'une vidéo

**Comment by louis-ev** [comment]
Ok.
On le garde ce mode du coup ?

**Comment by jubonhomme** [comment]
@PixnWave Est-ce que tu as réalisé en utilisant l'outil dessin ne pouvait pas être fait directement dans le page à page et exporté en utilisant Céer / Image (Une page seule) ?

![image](https://user-images.githubusercontent.com/29262866/112334842-07f26b00-8cbc-11eb-8669-e6bc0ff4994e.png)

![image](https://user-images.githubusercontent.com/29262866/112335044-3112fb80-8cbc-11eb-9160-bde542441c69.png)

**Comment by PixnWave** [comment]
ah génial je ne l'avais pas vue ça ira pour moi

**Comment by PixnWave** [comment]
vous pouvez le suprimer

**Comment by jubonhomme** [comment]
Merci pour ton retour... ça confirme que les outils du page à page sont maintenant au niveau du bloc dessin mais aussi qu'il faudrait peut être juste mieux mettre en avant la possibilité d'export d'une page comme une image/dessin.
Est-ce qu'à la place de la liste déroulante (pdf / image ) du menu "créer"  on pourrait voir les deux propositions directement ?

**Comment by PixnWave** [comment]
ou le préciser dans le texte au dessus ?

**Comment by jubonhomme** [comment]
Avec le risque que les utilisateurs ne lisent pas le texte et regardent juste les boutons

**Comment by sarahgarcin** [comment]
Je suis d'accord avec @jubonhomme au lieu de la liste déroulante avoir 2 petits pictos avec les deux possibilités ?

**Comment by louis-ev** [comment]
Oui ok, ça me semble bien :)

**Comment by louis-ev** [comment]
![image](https://user-images.githubusercontent.com/1948417/112860833-7a948980-90b4-11eb-81f8-288373983913.png)

![image](https://user-images.githubusercontent.com/1948417/112860838-7bc5b680-90b4-11eb-8489-5305dcec6fab.png)

Vous en pensez quoi ?

**Comment by jubonhomme** [comment]
Top !
Juste peut-être mettre "Document en PDF"  au lieu de PDF tout court.
J'ai toujours un peu de réticence à nommer un document par son extension seule.

**Comment by louis-ev** [comment]
Avant que je la supprime pour de bon… je la supprime ?

**Comment by jubonhomme** [comment]
OK pour moi
