### ISSUE TITLE
la marmite de média

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#186]
Un système de combinaison de différents média selon des recettes, pour en créer des nouveaux, par exemple : 

- photo + audio = vidéo

- vidéo + audio = remplacer la bande sonore d’une vidéo par cette piste sonore

- photo + photo + photo + … = vidéo qui défile dans les photos, avec réglage vitesse

- vidéo + vidéo = vidéo qui les réunit

- photo + vidéo + photo + vidéo + photo = vidéo comme avec des écrans titres

- vectoriser une image (avec imagetracerjs, voir https://codepen.io/jesperkc/pen/WwJYRw )

**Comment by louis-ev** [comment]
Croquis rapide :

![Image](https://i.imgur.com/BhxYrZZ.jpg)

**Comment by louis-ev** [comment]
Une option possible dans la marmite (notamment pour des recettes comme _photo + vidéo + photo + vidéo + photo = vidéo_ ou _photo + photo + photo + … = vidéo) : 
--> pouvoir ajouter TOUS les médias actuellement visibles dans la marmite

Cas d’usage : fabriquer une vidéo rapidement de toutes les traces d’un projet, ou uniquement les traces "fav", ou seulement les photos, etc.

**Comment by louis-ev** [comment]
Réflexion en cours : et si la marmite était en fait des options de plus dans la création de publication ? Est-ce que ça ne serait pas plus simple comme ça, plutôt que d’ajouter un nouveau panneau ? À voir si on renomme "publication" en "marmite", le terme publication pouvant suggérer qqchose qui n’est pas tout à fait le but de cette fonctionnalité :

![image](https://user-images.githubusercontent.com/1948417/48254890-7ac05b80-e40b-11e8-9f65-a061f3261a2d.png)
(idéalement améliorer le sélecteur avec des petits gifs qui montrent ce que ça va faire)

**Comment by louis-ev** [comment]
Présent dans do•doc 8.
Manque juste la recette suivante : 
- vectoriser une image (avec imagetracerjs, voir https://codepen.io/jesperkc/pen/WwJYRw )

**Comment by louis-ev** [comment]
Petit point suite à la sortie de do•doc 8.2 en version stable :

> photo + audio = vidéo

en place

> vidéo + audio = remplacer la bande sonore d’une vidéo par cette piste sonore

fonctionnel

> photo + photo + photo + … = vidéo qui défile dans les photos, avec réglage vitesse

opérationnel

> vidéo + vidéo = vidéo qui les réunit

itou

> photo + vidéo + photo + vidéo + photo = vidéo comme avec des écrans titres

pareil

Un manque : montage audio (son + son + son).
Voir du montage un peu plus élaboré, pour gérer l’enchainement des séquences (transition, synchronisation d’un fichier audio + plusieurs vidéos).

**Comment by sarahgarcin** [comment]
Il reste donc une recette montage audio (son + son)
On en aura probablement besoin pour un atelier en septembre.
Je passe ça sur do·doc 10

**Comment by jubonhomme** [comment]
Je trouve que la nouvelle répartition des recettes dans la V10 - "Remixer"  et  "Publier"  est plus claire.
 
Il reste à remettre en fonction les remix déjà existante sur la V9 et à ajouter un remix pour le  montage son #606 

A fermer ?

**Comment by louis-ev** [comment]
Archéologie d’un logiciel libre :)
Je ferme !
