### ISSUE TITLE
Reprendre le design des favoris (bibli et publi)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#187]
- bug du fond qui s'affiche (en gris ou en bleu si favori) dans la publi
![image](https://cloud.githubusercontent.com/assets/7995654/20323996/37f66068-ab7f-11e6-9042-4aa96059ad18.png)

- fond blanc préféré
- écrire en gris le code de mark down dans l'édition du texte ? (qui s'efface quand on écrit ?)

**Comment by louis-ev** [comment]
Mieux ? 

![image](https://cloud.githubusercontent.com/assets/1948417/20388262/5754d5fc-acc4-11e6-8e38-1a25857243da.png)
