### ISSUE TITLE
Affichage média PAGE CATURE

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#188]
PAGE PUBLI
> Vidéo et Animation : le container des médias sont immenses ! mais média ont l'air d'être à la bonne taille dedans.
![image](https://cloud.githubusercontent.com/assets/7995654/20345836/4210c410-abf9-11e6-85ff-94b306cba734.png)

PAGE CAPTURE
Pour photo et vidéo : OK !
Pour anim /
Problème avec les boutons : supprimer le bouton "prévisualiser", quand on est en train de prévisualiser.

Problème avec res bizarres : sort du cadre quand prévisualisation.
![image](https://cloud.githubusercontent.com/assets/7995654/20345603/35a2c03a-abf8-11e6-8094-40119348873d.png)
--
QUESTION : quand on commence une anim avec une res, on peut pas continuer l'anim avec d'autres res ? Je l'ai fait et dans le sens de normal vers bizarre > la lecture saute les res bizarres /// dans le sens bizarre vers normal > les res normales sont transformées dans le format bizarre (déformation)
QUE FAIT-ON ? On l'interdit ?

**Comment by louis-ev** [comment]
en cours, à tester (avec des résolutions étrange)

![image](https://cloud.githubusercontent.com/assets/1948417/20316407/fd1567a4-ab61-11e6-8c66-d5ae30dd977a.png)

**Comment by paulinegourlet** [comment]
Toujours pas bon chez moi (dans l'app dodoc)
![image](https://cloud.githubusercontent.com/assets/7995654/20323922/00188644-ab7f-11e6-8121-dc43db419653.png)

**Comment by louis-ev** [comment]
J'ai résolu tout ça (sauf le soucis au niveau des publications, mais j'arrive pas à le reproduire alors il me faut plus d'info si ça te le fait encore…). La capture stopmotion a pas mal changé.
Tu pourra fermer si c'est ok ?
