### ISSUE TITLE
CAPTURE - problème de proportions affichage des "boîtes"

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#200]
- Ce serait bien de ne pas avoir à scroller pour le bouton capture
- il y a la boîte de "rendu" qui n'a pas les mêmes proportions/marges que la boîte "flux".

![image](https://cloud.githubusercontent.com/assets/7995654/20574177/930dc876-b1b3-11e6-9e60-2078e48e6f94.png)

**Comment by louis-ev** [comment]
![image](https://cloud.githubusercontent.com/assets/1948417/20636904/d44c9ba4-b376-11e6-86a2-df0d23ea3242.png)
![image](https://cloud.githubusercontent.com/assets/1948417/20636905/d83a3708-b376-11e6-9628-ff459bc1be55.png)
![image](https://cloud.githubusercontent.com/assets/1948417/20636908/dd86c262-b376-11e6-9e7f-0cd86229efb4.png)
![image](https://cloud.githubusercontent.com/assets/1948417/20636912/e3018c4a-b376-11e6-989c-7c68f7e3026f.png)

**Comment by paulinegourlet** [comment]
Ok pour moi, sauf stop-motion (cf. remarque dans capture stop-motion)
