### ISSUE TITLE
CAPTURE - Stop motion

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#201]
- problème avec l'onion skin
![image](https://cloud.githubusercontent.com/assets/7995654/20574375/69b584a4-b1b4-11e6-958d-5546c2a5b5bc.png)

- dans tous les formats : impossible de lire la preview / le bouton de retour ne marche pas et celui de previsualisation est inutile (à suppr.)
![image](https://cloud.githubusercontent.com/assets/7995654/20574430/a989333c-b1b4-11e6-9125-0fb79f8e4599.png)

et impossible d'enregistrer non plus, je ne retrouve rien dans ma bibli.

**Comment by louis-ev** [comment]
L’onion skin est corrigé.

Pour la compilation stopmotion qui ne marche pas en package je regarde

**Comment by paulinegourlet** [comment]
![image](https://cloud.githubusercontent.com/assets/7995654/20639880/23ff85ea-b3d0-11e6-8c18-eca39258dd94.png)

![image](https://cloud.githubusercontent.com/assets/7995654/20639913/7a2befc6-b3d0-11e6-9409-f2ffc4d0cb0a.png)

> bug onion skin encore présent et reste visible sur photo
> manque l'indicateur de compilation du stop motion qui montre qu'il faut attendre
> proportions pas top = à droite : mettre les infos dans le bandeau blanc aligner avec le bandeau blanc du flux vidéo

**Comment by louis-ev** [comment]
Corrigé
