### ISSUE TITLE
TEXTE

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#202]
L'éditeur ne prend pas en compte les retours à la ligne et la typo du titre est un peu faible comparée à # ou ## ou ### non ?
A reprendre / et écrire les consignes-indications du markdown en gris qqpart.

**Comment by louis-ev** [comment]
Ok pour les retours à la ligne, ça devrait être ok pour les médias texte et les légende d’image.

Pour homogénéiser les h1,h2,h3, il faudrait savoir d’abord si on garde le titre des médias texte. J’ai l’impression que si les fonctions en markdown sont bien expliquées on peut s’en passer et ça donnerait plus de souplesse. Non ?

**Comment by louis-ev** [comment]
Éditeurs JS intéressant (deux approches) : 

1. https://yabwe.github.io/medium-editor/demo.html

2. https://simplemde.com/

**Comment by paulinegourlet** [comment]
Ok pour les retours à la ligne.

J'aime beaucoup celui de médium. Le mark-down je trouve ça quand même vachement compliqué pour des novices. 
Ok pour virer le titre, tant qu'on peut facilement identifier les éléments dans le bloc.

**Comment by louis-ev** [comment]
Résolu dans la v7 à venir, qui utilise maintenant quill et du html, plus du markdown. Éditeur en wysiwyg
