### ISSUE TITLE
use ffmpeg binaries

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#206]
Using http://ffbinaries.com/
with https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#setting-binary-paths-manually
and http://stackoverflow.com/a/20698887

**Comment by paulinegourlet** [comment]
Je sais pas si c'est à propos de ça, mais j'ai téléchargé la nouvelle version de l'app et ça marche pas le stop-motion.
