### ISSUE TITLE
Bibli - Quand la légende fait deux lignes elle est coupé 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#214]

**Comment by louis-ev** [comment]
Ça dépend des résolutions en fait.
Je passe sur une ligne du coup, avec ellipse si le texte continue

![image](https://cloud.githubusercontent.com/assets/1948417/20706170/33529fac-b626-11e6-8ba2-8edb8e8ec460.png)
