### ISSUE TITLE
Déplacement fichier source dodoc

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#233]
Le déplacement du fichier racine ne copie pas les nouveaux éléments créés (que le dossier installation de dodoc qui va avec)

**Comment by louis-ev** [comment]
Alors, oui mais c'est normal :)
Le soucis du déplacement après coup c'est que t'as potentiellement plusieurs gigaoctects de contenus à déplacer (et je préfère pas le déplacer (couper/coller) en code, trop de risque qu'il y ait un problème). Ça ne fait que changer l'emplacement où il va chercher le dossier dodoc, et s'il n'existe pas le recréé. 
Outre le fait de copier tout le contenu, tu proposes autre chose ? Afficher un lien clickable qui ouvre le finder à l'emplacement actuel de dodoc ?

![image](https://cloud.githubusercontent.com/assets/1948417/21593992/c31e52fe-d11d-11e6-9b9e-5297e0198101.png)

**Comment by louis-ev** [comment]
(pour référence future si on part là-dessus : https://github.com/electron/electron/blob/master/docs/api/shell.md#shellshowiteminfolderfullpath )

**Comment by paulinegourlet** [comment]
Tu as fermé cette issue mais est-ce que le chemin vers l'ancien emplacement est clickable comme tu le proposais ?
