### ISSUE TITLE
bug de rendu de publi utilisant object-fit en PDF

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#236]
cross-platform, lié à phantomjs ?
Peut-être tester une bibliothèque d'export PDF plus légère, et qui fait que ça mais proprement. Il faudrait tester un export "manuel" en passant par un navigateur pour voir si object-fit est respecté.

![image](https://cloud.githubusercontent.com/assets/1948417/21603896/90af597a-d1a0-11e6-93f2-d384f5097d21.png)

**Comment by paulinegourlet** [comment]
Une idée ? C'est assez embêtant ça...

**Comment by louis-ev** [comment]
Résolu dans dodoc v6 (car changement de moteur de rendu de PDF).
