### ISSUE TITLE
ajouter la possibilité de télécharger les médias depuis la fenêtre modale du média

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#239]
En cliquant sur le lien ? un bouton séparé ?

![image](https://cloud.githubusercontent.com/assets/1948417/21937796/ea69e410-d9b8-11e6-9338-58b20d12d1d1.png)

**Comment by lrault2** [comment]
La création d'un bouton serait très appréciée des enseignants moins spécialistes.

**Comment by louis-ev** [comment]
Bien noté, c'est prévu pour la prochaine version de dodoc.

**Comment by louis-ev** [comment]
Un aperçu de ce qui arrive.

![image](https://cloud.githubusercontent.com/assets/1948417/22163165/01abbc40-df52-11e6-8760-0d77802b4914.png)
![image](https://cloud.githubusercontent.com/assets/1948417/22163172/06b29740-df52-11e6-89da-86fde049cbbc.png)
