### ISSUE TITLE
Déplacement de la fenêtre "do.doc"

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#240]
Bonjour,
Je reviens vers vous à propos des problèmes constatés sous windows. Pour l'instant, je n'ai plus mon poste sous linux mais dès retour je testerai également.

Sous windows10 pro, le déplacement de la fenêtre "do.doc" ne pose pas de souci.

Sous windows7, par contre, le déplacement et le redimensionnement par "glissement" de la souris renvoient un message d'erreur assez rapidement. Cela ne rend pas "do.doc" inutilisable, mais cela nécessite de faire plusieurs fois la manipulation avant d'obtenir le résultat souhaité. L'agrandissement et la réduction de la fenêtre en utilisant les "boutons" prédéfinis de windows (en haut à droite de la fenêtre) ne pose quant à eux aucun problème.

**Comment by louis-ev** [comment]
Bonjour,

Merci pour ce retour précis. 

Il semble que nous nous heurtons à un bug spécifique à Windows 7. Nous allons masquer cet avertissement (qui signale simplement que la position de la fenêtre de dodoc ne pourra pas être rechargée au prochain lancement, comme c'est le cas de la plupart des applications).

**Comment by louis-ev** [comment]
lien pour référence au moment du développement : https://github.com/lmaccherone/node-localstorage/issues/23

**Comment by louis-ev** [comment]
Bonjour,
Ce bug est-il toujours d'actualité sous windows 7 et dodoc 5.1.0 ?

**Comment by lrault2** [comment]
Bonjour,
Je pensais y avoir répondu, désolé.
Mais c'est tout bon.
Merci
