### ISSUE TITLE
do.doc, OS et navigateurs web

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#241]
Après lancement de "do.doc" sur PC Windows, j'ai testé 3 tablettes différentes pour accéder à "do.doc".
--> galaxy tab A sous android 6 : pas de souci, les outils de capture sont laisser à la discrétion des utilisateurs. Il faut simplement passer les étapes de mise en garde (sous chrome et firefox) ;
--> tablettes windows10 pro : pas de souci non plus sous les deux navigateurs
--> I-pad mini 4 : Apple et IOS 10 n'autorise aucun navigateur web à utiliser directement la caméra ou le micro. Il faut utiliser la "bibliothèque de médias" mais cela reste limité aux images et vidéos. J'ai donc tenté un cloud (Hubic) et là même constat, il n'y a pas la possibilité d'importer une source audio.

Il semblerait donc que seules les applications de l'applestore soient autorisées à utiliser le micro.

**Comment by louis-ev** [comment]
> galaxy tab A sous android 6 : pas de souci, les outils de capture sont laisser à la discrétion des utilisateurs. Il faut simplement passer les étapes de mise en garde (sous chrome et firefox) ;

vous parlez bien de l'avertissement initial à la connexion qui dit que la page n'est pas privée, c'est bien ça ?

> tablettes windows10 pro : pas de souci non plus sous les deux navigateurs

Bonne nouvelle ! Merci pour le test.

> I-pad mini 4 : Apple et IOS 10 n'autorise aucun navigateur web à utiliser directement la caméra ou le micro. Il faut utiliser la "bibliothèque de médias" mais cela reste limité aux images et vidéos. 

C'est malheureusement bien le cas.

> J'ai donc tenté un cloud (Hubic) et là même constat, il n'y a pas la possibilité d'importer une source audio.

Je ne suis pas sur de bien comprendre ce test. Comment vous y êtes vous pris ? Toujours sur ipad ?

> Il semblerait donc que seules les applications de l'applestore soient autorisées à utiliser le micro.

Oui, c'est bien ça. Mais il est tout à fait possible (même probable) que cette situation change courant 2017, Apple a embauché des développeurs pour ajouter l'accès à la caméra et au micro comme sur Chrome sous Android. On croise les doigts. En attendant il faut passer par l'import de la page bibli.

**Comment by lrault2** [comment]
Hubic et I-Pad
Les applications sur I-pad peuvent utiliser le micro, la caméra pour importer des médias. Il est possible d'autoriser ces applications à utiliser un cloud.
Dans do.doc et la bibliothèque de média j'ai touché "importer un média", dans le pop-up à nouveau "importer..." là il y a la possibilité d'utiliser la caméra ou un cloud. Dans hubic, je peux prendre les images mais pas les sons.

**Comment by louis-ev** [comment]
Je ne savais pas qu'il était possible de sélectionner cette application
depuis ce menu, je pensais que seul les applications d'Apple pouvait venir
à cet endroit là. Intéressant.
En l'état le menu d'import ne permet d'ajouter que les formats suivants :
jpeg, png (images) et mp4 (vidéo).
Nous pouvons ajouter un format audio si nécessaire, il faudrait juste
lister les formats acceptés.
Pouvez-vous m'envoyer un fichier audio provenant de hubic pour que je test ?
En pièce jointe d'un post ici, ou par mail hello@louiseveillard.com
Merci

**Comment by lrault2** [comment]
Voici une série de captures d'écran montrant les étapes pour importer un média avec un iPad.
On y voit clairement que les fichiers audios sont vus uniquement alors que les fichiers vidéos sont disponibles au téléchargement.

![img_0003](https://cloud.githubusercontent.com/assets/24780752/22042304/cc7c60f4-dd0a-11e6-91b4-c9155beb0ec3.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/24780752/22042303/cc7a5e8a-dd0a-11e6-9e78-8aea1c1d9db5.PNG)
![img_0005](https://cloud.githubusercontent.com/assets/24780752/22042302/cc742aba-dd0a-11e6-9a91-0a09df306863.PNG)
![img_0006](https://cloud.githubusercontent.com/assets/24780752/22042306/ccac56f6-dd0a-11e6-905f-b9eac1cbac8a.PNG)
![img_0007](https://cloud.githubusercontent.com/assets/24780752/22042307/ccad1e06-dd0a-11e6-8405-25ac0ef6c2a8.PNG)
![img_0008](https://cloud.githubusercontent.com/assets/24780752/22042305/ccab65d4-dd0a-11e6-9f38-2b2c3c986ee1.PNG)
![img_0010](https://cloud.githubusercontent.com/assets/24780752/22042308/ccaeced6-dd0a-11e6-8d0e-c0d41b29dce2.PNG)
![img_0011](https://cloud.githubusercontent.com/assets/24780752/22042309/cccf3072-dd0a-11e6-8d93-2339516181d7.PNG)

**Comment by louis-ev** [comment]
Oui, c'est bien ça : le bouton a comme attribut HTML `accept="image/*,video/*"`

On pourrait le préciser et ajouter la mention audio sans soucis

Note pour plus tard : préciser les extensions acceptés pour éviter les soucis à l'envoi, par exemple : 
`accept="image/png,image/gif,video/mp4,image/jpeg"`

**Comment by lrault2** [comment]
et audio/ mp3
Super

**Comment by louis-ev** [comment]
La version 5.1.0 est sortie, elle inclue cette fonction : https://github.com/l-atelier-des-chercheurs/dodoc/releases/tag/v5.1.0

Pouvez-vous tester et le confirmer ? merci !

**Comment by lrault2** [comment]
Bonjour. 
Voici quelques captures d'écran avec IPad pour insérer différents médias dans la bibliothèque. Pour les audios, cela ne semble pas fonctionner.
![img_0012](https://cloud.githubusercontent.com/assets/24780752/22178531/24896a40-e039-11e6-9c72-1abd078fd75a.PNG)
![img_0013](https://cloud.githubusercontent.com/assets/24780752/22178535/24bd8d66-e039-11e6-9898-b2bfeca3e80e.PNG)
![img_0014](https://cloud.githubusercontent.com/assets/24780752/22178533/24bb4d26-e039-11e6-99b2-054269e8e89a.PNG)
![img_0015](https://cloud.githubusercontent.com/assets/24780752/22178534/24bd5710-e039-11e6-9f7d-bbcf6e0f46ce.PNG)
![img_0016](https://cloud.githubusercontent.com/assets/24780752/22178532/24a7deb2-e039-11e6-9e07-6e38fc0b28c3.PNG)
![img_0017](https://cloud.githubusercontent.com/assets/24780752/22178536/24c709cc-e039-11e6-8827-3e5daa217de2.PNG)
![img_0018](https://cloud.githubusercontent.com/assets/24780752/22178537/24e4455a-e039-11e6-94dc-28bb5bafe082.PNG)

**Comment by louis-ev** [comment]
Bonjour
cela fonctionne bien sur Android (je viens de tester), il est possible que ce soit un soucis lié au cache du navigateur ipad. Pouvez-vous recharger cette page à plusieurs reprises ?
Je vois également que je n'ai pas mis à jour le message avec les formats, je m'en occupe.
merci !

**Comment by lrault2** [comment]
Bonjour,
Je viens de tester chrome, safari, firefox avec l'ipad, après avoir effacé le cache, et l'import audio ne fonctionne pas.
Par ailleurs, sous android, quand je cherche à importer des médias, je n'ai comme possibilité que les outils propres à la tablette (APN, mémoire, micro (pas sous firefox)... 
La possibilité de télécharger un média va être très appréciée : OK sous windows7 et Android mais pas sous Ipad.

**Comment by louis-ev** [comment]
Le difficulté est liée à la diversité des médias vidéo/audio entrant : mp4,
m4a, mp3, mov, avi, etc. Et je ne parle que des containers, pas des codecs
qui sont nombreux et pas systématiquement compatible avec les navigateurs
web… On se retrouverait dans le cas de figure ou un média est importé mais
ne peut être lu.
L'idéal serait une reconversion des médias importés (pour qu'un mov
devienne un webm, qui est un format vidéo web natif, par exemple) mais ce
n'est pas évident à gérer et ça demande d'embarquer un paquet de codecs.
Cette question est problématique. S'il y a des formats de référence à
favoriser ça serait vraiment plus simple de partir là-dessus, tant pour la
vidéo que l'audio.

J'aurai un ipad sous la main demain pour tester ça également, je vous dirai
ce qu'il en est de mon côté pour l'audio. Je regarderai aussi pour le
téléchargement de médias.

Sous Android il devrait y avoir l'option "gallerie" ou "document" au moment
de l'import, nous l'avons utilisé toute l'après-midi dans le cadre d'un
atelier et ça a marché sur tous les smartphones/tablettes/iphones sans
soucis. Pas sur de voir où pourrait se situer ce bug, mais peut-être au
niveau de l'appareil ?

**Comment by lrault2** [comment]
Oui oui, il y a bien "documents".

**Comment by louis-ev** [comment]
Renseignements pris, il n'existe pas d'option "enregistrement audio" sous
safari pour iOS.
Sur ipad, Il n'est possible que d'importer un fichier audio après l'avoir
capturé dans une autre application. Sur Android, le format utilisé semble
être le .amr et n'est pas standard. À voir s'il peut être converti.
Il n'existe pas non plus l'option "download" sous safari (mobile ou bureau)
donc pas de téléchargement possible depuis ces appareils. Safari ne suit
pas encore les standards malheureusement.

**Comment by louis-ev** [comment]
Je ferme pour nettoyer les issues, mais n’hésite pas à créer une autre issue si ce genre de bug se manifeste sur dodoc 7 !
