### ISSUE TITLE
Calibrage de la publication en pdf

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#242]
Dans les différents cycles de l'école et à travers les nouveaux programmes, les enseignant ont à permettre aux élèves de produire des documents relatant leurs parcours d'apprentissages dans différents domaines. On peut parler de portfolio. L'outil numérique est très pertinent car, l'élève montre ses apprentissages mais aussi ses compétences...
Du coup, cette possibilité qu'offre "do.doc" est très intéressante et des suggestions / questions me viennent. Imaginons, une classe. Chaque élève pourrait avoir son dossier dans lequel seraient rangés ses projets.
--> Est-il possible de permettre les utilisateurs de personnaliser l'en-tête et le pied de page ?
Cela pourrait se faire à l'installation de "do.doc" pour ce qui est de l'identité de l'école et la classe puis lors de la création de la publication pour l'identité de l'élève.
--> Dans un projet, il peut y avoir une vidéo, est-il possible que la création du pdf "fige" une capture de cette vidéo ? ou préserve l'emplacement avec un texte de remplacement ?
--> Est-il possible d'autoriser le redimensionnement des images lors de la création de la publication ? Je prends pour exemple la mise en page "marseille", selon l'ordre de choix des médias la taille est plus ou moins bien adaptée. Par ailleurs, dans ce thème, je ne parviens pas à déplacer les médias choisis même si le survole semble l'autoriser.
--> Est-ce un choix ? La publication en colonne édite les commentaires mais ce n'est pas le cas pour les autres mises en page ...

**Comment by louis-ev** [comment]
> Est-il possible de permettre les utilisateurs de personnaliser l'en-tête et le pied de page ? Cela pourrait se faire à l'installation de "do.doc" pour ce qui est de l'identité de l'école et la classe puis lors de la création de la publication pour l'identité de l'élève.

Cette personnalisation se ferait donc à l'échelle d'un programme dodoc, et non à l'échelle d'un dossier ou d'un projet ? On considèrerait donc qu'une application dodoc = un lieu (par exemple, un établissement, une classe ou un fablab) et donc une identité commune à tous les dossiers et tous les projets ? 
La personnalisation "élève" se ferait en récupérant automatiquement le nom du dossier et du projet et en les plaçant en haut de la page, par exemple. Le titre de la publication fait aussi partie des champs  "personnalisables" que nous avons envisagé. Est-ce que ça correspond à ce que vous imaginiez ?

En entête de publication, nous aurions donc comme information : 
1. petit logo dodoc
2. nom donné à ce dodoc ("Classe de CM1 B")
3. le nom du dossier
4. le nom du projet
5. le titre de la publication

C'est bien ça ?

> Dans un projet, il peut y avoir une vidéo, est-il possible que la création du pdf "fige" une capture de cette vidéo ? ou préserve l'emplacement avec un texte de remplacement ?

Absolument ! Nous pouvons sortir l'aperçu de la vidéo plutôt que la vidéo dans ce cas.

> Est-il possible d'autoriser le redimensionnement des images lors de la création de la publication ? Je prends pour exemple la mise en page "marseille", selon l'ordre de choix des médias la taille est plus ou moins bien adaptée. Par ailleurs, dans ce thème, je ne parviens pas à déplacer les médias choisis même si le survole semble l'autoriser.

Cela fait partie des choses un peu délicates à gérer : les templates de publication définissent des emplacements prédéfinis pour les médias. Un média rentre en quelque sorte dans "une case" et n'a pas (encore) d'options propres, elles dépendant soit de sa taille propre (pour le template "une colonne") soit de la taille définie en code (pour la grille et marseille).
L'édition des publications est encore rudimentaire et demande pas mal de réflexion pour que le système reste pratique et modulaire, mais le redimensionnement des médias semble être utile et pratique.

> Est-ce un choix ? La publication en colonne édite les commentaires mais ce n'est pas le cas pour les autres mises en page ...

Oui, c'est un parti pris. Les templates de publication sont éditables en code CSS (il y a des instructions dans le dossier `dodoc/templates/_exemple` si vous suivez le chemin indiqué en bas de page) et définissent à eux seuls comment s'afficheront les publications qui utilisent leur template.

Nous n'avons pas encore conçu une approche plus accessible car c'est un travail important et il nous manque des retours sur le terrain (comme les votres) pour affiner le système avant de le réaliser.

Nous avons cependant plusieurs autres approches plus permissives en tête et que nous avons testé sur d'autres outils, notamment sur carreau.js : https://github.com/louis-ev/carreau.js
Cela correspond-il plus à la manipulation d'une publication tel que vous l'imaginiez ?

**Comment by lrault2** [comment]
La proposition d'en-tête semble suffisamment précise.
Peut-il y avoir aussi un espace pour identifier le nom du créateur de la publication ? Peut-être au moment de cette création ...

La publication telle que vous la proposez pour le moment me convient, c'est juste que le cadrage ne convient pas forcément à toutes les prises de vues. C'est ce point qui est plus gênant mais ce que vous faites sur l'autre projet est effectivement très intéressant.

**Comment by louis-ev** [comment]
Nous avions dans l'idée d'ajouter un menu d'édition des médias dans la
bibliothèque : à l'ouverture d'un pop-up média (où il est possible déjà
d'ajouter une légende), permettre de recadrer les photos pour ne garder que
ce qui est pertinent. Nous pensions aussi ajouter une fonctionnalité de
dessin type "annotation" simple sur une image ou une vidéo. Qu'en
pensez-vous ? Est-ce que ça répondrait à ce besoin ?

**Comment by lrault2** [comment]
Oui, très bien pour le recadrage du média.
Si je comprends bien, "l'annotation" permettrait de commenter le média ?
Je pensais plutôt à identifier le créateur... en fait en réfléchissant, le créateur peut déjà s'identifier dans le titre de la publication (ex : réalisation d'un origami par Mathis". Peut-être est-il possible d'avoir deux champs "caractérisés" différemment : un pour le titre, un pour le ou les auteurs.

**Comment by lrault2** [comment]
J'ai commencé à travailler avec des enseignants en classe avec dodoc. Il mesure bien la pertinence de l'outil et les possibilités offertes.
Les points soulevés dans ce fil sont importants pour eux : 
- calibrage des médias lors de la création de la publication
- calibrage du pdf ( personnalisation de l'en-tête, commentaire des médias disponibles pour chacune des mise en page proposée 
Le dispositif sous carreau.je semble pertinent pour la modularité de la mise en page.
Merci

**Comment by louis-ev** [comment]
Je me pose une question sur le recadrage des photos : que devient la photo non-recadrée ? Est-ce qu'elle est supprimée et remplacée par la photo recadrée, ou est-ce que quand on recadre une photo ça créer un nouveau média en haut de la bibliothèque ? Est-ce gênant que l'image non recadrée disparaisse ? On pourrait aussi la conserver dans le dossier mais n'afficher que la version recadrée dans dodoc (pour qu'elle puisse éventuellement être importée dans une bibliothèque pour ne pas la perdre). Qu'en pensez-vous ?

**Comment by lrault2** [comment]
Si conserver l'original ne pose pas de souci sur le fonctionnement général alors autant le conserver. Sinon lors du recalage un pop-up pourrait avertir de l'irreversibilité de l'opération.
Ce n'est pas tant le recadrage et le redimensionnement dans la bibliothèque que dans la publication qui est important. Ainsi avoir sa bibliothèque de médias originaux que l'on peut recadrer / redimensionner à loisir dans une ou plusieurs publications est un atout. 
Mais si comprends bien, permettre ces opérations dans la publication entraîne obligatoirement la creation de nouveaux médias aavec les nouveaux paramètres définis alors ?

**Comment by louis-ev** [comment]
Oui et non. 
Pour l'instant, les médias affichés dans la publication n'ont pas de paramètres propres, ils sont des liens dynamiques vers les médias de la biblitothèque. Par exemple, en ouvrant le fichier d'un publication située dans `mon-dossier/mon-projet/publications/nom-de-ma-publication.txt`, on y trouve : 
```
medias: 

-
name: 01-photos/20170120_091318.txt
-
name: 01-photos/20161225_223806.txt
-
name: 01-photos/20161225_223744.txt
-
name: 01-photos/20161225_223750.txt
```

Mais le moteur qui lit les fichiers texte est conçu pour gérer la syntaxe suivante : 
```
medias: 

-
name: 01-photos/20170120_091318.txt
echelle: 92%
-
name: 01-photos/20161225_223806.txt
point-recadrage-debut: 8% 12% 
point-recadrage-fin: 88% 92% 
-
name: 01-photos/20161225_223744.txt
fond-de-couleur: vert
-
name: 01-photos/20161225_223750.txt
rotation: 12deg
```

Cela permettrait de préciser des informations sur chaque média sans toucher à l'original de la bibliothèque. Nous n'avons pas encore créé de publications sur ce modèle mais c'est dans les objectifs.

Ma question portait plutôt sur le recadrage de média pour corriger des soucis à la capture (par exemple, un doigt visible ou un visage à enlever). Ce qui appliquerait l'opération à toutes les publications qui utilisent ce média. Ce recadrage me parait plus nécessaire dans l'immédiat que celui par publication, non ? Dans ce cas nous pourrions créer un fichier `xxx-crop.jpeg`, qui prend le pas sur le fichier original dans l'interface dodoc mais dont l'original `xxx.jpeg` resterait présent dans le dossier `01-photos` (de manière à pouvoir être réimporté, par exemple). On pourrait aussi ré-afficher la version non-recadrée en supprimant la version recadrée depuis le dossier 01-photos.

![image](https://cloud.githubusercontent.com/assets/1948417/22626931/26e617b8-ebb8-11e6-9621-17ba799efbf1.png)

**Comment by paulinegourlet** [comment]
1) **pour les médias dans la bibliothèque** -- PRIORITE dans le pop-up: recadrage, rotation, colorimétrie PUIS annotation sur le média (exemple, entourer des éléments, faire une flèche, dessiner par dessus) 
Je trouve l'idée de ne pas écraser le média d'origine intéressante, si on affiche la dernière version créée dans l'interface.

2) **pour les médias dans la publication**, il faudrait en effet pouvoir "bouger" les médias dans leur "case" dans la publi pour cadrer sur ce que l'on veut. Cela veut dire ajouter des options qui apparaissent au survol d'un case (rotation, souris avec un curseur différent, type 
![capture d ecran 2017-02-08 a 11 24 59](https://cloud.githubusercontent.com/assets/7995654/22746288/4368b5c2-edf1-11e6-8fac-eff4a722c4be.png)

3) **pour l'export en PDF**, il faut RAPIDEMENT reprendre:
a. le css de l'en-tête (enlever do.doc et les boutons) --> cf maquette (en cours)
b. ajouter une image prise à partir d'une vidéo pour les médias vidéo/stop-mo
c. Régler le problème de déformation des contenus
d. dans les templates, quand on choisit, avoir le choix d'afficher ou non les légendes (cf. mock-ups du menu de sélection de template à la base)
e. Proposer d'autres mises en page, plus adaptées au papier (format A4) -- proposer de plier /agrafer pour faire des petits carnets par ex?

**Comment by lrault2** [comment]
Ces propositions correspondent aux besoins actuels.

**Comment by louis-ev** [comment]
Note : à venir dans dodoc 6.0.0 = un autre moteur pour générer des PDF, qui affiche bien les aperçus des vidéos d’une publication.
