### ISSUE TITLE
Logique d'école et du travail de l'enseignant

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#243]
Cet outil tel que je le vois peut devenir le compagnon des enseignants qui souhaitent faire évoluer leur pratiques vers plus de valorisation, vers plus de différenciation, vers plus de travaux collaboratifs et coopératifs. 

Les fonctionnalités déjà proposées sont très riches mais une possibilité supplémentaire peut le rendre encore plus attrayant.
Les élèves travaillent sur des projets et pour cela engagent plusieurs actions qui peuvent être objets de captures (prises de vue). Ces actions se réfèrent à certaines compétences, connaissances des programmes.

Après avoir cliqué sur "Prise de vue" mais avant d'avoir accès aux quatre types de capture : 
--> est-il possible de mettre en place une série d'images cliquables qui référaient aux domaines, disciplines, connaissances des programmes ?
ou bien
--> est-il possible de mettre en place un système de listes déroulantes pour choisir le domaine, la discipline, les connaissances en jeux ?

Que ce soient ces images cliquables ou ces items choisis, ce serait pris en compte automatiquement dans la publication.
J'imagine que cela représente énormément de travail de développement informatique mais pour ce qui concerne les items ou les images des enseignants peuvent fournir leurs documents...

**Comment by louis-ev** [comment]
> Cet outil tel que je le vois peut devenir le compagnon des enseignants qui souhaitent faire évoluer leur pratiques vers plus de valorisation, vers plus de différenciation, vers plus de travaux collaboratifs et coopératifs.

Super ! C'est aussi ce que nous imaginions et avons expérimenté !

Je ne suis pas sur de bien comprendre les 2 pistes : 

- il me semble que la première est une sorte de tutoriel qui vient indiquer juste avant la capture le type de documentation demandée ?

- pour la deuxième, vous évoquez la possibilité de catégoriser les contenus au moment de leur capture, c'est bien ça ? Les taxinomies seraient définies à quel moment ? Par projet ou par dossier ? Comment seraient-ils utilisés dans la publication ?

**Comment by lrault2** [comment]
Les deux pistes orientent les élèves (ou les enseignants) vers un tri, une classification de leurs travaux au regard des programmes scolaires : 

-1--> des images cliquables plus adaptées pour la maternelle ou pour les non-lecteurs.
Exemple pour un élève de maternelle : il doit reconstituer son prénom à l'aide des étiquettes-lettres, do.doc permet de prendre en photo l'évolution de ces essais.
Cela à avoir avec la reconnaissance des lettres donc avant de commencer sa prise de vue l'élève aura cliqué sur l'image-cliquable qui permet de catégoriser ce type de travail. Cette image-cliquable sera utilisée à chaque fois qu'il aura ce type de travail à faire. Au cours de l'année, les demandes de l'enseignante deviendront plus difficiles mais seront identifiées toujours sous cette image-cliquable. Lors de la publication cette image-cliquable serait intégrée à la prise de vue.

-2--> les listes déroulantes (plus adaptées aux lecteurs et plus précises du fait du grand nombre de connaissances / compétences) relèvent du même objectif : identifier, classer.
Un élève va montrer sa procédure pour faire un tracé géométrique. Avant la prise de vu, il choisit le domaine "mathématiques" puis "espace et géométrie" et enfin la compétence "représenter une figure simple".
Ici aussi, ces choix seraient directement intégrés à la prise de vue et ensuite à la publication.


Dans les deux cas : 
--> ce choix par image-cliquable ou par liste de choix serait fait juste avant la prise de vue, donc une fois que l'élève a choisi le dossier puis le projet dans lequel il veut faire apparaître son travail, sa proposition.
--> la possibilité d'un commentaire déjà existante permet aux élèves de préciser si besoin.

**Comment by louis-ev** [comment]
Je vois mieux, merci pour les explications.
Dans l'absolu ça n'est pas prévu pour l'instant dans le futur de dodoc.
Mais peut-être que nous pouvons trouver un moyen simple d'ajouter ces instructions ? Cocher une case sur un média pour lui demander de figurer sur le page de capture sous forme de vignette, au-dessous ou au-dessous du flux de l'écran ?
@sarahgarcin @paulinegourlet vous avez une idée là-dessus ?

**Comment by lrault2** [comment]
Effectivement, ça peut être une solution.
Cela suppose de créer une bibliothèque de médias en référence aux programmes. Pour simplifier et diminuer le nombre, il faudrait travailler à une série de vignettes en référence au socle commun de connaissances et de compétences.

**Comment by louis-ev** [comment]
Plus je réfléchis à cette fonction et plus ça me paraît difficilement compatible avec le design de la page de capture (qui risque de devenir, très, très lourde et complexe).

À un moment nous avions envisagé d'ajouter une fonctionnalité permettant de "sortir" un pop-up de média pour le faire s'afficher dans sa propre fenêtre, ce qui permettrait de laisser toujours visible une vidéo ou une image de référence ou d'enregistrer la bande sonore d'une vidéo sans le son. Peut-être que c'est aussi une solution pour votre cas d'usage : en poussant ce principe, on pourrait imaginer pouvoir ouvrir une nouvelle fenêtre dans un autre dossier/projet, par exemple sur une bibliothèque de média de référence, et qui resterait visible et navigable à côté du projet de l'enfant. Actuellement c'est déjà ce qu'il se passe avec la page d'une publication : elle s'ouvre dans une fenêtre dédiée (mais se ferme si on quitte la page de bibliothèque). D'ailleurs, peut-être que finalement c'est une publication comportant les instructions qu'il faudrait imaginer ?
En imaginant que la fenêtre de la publication reste ouverte quel que soit la page navigué par ailleurs, ça pourrait peut-être fonctionner.

Je vous ai fais une simulation en pièce jointe, qu'en pensez-vous ?

<img width="1643" alt="capture d ecran 2017-01-18 a 19 05 06" src="https://cloud.githubusercontent.com/assets/1948417/22076659/4db18fae-ddb1-11e6-965a-b656a040984d.png">

**Comment by lrault2** [comment]
Si je comprends bien, cette seconde fenêtre de médias de références s'afficherait à la demande et pourrait "alimenter" la prise de vue pour définir la compétence présentée ? 
Ce serait parfait.

**Comment by louis-ev** [comment]
Oui, l'enseignant pourrait créer un dossier dédié et y regrouper tous ses médias, et éventuellement préparer une publication pour chaque instruction. En jonglant avec deux fenêtres cote à cote il y aurait la possibilité d'ouvrir la publication et la page de capture d'un autre projet.

En fait vous pouvez déjà tester ce système en copiant l'adresse qui est dans le pied de page de dodoc directement dans un navigateur web, depuis la même machine. Vous pouvez ainsi créer autant de fenêtre de dodoc en parallèle que nécessaire, chacune sur un projet ou une publication différente. Les contenus sont synchronisés sur toutes les pages.
Si vous pouvez confirmer que ça répond bien à l'usage, nous pouvons l'ajouter dans la liste des fonctionnalités pour dodoc 5.1.0 et faire ça proprement dans l'interface.
Merci !

**Comment by lrault2** [comment]
J'ai fait le test mais je ne suis pas certain d'avoir bien compris.
Une petite vidéo dans ce dossier hubic : [http://ovh.to/xNAG2aE](http://ovh.to/xNAG2aE)
Si c'est la bonne démarche... cela ne semble pas fonctionner.
@+

**Comment by louis-ev** [comment]
Ha oui non je me suis mal exprimé, il n'est pas possible de passer un média
d'une fenêtre à une autre. Je pensais plutôt à préparer une publication et
la laisser ouverte à côté comme instruction/référence.
Voici une démo :
https://www.youtube.com/watch?v=qL51te2cMww&feature=youtu.be
Est-ce que ça pourrait marcher ?

**Comment by lrault2** [comment]
Ca peut servir effectivement.

La bibliothèque de médias tout comme les publications appartiennent donc au projet. Serait-il possible de partager la bibliothèque créée par un groupe d'élèves pour qu'un autre groupe l'intègre à un nouveau projet ou bien pour qu'ils puissent venir y prendre des médias selon les besoins.
Exemples : 
1- la classe travaille sur un film en stop motion - un groupe réalise une partie - des scènes réalisées vont se répéter - Un autre groupe va y travailler et souhaite récupérer des photos déjà prises...
2- compte-rendu d'une sortie, d'une expérience - un groupe dépose ses médias et partage - un autre groupe peut compléter ses médias en se "servant" dans la bibliothèque partagée...

Ce principe pourrait ainsi être repris à l'envie par l'enseignant pour déposer des images à utiliser...
Merci

**Comment by louis-ev** [comment]
C'est encore limité mais la fonction d'import est censée combler ce besoin : l'organisation des fichiers de stockage de dodoc (le dossier dodoc) reprend l'arborescence `dossier/projet/type-de-media`. L'idée est de placer le dossier de stockage à un endroit facilement accessible (par exemple, le dossier `Mes documents` en passant par l'option en pied de page) et de naviguer à l'intérieur avec l'option "Importer un média" pour récupérer des médias d'autres projets. Cela le copie alors dans le dossier correspondant au projet ouvert.
Pour l'instant cela n'est pas possible avec un média texte (je vais l'ajouter dans les issues) mais ça fait partie des objectifs, pour que tous les médias créés dans un projet puissent être aussi importés dans un autre projet sans soucis.
Est-ce que ça vous semble correspondre ?

**Comment by lrault2** [comment]
Avec cette évolution, la collaboration prendrait encore de l'ampleur. 
Super.
Cependant, si le dossier de partage se trouve dans "mes documents" (si c'est bien le dossier de l'ordinateur dont il est question !) alors sera-t-il toujours accessible à partir d'un autre appareil connecté à do-doc via un navigateur web ?

**Comment by louis-ev** [comment]
Non, malheureusement, car ces périphériques n'ont pas accès au système de
fichier de l'application dodoc.
Par contre une tablette, un smartphone ou le navigateur web d'un autre
ordinateur peut télécharger ces contenus puis les envoyer en passant par
"Importer un média". Pas l'idéal mais pas impossible non plus. Mais à
priori cela se ferait depuis le dodoc central, donc je ne suis pas sur que
ce soit embêtant.

**Comment by louis-ev** [comment]
Bien sur l'ipad pose encore problème s'il ne permet pas le téléchargement.
Safari Technology Preview (qui est en gros la version béta de Safari et
présage de ce qui est à venir) le supporte, alors c'est tout à fait
possible que la prochaine version de Safari sur ipad (et de tous les
navigateurs de l'ipad, car ils utilisent tous safari en tâche de fond)
supporte le téléchargement de médias.

Le lun. 23 janv. 2017 à 17:40, Louis Eveillard <barlou15@gmail.com> a
écrit :

**Comment by lrault2** [comment]
Si l'interface du do-doc central permet à un élève de naviguer aisément dans les différents dossiers pour importer des médias dans un autre dossier, alors, l'essentiel sera atteint. La problématique de l'I-pad restera secondaire, puisque l'ordinateur pourra gérer ces partages.

**Comment by louis-ev** [comment]
Oui, je suis d'accord.
On pourrait améliorer le système en plaçant automatiquement le sélecteur de
fichier au niveau des dossiers de dodoc lorsqu'il s'ouvre, pour que la
navigation soit plus facile. Je le note pour la prochaine version.

**Comment by lrault2** [comment]
Parfait.

Par ailleurs, pour ma culture personnelle : 
--> si je comprends bien le fonctionnement de cet espace d'échanges (github), vous déposez votre projet, notez les évolutions travaillées, et sollicitez des aides si besoin ?
--> je n'y connais rien en programmation, mais quels outils utilisez-vous ?
merci

**Comment by louis-ev** [comment]
Pour faire simple : 
Github est basé sur une technologie open-source, git, qui permet de faire du suivi de code par "commit". Un commit est un ensemble de modifications de code informatique appliqué à des fichiers pour corriger un bug, ajouter une fonctionnalité, etc. 
La liste des commits de dodoc se trouve ici et la naviguer permet effectivement de remonter dans le temps pour voir toutes les étapes du travail : https://github.com/l-atelier-des-chercheurs/dodoc
Comme nous travaillons en open-source, cela permet à n'importe qui d'apprendre de nos méthodes et de potentiellement reprendre notre travail pour l'emmener ailleurs.

Github est une société qui fournit gratuitement un hébergement de git pour les projets open-source, sans restriction. Ils fournissent également un système de suivi de "tâches" (appelées les issues) qui peuvent être couplées aux commits (qqun créé une tâche "ajouter l'option pour importer des gifs" et en retour quelqu'un d'autre commit le code qui correspond à cette option). Très pratique, surtout sur les projets comportant de nombreux collaborateurs. Si quelqu'un souhaite prendre en charge une issue, il peut aussi nous soumettre du code, que nous pouvons rapatrier après validation.

Pour ce qui est des outils de programmation, nous utilisons les langages du web : HTML, CSS et JavaScript. L'application dodoc embarque à la fois un serveur web et un navigateur très simplifié, Chromium. Donc quand vous démarrez dodoc, vous lancez un serveur web sur votre machine et aussi un navigateur qui pointe sur le serveur web. Le serveur est entièrement écrit en JavaScript et utilise [node.js](https://en.wikipedia.org/wiki/Node.js).

dodoc utilise de très nombreuses dépendances open-source, c'est à dire des paquets de code externes qui sont développés par d'autres dans le but de fournir une fonctionnalité spécifique à de très nombreux programmes. Il y en a une pour produire des PDF à partir d'une page web, une pour enregistrer des images, une pour convertir les vidéos, une pour enregistrer des fichiers texte, etc.
Vous pouvez retrouver cette liste dans le fichier `package.json` (sous le nom `dependencies`), qui déclare en quelques sortes l'identité et la configuration du programme lors de l'installation : https://github.com/l-atelier-des-chercheurs/dodoc/blob/master/package.json

N'hésitez pas si vous avez d'autres questions.
D'ailleurs, il faudrait que nous nous attaquions à une documentation exhaustive des fonctionnalités et des fiches d'usage du logiciel pour aider à comprendre son utilisation, et je me resservirai très probablement de l'explication que je viens de vous faire pour la section "Technologies et développement".

**Comment by louis-ev** [comment]
Je pense à une dernière chose sur github (pour la prochaine fois où vous avez besoin de nous envoyer des issues) : pour utiliser au mieux ce système, il faut décomposer chaque besoin et bug en tâches simples. Par exemple un sujet par question ou retour de manière à pouvoir bien les référencer individuellement, leur attribuer un numéro de version où ils seront réalisés, et éviter qu'ils ne se perdent dans le flux de discussion d'une issue.

**Comment by lrault2** [comment]
Merci bien d'avoir éclairé ma lanterne/
@bientôt pour de nouvelles "issues".
