### ISSUE TITLE
permettre de recadrer les médias photo sur encart projet

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#244]

**Comment by lrault2** [comment]
![image-projet](https://cloud.githubusercontent.com/assets/24780752/22564363/8bd0994a-e984-11e6-9636-50e7e6153da5.jpg)
Permettre de recadrer l'image de personnalisation des projets...

**Comment by louis-ev** [comment]
dodoc 7 gère différemment les vignettes projets, à voir si c’est encore nécessaire ?
