### ISSUE TITLE
Export de vidéos et stop-motion en gif

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#249]
Ajouter l'option d'exporter un gif depuis le panneau d'édition d'un media, sous l'option de téléchargement.
Ne générer le gif que lorsque l'option est sélectionnée. Afficher le lien dans une notification en bas à gauche ? Ou un aperçu du progrès + file picker ?

**Comment by paulinegourlet** [comment]
Qu'est ce qui est lisible sur un pdf ? Le gif marche ?

**Comment by jubonhomme** [comment]
Je ne sais pas si ça peux aider... je ne suis pas doué en code js :
https://github.com/jnordberg/gif.js

**Comment by louis-ev** [comment]
C’est pas une mauvaise piste non !
Mais si on veut que ça passe sur les machines les moins puissantes (type Raspberry) et dans les navigateurs contraignants (Apple) on peut pas faire ça côté navigateur avec des web workers :/
C’est forcément côté server, avec ffmpeg (comme pour le montage vidéo), qui est bcp mieux optimisé pour produire des contenus vidéos sous tous les formats :)

**Comment by jubonhomme** [comment]
Exemple avec ffmpeg :
https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality

https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/

**Comment by louis-ev** [comment]
Oui, j’y pense de temps en temps.
C’est comme pour le fait de télécharger des versions allégées des images : je pense que ça serait bien pratique de pouvoir récupérer une version avec une résolution un peu inférieur mais du coup beaucoup plus légère.

**Comment by louis-ev** [comment]
Retomber sur cette issue 6 ans après et la reporter encore une fois 😄 
On en reparle pour la v10.1 !

**Comment by jubonhomme** [comment]
J'aurais bien ajouté un gif ici mais ... ;)

**Comment by jubonhomme** [comment]
Une piste avec cet exemple de La Digitale

https://codeberg.org/ladigitale/digigif

**Comment by jubonhomme** [comment]
On ferme ici ? 
Ou l'export GIF est possible aussi pour une vidéo hors mode animation ?

**Comment by louis-ev** [comment]
Oui, ce sera possible, mais pour l'instant je n'ai pas remis le stopmotion :)

**Comment by jubonhomme** [comment]
L'export en format GIF est maintenant possible pour :
- Capter / Animation / Assembler 
![image](https://github.com/user-attachments/assets/57e1487b-f155-433c-97e1-2624ac2e6f67)


- Fabriquer / Animation Image par Image
![image](https://github.com/user-attachments/assets/81e89009-e829-420a-944b-5aa632bf68a3)
