### ISSUE TITLE
pouvoir inverser le sens de lecture d'un stopmotion

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#250]

**Comment by paulinegourlet** [comment]
pas prioritaire non plus

**Comment by louis-ev** [comment]
Je le laisse de côté

**Comment by louis-ev** [comment]
Une recette dans la marmite ? Ou une option dans le menu "ajuster" à droite ?
Peut s’appliquer à toutes les vidéos

**Comment by jubonhomme** [comment]
Recette "inverser le début et la fin" répond à la question... avec la recette image par image on a deux solutions possibles.
Tu peux clôturer je pense
