### ISSUE TITLE
diversifier l'import de médias

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#257]
Faire une liste des type de média.
Les importer tel quel dans un dossier de cache
Tenter de les reconvertir, puis de les importer comme médias de dodoc avec pour `informations` le nom du fichier original.

**Comment by louis-ev** [comment]
Permettre l'import de fichiers texte comme médias texte

**Comment by lrault2** [comment]
Pouvoir importer plusieurs médias à la fois dans la bibliothèque de média d'un projet, à partir de l'ordinateur

**Comment by paulinegourlet** [comment]
permettre l'import de média .wav (car là on ne peut pas importer les fichiers sons qu'on aurait préalablement fait avec do.doc...)

**Comment by louis-ev** [comment]
Ajouté (pour tout sauf le texte, qui peut être copié collé dans un bloc texte, vu que c’est du markdown ça parait mieux).
