### ISSUE TITLE
Export PDF

### ISSUE THREAD

**Issue by ericgaspar** [l-atelier-des-chercheurs/dodoc#261]
Lors du téléchargement d'une publication PDF, le titre par défaut est publication.pdf au lieu de Titre_de_la_publication.pdf

**Comment by ericgaspar** [comment]
au lieu de **Titre de la publication.pdf**

**Comment by louis-ev** [comment]
Noté, ça serait effectivement mieux. Merci !

**Comment by louis-ev** [comment]
à venir dans dodoc 5.2.0
