### ISSUE TITLE
Personnalisation des dossiers

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#264]
Est-il possible de personnaliser les dossiers avec une image, tout comme les projets (+recadrage) ?
Merci

**Comment by louis-ev** [comment]
À la place des projets qu'ils contiennent, c'est ça ? Où proposez-vous de mettre cette image ?

**Comment by lrault2** [comment]
A côté du nom du dossier (ici HomeLab) comme pour le projet "Matériels". 
![screenshot_20170203-210540](https://cloud.githubusercontent.com/assets/24780752/22606670/f1144aa6-ea54-11e6-890b-94c80c9328f9.png)

**Comment by paulinegourlet** [comment]
Je ne suis pas sûre de voir l'intérêt de mettre une image pour un dossier, comme il contient plusieurs projets avec possiblement des contenus très différents.

**Comment by paulinegourlet** [comment]
ça me fait d'ailleurs penser à l'idée de badges pour identifier les compétences acquises à la réalisation d'un projet. Peut-être que l'enseignant pourrait identifier ces badges pour chaque dossier ?

**Comment by lrault2** [comment]
L'idée de cette image identifiant le dossier correspond aux usages d'élèves non-lecteurs. Avec une image qu'ils auraient repérées, les élèves pourraient naviguer dans les dossiers facilement, en autonomie. Alors, effectivement, le système d'icônes se référant une identification serait très pertinent.
L'utilisation de badges est de même très pertinente.

Dans la classe : 
--> un enseignant utilise souvent des "bannettes" pour un élève ou un groupe d'élèves : "dossier" dans do.doc. 
--> l'élève la repère facilement à la couleur, ou une étiquette : dans do.doc l'icône. 
--> cette "bannette" peut contenir différents travaux : "projets" dans do.doc identifiés par une image
=> les badges utilisés en classe viennent valider, situer les travaux

Si do.doc peut faire ça, l'usage du numérique entrerait alors complètement dans la logique déjà en classe et encouragée par les nouveaux programmes : individualisation, collaboration, évaluation positive, suivi du parcours....

**Comment by louis-ev** [comment]
On s’approche lentement mais sûrement de ça avec la nouvelle version, non ?
Codes QR = accès à des projets
Tags NFC = activer un auteur

**Comment by lrault2** [comment]
Je pense même que l'approche est moins lente que ça... Les usages devraient le confirmer.
