### ISSUE TITLE
copie de dossier et de projet

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#265]
Donner la possibilité de dupliquer un dossier tout en le renommant avec tous ses projets.
donner la possibilité de copier un projet d'un dossier vers un autre.

**Comment by louis-ev** [comment]
> Donner la possibilité de dupliquer un dossier tout en le renommant avec tous ses projets.

Cela peut se faire facilement en passant par l'explorateur de fichier. Il suffit ensuite de relancer dodoc ou de changer de page pour que ce dossier s'affiche. Pour le renommer sans passer par dodoc il suffit d'éditer le fichier "dossier.txt". 
Le but de cette démarche est aussi de faire comprendre que tout le contenu repose dans des fichiers et des dossiers qui peuvent être manipulés directement.

![image](https://cloud.githubusercontent.com/assets/1948417/22599662/f03541e8-ea37-11e6-8785-e7f6f53cf4b9.png)

Par contre on pourrait améliorer les choses en ouvrant l'emplacement des contenus au clic sur le chemin qui est dans le pied de page par exemple : https://github.com/l-atelier-des-chercheurs/dodoc/issues/267

**Comment by lrault2** [comment]
Bonsoir,
C'est effectivement ce que j'ai fait et en le faisant je me suis dit que l'utilisateur moyen pouvait ne pas voir cela de lui même. .. le raccourci peut être une aide. Merci

**Comment by louis-ev** [comment]
Cette fonctionnalité arrive dans dodoc 5.2.0
D'ailleurs le footer prend moins de place et est un peu plus clair : 

![image](https://cloud.githubusercontent.com/assets/1948417/22619372/a26e6680-eaf3-11e6-8155-ca0294fabea5.png)

Il mériterait un bon lifting d'ailleurs. @sarahgarcin, @paulinegourlet  ?
