### ISSUE TITLE
activer le changement de langue

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#266]
Au lancement, détecter la langue du système et charger les termes nécessaires dans `dodoc.js`

**Comment by louis-ev** [comment]
Actif. Il existe maintenant un fichier lang.fr.json et lang.default.json qui contiennent respectivement le français et l'anglais.

**Comment by paulinegourlet** [comment]
Il faut un bouton (dans le footer ?) pour changer la langue.

**Comment by louis-ev** [comment]
La difficulté est que la langue est gérée surtout côté server et pas côté client (comme dans les Cahiers). Du coup tous les utilisateurs partagent une langue sur le modèle actuel. 

Donc changer la langue dans le footer demande un redémarrage de l'app. À priori cela ne devrait être possible que sur l'app, et pas dans les navigateurs donc. Non ?
