### ISSUE TITLE
le déplacement du dossier des contenus ne copie pas tous les contenus déjà créés

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#271]
C'est un problème car 1) j'ai l'impression qu'ils ont été supprimés, 2) si je veux vérifier, je n'ai plus le lien pour aller les chercher et je ne les retrouve pas !

**Comment by louis-ev** [comment]
Je n’ai pas compris… Le retour est vieux, tu peux me réexpliquer ? 
Peut-être un truc à ajouter à la doc aussi ?
https://latelier-des-chercheurs.fr/docs/manuel-dodoc

**Comment by louis-ev** [comment]
Ok j’ai compris. Je vais supprimer cette fonctionnalité qui n’apporte à priori pas grand chose mais pose visiblement pas mal de problèmes.
