### ISSUE TITLE
Affichage sur tablettes / téléphones

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#272]
Pas mal des choses que j'avais notées sur la liste (à la Générale --> Sarah) n'ont pas été implémentées. A reprendre (Sarah, tu as encore la liste?)
Par ex.: - affichage dans le bandeau sur iPad (cf. screenshot de Lionel R. > le chemin prend deux lignes, on avait dit de mettre "...")
- ![screenshot_20170208-175641](https://cloud.githubusercontent.com/assets/7995654/22748042/ca702992-edf6-11e6-9bef-1d86cd3b2219.png)
- ![screenshot_20170208-175400](https://cloud.githubusercontent.com/assets/7995654/22748053/d27e9dbc-edf6-11e6-8ed3-5289503be252.png)
- ![screenshot_20170208-175454](https://cloud.githubusercontent.com/assets/7995654/22748062/d9e6f018-edf6-11e6-87fb-9a1626b0252a.png)

Il y avait d'autres choses, il faudrait retrouver cette liste.

**Comment by louis-ev** [comment]
Pareil, recréer avec les bugs de la v7 si besoin.
