### ISSUE TITLE
Linux 5.2.0

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#276]
Bonjour
J'ai suivi le tuto trouvé sur ce site [http://appimage.org/] en tentant d'installer une version 32 bits et une 64bits de subsurface et seule la 32 est passée.
Mes PC sous linux commence à dater et je pense qu'il me faudrait des .AppImage en 32bits... Est-ce possible ?
Merci

**Comment by louis-ev** [comment]
Bonjour,
malheureusement la dépendance "Sharp" (le module qui gère la manipulation d'images) n'est pas simple à installer pour du linux 32 bits. Je n'ai pas réussi à le compiler sous Linux mais uniquement sous macOS. Voici le AppImage "ia32" : https://latelier-des-chercheurs.fr/dodoc-5.2.0-ia32.AppImage

Note pour plus tard : compilé avec `node_modules/.bin/build --linux --ia32`

**Comment by louis-ev** [comment]
Avez-vous pu tester ce fichier sous linux 32 bit ?

**Comment by louis-ev** [comment]
Je ferme pour l'instant, si vous avez du nouveau je peux rouvrir l'issue.

**Comment by lrault2** [comment]
Bonjour,
(me voilà de retour)
![image](https://cloud.githubusercontent.com/assets/24780752/24199420/c1819648-0f09-11e7-9c54-7816c7f2e7eb.png)
J'ai bien installé node sous linuxmmint.
J'essaie ensuite d'installer DoDoc.
![image](https://cloud.githubusercontent.com/assets/24780752/24199531/362edb68-0f0a-11e7-8ec3-b02da623fdcf.png)
Merci pour votre aide...

**Comment by louis-ev** [comment]
À priori le plus simple (vu que vous avez déjà installé node) est de suivre la méthode 2 : https://github.com/l-atelier-des-chercheurs/dodoc#method-2---the-long-way-for-development-and-editing-the-source-code

Les AppImage pour linux 32 bits et ARM posent encore des soucis apparement.

**Comment by lrault2** [comment]
Bonjour
Je persiste ... Je pense avoir suivi le tuto.
Mais des erreurs à voir en PJ.
merci


[npm-debug.log.zip](https://github.com/l-atelier-des-chercheurs/dodoc/files/864616/npm-debug.log.zip)

**Comment by louis-ev** [comment]
Cela demande trop de travail de sortir des versions 32 bits en plus des versions 64 bits pour les 3 plate-formes, du coup nous préférons nous focaliser sur la résolution de bugs des versions 64 bits.
On pourra en reparler plus tard une fois que la version 6 est stabilisée, éventuellement.
