### ISSUE TITLE
Probleme avec la publication vers un FTP

### ISSUE THREAD

**Issue by prof2meca** [l-atelier-des-chercheurs/dodoc#277]
J'ai créé une page perso sur Orange

Je crée une publication avec Dodoc et je souhaite l'exporter vers mon site perso grâce à l'option ENVOYER LA PUBLICATION VERS UN FTP

Je renseigne les champs, et Dodoc me dis : La publication a bien été transférée au server, mais je ne retrouve rien dans le répertoire de ma page.

Merci pour l'aide que vous apporterez à la résolution de mon problème

**Comment by sarahgarcin** [comment]
L'option _Envoyer la publication vers un ftp_ est encore en développement mais elle devrait fonctionner. Pour que ça marche correctement, quand vous renseignez les champs il faut bien indiquer dans le champ _Sous Dossier_ le dossier dans lequel vous souhaitez déposer votre publication. Le mieux est de créer un dossier spécifique sur votre serveur. 

Dites nous si cela fonctionne pour vous.

**Comment by prof2meca** [comment]
j'ai bien suivi à la lettre la procédure

j'ai créé via FTP un dossier dodoc et je souhaite faire l'export dans ce
dossier mais aucun fichier n'apparait dans ce dossier

je vous joins les impressions d'écrans

**Comment by sarahgarcin** [comment]
Lorsque que l'on clique sur le bouton envoyer vers un ftp, normalement dodoc génère les fichiers web de la publication. Vous pouvez ensuite les mettre en ligne manuellement via un ftp. 
Dans Dodoc, en bas de chaque page, il y a des petites mentions d'information, l'une d'elle vous donne le dossier dans lequel les contenus générés par Dodoc sont stockés. Dans ces contenus, il y a un dossier publications dans lequel vous devriez trouver vos publications générées avec un fichier index.html, un fichier template.css et un dossier medias contenant tous les médias de la publication.

**Comment by louis-ev** [comment]
Bonjour,
votre bug est-il résolu ? puis-je fermer cette issue ?

**Comment by prof2meca** [comment]
Pas encore teste

Nous avons tester dodoc lors des portes ouvertes et plusieurs personnes ont
eu un probleme commun :

Ils se sont connectés a dodoc par contre la mise a jour des dossiers ne se
faisait pas : ils ne voyaient pas les projets et les dossiers. Le probleme
a ete rencontre sur des tablette avec android sur un ipad et un nokia

Je vais me pencher sur le probleme

Le 12 mars 2017 1:32 PM, "Louis Eveillard" <notifications@github.com> a
écrit :

Bonjour,
votre bug est-il résolu ? puis-je fermer cette issue ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/l-atelier-des-chercheurs/dodoc/issues/277#issuecomment-285941534>,
or mute the thread

**Comment by louis-ev** [comment]
> Ils se sont connectés a dodoc par contre la mise a jour des dossiers ne se
faisait pas : ils ne voyaient pas les projets et les dossiers. Le probleme
a ete rencontre sur des tablette avec android sur un ipad et un nokia

Très possible que cela vienne du navigateur utilisé et de l'appareil : si c'est un navigateur embarqué (donc, ni Firefox ni Chrome), c'est probablement l'absence du support de fonctionnalités avancées que nous utilisons.

**Comment by prof2meca** [comment]
J essaie de voir si l export ftp fonctionne mais je suis incapable de
retrouver le bouton pour exporter

Peux tu m aider ?

Le 12 mars 2017 5:52 PM, "Louis Eveillard" <notifications@github.com> a
écrit :

**Comment by prof2meca** [comment]
Bon je viens de retrouver le bouton je n'avais pas les yeux en face des
trous...

Par contre tujours impossible d'exporter vers mon FTP. Dodoc me disque les
fichiers sont bien transférés mais rien n'aaprait sur el FTP et la page
créé n'existe pas ....

Comme fait on pour exporter en local ?

**Comment by prof2meca** [comment]
Bonsoir

je viens de recevoir mes identifiants Free donc je viens de créer une page
perso et j'exporte dodoc via ftp

l'export réussit j'exporte bien des fichiers et des répertoires mais les
pages ont des problèmes avec de grosses icônes.

Je remarque aussi que les vidéos ne sont pas exportées

une idée ?

**Comment by louis-ev** [comment]
Bonjour,
merci d'avoir testé. L'upload ne semble plus fonctionner chez moi non plus depuis la dernière version (malgré le message qui s'affiche).
Le fichier CSS n'est pas non plus copié correctement.
Je passe cette issue en priorité maximale et nous allons la résoudre avant la sortie de la 6.0.0.
Merci !

**Comment by louis-ev** [comment]
résolu dans b452d5c54f6874a206ccdd4a8445eb4ac8d678fb
