### ISSUE TITLE
erreur java

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#281]
Bonjour, 
des petites nouvelles et une question :
--> je présente l'outil à différentes personnes dont une collègue conseillère pédagogique arts plastiques qui le trouve fort intéressant.
--> nous allons le faire utiliser lors de formation de formateurs
--> j'accompagne une collègue en maternelle dans son utilisation, organisation de classe
Et du coup, j'ai fait quelques installations et me voilà avec une erreur sur deux PC (win7 et win 10)
![erreur java](https://cloud.githubusercontent.com/assets/24780752/25528253/215422e0-2c1d-11e7-85a6-8f787f7c85a5.jpg)
Qu'en pensez-vous ?
Merci

**Comment by louis-ev** [comment]
Bonjour
merci pour ces nouvelles et les retours, de notre côté nous continuons à tester et à préparer la version 6.
Le soucis que vous relevez provient du lancement de dodoc alors qu'un autre dodoc est déjà lancé. Le mieux dans ce cas est d'ouvrir le gestionnaire de tâches avec CTRL + ALT + SUPPR et de fermer le(s) *dodoc*  qui apparaissent dans la liste. Au pire, un redémarrage devrait résoudre le soucis.

**Comment by louis-ev** [comment]
Bonjour,
une question sur ce soucis : empêche t'il l'app de démarrer ? Cela bloque t'il complètement le lancement de dodoc ?

**Comment by louis-ev** [comment]
Bonjour,

cette erreur est résolue dans la version 6 à venir : si une application dodoc tourne déjà ou si une autre application utilise le port 8080, alors dodoc essayera d’utiliser le port 8081. Si le port 8081 est occupé, alors le port 8082 sera utilisé (ainsi de suite jusqu’à trouver un port disponible, dans la limite de 20 ports scannés).

À tester à la sortie de la béta de la version 6 du coup.
