### ISSUE TITLE
Retour d'usage en formation de formateurs

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#285]
Bonjour,
Je reviens avec un peu plus de disponibilité et de temps...
J'ai proposé d'utiliser DoDoc au cours d'une formation de formateurs aux usages du numérique. Il était question de faire travailler les "stagiaires" sur l'enseignement de la LVE à travers d'autres champs disciplinaires. Pour DoDoc, nous avons choisi d'allier LVE/Numérique/Histoire des Arts/Arts plastiques.
Les outils de Dodoc ont été utilisés sans plus d'explication. Ainsi, ces formateurs ont pu s'en emparer sans y être vraiment formés.
Tout d'abord l'outil plait ! Le côté intuitif avec des commandes peu nombreuses, claires attire et le rend utilisable très rapidement et ce même par des non-experts.
Et maintenant ? Et bien certains souhaitent prolonger l'expérimentation pour des formations d'enseignants et pour développer des projet mais... à l'usage deux difficultés importantes sont apparues. 

Nous utilisions des tablettes pour l'atelier car nous avions besoin d'être mobile dans notre contexte de formation. Lors de prises de vue la position "à l'italienne" de l'appareil ne permettait pas d'avoir accès à tous les "boutons" de l'application alors qu'en mode "portrait" tout était disponible. La tablette a aussi été utilisée pour faire des films d'animations et cela n'a pas fonctionné : impossible de voir la prise de vue avant validation et impossible de voir ou créer un film.
La publication intéresse tout le monde. Le format pdf est une excellente proposition mais il est souhaitable que ce soit plus adaptable : pour l'instant un seul modèle embarque les commentaires or il faudrait que ce soit le cas pour tous les modèles. L'en-tête et le pied de page doivent permettre une personnalisation de l'école, de l'utilisateur.

Les formateurs ont aussi été très intéressés par le module de publication en ligne : avez-vous des explications supplémentaires sur ce mode ?
Vos outils interpellent : est-il possible d'utiliser ce matériel ? avez-vous des plans ? une liste ?

Nous avons un projet de liaison CM2/6ème avec une école, un collège, l'UFEJJ Bretagne, la DRAC et l'EN. Il sera question de réaliser un film d'animation. Votre outil pourrait être la solution utilisée. Pour cette raison, vos réponses me seront d'une grande utilité afin d'avancer dans le projet.
Merci bien

**Comment by paulinegourlet** [comment]
Bonjour Lionel,
Merci beaucoup pour ces retours. Nous sommes vraiment contents de voir que do.doc vous est utile et que l'expérimentation se poursuive avec enthousiasme.
Sur les points que vous abordez, nous sommes exactement sur les mêmes priorités (ce qui est rassurant! nos expériences convergent). Nous comptons en effet travailler en priorité sur :
- l'adaptation de l'interface sur tous les supports et formats (ipad, téléphone / horizontal et vertical)
- les formats de sortie et mises en page (pdf et website)
Nous serions ravis sur ce dernier point de collaborer à partir de vos besoin. Vous mentionnez déjà quelques éléments intéressants. Nous allons essayer de les prendre en compte.

En terme de calendrier, nous aimerions arriver à une v6 à la rentrée, améliorant ces deux aspects principalement.
Au cours de l'année, nous allons nous attaquer au développement d'une plateforme pour publier en ligne les contenus produits. Nous collaborons avec plusieurs enseignants d'une école parisienne sur ce point (pour concevoir les fonctionnalités et les modes de partage, ce qui n'est pas une question évidente!). Si vous voulez vous joindre à ces discussions pour élaborer un cahier des charges qui puisse être adaptable à différents environnements scolaires, cela pourrait être vraiment pertinent.
Quel est votre calendrier pour le projet dont vous parlez ?

Nous allons équiper une dizaine d'enseignants (dans 3 écoles) à partir de l'année prochaine, pour une expérimentation sur l'année. Ue demi-journée dans un fablab avec les enseignants les initiera à la fabrication de stations de prise de vue pour leurs classes et nous espérons que certains auront envie d'utiliser les ressources du fablab pour d'autres projets à développer avec leurs élèves. 
Peut-être qu'une collaboration entre des écoles dans différentes villes pourraient être une étape intéressante au cours de l'année, si cela vous intéresse et est possible de votre côté ?
Nous aimerions qu'une communauté enseignante/éducative émerge autour de ce projet, pour partager les pratiques autour de la création de médias par les élèves et les pratiques de remédiation et d'étayage qui émergent. Poursuivons l'échange, nous vous tiendrons au courant dès que nous avançons sur l'implémentation de la v6. N'hésitez pas à nous faire part de vos idées et besoins, comme vous l'avez fait et/ou si vous avez des questions.

Bien à vous.
l'atelier

**Comment by lrault2** [comment]
Bonjour,

Le projet que nous allons développer avec une école et un collège démarre dès septembre avec l'entrée dans le dispositif Ecole et Cinéma. C'est un projet comprenant plusieurs partenaires, Education Nationale (Direction Académique, école, collège), l'UFEJ, la DRAC. Le travail de préparation devrait les amener à un temps de réalisation en janvier 2018. Il faut pour cela que nous puissions leur proposer un outil de captation pertinent. Dodoc me paraît l'être. Mais il faudrait que je puisse le mettre à disposition en amont pourr que les enseignants et les élèves le découvrent et se l'approprient. Dans ce cadre, ce serait intéressant de pouvoir proposer l'utilisation de vos matériels. Seraient-ce possible ? 

Par ailleurs, nous avons proposé à certaines circonscriptions de mettre en place des animations pédagogiques incluant le numérique, pour les enseignants. Certaines seront associées aux arts, d'autres à la LVE, d'autres encore aux deux. Dans ce cadre, nous n'aurons besoin que de l'outil numérique car ce sera sur des temps contraints et en mobilité. L'idée est aussi de montrer qu'il est possible d'utiliser les dispositifs présents dans les écoles pour utiliser votre outil.
A travers ces actions, mon idée est de : 
- faire en sorte que votre outil soit utilisé dans les écoles 
- créer des réseaux d'enseignants (au niveau local mais effectivement un réseau plus large est encore plus intéressant)

Pour tout cela, vous l'aurez compris, cela m'intéresse de participer à l'élaboration du cahier des charges.
Au plaisir...

**Comment by lrault2** [comment]
Bonjour,
je reviens vers vous à la veille de ces vacances concernant DoDoc. L'ayant utilisé en formation de formateurs, j'ai maintenant suscité des envies et des besoins. Pouvez-vous me dire où vous en êtes par rapport aux évolutions envisagées ?
Merci
Par ailleurs, fréquentez-vous Educatec ?
; )

**Comment by paulinegourlet** [comment]
Bonjour Lionel, 

Nous sommes en train d'avancer sur les modalités de sortie (print et web). Nous avons maintenant une possibilité d'export PDF qui fonctionne bien et nous allons travailler dans les jours qui viennent à l'export web (je peux vous envoyer la version que nous venons de finir pour l'export PDF pour que vous testiez si vous voulez). 
Pour ce qui est de la customisation des ces formats, nous pouvons voir avec vous ce qui serait intéressant d'envisager (vous parliez de placer le nom de l'école ou de l'enseignant par ex.)
Quelles sont les autres fonctionnalités qui seraient indispensables à un usage prochain de votre côté ? De quelles information / documentation auriez vous besoin pour faciliter l'adoption par les enseignants ? 

Par ailleurs, non, nous ne connaissons pas le réseau dont vous parlez, mais ravis d'en savoir plus.

Bien à vous,
Pauline pour l'atelier

**Comment by lrault2** [comment]
Bonjour,
Très content d'avoir ces informations et je suis preneur de la version sur laquelle vous travaillez.
Pour la personnalisation des éditions, il me paraît important de pouvoir identifier l'école, la classe, l'élève ou le groupe d'élèves, la date.
Comme je l'ai évoqué dans un fil de discussion précédent il serait intéressant de disposer d'une bibliothèque d'images (alimentée par l'enseignant) accessible à partir de n'importe quel projet. Dans l'idée de carnet de suivi des apprentissages, cela permettrait d'identifier la compétence facilement à l'aide des images collectées dans la bibliothèque, comme un tampon ...

Educatec Educatice est en fait un salon de l'éducation qui se déroule Porte de Versailles du 15 au 17 novembre. Normalement je dois m'y rendre, cela aurait été l'occasion de vous rencontrer.
@+

**Comment by paulinegourlet** [comment]
Bonjour Lionel, 
En attendant de vous envoyer la version v6 "clean" (ça ne saurait tarder), voilà un pdf généré à partir de do.doc pour que vous voyiez ce que ça peut donner. Nous allons rajouter la date comme vous le suggérez. Pour les autres méta-données que vous mentionnez, cela nécessite de pouvoir rentrer ces informations à un endroit à partir de l'instance installée dans une classe. Pour l'instant, nous n'avons pas de système de profil par élève ou même par classe. Nous l'envisageons évidemment mais cela demande de repenser sensiblement l'architecture actuelle. 
Puisqu'une collaboration se profile avec l'école Trébédan, pourquoi ne pas profiter de cela pour refaire une passe globale sur l'interface et intégrer les autres choses que vous mentionnez aussi (le système de tampons par ex.)? L'enseignant avec lequel nous travaillons à Paris parle aussi d'un système de badges de compétences, donc c'est intéressant de croiser les approches là-dessus avant développement.
Nous aimerions beaucoup travailler avec vous et l'école sur un mode d'aller-retour et de manière participative (en incluant peut-être les enfants aussi dans la mesure du possible) et en venant peut-être sur place pour une conception plus et adaptée aux besoins, en discutant avec vous et l'enseignante intéressée par le dispositif.
Qu'en pensez-vous ?

En tout cas, Louis sera à Paris pendant le salon, peut-être pourrez vous vous rencontrer aussi à cette occasion.

A très bientôt,
(j'ai par ailleurs répondu à l'enseignante avec qui vous travaillez, nous devrions discuter de tout ça aussi dans les jours qui viennent.)

[un-voyage-a-travers-la-fabrication-de-lettres_v2.pdf](https://github.com/l-atelier-des-chercheurs/dodoc/files/1409147/un-voyage-a-travers-la-fabrication-de-lettres_v2.pdf)
