### ISSUE TITLE
Problème suppression des phots

### ISSUE THREAD

**Issue by RomainLalande** [l-atelier-des-chercheurs/dodoc#287]
Hello,
On vient de mettre en service DoDoc au FunLab à Tours, ça marche niquel, sauf pour le bouton de suppression des photos. Quand on clic dessus, cela nous demande confirmation mais après avoir fait OK, la photo est toujours là. 
On peut toujours supprimer en passant par les dossiers dans lesquels elles sont stockées mais ce n'est pas très pratique :)
Merci pour #DoDoc !
Romain

**Comment by louis-ev** [comment]
Bonjour,
merci pour votre retour et l’utilisation de DoDoc !
Êtes-vous bien sur la dernière version, 5.2.0 ? Pouvez-vous décrire exactement les étapes, de la création de l’image à sa suppression ? Je n’arrive pas à reproduire ce bug en utilisant l’installer pour Mac.
Merci !

**Comment by RomainLalande** [comment]
Hello,
Oui nous sommes bien sur la 5.2.0.
Nous prenons l'image via une photo (webcam) déclenchée via l'appui sur la lettre A du clavier (simulé par un bouton). 
J'ai capturé une vidéo de la séquence d'usage (assez basique : prise de photo, suppression, relance du logiciel) : https://cloud.artefacts.coop/index.php/s/Q5KVFkz9BFLMVfY . 
Merci pour la réactivité en tous cas :)

**Comment by louis-ev** [comment]
Le bug est (à priori) résolu ! 
Il ne s’activait qu’à la suppression de médias dont la date de capture contient un "5" (d'où le fait qu’il intervenait de manière intermittente). Corrigé sur la branche Master, version 5.2.1.

Pour info, la suppression dans dodoc ne supprime pas le fichier : il le renomme avec comme préfixe un "x_" , par exemple : 

![image](https://user-images.githubusercontent.com/1948417/30594737-5c78db38-9d4f-11e7-8cf8-900f0cc54dbb.png)

La raison pour laquelle nous avons opté pour ça est pour éviter la suppression définitive par erreur, ou par malveillance. Tous les fichiers dont le nom commence par "x_" ne sont pas lus par l’interface, donc il suffit de retirer ce préfix x_ pour les rétablir si besoin. On peut aussi les supprimer définitivement par le finder.

Pouvez-vous tester et confirmer que ça fonctionne chez vous ? Vous faut-il un .dmg ou .exe pour ça, ou vous installez dodoc par un terminal ?

**Comment by RomainLalande** [comment]
Oh merci  !
Oui nous testons dés que possible, normalement fin d'après midi, mais par contre je ne sais pas comment installer via un terminal sur windows, c'est du travail de produire un .exe ? Si oui je trouverai !

**Comment by louis-ev** [comment]
Je vais vous sortir un .exe, ça sera un test en condition réelle, pas de soucis !

**Comment by RomainLalande** [comment]
:-)

**Comment by louis-ev** [comment]
Voici un lien pour télécharger un .exe de test (version 5.2.1) : https://send.firefox.com/download/c9949ad5e2/#6EzWOvEiG8KiL_a7pq7fzA

**Comment by louis-ev** [comment]
Je ne sais pas si vous avez eu le temps de récupérer ce fichier, vu que le lien a déjà expiré je vous en remet un autre ici : https://www.dropbox.com/s/xt64s2pncgkfogp/dodoc%20Setup%205.2.1.exe?dl=0

**Comment by RomainLalande** [comment]
Hello ! 
Désoler je n'avais pas vu passer ton message; Je viens de tester... ça fonctionne parfaitement ! 
#GOGOGO 
MErci beaucoup en tous cas, pour le boulot et la réactivité :-)

**Comment by louis-ev** [comment]
Parfait, je publie !
Merci à vous 👍
