### ISSUE TITLE
bug css export web

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#293]
![capture d ecran 2017-11-28 a 3 17 46 pm](https://user-images.githubusercontent.com/7995654/33438007-a2e94878-d5b7-11e7-8c41-afe88f7d2e25.png)

**Comment by louis-ev** [comment]
Quel template ? 
Dans quelle condition ?

**Comment by louis-ev** [comment]
Ici ça fonctionne sur le template une colonne, lorsque j’ouvre le zip après export.

**Comment by paulinegourlet** [comment]
Il n'y a pas de css dans le dossier zippé que j'ai à l'export, donc ton appel à la feuille template.css ne marche pas.

**Comment by louis-ev** [comment]
Même soucis que #294, c'est parce que tu as un dossier templates pas à jour.

**Comment by sarahgarcin** [comment]
![screen shot 2017-12-05 at 08 04 37](https://user-images.githubusercontent.com/4678296/33594148-04495444-d993-11e7-93b2-f99c125b705f.png)

En plus le fichier template.css est quasi vide !

**Comment by louis-ev** [comment]
Redis-moi ça ? le fichier `style.min.css` est bien copié mais mal linké ?
Oui, `template.css` est presque vide parce que y a presque rien comme CSS dans son gabarit. Mais si on a un gabarit + recherché, il sera plus long.
Mais c'est l’idée, tu peux créer des gabarits en CSS pour tes publications et ça les exporte avec tes publis.

**Comment by sarahgarcin** [comment]
Ok j'ai compris mais le fichier style.min.css n'est pas copié

**Comment by sarahgarcin** [comment]
J'ai aussi l'impression que les links sont pas bons

**Comment by louis-ev** [comment]
À priori c’est tout bon chez moi. Bien penser à bien mettre à jour pour la v6.
