### ISSUE TITLE
problème d'affichage dans la publi

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#294]
![capture d ecran 2017-11-28 a 3 10 58 pm](https://user-images.githubusercontent.com/7995654/33438049-bccb2982-d5b7-11e7-8a4a-bc2689010722.png)

**Comment by louis-ev** [comment]
Quel template ? Uniquement sur des vidéos ?

**Comment by paulinegourlet** [comment]
Lorsque les formats sont pas paysages (cad carrés ou portraits) ils ne se s'adaptent pas à la largeur de la publi. Est-ce normal ?

![capture d ecran 2017-12-02 a 3 43 42 pm](https://user-images.githubusercontent.com/7995654/33519606-e0cbc168-d777-11e7-9f24-6f00cc08863d.png)

**Comment by louis-ev** [comment]
Peux-tu fermer l’app dodoc, aller dans documents, renommer le dossier dodoc en dodoc-2, rebooter dodoc, et tester avec le dossier par défaut ?
