### ISSUE TITLE
template ne marchent plus

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#295]
Quelque soit le template sélectionné, les médias s'affichent sur le template une colonne.

**Comment by louis-ev** [comment]
Oui, les autres templates étant mal finalisés ils sont supprimés du dossier template. Mais comme tu utilisais la version précédente, il te reste des templates encore. Ils devraient être encore fonctionnels par contre, je vais regarder dans le CSS.

**Comment by louis-ev** [comment]
À la mise à jour de dodoc v6, il faut supprimer le dossier templates pour qu’il soit recréé avec les nouvelles infos (et seulement deux templates, le une colonne et la grille). J’ai du changer un peu des éléments que je ne pensais pas devoir changer et qui ont pour objectif de pouvoir être modifiés et édités par les utilisateurs (le dossier `templates`), c’est pour ça.
