### ISSUE TITLE
RESPONSIVE ! à finir

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#296]
téléphone et tablette : prb d'affichage

**Comment by paulinegourlet** [comment]
exemples
![screenshot_20171128-150445](https://user-images.githubusercontent.com/7995654/33442819-175e3a04-d5c4-11e7-819b-d889db1b4383.png)
![screenshot_20171128-150609](https://user-images.githubusercontent.com/7995654/33442822-17ac3b32-d5c4-11e7-88e1-13142563a41a.png)

**Comment by louis-ev** [comment]
Des screenshots de tous les endroits où ca ne fonctionne pas seraient top, ça servirait de todo visuelle :)

**Comment by paulinegourlet** [comment]
Je l'avais déjà fait à la Générale. Sarah doit avoir une trace de ça, c'était tout décrit point par point. J'ai pas de tablette là... Mais le plus gros problème est celui de la publi qui s'affiche toujours dans la bibli des médias (voir screenshot 1).

**Comment by louis-ev** [comment]
Ça a changé depuis un an, c'est mieux qu’à la générale.
Je résous le plus urgent et on verra la suite ensemble IRL.

**Comment by louis-ev** [comment]
La v7 changeant beaucoup l’interface, il faudrait restester dessus.

**Comment by louis-ev** [comment]
Je ferme pour pas melanger
