### ISSUE TITLE
Les templates ne marchent plus dans la publication

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#298]
Quelque soit le template choisit on a toujours le une colonne

**Comment by sarahgarcin** [comment]
Ok j'ai testé le truc de l'issue #294 
j'ai renommé le dossier dodoc en dodoc-2 maintenant les templates marche mais j'en ai que 2 grille et une colonne. 
C'est un peu embêtant pour les gens qui ont déjà installé dodoc et qui veulent faire la MAJ non ?

**Comment by louis-ev** [comment]
De quoi ? La complexité de la MAJ ou le fait d’avoir moins de templates ? J’ai viré les templates qui servaient vraiment pas trop et pas très bien finalisés.

**Comment by sarahgarcin** [comment]
Je parlais de la complexité de la MAJ.
Je me doutais que tu avais viré les autres templates exprès ;)

**Comment by louis-ev** [comment]
Il suffira de supprimer le dossier `templates` et de lancer dodoc v6, ça me parait pas si laborieux :)
Mais oui c'est pas idéal, on a voulu sortir le moteur de gabarit trop vite l’année dernière alors qu’il était pas bien finalisé…

**Comment by louis-ev** [comment]
Note : vérifier l’état du template `_exemple`
