### ISSUE TITLE
Ajouter la possibilité d'ouvrir une preview du PDF directement après l'avoir exporté ? 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#301]

**Comment by louis-ev** [comment]
Impossible, y a pas de preview PDF dans electron. C'est un plugin propriétaire qui fournit ça.

Par contre on peut faire un openItem : https://github.com/electron/electron/blob/v0.36.10/docs/api/shell.md#shellopenitemfullpath

> Open the given file in the desktop's default manner.

Mais ça ferait quoi sur smartphone ou tablette ? pas sur que ça fonctionne

**Comment by sarahgarcin** [comment]
Et c'est possible que ça soit juste un lien qui vers le pdf que tu as téléchargé et que ça te l'ouvre directement dans ton lecteur de pdf par défaut sur ton ordi ?

**Comment by louis-ev** [comment]
C'est ce que je te montrai oui, shell.openItem. Mais je n’ai pas accès à shell depuis un navigateur, du coup hors électron ça resterait un lien "download". Ou alors on le passe en lien nouvel onglet.
Et sur electron ça ouvre dans le logiciel interne.

Je met "Ouvrir le PDF" et "Télécharger le PDF" du coup ?

**Comment by sarahgarcin** [comment]
Oui je trouve ça mieux de mettre ouvrir et télécharger !
