### ISSUE TITLE
Fenêtre d'erreur qui apparait lorsque que je clique sur le bouton "Export as a website"

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#302]
![screen shot 2017-12-03 at 14 54 55](https://user-images.githubusercontent.com/4678296/33526004-0555c8fe-d83a-11e7-9586-2fd41b3e2941.png)

**Comment by louis-ev** [comment]
Étrange… ça correspond à la copie de la typo

![image](https://user-images.githubusercontent.com/1948417/33529681-7fa64b80-d874-11e7-892a-7e66d5428c06.png)

**Comment by sarahgarcin** [comment]
L'export des fichiers typo ne fonctionne pas chez moi. 
Chez moi c'est tout moche quand on export le pdf. 

Ce que j'ai pas précisé c'est que malgré le message d'erreur l'export du site web fonctionne, j'ai bien un dossier avec le site dedans même si le css ne marche pas.

**Comment by louis-ev** [comment]
Duplicate of #293
