### ISSUE TITLE
Permettre l'import au drag and drop dans la media library d'un ou plusieurs média(s)

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#304]

**Comment by louis-ev** [comment]
Résolu dans la v7 à venir, en glissant sur le bouton « import », qui n’est pas forcément évident d’ailleurs. À améliorer.
Mettre aussi un message qui indique la possibilité de drag and drop.

La bibliothèque entière est surface de drag/drop, et le dit quand elle est vide.
