### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#309]
Windows 10 64bits OK
Windows 7 64bits OK
J'ai un autre PC au bureau avec un windows? 32bits... j'essaierai.
Jai un poste sous linuxmint mais je ne parviens pas à installer l'appimage (un conseil ?)

QR code OK (avec Android et Ipad) c'est TOP.
Import multiple  de médias OK.

Suppression média NON même après redémarrage.
Lors de la création du pdf incluant photos et vidéos, les images ne font pas les mêmes dimensions selon que c'est une vidéo ou une photo.
Commentaires présents dans le format pdf en colonne mais pas en quadrillage

Utilisation d'une caméra logitech 720p HD et d'une caméra HUE HD sur un même poste et en m^me temps OK (DoDoc propose au choix les 3 caméras)

Connexion d'un Ipad sur PC windows7 OK sans confirmation
Prise de photos OK
Mais choix de caméra impossible
Prise de son NON
Prise de vidéos NON
Prise d'animation OK jusqu'à la prévisualisation

Connexion android 7 sur PC windows7 OK avec confirmation
Prise de photo OK
Choix de caméra OK
Prise de son OK
Prise de vidéos OK
Prise d'animations OK

Voilà pour quelques premières manip...

Je suis de plus en plus convaincu
J'ai lancé deux instances en parallèles puis tenté d'utiliser un média d'un projet dans la publication d'un autre projet... j'ai été trop gourmand...
@bienôt

**Comment by louis-ev** [comment]
Pour le bug de suppression, à priori on est bon avec la bêta 3.
À tester ici : https://github.com/l-atelier-des-chercheurs/dodoc/releases/tag/v6.0.0-beta.3

**Comment by louis-ev** [comment]
Merci pour ce retour ! content d’entendre que ça avance dans la bonne direction :)

Question concernant ce retour : 
> Lors de la création du pdf incluant photos et vidéos, les images ne font pas les mêmes dimensions selon que c'est une vidéo ou une photo.

Est-il possible d’avoir un screenshot et les médias en question en pièce jointe d’un post ici ?

Merci par avance
