### ISSUE TITLE
Ajout d'une exportation en Markdown

### ISSUE THREAD

**Issue by iooner** [l-atelier-des-chercheurs/dodoc#310]
Hello!
Une exportation en markdown serait très utile pour les wiki de nos fablab/hackerspace/...
Ou encore github et les staticgens en général.

**Comment by louis-ev** [comment]
Une première implémentation suivant ce modèle parait envisageable : 

- un bouton "export markdown" en plus dans la page d’une publication
- qui créé un zip
- qui contient un fichier .md reprenant la publi sous un format du type : 
```
# Titre de publication
## Un sous-titre

Du texte en paragraphe et *du gras*.

<figure>
  <img src="medias/photo.jpeg">
  <figcaption>
    La Légende en HTML ici.
  </figcaption>
</figure>

La suite du texte ici.
```

- et qui contient dans une sous-dossier medias tous les médias de la publication.

Les médias non-textuels sont intégrés inline dans le markdown pour simplifier.

**Comment by louis-ev** [comment]
Bonjour,

la nouvelle version de do•doc s’éloigne un peu de cette fonctionnalité car elle embarque un éditeur de texte qui ne gère pas le markdown (qui était de toute façon très peu utilisé et trop compliqué pour beaucoup de monde, d’après les retours que nous avons reçu).

Mais cette nouvelle version exporte une page statique beaucoup plus propre et modulaire, est-ce que cela aurait du sens d’ajouter une options pour convertir le texte en HTML en markdown ?

Y a t’il un wiki (dokuwiki ? mediawiki ?) qui pourrait servir de test ?
