### ISSUE TITLE
BUG Publi / ajout média uniquement sur première page

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#315]
[Systématique chez moi] 
L'ajout de médias se fait toujours sur la première page alors que je scrolle sur la page suivante (avec curseur rouge sur page suivante).

**Comment by louis-ev** [comment]
Il faudrait que je vois directement sur ton ordi, parce que c’est très étonnant (vu que le navigateur est embarqué dans electron, tu utilises forcément le même que moi).

Peux-tu faire les choses suivantes : 
- créer une publi in titutlée "Test de publication"
- l’ouvrir et ajouter une seconde page
- mettre un média sur la première et sur la seconde page (avec le curseur rouge au bon endroit en tout cas)
- aller dans le dossier *dodoc2/_publication/test-de-publication*
- copier le contenu de chaque fichier .txt présent dans ce dossier ici.

Merci !

**Comment by paulinegourlet** [comment]
(bonne nouvelle) Je n'arrive à reproduire le bug... 
ça veut pas dire qu'il n'arrivera pas mais pas si systématiquement finalement :)

**Comment by louis-ev** [comment]
Se pourrait-il que ça se soit fait sur une publi que tu avais créé avant a version 7.0.2 ? J’ai changé la logique de placement des médias dans les pages, chaque média est rattaché à une page par un ID et chaque page a un ID. Comme ça si on bouge une page, les médias restent bien sur elle.
