### ISSUE TITLE
Réglages typographiques publi

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#316]
• Pas de césure 
• Option de choix typo ? / taille ?

Pour le moment : 
[Taille TYPO dodoc - Fira Sans.pdf](https://github.com/l-atelier-des-chercheurs/dodoc/files/2046378/Taille.TYPO.dodoc.-.Fira.Sans.pdf)

**Comment by louis-ev** [comment]
Implémenté dans la v7.1.1
