### ISSUE TITLE
Affichage des pages dans le panneau de publication (BUGS et AMELIORATIONS)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#317]
- problème de centrage des pages au dézoom dans la publi / réalignement des pages (difficile de naviguer - voir capture 01)
- problème d'espace entre les pages au dézoom (voir capture 02)
- après changement des paramètres sur publi = première page changée mais pas deuxième (voir capture 03)
- ce serait pas mal qu'au repli/dépli du panneau publi, le zoom de la page soit adapté automatiquement (vue pleine page par défaut)
(01)
![screenshot 2018-05-24 18 31 50](https://user-images.githubusercontent.com/7995654/40632535-132eac14-62b6-11e8-9db6-820cc282652c.png)
(02)
![screenshot 2018-05-24 18 32 30](https://user-images.githubusercontent.com/7995654/40632529-04495438-62b6-11e8-9fdc-639061df3dc0.png)
(03)
![screenshot 2018-05-24 18 48 03](https://user-images.githubusercontent.com/7995654/40632532-08d9c6f4-62b6-11e8-996d-f5f83a09a512.png)

**Comment by louis-ev** [comment]
En cours d’amélioration : 

![image](https://user-images.githubusercontent.com/1948417/40664191-a7dfc114-635a-11e8-86a0-204b8922429f.png)

**Comment by louis-ev** [comment]
Tous les points sont résolus dans la 7.7.7 sauf : 

> ce serait pas mal qu'au repli/dépli du panneau publi, le zoom de la page soit adapté automatiquement (vue pleine page par défaut)

**Comment by louis-ev** [comment]
À ajouter dans do•doc 9

> ce serait pas mal qu'au repli/dépli du panneau publi, le zoom de la page soit adapté automatiquement (vue pleine page par défaut)

**Comment by louis-ev** [comment]
C’est prêt pour do•doc 8.2 finalement !

![resize_publi_dodoc](https://user-images.githubusercontent.com/1948417/68074795-a1f00580-fd9f-11e9-93d8-68306a375f08.gif)
