### ISSUE TITLE
BUG capture vidéo

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#318]
• problème de flux à répétition, après plusieurs tests, surtout avec la vidéo  (voir message erreur ci-dessous)
• Flux hâché et latences (feedback clic, lecture vidéo enregistrée...)

<img width="532" alt="screenshot 2018-05-24 18 38 21" src="https://user-images.githubusercontent.com/7995654/40632565-6c8d5922-62b6-11e8-96d0-d5c86765576d.png">

**Comment by louis-ev** [comment]
Il me faut un retour plus précis, pour que je puisse reproduire ce bug, peux-tu me faire un pas-à-pas avec une manière de reproduire ce bug ?

**Comment by louis-ev** [comment]
Retour vers le mode capture webm classique. La conversion pourrait peut-être se faire à un autre endroit après coup… Dans la bibli ?
