### ISSUE TITLE
Choix post-capture (garder / supprimer / tag)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#320]

**Comment by louis-ev** [comment]
Cette idée est-elle toujours valable ? On la garde ? 

Où mettrait-on le système de choix et tag/mots clés ? Les mots-clés des médias sont-ils communs aux projets ? @paulinegourlet tu peux proposer qqchose sur la gestion des mots-clés ? 

![image](https://user-images.githubusercontent.com/1948417/44920169-7c044680-ad3f-11e8-86cb-e2ada787c2e1.png)

**Comment by louis-ev** [comment]
@paulinegourlet on ferme ou pas ?
Tu peux revenir là-dessus ?
