### ISSUE TITLE
Filtrage

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#323]
• par auteurs
• autres tags ?

**Comment by louis-ev** [comment]
En priorité dans un projet ou sur la home ?

**Comment by paulinegourlet** [comment]
Les auteurs dans un projet en priorité.

**Comment by lrault2** [comment]
Dès l'arrivée dans DoDoc, pouvoir choisir affichage par date, par auteur, ou par projet.

**Comment by louis-ev** [comment]
On y est presque. 
L’organisation par date se ferait comment ? Trier par jour, ou sur une période ?

**Comment by lrault2** [comment]
Par jour, je pense.

**Comment by louis-ev** [comment]
Du coup c’est assez proche du mode "médias" ajouté sur la home. Ça marche.
