### ISSUE TITLE
Auteur, média et dossier

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#325]
A la création d'un auteur, création automatique d'un dossier/projet au nom de cet auteur.
Lors de toute captation, le média est enregistré dans le dossier de l'auteur.
Pour autant, si la saisie est faite au sein d'un autre projet, le média apparaît dans les deux dossiers.

**Comment by lrault2** [comment]
Chaque miniature de média peut-elle afficher les différents tags : auteur, date, projet ?

**Comment by louis-ev** [comment]
Dans la mesure où la possibilité de filtrer les médias par auteur sur la page d’accueil ou dans un projet est prévue, est-ce que cela ne fait pas doublon ?

Au final la vue par "projet" est là par défaut pour *guider* une utilisation pour laquelle do•doc est particulièrement adapté, mais une des raisons de la refonte pour la v7 est de pouvoir aller beaucoup plus loin dans une navigation qui ne se limite plus au projet (ou au dossier).

Pour l’affichage d’informations sur les miniatures, le risque est de surcharger la bibliothèque. Est-ce que nous pouvons les afficher uniquement lorsqu’un tri de ce type est demandé ? 

Exemple : dans un projet, je demande à trier les médias par auteur. Sur chaque petite miniature de média s’affiche le nom de l’auteur correspondant, en plus d’un nouvel ordre.

**Comment by lrault2** [comment]
Cela peut effectivement faire doublon. Mais est-ce qu'un même média pourra apparaître dans un projet au nom de l'élève et dans un projet au nom du projet ?
Concernant l'affichage d'information que tu proposes devrait être suffisant.
Par contre, la question de la création automatisée d'un dossier lors de la création d'un auteur me semble intéressante.

**Comment by louis-ev** [comment]
La dernière version 7.2.0 répond-elle à ce besoin ? Notamment en permettant de consulter la production d’un auteur/élève organisée par date sur l’accueil ?

Pour le retour suivant, peux-tu en faire une issue en elle-même ? il me semble que ça n’est pas connecté : 
> Chaque miniature de média peut-elle afficher les différents tags : auteur, date, projet ?

**Comment by lrault2** [comment]
Je viens de regarder.
Effectivement c'est plutôt pas mal. La navigation est du coup différente que celle que nous pouvons avoir dans une arborescence de PC. Cela m'a questionné deux secondes mais je trouve ça très bien de ne pas rester dans ce même fonctionnement.
Le picto "loupe" n'est peut-être pas assez explicite mais je n'ai pas d'autres idées et quand on le sait...

> Chaque miniature de média peut-elle afficher les différents tags : auteur, date, projet ?
Pour moi, c'est dans le message car cela correspond à un autre niveau de filtre : après "auteur", "date", il peut y avoir projet...

**Comment by louis-ev** [comment]
> Pour moi, c'est dans le message car cela correspond à un autre niveau de filtre : après "auteur", "date", il peut y avoir projet...

Je suis un peu perdu… tu parles de la fenêtre d’édition de média ? Qui contient la date, le champ auteurs, les mots-clés, etc. ?
Tu crois qu’il faudrait inscrire le nom du projet auquel appartient le média, c’est bien ça ?

**Comment by lrault2** [comment]
Exact. Et du coup sera-t-il possible d'avoir un filtre sur un nom de projet auquel participent plusieurs auteurs ?

**Comment by louis-ev** [comment]
Dans ce cas autant rentrer dans le projet, puis filtrer par auteur à cet endroit là non ?

**Comment by lrault2** [comment]
ah effectivement... je crois que je me suis perdu.

**Comment by louis-ev** [comment]
C’est pas forcément évident, peut-être à améliorer

**Comment by louis-ev** [comment]
Pour les infos sur les miniatures le risque est de surcharger visuellement et d’avoir trop de texte rapidement. Du coup soit c’est à configurer en amont (choisir les infos à afficher sous les vignettes de médias) soit au survol, à voir.

**Comment by louis-ev** [comment]
Où en est cette issue ? Peut-on la fermer ?

**Comment by lrault2** [comment]
Oui

**Comment by louis-ev** [comment]
Ok
