### ISSUE TITLE
démarrage

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#327]
DoDoc met du temps à démarrer sur windows 7.

**Comment by lrault2** [comment]
Une vidéo... [https://hubic.com/home/pub/?ruid=aHR0cHM6Ly9sYjk5MTEuaHViaWMub3ZoLm5ldC92MS9BVVRIXzdkZGQ1ZWQyZjJhNzJhZWExMmViNmQ2NWQ0NDlmZWI5L2RlZmF1bHQvLm92aFB1Yi8xNTI4NDM5NTMxXzE1MjkzMDM1MzE/dGVtcF91cmxfc2lnPTIxNWNkYjhhZmMxMzg1Njk3ZWE2YTlmZWZhYjM4ZTA0OThjZDNhNjgmdGVtcF91cmxfZXhwaXJlcz0xNTI5MzAzNTMx](url)
J'ai le sentiment que c'était moins long avant cette toute dernière version.

**Comment by lrault2** [comment]
C'est jour-ci je suis plus sur mon PC.
Je viens de relancer :
- 1ère fois assez longue
- 2ème fois plutôt rapide
Mon PC a besoin d'un bon lifting alors attendons...

**Comment by louis-ev** [comment]
Première fois = installation de do•doc, ou un lancement "à froid" ?

**Comment by lrault2** [comment]
Juste démarrage de do•doc alors qu'il est déjà présent sur le PC.

**Comment by louis-ev** [comment]
ça c’est étrange… À voir si ça se reproduit sur d’autres machines mais sur tous les OS (et sous des machines virtuelles pas très puissantes) le démarrage prend max 5 secondes.

**Comment by lrault2** [comment]
OK. A suivre donc. Je te dirai après mes nouvelles installations sur d'autres machines.

**Comment by louis-ev** [comment]
Ce soucis se manifeste-t’il lui aussi sous la version 7.4.0 ?

**Comment by lrault2** [comment]
Ca roule...

**Comment by louis-ev** [comment]
C’est plus rapide du coup ?
J’ai modifié deux endroits dans le code qui pouvaient poser des problèmes sous Windows, tant mieux si ça a fait effet.
