### ISSUE TITLE
Polices

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#328]
Ajouter quelques polices de caractères dont opendyslexic.

**Comment by lrault2** [comment]
Tu veux dire qu'en choisisant ce gabarit alors tous les écrits seraient en opendyslexic ?
Mais est-ce que les auteurs auraient le choix de la police lors de la création d'un texte ?

**Comment by louis-ev** [comment]
Oui, une publication toute entière passerait en opendyslexic.
Ça me parait être une mauvaise idée de passer do•doc en lui-même en opendyslexic — qui n’est pas suffisament souple pour s’adapter à tous les corps typo que nous utilisons.

Par contre éditer une publication en opendyslexic aurait du sens. Étant donné que c’est de la mise en forme, ça serait à choisir dans le gabarit d’une publi et pas dans les options d’édition d’un bloc texte (qui lui ne suggère pas de mise en forme de lui-même, juste le texte et des sous-titres).

**Comment by lrault2** [comment]
![image](https://user-images.githubusercontent.com/24780752/41823485-df9a424a-7800-11e8-811a-44a9b234a1e4.png)
Non, il ne faut pas passer dodoc en opendyslexic mais donner la possibilité d'écrire les textes (voire les commentaires des images et vidéos) dans cette police peut être intéressant pour un élève qui en a besoin et pas seulement lors de la création de la publication.

**Comment by louis-ev** [comment]
On pourrait aussi imaginer qu’il existe une case "mode dysléxique" à la création d’un auteur, et qui passe certains champs en opendyslexique ?
Mais ma première idée serait d’éditer des ressources (par exemple, publication imprimée) en opendyslexique, ce qui ne me paraît pas inutile.

**Comment by lrault2** [comment]
Grand OK pour les deux.

**Comment by louis-ev** [comment]
Ok. C’est pas hyper compliqué, surtout la publi dyslexique, du coup je regarde si c’est jouable pour le lancement stable.

**Comment by lrault2** [comment]
Si tu te rappelles de [Edu-Up](http://eduscol.education.fr/pid25518/soutien-a-la-production-et-a-la-diffusion.html), ça pourra les intéresser. Et ça peut parler à la MAIF...

**Comment by louis-ev** [comment]
À venir dans les publications : un gabarit "open dyslexique".

**Comment by sarahgarcin** [comment]
@louis gabarit "open dyslexique", on reporte à dodoc v10 ou c'est pour la v9
cette issue fait doublon avec la #511, on pourrait merger les deux

**Comment by louis-ev** [comment]
Non non on ferme, c’est implémenté après 3 ans ! :)

<img width="170" alt="image" src="https://user-images.githubusercontent.com/1948417/112492836-e65bb700-8d81-11eb-867b-e62908e133bb.png">
