### ISSUE TITLE
Export epub

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#332]

**Comment by louis-ev** [comment]
Un chantier potentiellement long et complexe, à venir mais impossible de savoir quand.

**Comment by sarahgarcin** [comment]
Je mets ça pour plus tard, gros gros chantier

**Comment by louis-ev** [comment]
À vrai dire j’ai l’impression que le format epub est de moins en moins pertinent… Toujours intéressant de se pencher là-dessus ?

**Comment by louis-ev** [comment]
Je ferme, c'est trop
Contraignant et le format me semble disparaître avec le temps...
