### ISSUE TITLE
lecteur pdf

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#333]
lecture d'un document pdf importé

**Comment by louis-ev** [comment]
Besoin de plus d’informations : dans l’application même ? Depuis d’autres appareils quand on passe par le navigateur ? Si non, sur quel type de machine (windows, linux, mac ?) ?

**Comment by lrault2** [comment]
Tout comme on peut importer une image, avoir la possibilité d'importer un pdf et pouvoir le lire dans dodoc. Toutes les machines.

**Comment by louis-ev** [comment]
À venir dans la version 7.
