### ISSUE TITLE
médias : des pictos pour supprimer, modifier

### ISSUE THREAD

**Issue by lrault2** [l-atelier-des-chercheurs/dodoc#334]

**Comment by louis-ev** [comment]
Ajouté dans do•doc 8 :

<img width="516" alt="image" src="https://user-images.githubusercontent.com/1948417/63841176-9db00200-c982-11e9-9353-63f9a9ec861d.png">

C’est suffisament clair ?

**Comment by jubonhomme** [comment]
Une proposition :
flèche vers le bas pour le "Télécharger"
crayon pour "Ajuster"

![icone_parametre_media](https://user-images.githubusercontent.com/29262866/71123687-7efca200-21e3-11ea-8490-b8b931e9ce8a.png)

**Comment by louis-ev** [comment]
Flèche bas : risque de conflit sémantique avec le bouton IMPORTER, qui est
lui aussi une flèche vers le bas…
Dans la métaphore, l’appli est en bas et sortir des fichiers (en les
téléchargeant) = les "soulever". Mais  je suis d’accord que ça ne fait pas
tout à fait naturel.
Tu en penses quoi ?

Crayon : le même que pour éditer les projets donc ? C’est cohérent avec la
fonction du crayon ?

-----------
Louis Eveillard

Tel : 06 31 42 79 65
Mail : louis.eveillard@gmail.com
Web : louiseveillard.com <http://www.louiseveillard.com/>
Blog : beautifulseams.com <http://www.beautifulseams.com>

**Comment by jubonhomme** [comment]
Perso je trouve plus parlant : vers le bas = "télécharger"  (réf à download / upload ) c'est encore plus vrai sur une instance serveur de Dodoc = dans le nuage
De mon disque dur vers l'appli (téléverser) = flèche vers le haut ou de l'appli vers mon disque (télécharger)= flèche vers le bas, même si je me place depuis l'appli.
Si je prends l'exemple de Firefox le téléchargement est une flèche vers le bas...

J'avoue que je n'avais pas fait attention à la flèche vers le bas de "Importer"
En recherchant d'autres exemples, je trouve qu'une flèche vers la droite correspondrait assez bien, comme les flèches pour ajouter des médias à une publication.
Donc
![picto_importer](https://user-images.githubusercontent.com/29262866/71130620-b0c93500-21f2-11ea-9135-e85536849c4e.png)
![picto_importer_ligne](https://user-images.githubusercontent.com/29262866/71130946-8d52ba00-21f3-11ea-84aa-b5cc1a1d812d.png)

Au final :  je dirais : télécharger / téléverser = bas / haut
importer / exporter : horizontale entre / sort

Mais c'est un peu comme le scroll à la molette sous Linux et sous MacOS, je me fais toujours surprendre  ;) 


**Pour le picto crayon = "Ajuster",** je n'étais pas non plus satisfait, tu as raison, il faudrait un picto plus cohérent avec un média image, peut-être une baguette magique (= Améliorer dans Shotwell sous linux) ? : 
![baguette_magique](https://user-images.githubusercontent.com/29262866/71131970-81b4c280-21f6-11ea-9609-d85aa0a6ef0a.png)
https://www.shutterstock.com/fr/image-vector/simple-set-image-editing-related-vector-1542182165
ou les niveaux si d'autres outils (contraste / luminosité / couleur ) arrivent plus tard?
![ajuster](https://user-images.githubusercontent.com/29262866/71132119-e8d27700-21f6-11ea-8a05-05e32d7812fd.png)

https://www.shutterstock.com/fr/image-vector/simple-set-photo-editing-related-vector-1480268888


J'ai vu aussi que "Ajuster" était présent pour les son / texte / document mais qu'il n'est pas utilisé.
Peut-être le masquer si inutile ?
Pour les vidéos, à quoi correspond l'option "Optimiser la vidéo" ?
Chez moi ça tourne en boucle quand je la lance sur une vidéo.

**Comment by louis-ev** [comment]
Ok avec tout ça, ça me parait effectivement plus cohérent. Merci !

**Comment by jpclerc39** [comment]
> Au final : je dirais : télécharger / téléverser = bas / haut
> importer / exporter : horizontale entre / sort

+1

à l'image du téléchargement d'un projet, il y a une flèche vers le haut, + logique de l'inverser
![image](https://user-images.githubusercontent.com/57361822/71319478-3709a380-249f-11ea-9767-cd05ddeb3f7f.png)

**Comment by louis-ev** [comment]
Dernier ajout à do•doc 8.2 :)
