### ISSUE TITLE
Emplacement du dossier de stockage

### ISSUE THREAD

**Issue by alejandrovze** [l-atelier-des-chercheurs/dodoc#336]
Bonjour,

Il me semble que nous ne pouvons pas contrôler l'emplacement du dossier de stockage - sur Mac OS il est situé à ~/Documents/dodoc2. Il serait bien de pouvoir utiliser le dossier qu'on veut et orienter l'application vers son emplacement. 

alejandro

**Comment by louis-ev** [comment]
Bonjour, merci pour votre retour
c’était possible sur la version précédente (la 6.2.1) mais ça complexifiait trop pour les utilisateurs novices… Dans quelle(s) situation(s) cela vous serait-il utile ?

**Comment by alejandrovze** [comment]
Bonjour, désolé pour le délai de réponse. Ça serait pour mettre le dossier de stockage dans une Dropbox pour y avoir accès depuis différents ordinateurs, sans avoir besoin de passer par le processus de scanner le code QR sur l'ordinateur principal.

**Comment by louis-ev** [comment]
Bonjour,

c’est une chouette idée qui justifierai de pouvoir déplacer le dossier de stockage.

La seule limite à ce cas de figure est dans le cas où dodoc est lancé alors que dropbox synchronise de nouveaux contenus – qui n’apparaîtraient donc pas dans l’application à moins de la relancer.

Malgré cette limite ça semble effectivement pertinent pour un certain nombre de situations, je la place dans la liste des fonctionnalités pour la prochaine version majeure.

**Comment by louis-ev** [comment]
@sarahgarcin j’attends un descriptif détaillé de l’emplacement de l’option, et de son comportement (elle déplace les contenus déjà créés ou pas, fait redémarrer do•doc, etc.)

**Comment by louis-ev** [comment]
Une fonctionnalité avancée intéressante pour la version 9 de do•doc (qui embarquera probablement un panneau "réglages" permettant d’ajuster ce genre de choses).
À venir donc, mais impossible de savoir quand.

**Comment by sarahgarcin** [comment]
Il faudrait effectivement un panneau réglages permettant de d'ajuster des fonctionnalités générales de dodoc en local.
J'imagine que lorsqu'on installe dodoc, le dossier se créer par défaut sur Documents/dodoc2. 
Dans le panneau de réglages, un bouton permet de choisir un nouvel emplacement, lorsqu'on change d'emplacement, le dossier se déplace, dodoc remet tous les liens à jour et redémarre.

Tu en penses quoi @louis-ev ?
On repousse à la version 10 ?

**Comment by louis-ev** [comment]
On repousse oui :)

**Comment by jubonhomme** [comment]
Je pense qu'on peut fermer celle-ci non ?

![image](https://user-images.githubusercontent.com/29262866/220757535-48b28cee-0818-42b5-a0a4-476350c1fece.png)
