### ISSUE TITLE
NFC comment ça marche ?

### ISSUE THREAD

**Issue by t3vall** [l-atelier-des-chercheurs/dodoc#337]
Bonjour, nouvel utilisateur (fablab) de do.doc (bel outil au passage) je cherche des infos sur le fonctionnement du NFC.
Comment cela marche avec do.doc et comme l'installer.
De mon coté j'ai des arduinos et lecteurs mais comment se fait l'interaction ? la connexion avec le pc ?

Merci

Sinon super outil pour documenter. Merci

**Comment by louis-ev** [comment]
Bonjour,

la fonctionnalité NFC permet de simplifier la connexion d’un utilisateur, de manière à bien tagger les médias qu’il ajoute (à terme l’objectif est d’aller plus loin dans la personnalisation de l’interface pour chaque contributeur). Pour des raisons de simplicité d’utilisation elle a été développée avec/pour un boitier de ce type : http://amzn.eu/d/7wykCYQ et des tags NFC du commerce (nous utilisons ceux-là : https://letmeknow.fr/shop/fr/cartes-programmables/223-tag-nfc-dynamique.html?search_query=nfc&results=4

Elle devrait être compatible avec Arduino sans trop de difficultés : il suffit que l’Arduino lise l’ID du tag et le renvoie comme des événements clavier suivi de la touche entrée.
Dans toutes les pages, do•doc écoute tous les codes qui font 8, 10, 12 ou 13 chiffres de long (par exemple 42578427) suivis de la touche entrée, le tout enregistré dans un interval de temps inférieur à 1 seconde.

Le tuto et le code sur la page suivante peuvent servir de base pour utiliser Arduino et un module NFC : https://learn.adafruit.com/nfc-ring-password-helper/code

Remplacer les événements `Keyboard.write('m');` par :
```
Keyboard.write(cardidentifier);
Keyboard.write('\n');
``` 

(à vue de nez).

Si besoin nous pouvons vous aider à débugger ce montage et si vous pouvez le documenter nous sommes intéressés.

Merci à vous !

**Comment by t3vall** [comment]
bonjour, merci pour votre retour.
Si je documente je vous tiendrai au courant.

Cordialement

Le lun. 8 oct. 2018 à 13:20, Louis Eveillard <notifications@github.com> a
écrit :
