### ISSUE TITLE
identification obligatoire

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#345]
Une option sur l’application (et pour tous les appareils) qui oblige à s’identifier avant de capturer/publier.

Un timeout qui déconnecte un utilisateur si inactivité ?

**Comment by louis-ev** [comment]
Dans le panneau de règlages

**Comment by jubonhomme** [comment]
Il me semble que c'est possible sur la version 9.0.15 
![image](https://user-images.githubusercontent.com/29262866/85343803-25f12c00-b4ee-11ea-823a-6edce44c1531.png)

A fermer ?

**Comment by louis-ev** [comment]
Pour l’instant l’obligation est superficielle, uniquement au niveau interface (et pas côté serveur) donc je préfère la laisser ouverte pour créer des vérifications côté serveur qui empêchent bien la connexion et la création si on est pas auteur.

**Comment by sarahgarcin** [comment]
un option à ajouter dans le panneau de réglages ?

**Comment by louis-ev** [comment]
Ce panneau de réglage viendra dans la v10.

**Comment by jubonhomme** [comment]
voir issue #440

**Comment by jubonhomme** [comment]
Je ferme celle ci, doublon avec la #440
