### ISSUE TITLE
Mettre les thumbs dans un dossier thumbs ? 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#346]
Ça serait plus pratique quand tu navigues dans les dossier

**Comment by louis-ev** [comment]
C’est déjà le cas ?
Un dossier dodoc2 > _thumbs  contient toutes les _thumbs.
Tu pensais à autre chose ?

**Comment by sarahgarcin** [comment]
non c'est moi qui suis bête et qui ai confondu les versions de dodoc
