### ISSUE TITLE
exporter un projet facilement

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#347]
Export possible de projet : 
1. génération d’un zip 
2. téléchargement depuis n’importe quel appareil
3. importation grâce à un bouton sur la home, qui place ensuite le projet au bon endroit. Si dossier déjà existant renommage du dossier.

**Comment by jubonhomme** [comment]
L'export fonctionne très bien avec le bouton "télécharger".
Reste à implémenter l'import d'un projet à partir d'un ZIP

**Comment by louis-ev** [comment]
Oui, c’est pas top.
J’y vais molo la dessus car il faudrait pas qu’en important un dossier corrompu (qui ne contient pas de fichier meta.txt par exemple) ça fasse  planter l’ensemble du dodoc ! Ou en important un zip très très lourd, trop pour la machine qui héberge dodoc (décompresser un zip c’est pas mal de taf).
Je regarde bientôt. Merci pour la relance en tout cas :)

**Comment by jubonhomme** [comment]
J'ai eu plusieurs retours pour avoir cette fonction d'import.

Par contre que se passe -t il pour les noms d'auteurs qui n'existent pas sur la nouvelles instance par exemple, ou pour les accès si le projet est verrouillé pour un auteur à l'export et que cet auteur n'existe pas du côté import ?

A la place d'un dossier ZIP... est-ce qu'on pourrait imaginer que ce soit dodoc qui aspire du contenu dans un autre dodoc ?
Exemple : je veux passer le projet X de dodoc A local vers dodoc B serveur
Je me connecte sur dodoc B serveur en tant qu'auteur depuis un navigateur
Je clique sur importer dans la home
je colle l'url du projet que j'ai récupéré de depuis dodoc A local / ou je scan le QR code du projet 
dodoc B serveur aspire le projet avec média / mot clé / auteurs liés

**Comment by louis-ev** [comment]
Non malheureusement, le serveur ne peux pas récupérer du contenu sur ta machine — par contre il existe un attribut pour pouvoir sélectionner un dossier entier / plus pratique que d’exporter un ZIP puis de l’importer ensuite. Tu peux tester ça : https://codepen.io/simevidas/pen/ZJjmWG ?
On pourrait imaginer un menu "Importer un projet" = deux possibilités 
-> importer un ZIP exporté depuis do•doc (fonctionnalité "Télécharger tout un projet") ou  
-> importer directement un dossier qui correspond à un projet et se trouve dans `Documents/dodoc2`

Voir importer tout un do•doc : projets + auteurs + recettes. Mais alors gros risque de conflits…

> Par contre que se passe -t il pour les noms d'auteurs qui n'existent pas sur la nouvelles instance par exemple, ou pour les accès si le projet est verrouillé pour un auteur à l'export et que cet auteur n'existe pas du côté import ?

Si nom d’auteurs non-existants : rien. C’est comme si la fiche auteur du projet avait été supprimée. Du coup un projet protégé par ses auteurs est bloqué (sauf aux admins). À noter cependant que si une fiche auteur comporte le même nom "slug", alors elle devient auteur. Si il y a un auteur "louis" en local au projet, si l’auteur "louis" existe en ligne alors il deviendra auteur.

**Comment by jubonhomme** [comment]
Il est maintenant possible d'exporter un projet de dodoc 10 en téléchargeant un ZIP et de l'importer dans un autre dodoc 10
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/88988fdb-91fa-4ccc-a909-42e89ad6c80b)

**Comment by louis-ev** [comment]
Mieux vaut tard que jamais 😄
