### ISSUE TITLE
Utilisation d'un reflex numérique comme webcam (Ubuntu)

### ISSUE THREAD

**Issue by BenChico** [l-atelier-des-chercheurs/dodoc#348]
A fonctionné pour un Canon EOS 550D avec Dodoc.

[Ici](http://gphoto.org/proj/libgphoto2/support.php) la liste des appareils photos supportés.
Nous utilisons DoDoc sous ubuntu.
Il est nécessaire d'installer les paquets suivants:
- v4l2loopback
- gphoto

Il faut connecter l'appareil en USB puis le déconnecter dans le gestionnaire de fichier (pour pas qu'il soit identifié comme un disque).
Ensuite saisir les commandes suivantes dans le terminal:
modprobe v4l2loopback exclusive_caps=1
puis
_gphoto2 --stdout --capture-movie | gst-launch-1.0 fdsrc fd=0 ! decodebin name=dec ! queue ! videoconvert ! tee ! v4l2sink device=/dev/video0_

Pour arrêter le processus:
_sudo rmmod v4l2loopback_

**Comment by jubonhomme** [comment]
Bonjour, 
Merci pour cette astuce, fonctionne aussi avec un canon 70D / Do•doc 8.2.5 / Ubuntu 18.04
J'ai juste modifié  "device=/dev/video0" en  "device=/dev/video1" car sur mon ordinateur portable video0 correspond à la caméra intégrée.

En route pour le StopMotion avec la profondeur de champ d'un appareil réflex et le pilotage depuis l'interface de Do•oc !!

**Comment by lienardj** [comment]
Bonjour
Ca marche pour moi avec un Eos 70d, mais la vidéo est très saccadé. VLC rapporte un débit de 30 i/s, mais la video fait plutôt penser à 10 i/s. Une idée?

**Comment by tooms4444** [comment]
Hello, I know it's been a long time; but I'm missing the **v4l2sink** command. Is there any detailed explanation somewhere about all this ? Thanks for any update, if somebody hears me

**Comment by jubonhomme** [comment]
Hello,
in a terminal :
`sudo modprobe v4l2loopback exclusive_caps=1`

`gphoto2 --stdout --capture-movie | gst-launch-1.0 fdsrc fd=0 ! decodebin name=dec ! queue ! videoconvert ! tee ! v4l2sink device=/dev/video1`

**Comment by tooms4444** [comment]
Thanks for following up; but that won't work for me.
I've tried it a while a go and couldn't find "v4l2sink" in my system whatever this is.

BTW> v4l2-ctl --list-devices
```
GPhoto2 Webcam (platform:v4l2loopback-000):
	/dev/video2
Integrated_Webcam_HD: Integrate (usb-0000:00:14.0-12):
	/dev/video0
	/dev/video1

```
BTW> ffmpeg -f v4l2 -i /dev/video1 my_session.mp4
```
[video4linux2,v4l2 @ 0x56455486f6c0] ioctl(VIDIOC_G_INPUT): Inappropriate ioctl for device
/dev/video1: Inappropriate ioctl for device

```
BTW> ffmpeg -f v4l2 -i /dev/video2 my_session.mp4
```
[video4linux2,v4l2 @ 0x5601469216c0] Not a video capture device.
/dev/video2: No such device

```

**Comment by tooms4444** [comment]
BTW> gphoto2 --stdout --capture-movie | gst-launch-1.0 fdsrc fd=0 ! decodebin name=dec ! queue ! videoconvert ! tee ! v4l2sink device=/dev/video1
```
Acquisition d'aperçus d'image comme vidéo de « stdout ». Ctrl-C pour abandonner.
AVERTISSEMENT : pipeline erroné : pas d’élément « v4l2sink »
```
BTW> gphoto2 --stdout --capture-movie | gst-launch-1.0 fdsrc fd=0 ! decodebin name=dec ! queue ! videoconvert ! tee ! v4l2sink device=/dev/video2
```
AVERTISSEMENT : pipeline erroné : pas d’élément « v4l2sink »
Acquisition d'aperçus d'image comme vidéo de « stdout ». Ctrl-C pour abandonner.
```

**Comment by tooms4444** [comment]
That command is working, though :
`gphoto2 --set-config capturetarget=1 --set-config viewfinder=1 --set-config movierecordtarget=Card --wait-event=10s --set-config movierecordtarget=None --wait-event-and-download=2s`

**Comment by jubonhomme** [comment]
Je pense pas que ce soit nécessaire de le mettre dans l'interface de dodoc. Utilisation très rare quand même

Je vois ça plus dans une belle documentation sur une recette ;)
J'avais commencer un récap sur le forum
https://forum.latelier-des-chercheurs.fr/t/capturer-avec-differentes-cameras-dans-do-doc/218
