### ISSUE TITLE
marmite - retour d'atelier avec les lycéens

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#351]
Fonctionnalités utilisées fréquemment par des lycéens dans Première Pro pour réaliser des petites vidéos. 
Ces fonctionnalités me semblent nécessaires à intégrer dans la marmite de médias.
- Agencer / mettre dans l'ordre souhaité les médias (vidéos, images, écran titre) 
- Créer un écran titre
- Couper / rogner / raccourcir les séquences vidéos
- Changer la vitesse des séquences vidéos
- Changer la taille des images ou des vidéos 
- Créer des transitions entre les séquences (fade et fondu au noir) 
- Exporter en format mp4

**Comment by jubonhomme** [comment]
Une partie des fonctionnalités ont été ajoutées, le reste revient en partie à l'issue #350 

Les deux sont peut être à fusionner

> Ces fonctionnalités me semblent nécessaires à intégrer dans la marmite de médias.
> 
>     Agencer / mettre dans l'ordre souhaité les médias (vidéos, images, écran titre)
Possible dans recette "Montage vidéo"
>     Créer un écran titre
Possible dans recette "Page à Page" ou "dessin" export image
>     Couper / rogner / raccourcir les séquences vidéos
A ajouter #350
>     Changer la vitesse des séquences vidéos
Possible dans recette "Effet vidéo"
>     Changer la taille des images ou des vidéos
A ajouter
>     Créer des transitions entre les séquences (fade et fondu au noir)
Possible dans recette "Montage vidéo"
>     Exporter en format mp4
A ajouter

**Comment by louis-ev** [comment]
> Changer la taille des images ou des vidéos

Plus précisément, il faudrait pouvoir faire quoi ?

> Exporter en format mp4

C’est déjà le cas ?

**Comment by sarahgarcin** [comment]
Je pense qu'on peut fermer, c'est tout bon ! 
Ça a été implémenté en septembre 2020
