### ISSUE TITLE
marmite - son sur les vidéos

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#352]
— Pouvoir enlever le son de ou des vidéos 
— Mettre un autre son si le commentaire est à refaire par-dessus.
— Fond sonore avec volume ajustable (pour mettre une musique de fond)

**Comment by louis-ev** [comment]
Il manque plus que pouvoir enlever le son d’une vidéo. Pas sur de l’intérêt de cette recette cela dit… ?

**Comment by sarahgarcin** [comment]
Je pense que ça va être utile de pouvoir enlever le son d'une vidéo pour l'atelier à Crest

**Comment by jubonhomme** [comment]
Je complète ce fil avec une demande pour simplifier l'ajout d'un doublage son sur une vidéo.

Dans le cas d'une animation réalisée avec l'outil capture, il n'y a jamais de son puisque c'est une série d'images qui servent à construire la vidéo. Une fois que l'on a produit la séquence vidéo, on souhaite souvent ajouter un doublage son.
Au début je pensais qu'il pourrait y avoir un ajout directement dans l'outil animation. 
Voici un exemple l'appli "stop motion studio" qui permet l'ajout de son sur la séquence vidéo :  
https://test.dodoc.fr/film/media/sons-sur-video*webm*txt

Pour l'instant : 
j'enregistre la vidéo sur l'ordi
je la lance en boucle dans VLC en lecture
j'ouvre la capture son dans dodoc
au moment où la vidéo reprend au début je lance l'enregistrement du son et je double en live, j'arrête quand la vidéo arrive à la fin. 
J'utilise ensuite la recette son sur vidéo pour recoller le son que je viens d'enregistrer et la vidéo dans dodoc.

Bref c'est pas simple ;)

Mais cela pourrait très bien se faire dans la recette "son sur vidéo" et être aussi utilisé pour d'autres vidéos que celle du mode animation.

Donc dans la recette son sur vidéo  il y aurait la recette actuelle  :  une vidéo + un son d'un projet 
et
une vidéo + un micro -> on clique sur le micro -> ouverture d'une petite popup en dessous de la vidéo (comme celle de l'outil capture son du menu de la recette page à page ou d'un bloc de récit éditable enregistrement son)
-> on clique sur le bouton d'enregistrement -> un compte à rebours 3...2....1 -> lancement de la lecture de la vidéo et d'un enregistrement son dans la capture en dessous en simultané

Un peu comme une recette Récit avec un bloc vidéo au dessus et un bloc enregistrement son en dessous et lorsque l'on clique sur enregistrer son ça lance la vidéo avec un compte à rebours de 3s et l'enregistrement son se déclenche aussi avec un retard de 3s.

Un peu sur le modèle de l'app Stop Motion Studio ou d'IMovie

**Comment by louis-ev** [comment]
On peut faire ça avec le mode "référence" de la fenêtre "éditer un média".

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/1948417/112297260-f9915880-8c95-11eb-8b86-57a5fb84fdb2.png">

On peut envisager un mode plus pratique qui suit ce que tu dis pour la prochaine version :)
Je reporte !

**Comment by jubonhomme** [comment]
Un petit point d'étape sur enlever le son d'une vidéo / remplacer le son d'une vidéo par un autre / ajouter une deuxième piste son / caler un son sur une vidéo.

La recette "Recouper une vidéo" permet presque la suppression du son sur la vidéo. On pourrait mettre le niveau à zéro et exporter la vidéo complète. 
Sauf que le volume de la piste son n'est pas repris à l'export d'après les tests que j'ai fait.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/1b049845-0631-4292-840c-9059ed7699dd)

Si on arrive à reprendre le multipiste de Logimix / waveform on pourra aussi ajouter une deuxième piste ou des bruitages et exporter le tout.
Voir #535 #606

**Comment by louis-ev** [comment]
À tester
j'ai ajouté deux boutons "au tout début" et "à la toute fin" pour annuler le raccourci quand on veut juste changer le volume.
Le volume devrait s'enregistrer dans les métadonnées de la fabrication et être syncrhonisé à tous les utilisateurs connectés sur la recette

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/5852aaa4-bc33-4b64-b6ea-5b650d85cfd7)

**Comment by jubonhomme** [comment]
J'ai fait quelques tests et oui je confirme que le volume est bien pris en compte maintenant à l'export. 
Très bonne idée aussi de permettre l'export même si on raccourci pas la vidéo.
