### ISSUE TITLE
publication - pouvoir choisir une taille de typo spécifique

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#355]
Lors des ateliers avec les lycéens, on était assez vite bloqué avec le peu de taille de typo que propose l'éditeur de texte (h1, h2, h3…) 
Il faudrait avoir un menu déroulant pour choisir la taille de la typo.

**Comment by louis-ev** [comment]
Possible en CSS mais un petit menu ne serait pas de trop, c’est sur…

**Comment by jubonhomme** [comment]
Juste un bug d'affichage avant de pouvoir fermer ce post : 

Quand on veux réduire la taille de police et que l'on pousse à gauche le curseur ça clignote au bout voir ici
https://test.dodoc.fr/presentation-7-mai-atelier-canope-57/media/bug-taille-police-1*webm*txt
