### ISSUE TITLE
Amélioration des options de mise en forme de la publication 

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#358]
> Voici quelques exemples qui me semblent pertinents :
– centrage des textes avec ferrage à gauche / droite ou justification.
– gérer des calques, les verrouiller si besoin. Exemple : images plein pot avec textes par-dessus.
– modifier les typos, changer la couleur.
– créer des blocs de couleur pour faire des bandeaux par exemple.
– possibilité de rendre le fond des blocs de texte transparent.
– changer la forme des blocs (rectangle / cercle…)
– possibilité de tracer des flèches ou des lignes avec des cercles pour pointer sur un paragraphe.

de http://forum.latelier-des-chercheurs.fr/t/evolution-de-do-doc

**Comment by olerun** [comment]
+1
à minima verrouiller position et dimension

**Comment by jubonhomme** [comment]
Tout y est je pense... à fermer aussi !

**Comment by louis-ev** [comment]
Il me semble qu’il manque la transparence des fonds… utile ?

**Comment by jubonhomme** [comment]
Heu non ça fonctionne bien...

https://test.dodoc.fr/_publications/test-dessin/

**Comment by jubonhomme** [comment]
Par contre je viens de trouver un bug... quand on applique une rotation à un objet on ne peut pas le déplacer au delà de son emprise lorsqu'il n'est pas tourné.
Par exemple la ligne droite sur cette recette : 
https://test.dodoc.fr/_publications/test-dessin/

une fois que je la met à la verticale, je ne peux pas la déplacer vers la gauche jusqu’au bord, mais seulement à la limite de ce qu'elle pourrait si toujours à l'horizontale... je ne sais pas si c'est clair.
Je peux faire une vidéo s'il faut pour expliquer.

**Comment by louis-ev** [comment]
Je pensais à ces fonds colorés là : 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1948417/82028031-5e9f1980-9695-11ea-8eb4-0fc6f5410ece.png">

Pas possible actuellement de les mettre à 30 ou 40% d’opacité, c’est forcément un aplat. Je crois que @pog voyait une utilité à mettre de la transparence, pas toi ?

> Par contre je viens de trouver un bug... quand on applique une rotation à un objet on ne peut pas le déplacer au delà de son emprise lorsqu'il n'est pas tourné.

Alors c’est pas vraiment un bug vu que le code fait exactement ce qu’il faut mais pas assez malin pour détecter la rotation… En fait mes compétences en géométrie sont trop limitées (j’en ai bavé déjà pour trouver la bonne logique pour que la rotation suive bien la souris : 

`    rotateMove(event) {
      if (this.$root.state.dev_mode === "debug")
        console.log(
          `METHODS • MediaPublication: rotateMove with is_rotated = ${this.is_rotated}`
        );

      const pageX = event.pageX ? event.pageX : event.touches[0].pageX;
      const pageY = event.pageY ? event.pageY : event.touches[0].pageY;

      const center_of_block = {
        x:
          this.$refs.media.getBoundingClientRect().x +
          this.$refs.media.getBoundingClientRect().width / 2,
        y:
          this.$refs.media.getBoundingClientRect().y +
          this.$refs.media.getBoundingClientRect().height / 2,
      };

      function angle(cx, cy, ex, ey) {
        var dy = ey - cy;
        var dx = ex - cx;
        var theta = Math.atan2(dy, dx); // range (-PI, PI]
        theta *= 180 / Math.PI; // rads to degs, range (-180, 180]
        //if (theta < 0) theta = 360 + theta; // range [0, 360)
        return theta;
      }

      if (!this.is_rotated) {
        this.is_rotated = true;
        this.selectMedia();

        // this.rotateOffset.x = pageX;
        // this.rotateOffset.y = pageY;

        const initial_angle = angle(
          center_of_block.x,
          center_of_block.y,
          pageX,
          pageY
        );

        this.rotateOffset.angle = this.rotate - initial_angle;
      } else {
        const current_angle = angle(
          center_of_block.x,
          center_of_block.y,
          pageX,
          pageY
        );

        this.rotate = this.rotateOffset.angle + current_angle;

        console.log("this.rotate = " + this.rotate);

        const angle_on_90pos = Math.abs(this.rotate % 90);
        if (angle_on_90pos < 5 || angle_on_90pos > 85)
          this.rotate = Math.round(this.rotate / 90) * 90;
      }
    },
`

Je crois que j’ai besoin d’un cours ou d’un prof de math pour faire ça :) Détecter les bords extérieurs d’un rectangle en prenant en compte la rotation.

**Comment by jubonhomme** [comment]
Pour la transparence : 
> Pas possible actuellement de les mettre à 30 ou 40% d’opacité, c’est forcément un aplat

Exact, on peut enlever le fond d'un bloc (pas de couleur) mais pas gérer l'opacité... j'avais le souvenir d'en avoir fait mais c'était par le css (opacity: ... )
Donc oui pour un curseur pour gérer l'opacité/transparence des blocs sans passer par le css

Pour la rotation : 
Si je comprends bien... c'est le centre de l'objet qui sert de position quelque soit la rotation.
Tu n'as pas les coordonnées des sommets ?

**Comment by jubonhomme** [comment]
L'opacité est fonctionnelle
Le bug sur les déplacements limités après une rotation est réparé aussi

Je pense que cette fois ci tout est bon pour fermer

**Comment by louis-ev** [comment]
Je suis pas entièrement satisfait du redimensionnement après une rotation mais pour l’instant je pense que c’est suffisament fonctionnel pour la v9. À améliorer + tard :)
