### ISSUE TITLE
Espacer les boutons "sélectionner" et "supprimer" des vignettes auteurs

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#364]
Plusieurs élèves ont supprimé leur vignette "auteur" en voulant la "sélectionner" ou "dé-sélectionner".
Les deux boutons sont très proches sur la vignette auteur.
En testant la zone de sélection, je me suis aperçu qu'en fait c'est toute la vignette qui est cliquable pour sélectionner et dé sélectionner.  
Je me demande s'il ne serait pas préférable d'enlever complètement le bouton "sélectionner" / "dé sélectionner" et ne laisser qu'une petite icône type corbeille dans un coin pour la suppression de l'auteur, ou encore à l'aide d'une vignette "supprimer un auteur" identique à celle "créer un auteur" et qui permettrait une sélection multiple d'auteurs à supprimer.
La simple vignette cliquable est suffisante à mon avis, et qui rendrait aussi plus évident le fait que toute sa surface est cliquable.

**Comment by louis-ev** [comment]
C’est une bonne idée oui, on voit ça.
