### ISSUE TITLE
Chaque tag se transforme en couleur dans la galerie de medias

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#366]

**Comment by louis-ev** [comment]
Ça n’a de sens que si tous les tags ont bien des couleurs différentes non ? Tu peux donner un cas de figure où ça serait utile ?

**Comment by louis-ev** [comment]
Manque des infos.

**Comment by sarahgarcin** [comment]
je ne me rappelle plus pourquoi j'avais noté ça, je pense juste que c'est perturbant que les mots clés aient des couleurs différentes sans raison, actuellement bleu ou rouge

**Comment by louis-ev** [comment]
Tu penses qu’il faudrait pas mettre de couleurs ?

**Comment by sarahgarcin** [comment]
JE dirais, soit pas de couleur type en noir sur gris clair soit une seule couleur

**Comment by sarahgarcin** [comment]
si t'es ok je le mets en dodoc v9

**Comment by louis-ev** [comment]
Je suis un peu ambivalent…

Tu préfère B à A ?

A 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1948417/112484812-90374580-8d7a-11eb-8944-c1da8bacb157.png">

B
<img width="306" alt="image" src="https://user-images.githubusercontent.com/1948417/112484823-92999f80-8d7a-11eb-9ab9-93e10ee0bebc.png">

**Comment by louis-ev** [comment]
@jubonhomme ton avis sur la question ?

**Comment by jubonhomme** [comment]
Effectivement j'ai eu plusieurs fois la question lors de présentation de dodoc... "ça correspond à quoi les couleurs des mots clés ?" 
Si j'ai bien compris c'est un peu aléatoire... donc pas d'infos à en tirer.
Si c'est juste pour mettre de la couleur je pense que ça perturbe un peu les utilisateurs qui cherchent une signification. 
Donc plutôt B
Mais pourquoi pas trouver une utilisation pertinente pour utiliser deux ou trois couleurs de mots clés. 
Par exemple : 
dodoc = mot simple = couleur 1  
machine à coudre = mot composé = couleur 2

**Comment by louis-ev** [comment]
En fait c’est pas totalement aléatoire, c’est un calcul de math qui renvoie toujours le même nombre et applique un traitement ou l’autre s’il est pair ou impair. Comme ça la couleur reste associée.
Si j’en ajoutai 4 ou 5 autres ça serait plus pertinent, mais toujours arbitraire. L’idée était de faciliter la reconnaissance visuelle, mais il y a mieux à faire probablement.

Ta règle de mot simple et mot composé me paraît étonnante mais après tout… @sarahgarcin  ?

**Comment by sarahgarcin** [comment]
Effectivement, j'ai eu plusieurs fois la question concernant l'utilité des couleurs, il apparait que c'est perturbant. Je serai personnellement plutôt partante pour la solution B

**Comment by louis-ev** [comment]
B implémenté.
