### ISSUE TITLE
avoir un système de retouche d'images

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#367]
à définir mais fonctionnalités possibles: 
- Rogner
- noir et blanc / monochromie / bichromie
- contraste
- Luminosité
- Niveaux

**Comment by jubonhomme** [comment]
Il sera peut être possible de reprendre en partie le menu "effet" de la capture

![image](https://user-images.githubusercontent.com/29262866/113788889-4ec17580-973e-11eb-9336-cb273eb39898.png)

et faire comme pour les effets vidéos mais à partir d'une image
![image](https://user-images.githubusercontent.com/29262866/113789004-9942f200-973e-11eb-964b-699e36d3b3f9.png)

**Comment by jubonhomme** [comment]
A fermer 

Recette "Modifier une image" dans la V10

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/e8bccc6d-db80-454c-a189-9ec1852a23fd)
