### ISSUE TITLE
Pouvoir sortir plus facilement du mode "déclenchement automatique" dans animation

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#371]
Une fois que l'on a sélectionné le mode déclenchement automatique dans Enregistrer/animation il faut mettre 0 sec pour sortir de ce mode ou bien fermer complètement Dodoc.

Il faudrait ajouter une possibilité de revenir plus facilement au mode de capture image par image.

(version 8.0.8)

**Comment by louis-ev** [comment]
Effectivement oui, c’est assez peu pratique en l’état.

Par exemple comme ça ? J’ai essayé d’espacer suffisament pour éviter de cliquer sur le bouton "désactiver" en essayant de cliquer, tu me diras si tu as une autre idée ou si il faut + d’espace.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/1948417/56914683-0494db80-6ab5-11e9-9dc9-5df29d4d1a3a.png">

**Comment by jubonhomme** [comment]
Je le verrai bien directement dans la barre de choix de durée pour éviter la confusion avec avec "désactiver l'animation"  et pour rester dans le bandeau des boutons. Comme ça par exemple  

![timelaps](https://user-images.githubusercontent.com/29262866/56929445-decdfd80-6ad9-11e9-8f84-23ed7fc15adf.png)

Et si possible avec la sélection du temps ( 2   5    10   secondes ) verrouillée et en gris clair si c'est désactivé


Autre proposition
bouton initial avec déroulé du choix d'une durée comme dans ta proposition au passage de la souris
![timelaps2](https://user-images.githubusercontent.com/29262866/56930480-1a1dfb80-6add-11e9-8891-98ddc4eaaeff.png)

Puis changement de couleur si activé avec possibilité de clic dessus pour le désactiver et retour au bouton initial
![timelaps3](https://user-images.githubusercontent.com/29262866/56930752-1e96e400-6ade-11e9-8702-1610833b75c4.png)

**Comment by jubonhomme** [comment]
autre détail, lorsque la durée de l'intervalle est supérieure à 99, le troisième chiffre est caché dans la fenêtre
![Capture d’écran de 2019-04-30 00-38-47](https://user-images.githubusercontent.com/29262866/56931489-75052200-6ae0-11e9-8233-9b0f64e63ebb.png)

**Comment by louis-ev** [comment]
Hello Julien,
ok je vois, je pense que si on peut se passer de la petite fenêtre et directement afficher l’info qqpart ça serait pas du luxe.
Merci pour tes propositions, je me penche dessus rapidement.

**Comment by louis-ev** [comment]
J’ai procédé à plusieurs améliorations là-dessus : 

<img width="183" alt="image" src="https://user-images.githubusercontent.com/1948417/58130810-4da3ff80-7c1d-11e9-973f-c68724462d35.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/1948417/58130814-509ef000-7c1d-11e9-9cbb-d8a78e3b798a.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1948417/58130835-5a285800-7c1d-11e9-9f07-1720cf6a36b1.png">

Dans la prochaine (et probable dernière) bêta de do•doc 8 avant la version stable :)

**Comment by jubonhomme** [comment]
Génial !
