### ISSUE TITLE
plantage au drag and drop sur linux

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#372]
De Lionel L. : 
```
Par contre j'ai un dysfonctionnement quand je fais - par erreur - un drag&drop sur un élément. L'application se gèle et je suis obligé de la killer.
J'ai fait une petite vidéo (ci-joint) pour te montrer ça.
```
![dodoc Peek 05-05-2019 15-56](https://user-images.githubusercontent.com/1948417/57215127-4a3d3100-6fec-11e9-846b-b5df74832fa6.gif)

**Comment by jubonhomme** [comment]
Je suis sur linux Ubuntu 18.04 et Dodoc 8.0.8 dev et je n'arrive pas à reproduire le bug.

Quand j'essaie de faire un Drag an drop comme toi, j'ai une flèche rouge sur fond gris qui s'affiche avec le texte "déposer vos contenus ici pour les importer"

**Comment by llaske** [comment]
C'est moi Lionel L :smile: 

Je suis aussi en Ubuntu 18.04.
Je ne sais pas si ça peut jouer mais je l'ai lancé depuis l'AppImage ici: https://github.com/l-atelier-des-chercheurs/dodoc/releases/download/v8.0.8-dev/do.doc.8.0.8-dev.AppImage

**Comment by jubonhomme** [comment]
Bonjour Lionel
Moi j'ai téléchargé celle-ci ;
http://files.latelier-des-chercheurs.fr/do•doc%208.0.8-dev.AppImage

Mais j'imagine que c'est la même non ?

J'ai essayé de reproduire ton bug sur deux ordi différents et je n'ai pas ce problème. Je ne vois pas d'où ça peut venir.

Julien

**Comment by louis-ev** [comment]
Bonjour Lionel, Julien,
c’est effectivement le même fichier oui, donc c’est très étonnant que ce bug ne se manifeste pas systématiquement sur les mêmes configs.

`Quand j'essaie de faire un Drag an drop comme toi, j'ai une flèche rouge sur fond gris qui s'affiche avec le texte "déposer vos contenus ici pour les importer"`

Hmm c’est pas normal ça, ce visuel doit uniquement apparaître au glisser / déposer. Je corrige, du coup ça résoudra peut-être aussi ce soucis @llaske !
