### ISSUE TITLE
améliorer la gestion des blocs texte en publication

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#373]
Cet éditeur de texte sur le site de la fonderie Klim Type est plutôt intéressant : 

https://klim.co.nz/retail-fonts/national-2/

![image](https://user-images.githubusercontent.com/1948417/57300699-a4ff8700-70d7-11e9-8eb7-c3f1de3662b0.png)

**Comment by louis-ev** [comment]
C’est du quill, c’est à dire le même que celui qui s’affiche dans la page d’édition d’un média : 
<img width="702" alt="image" src="https://user-images.githubusercontent.com/1948417/57385347-976aff80-71b2-11e9-9d56-2f5764907bbb.png">

C’est effectivement assez malin d’utiliser quill pour ça, même si c’est pas forcément pertinent dans la mesure où y a pas d’édition de texte à cet endroit là… En même temps il pourrait y en avoir, et ça serait bien pratique de pouvoir éditer en place les blocs de texte.

À réfléchir pour la suite mais c’est une solution intéressante mine de rien.

Autre chose : pouvoir créer des blocs de texte dans une publication sans avoir à les placer dans un projet — notamment lorsqu’on parle de titres (ou ça complexifie de devoir les créer d’abord dans un projet).

**Comment by jubonhomme** [comment]
Juste pour info... avant fermeture aussi ;)

Sur cette page : [https://klim.co.nz/retail-fonts/national-2/](https://klim.co.nz/retail-fonts/national-2/)

Le curseur de la taille des textes n'a pas le bug comme sur dodoc... on dirait qu'il y a justement un temps de latence plus important à l'affichage.

**Comment by jubonhomme** [comment]
A fermer !
Si vraiment ça gêne j'ouvre une nouvelle issue pour le curseur de la taille des polices.

**Comment by louis-ev** [comment]
>  Si vraiment ça gêne j'ouvre une nouvelle issue pour le curseur de la taille des polices.

Résolu hier, tu as pu tester ?

**Comment by jubonhomme** [comment]
Oui j'ai vu un changement du bouton du curseur mais ça saute toujours... beaucoup moins mais toujours quand même.
[https://test.dodoc.fr/test-dodoc-9-1/media/curseur-saute*webm*txt](https://test.dodoc.fr/test-dodoc-9-1/media/curseur-saute*webm*txt)

Ce qui est assez étrange, c'est que ça ne le fait pas sur le curseur des marges... il y a une différence de comportement entre les deux.

**Comment by louis-ev** [comment]
Le plus simple serait que la valeur appliquée le soit quand on lève la souris, mais du coup ça enlève le côté « temps réel » qui permet de tâtonner et voir le résultat... 
Dans l’idéal il faudrait que tant que tu as pas lâché le curseur ça fasse varier que pour toi, et quand tu laches alors ça propage la valeur à tout le monde. Mais ça demande beaucoup de code et il peut y avoir des bugs (vu qu’il y a un décalage entre ce que tu vois et la valeur réellement enregistrée).

**Comment by jubonhomme** [comment]
le plus étrange c'est que ça ne le fait pas pour le curseur du haut (marge) et seulement pour le curseur du bas (taille). 
Au niveau du code, c'est exactement les mêmes curseurs ?

Après c'est fonctionnel. C'est plus étrange que gênant.

**Comment by louis-ev** [comment]
La gestion du minimum est différente :)
Je passe la taille minimum du texte à 1, ça sautera plus et c’est plus logique.

**Comment by jubonhomme** [comment]
Ah exact, dès qu'on arrive à 0% ça saute et ça repart à 100%.
Donc 1% mini c'est parfait.

Et en regardant de plus près les marges... avec le curseur on peut aller de 0 à 100 pt mais ça n'est pas limité si on passe par les petites flèches bas et haut à côté de la valeur, on peut aller dans du négatif et au delà de 100. Est-ce que tu peux mettre des limites également sur ces deux boutons pour que ce soit raccord avec le curseur ? Au moins pour le mini à 0 et pas en négatif.

**Comment by louis-ev** [comment]
C’était le but, que tu puisses mettre une valeur plus élevée si besoin. Par contre en négatif c’est pas utile, sauf si ça peut permettre des effets sympa ?

**Comment by jubonhomme** [comment]
Oui, je pense aussi que le négatif n'est pas utile et qu'il faudrait justement empêcher de descendre en négatif par le bouton bas

**Comment by louis-ev** [comment]
Ok
