### ISSUE TITLE
Pouvoir nommer une publication lors de sa création

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#374]
Sur la version test 8.0.8, chaque nouvelle publication est nommée automatiquement dans le dossier dodoc2/_publication/  :
sans-titre-1
sans-titre-1-2
sans-titre-1-2-3
etc...
Même lorsque l'on renomme une publication dans "modifier" le nom du dossier dans dodoc2/_publication/ n'est pas modifié.

Cela n'est pas très pratique pour retrouver une publication dans les dossiers et ça va surtout poser des problèmes de noms de fichiers trop long à la 50e publication ;)

Dans la version 7.7.7 (avant la marmite) un nom de publication était demandé à chaque nouvelle création de publication comme c'est le encore le cas pour la création d'un projet, et le nom de la publication pouvait se modifier à posteriori dans les "réglages".
Maintenant la publication est créée directement sans passer par cette étape et le titre est sorti des réglages pour avoir son propre bouton modifier.
Je pense qu'il est préférable d'imposer le nommage de la publication à lors de sa création comme pour les projets, cela évite d'avoir plein de publications "sans titre".

Concernant la modification du titre à posteriori 
**Version 7.7.7**  
![modiftitre_dodoc7](https://user-images.githubusercontent.com/29262866/57486288-198c1e80-72ae-11e9-8c67-a912a2ecd4b9.png)

**version 8.0.8**
![modiftitre_dodoc8](https://user-images.githubusercontent.com/29262866/57486379-50623480-72ae-11e9-8b37-2ac47ec11e8b.png)

**Je proposerais plutôt quelque chose entre les deux, un peu comme ça** 
![proposition-modiftitre_dodoc8](https://user-images.githubusercontent.com/29262866/57486709-eb5b0e80-72ae-11e9-9744-ca9db5d45831.png)

On gagnerait un peu de place en hauteur et on associe mieux la modification au titre et non pas à la publication elle même (qui correspond à l’œil). 
Le bouton "modifier" à côté de "exporter" et "supprimer" porte à confusion je trouve.

Julien

**Comment by louis-ev** [comment]
Hello !

`Sur la version test 8.0.8, chaque nouvelle publication est nommée automatiquement dans le dossier dodoc2/_publication/ :
sans-titre-1
sans-titre-1-2
sans-titre-1-2-3`

C’est un bug stupide dans mon code : ça devrait être
sans-titre-1 
sans-titre-2
etc.

Ce qui serait déjà mon laborieux. Je regarde si je peux corriger ça rapidement.

` Même lorsque l'on renomme une publication dans "modifier" le nom du dossier dans dodoc2/_publication/ n'est pas modifié.`

Oui, c’est tout à fait normal : le nom du dossier/fichier sert d’identifiant et ce serait risqué de le changer pendant l’exécution de do•doc. Tu peux toujours le changer à la main après avoir fermé do•doc, l’important est qu’il ne contienne si caractères spéciaux ni espaces.

`Cela n'est pas très pratique pour retrouver une publication dans les dossiers et ça va surtout poser des problèmes de noms de fichiers trop long à la 50e publication ;)`

Je suis bien d’accord. À terme il faudrait par exemple faire des "aperçus visuels" de chaque recette pour retrouver plus facilement à quoi elle correspond, par exemple ?

`Dans la version 7.7.7 (avant la marmite) un nom de publication était demandé à chaque nouvelle création de publication comme c'est le encore le cas pour la création d'un projet, et le nom de la publication pouvait se modifier à posteriori dans les "réglages".
Maintenant la publication est créée directement sans passer par cette étape et le titre est sorti des réglages pour avoir son propre bouton modifier.
Je pense qu'il est préférable d'imposer le nommage de la publication à lors de sa création comme pour les projets, cela évite d'avoir plein de publications "sans titre".`

Vaste discussion. La raison pour laquelle nous avons changé ça est qu’il y a de très nombreux cas ou choisir un nom ne correspond pas à l’activité en cours avec la marmite : par exemple, rapidement assembler deux vidéos pour faire un montage ou faire une image parlante. Difficile de leur trouver un nom qui ai du sens, et ça bloquait les élèves à une étape pas très pertinente.

`On gagnerait un peu de place en hauteur et on associe mieux la modification au titre et non pas à la publication elle même (qui correspond à l’œil).
Le bouton "modifier" à côté de "exporter" et "supprimer" porte à confusion je trouve.`

Oui je suis d’accord, j’avais bien identifié le soucis. Mais à terme les recettes pourront comporter également un mot de passe, pas seulement un titre (et éventuellement d’autres champs comme les auteurs, ce qui était le cas avant mais pas utilisé). Du coup il faut conserver un panneau d’édition des publications qui permet de préciser tout ça.

Peut-être que la solution est à mi-chemin : en cliquant sur "créer", avoir une fenetre modale qui s’ouvre comme avant mais avec un pré-remplissage du titre "Document page à page № 12", la possibilité de le changer mais aussi celle de valider rapidement et de lui associer un mot de passe.

Qu’en penses-tu ?

D’ailleurs je me demande si le bouton "exportation" lui-même ne devrait pas exister ailleurs, en "fin" de la recette, de manière contextualisée par rapport à la recette elle-même. En l’état c’est pas du tout évident qu’il correspond à la fonction de "mélange" de la recette.

**Comment by jubonhomme** [comment]
` Oui, c’est tout à fait normal : le nom du dossier/fichier sert d’identifiant et ce serait risqué de le changer pendant l’exécution de do•doc. `

Ok je vois mieux l'enjeu du nom

`Peut-être que la solution est à mi-chemin : en cliquant sur "créer", avoir une fenêtre modale qui s’ouvre comme avant mais avec un pré-remplissage du titre "Document page à page № 12", la possibilité de le changer mais aussi celle de valider rapidement et de lui associer un mot de passe.`

Oui, je trouve cette proposition très bonne car ça réglerai bien les deux questions, avoir la possibilité de nommer une publication dès le début et du coup avoir un vrai nom de dossier "informatif" qui n'as pas besoin d'être modifié après fermeture à l'extérieur de dodoc, et la possibilité de ne pas bloquer la création de recettes à la volée avec un nom généré automatiquement dans la fenêtre si on ne remplace pas cette proposition. Ça ne rajouterai qu'un seul clic  pour arriver dans une nouvelle recette. Et si possible avec une proposition de nom contextuelle à la recette ... 

- document 1, ... pour les pages à pages
- montage 1, 2... pour les assemblages de 2 vidéos / les images sonores et les remplacements de son
- animation 1,... pour les stopmotions

`Oui je suis d’accord, j’avais bien identifié le soucis. Mais à terme les recettes pourront comporter également un mot de passe, pas seulement un titre (et éventuellement d’autres champs comme les auteurs, ce qui était le cas avant mais pas utilisé). Du coup il faut conserver un panneau d’édition des publications qui permet de préciser tout ça.`

Effectivement, si "modifier" ne sert pas qu'à modifier le nom mais à d'autres champs "mot de passe / auteurs / tag... autant laisser un panneau d'édition qui rassemble le tout.

Du coup il ne resterai que le bouton "réglages" en dessous tout seul dans le bandeau blanc. C'est logique qu'il ne soit pas intégré au dessus pour être en accord avec les autres recettes mais ça mange un peu la hauteur de l'affichage de la publication. A voir s'il pourrait se déplacer sur le côté ou un endroit plus discret.

Concernant "exporter" ça ne me choque pas qu'il soit en haut à côté de supprimer. Ça me parait logique et facile d'accès.

**Comment by louis-ev** [comment]
Merci pour les retours, on cogite là-dessus mais ça viendra probablement pour la prochaine (et dernière ?) bêta de la v8.
