### ISSUE TITLE
améliorer le panneau de réglage caméra/audio

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#386]
Le bouton "mise à jour" est sacrément mal placé, pas tj visible, pas évident.

**Comment by jubonhomme** [comment]
Je fais remonter... pas de nouveauté ici, juste un peu de mise en forme ?

Question : doit-on forcément passer par un bouton "mettre à jour" ? 
Sur les appli photo ou vidéo si je sélectionne une autre caméra ça bascule de suite sans faire "mettre à jour".
On peut imaginer qu'on sélectionne avec le menu déroulant et une fois sélectionner ça applique la mise à jour automatiquement.

La partie accès à distance ne parait pas indispensable non plus pour le moment. A enlever pour gagner en place et simplicité à comprendre ?

Il resterait juste les sources et la résolution.

Le bouton avec la roue et réglage pourrait revenir au milieu de la fenêtre et fonctionner en miroir de la marmite et du chat

Exemple : 

![reglage](https://user-images.githubusercontent.com/29262866/98312196-81b9de80-1fd1-11eb-9794-32ea75cc05bd.png)
![reglage-depli](https://user-images.githubusercontent.com/29262866/98312205-8383a200-1fd1-11eb-99d0-dc21d7118ef9.png)

**Comment by jubonhomme** [comment]
A fermer
