### ISSUE TITLE
Pouvoir supprimer une animation depuis la liste des animations de l'outil capture

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#387]
Avoir la possibilité de supprimer une animation "stopmotion" depuis la liste des animations.

Exemple :
- Ajout d'un icône de corbeille à côté de l'animation dans la liste,
- si clic alors message d'alerte "toutes les images de l'animation seront supprimées"
- bouton "ok" et "annuler"

En effet au bout d'un certains nombres de tests de l'outil "animation" la liste devient très longue et il n'y a pas pour le moment de moyen de supprimer simplement des essais pour ne garder que les animations que l'on veut conserver à l'état de modifiable dans la liste. 
Le seul moyen pour l'instant est de les supprimer directement dans le dossier Dodoc2/_Stopmotions
Mais ce n'est pas simple d'usage.

**Comment by louis-ev** [comment]
Tout à fait oui.
Ta proposition me convient très bien. Je pense qu’il y aurait aussi moyen d’améliorer l’affichage pour inclure la date de création par exemple.

**Comment by jubonhomme** [comment]
Je remonte si ça n'est pas trop compliqué à faire ?

**Comment by louis-ev** [comment]
Non pas trop compliqué ! je le met dans ma to-do.

**Comment by jubonhomme** [comment]
A fermer ;)

**Comment by jubonhomme** [comment]
Je viens de refaire un test et tout fonctionne très bien.

A fermer ;)
