### ISSUE TITLE
Ajout de contenu par iframe/embed dans un projet et un document page à page / bloc dessin

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#389]
Le but serait de pouvoir intégrer du contenu interactif dans une publication page à page depuis un autre site / service web.
Exemple :
Intégration de carte [Openstreemap](https://developer.mozilla.org/fr/docs/Web/HTML/Element/iframe)

Liste non exhaustive d’intégrations possibles par ce moyen : 
- carte géographique Umap ou Openstreetmap
- visite 360° ( https://atelier-canope57.canoprof.fr/eleve/Florange/CPA-Aurelia/ )
- modèle 3D ([ex : Terre 3D ](https://sketchfab.com/3d-models/earth-core-44c547c28fbf46f4ab430bf1398f5fdb)) 
- [Activité geogebra](https://www.geogebra.org/m/je3SfjaE)
- site internet
- outils framasoft de type carte mentale ([framindmap](https://framindmap.org/c/maps/239/public)), questionnaire (framaforms) 
...

La même chose que sur [Book Creator](https://read.bookcreator.com/aWAhdfUWXPQR1UPW7fJOHnfObsb2/KdFQSD6gTSqd7QuG7gAfDA) mais en mieux ;)

J'ai vu dans la version dev que la marmite comporte maintenant une recette carreau.js qui permet l'ajout de page web par simple glisser déposer de l'URL. (cf [vidéo](https://vimeo.com/246796372) à 1'30)

Une fonctionnalité similaire dans la recette "page à page" serait-elle possible ?

Merci

Julien

**Comment by louis-ev** [comment]
Ajouté dans la liste des objectifs pour la version 9, je te fais signe après y avoir réfléchi.

**Comment by jubonhomme** [comment]
Est-ce que l'ajout  "[improved iframe integration in publi ](https://github.com/l-atelier-des-chercheurs/dodoc/commit/a129ef51f6394dfc6845556749599494d7ae2dd1)" sera juste pour le STL ?
Ou bien peut-on espérer ajouter n'importe qu'elle contenu type URL ?

**Comment by louis-ev** [comment]
À vrai dire on peut déjà en passant par un bloc texte !
https://test.dodoc.fr/_publications/pour-pauline/

Une question : ajouter des "embed" (youtube, vimeo, carte, etc.) se ferait dans une publi ? Ou serait un type de média dans la bibli ? ça a du sens de l’avoir dans les projets aussi non ?

**Comment by jubonhomme** [comment]
Oui, ça pourrait être utile de l'avoir comme média dans un projet, pour les conserver et les taguer avec mots-clés et auteurs... pour ensuite les ajouter si besoin à une publication.

Question : comment sont gérées les dimensions de l'Iframe... dans le code d'intégration ou dans la publication ? ou les deux ?

**Comment by louis-ev** [comment]
À priori ça vient de ton code iframe : 

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/CN--rSppq5g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
Essaye de modifier height, tu vois un changement ?

**Comment by jubonhomme** [comment]
Oui maintenant ça fonctionne... tout à l'heure non même en ayant modifier la hauteur.. les mystères du code

**Comment by jubonhomme** [comment]
A fermer !

C'est fonctionnel... perso ça me suffit.

Mais ça pourrait être plus confortable d'avoir un bouton dédié pour insérer du contenu.
Un peu comme le bouton "formule". Mais je n'ai rien vu sur Quill qui y ressemble.

Ou comme cet exemple un ENT
![image](https://user-images.githubusercontent.com/29262866/84714371-c0d98b80-af6d-11ea-8943-0528d2c2998b.png)

ça permettrait de venir modifier le code iframe, pour les dimensions par exemple.
Pour l'instant une  fois coller dans l'éditeur de texte, on ne peut plus y revenir... il faut supprimer et recommencer.

C'est pas indispensable mais ça simplifierait l'action d'ajouter du contenu iframe pour les personnes moins à l'aise avec le code.

A fermer  
Le bouton pourra faire l'objet d'une nouvelle issue plus tard si demande spécifique

**Comment by louis-ev** [comment]
En fait je m’étais dis que pouvoir insérer un site web pouvait toujours être utile : mettre une URL qui se place comme source d’un iframe. 
Le soucis est qu’on ne peut faire un iframe que vers un contenu utilisant le même protocol (http vers http ou https vers https), et que de plus en plus de sites bloquent l’intégration dans un iframe... Donc c’est pas forcément idéal comme situation, ça marcherait une fois sur 2.

**Comment by jubonhomme** [comment]
Intégrer par l'URL simplement me semble effectivement assez risqué, et même au niveau des droits je ne suis pas sur que ce soit très "recommandable".

Je parlais surtout d'un bouton pour ajouter un lien iframe comme l'exemple ci dessus avec possibilité de revenir dessus pour modifier la taille par exemple.
ça fonctionne bien dans l'éditeur de texte mais ça relève un peu de "l'astuce de la fonction cachée"... un bouton "</>" permettrait de le rendre la possibilité plus "officielle".

**Comment by louis-ev** [comment]
Hmm oui je vois.
On pourrait avoir une option pour insérer un bloc HTML dans le bloc texte — c’est un peu risqué (notamment d’un point de vue sécurité, un utilisateur malveillant pourrait injecter un code JS chez tout le monde pour attraper des infos perso) donc à voir si c’est une bonne idée.

**Comment by jubonhomme** [comment]
Effectivement je n'avais pas réalisé la possibilité d'ajout de code malveillant.

Actuellement c'est Quill qui reconnaît que c'est une iframe et qui ajoute directement, c'est la balise qui est reconnue c'est bien ça ?

**Comment by louis-ev** [comment]
Je reporte pour plus tard :)

**Comment by jubonhomme** [comment]
C'est ajouté dans la V10.


![image](https://user-images.githubusercontent.com/29262866/230773234-001385c5-04a8-475b-8857-140e37e4e96d.png)
