### ISSUE TITLE
recette pour manipuler les vidéos : filtres, vitesse, etc.

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#390]
Serait-il possible d'avoir un bouton pour inverser l'ordre des images directement dans l'outil Capture/Animation ?

A la manière de celui ci dans [Kool Capture](http://www.koolcapture.com/tuto)
![image](https://user-images.githubusercontent.com/29262866/65924014-30f9ae80-e3eb-11e9-9eed-0de23b4162e8.png)

En stopmotion il est quelques fois plus simple de partir d'une vue finale complète et bien ajustée et d'enlever les éléments au fur et à mesure. 

Actuellement, je fais les images avec l'outil "Animation" pour avoir la pelure d'oignon et le visuel direct. Ensuite je récupère dans le projet l'ensemble des images réalisées via la fonction import. Je finalise le montage dans l'ordre inverse de la prise de vue en utilisant la recette "animation image par image" de la marmite en sélectionnant chaque image dans l'ordre inverse.

La possibilité d'inverser l'ordre des images avant le montage depuis l'outil Capture / Animation 
simplifierait grandement le montage.

**Comment by louis-ev** [comment]
C’est une bonne idée oui — il me semble qu’on a eu cette demande il y a quelques années mais on n’a pas poussé pour aller + loin.
Le truc c’est que l’ordre se fait avec la date de capture et ça demanderait de changer assez fortement la logique. Faisable mais pas évident.

Est-ce que à la place on pourrait envisager une recette qui permet de manipuler une vidéo ? L’inverser, l’accélérer, la ralentir, la pivoter ? Qu’en penses-tu ?

**Comment by jubonhomme** [comment]
Oui, un outil d'inversion vidéo aura le même résultat final et permettra en plus d'être applicable à plus de média.
Donc oui pour quelques options sur les modifications de vidéo : vitesse / rotation / inversion

**Comment by louis-ev** [comment]
Filtres : 
- en noir et blanc : ffmpeg -i input.mp4 -vf hue=s=0 output.mp4
- jouer à l’envers : ffmpeg -i my-video.mp4 -vf reverse my-video.mp4
- accélérer / ralentir : ffmpeg.exe -i input.mp4 -filter_complex "[0:v]setpts=PTS/1.3[v];[0:a]atempo=1.3[a]" -map "[v]" -map "[a]" output.mp4

**Comment by louis-ev** [comment]
https://trac.ffmpeg.org/wiki/FancyFilteringExamples

**Comment by louis-ev** [comment]
Filtres audio : 
- accélérer / ralentir
- echo https://ffmpeg.org/ffmpeg-filters.html#toc-aecho

**Comment by jubonhomme** [comment]
Filtres : FFmpeg and Frei0r filter processing examples
https://yalantis.com/blog/experiments-with-ffmpeg-filters-and-frei0r-plugin-effects/

**Comment by louis-ev** [comment]
@jubonhomme malheureusement ça demande de compiler une version spécifique de ffmpeg pour chaque plate-forme… Actuellement j’utilise des versions compilés par d’autres avec les options suivantes : 

`--cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay`

Donc pas de plugin Frei0r ici. Il faudrait créer un binaire pour ffmpeg pour macOS, Windows, Windows 32 bits, Linux, Linux ARM. Gros taf.
Après il faudra peut-être le faire de toute façon pour inclure les transitions dans la recette montage, donc autant ajouter ça en même temps.

**Comment by louis-ev** [comment]
Pivoter la vidéo (par exemple pour corriger l’orientation d’une vidéo prise au téléphone) : 
`ffmpeg -i in.mov -vf "transpose=1" out.mov`

```
0 = 90CounterCLockwise and Vertical Flip (default)
1 = 90Clockwise
2 = 90CounterClockwise
3 = 90Clockwise and Vertical Flip

Use -vf "transpose=2,transpose=2" for 180 degrees.```
https://stackoverflow.com/a/9570992

**Comment by louis-ev** [comment]
https://github.com/adamarthurryan/tutsplus-video-tools/blob/master/filter.js

**Comment by louis-ev** [comment]
On commence à être pas mal du tout : 

<img width="710" alt="image" src="https://user-images.githubusercontent.com/1948417/76111346-6fba1300-5fe0-11ea-9a5c-616e433b80a3.png">

<img width="293" alt="image" src="https://user-images.githubusercontent.com/1948417/76111373-7b0d3e80-5fe0-11ea-8b7e-c5c4273fd2d5.png">

<img width="468" alt="image" src="https://user-images.githubusercontent.com/1948417/76111376-7c3e6b80-5fe0-11ea-9eea-6a855eacf3b0.png">

**Comment by louis-ev** [comment]
Deux petits nouveaux : 

<img width="287" alt="image" src="https://user-images.githubusercontent.com/1948417/76259703-7ea9fb00-6256-11ea-9888-56b9c7668a2a.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1948417/76259707-7fdb2800-6256-11ea-86df-de20a47258ca.png">

Un peu délicats à ajouter car demandant de réécrire entièrement la syntaxe pour utiliser les "complex filters" de ffmpeg sur tous les effets déjà en place. Mais c’est indispensable de passer par là pour proposer les transitions vidéo animées de toute façon, donc il fallait bien apprendre à un moment :)

**Comment by jubonhomme** [comment]
Je me suis demandé à quoi correspondait "complex filters" dans les commits...  Merci pour les explications.

Donc si je comprends bien ça permet d'envisager maintenant des transitions en fondu ?

**Comment by louis-ev** [comment]
- Oui ! Par contre je me rends compte que j’étais pas clair plus haut quand je parlais des transitions en recomposant FFmpeg : dans la version que dodoc embarque de FFmpeg, il y a de toute façon les transitions en fondu. Le fait de « builder » FFmpeg signifie d’inclure ce qu’on veut dedans, comme les filtres de Freior ou des transitions plus complexes.
A court terme, ajouter la possibilité d’avoir des transitions entre chaque vidéo ou image dans un montage est _relativement_ simple. Rebuilder FFmpeg l’est un peu moins (et c’est moins prioritaire).

**Comment by jubonhomme** [comment]
Ok, et merci pour ces explications toujours éclairantes... depuis que je suis le développement de Do•doc  j'ai appris beaucoup de choses sur FFmpeg (en plus du fonctionnement de Git et comment taper le  •  de dodoc ;) ) .
En recherchant des infos sur les filtres FFmpeg j'étais effectivement tombé au fil des liens sur Frei0r mais j'avoue que je n'avais pas compris le lien exact avec FFmpeg. Je l'avais mis de côté comme une note car les filtres me semblaient assez intéressant. Mais mon but n'était pas de t'ajouter des difficultés supplémentaires.

**Comment by louis-ev** [comment]
J’imagine !
Post-v9 pourquoi pas cela dit :)
La v9 commence à être bien bien chargée la, donc je vais éviter d’en mettre trop d’un coup pour pas la reporter à après les vacances d’été. Ça Parait jouable.

**Comment by louis-ev** [comment]
Nouvelle option : habillage. Prend une image et une vidéo : 


<img width="794" alt="image" src="https://user-images.githubusercontent.com/1948417/76462463-0708d700-63e2-11ea-9a46-6d11a87db695.png">

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/1948417/76462469-083a0400-63e2-11ea-8e1c-1aabe1e6f5df.png">

**Comment by jubonhomme** [comment]
Au hasard d'une navigation sur le Wiki du Studio des "Fées Spéciales", j'ai vu ça
http://les-fees-speciales.coop/wiki/ffmpeg

Dont cette biblio de stabilisation : 
http://les-fees-speciales.coop/wiki/stabilisation

Voir un exemple ici 
http://public.hronopik.de/vid.stab/

Encore une fois je ne comprends pas tout les détails, j'imagine qu'il faut encore une fois recompiler ffmpeg de façon spécifique. Mais le résultat est assez impressionnant.

C'est plus à titre d'info qu'une demande...

**Comment by louis-ev** [comment]
Je ferme cette recette et en créer une nouvelle du coup :)
