### ISSUE TITLE
textes non enregistrés

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#391]
De Lise : 
> des textes disparaissent. Pourtant, ils ont bien été enregistré, validé avec les élèves, mais à un moment donné, il n'y en a plus

**Comment by louis-ev** [comment]
Faire qq tests pour voir si ça tourne bien.

**Comment by jubonhomme** [comment]
Je pense qu'avec toutes les modifs sur l'outil texte, l'issue peut être fermée

**Comment by louis-ev** [comment]
Oui, il y a double mécanisme : un Check qui ne ferme la fenêtre de modif que si le serveur confirme l’enregistrement, et un enregistrement automatique à intervalle régulier dans les blocs « collaboratifs » (tous les blocs textes quill sauf le texte d’une publi page (que je vais switcher bientôt)).
