### ISSUE TITLE
erreur dans l’affichage "média déjà présent dans une publication"

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#392]
De Lise : 
> parfois des textes sont notés comme ayant déjà été mis en page alors que ce n'est pas le cas.

**Comment by jubonhomme** [comment]
Je n'arrive  pas à reproduire. Est-ce toujours d'actualité ?

**Comment by louis-ev** [comment]
Pas sur… et ça date.
Je ferme, on rouvrira si on constate que c’est tj le cas.

**Comment by jubonhomme** [comment]
A fermer
