### ISSUE TITLE
Pouvoir modifier une image de portrait d'un auteur

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#396]
Actuellement une fois qu'un auteur est créé, on ne peut plus ajouter ou modifier une image de portrait.

L'idée serait d'avoir un icône crayon sur la vignette auteur pour accéder à la même fenêtre que lors de la création afin d'ajouter ou modifier une image portrait.

![modif_auteur](https://user-images.githubusercontent.com/29262866/67532847-1bb13080-f6c8-11e9-9d18-ceda50d67e1d.png)

On peut supprimer et recréer un auteur pour ajouter/modifier une image mais avec le risque de ne pas le recréer avec le nom exact.

**Comment by louis-ev** [comment]
Très bonne idée, j’ajoute à do•doc 8.2 !

**Comment by louis-ev** [comment]
Prêt !
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1948417/68077903-720b2700-fdcc-11e9-8e10-cc7d6f939fa8.png">

**Comment by louis-ev** [comment]
À noter qu’un changement de nom d’un auteur "casse" le lien avec tous les projets et médias, car le nom stocké dans les projets et médias est le nom "humain" et pas le nom "machine"… C’était un choix délibéré de stocker ce nom, plus facile à lire dans les fichiers pour un utilisateur qui manipulerait directement les fichiers.
Peut-être qu’il faudrait un message qui indique que le changement de nom va tout casser… ?

**Comment by jubonhomme** [comment]
Oui je m'en suis aperçu, en transférant un dossier sur une nouvelle machine. Et il m'a suffit de créer ma fiche auteur sur le nouvel ordi avec le même nom pour tout récupérer.
Je suis aussi pour garder un nom "humain", on ne cherche pas une authentification pure et dure de l'auteur avec signature numérique. C'est beaucoup plus souple pour lire/ajouter un nom dans les métadonnées du fichier.
Je me demande du coup s'il ne faut pas bloquer le changement de nom. La modification ne concernerait que l'image "portrait" (et le tag nfc ? , mais ça je n'ai jamais essayé).
Si un auteur veut changer de nom il faut recréer un nouvel auteur, c'est peut être plus évident que les médias antérieurs garderont l'ancien nom d'auteur.
Car en réalité on ne modifie pas un nom, on recréé un nouvel auteur en laissant l'ancien de côté avec tous ses médias et projets tagger à l'identique.

Dans la même idée, j'ai eu la question au cours des ateliers de présentation de do•doc : Si je supprime un auteur, est-ce que tous ses médias et projets sont supprimés ?

Du coup je verrai plus une info générale sur le fonctionnement du tag auteur (peut-être juste dans le bandeau en haut "liste des auteurs": 
Par exemple :
"Lorsque vous êtes identifié comme auteur tous les projets, médias et publications porteront votre nom." 
et un "plus d'info" (comme pour la marmite): 
Vous pourrez ajouter d'autres co-auteurs directement dans les projets, médias et publications. Si vous supprimez un auteur, tous les médias, projets et publication conserveront son nom d'auteur."

<img width="1183" alt="auteur" src="https://user-images.githubusercontent.com/29262866/68083626-263b9a80-fe2b-11e9-8d87-13a383ca37d0.png">

**Comment by louis-ev** [comment]
Tout à fait d’accord ! 
Et merci pour les propositions de texte, c’est tout de suite beaucoup plus clair :)

` Je me demande s'il ne faut pas bloquer le changement de nom. La modification ne concernerait que l'image "portrait" (et le tag nfc ? , mais ça je n'ai jamais essayé).`

Probablement oui. ça serait trop perturbant que changer de nom casse tous les liens, et renommer les auteurs de tous les projets/médias est assez risqué d’un point de vue technique…
Peut-être qu’il faudrait une mini-explication sous le nom de l’auteur pour indiquer pourquoi il n’est pas modifiable.

Je remet sur le couvert pour do•doc 8.2 du coup

**Comment by jubonhomme** [comment]
En y réfléchissant, ta proposition d'un message d'alerte est peut être plus visible lorsque l'on supprime un auteur. 
Le texte dans le bandeau du haut comme j'ai proposé au dessus est peut-être mal placé, surtout sur un petit écran.
A voir...

**Comment by louis-ev** [comment]
D’une manière générale je me dis que c’est pas bien compliqué d’ajouter des
courtes explications de ce type à différents endroits de l’app où les
choses ne sont pas forcément claires — donc ta proposition me paraît tout à
fait pertinente, et ça serait pas idiot de décliner aux autres endroits où
les choses n’ont rien d’évident (à quoi servent les mots-clés, par
exemple). Non ?


-----------
Louis Eveillard

Tel : 06 31 42 79 65
Mail : louis.eveillard@gmail.com
Web : louiseveillard.com <http://www.louiseveillard.com/>
Blog : beautifulseams.com <http://www.beautifulseams.com>

**Comment by jubonhomme** [comment]
télescopage de réponses ;)
Oui pour les courtes informations.
J'aime l'interface de dodoc pour sa simplicité, et c'est le retour de beaucoup de personnes à qui je le présente. Mais quand on rentre un peu plus dans l'utilisation il y a quelques questions qui arrivent sur le mode de fonctionnement de certaines parties... et pour ne pas rentrer dans des tutos à rallonge, je pense qu'il est souvent plus clair d'ajouter des infos courtes là où elles sont nécessaires.

Je te laisse voir ce qu'il est possible d'afficher sans charger l'interface avec trop de textes... peut être avec des infos bulles : pas trop d'affichage pour l'utilisateur lambda (=enfant par exemple) et des infos complémentaires pour ceux qui cherchent à en savoir plus.

**Comment by louis-ev** [comment]
Oui, j’entends bien ! 
Il y a déjà des infobulles très courtes qui s’affichent en cas de survol prolongé (sur le picto marmite par exemple) mais parfois gênantes, et pas bien compatible avec les appareils tactiles.
Du coup peut-être qu’un petit picto  "?" qui apparaît à différents endroits et ouvre une explication courte ?

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1948417/68092601-574cb700-fe8d-11e9-8b7a-8095d7f97585.png">

Qui viendrait déclencher l’affichage de plusieurs infobulles qui "expliques" l’interface ? Voir par exemple : https://introjs.com/

**Comment by jubonhomme** [comment]
Oui, quand je parle d'infos bulles je ne pensais pas aux infos type "survol" mais plus à ce que tu proposes avec un picto "?" ou un "i" pour + plus d'infos comme dans la marmite.
Ce que tu as fait pour expliciter les recettes de la marmite est vraiment bien. 
La même chose en plus discret, accessible via un picto, pour certaines fonctions comme les tags "auteur" ou "mot clé" serait effectivement une bonne piste. 

J'ai en tête l'exemple du logiciel de montage vidéo [Openshot](https://www.openshot.org/fr/) qui propose aussi des didacticiels que l'on peut afficher ou masquer et passer de l'un à l'autre pour faire un tour des principales fonctions du logiciel
Ex : c'est accessible depuis le menu "aide/didacticiel
![Capture d’écran de 2019-11-03 23-22-20](https://user-images.githubusercontent.com/29262866/68093022-882eeb00-fe91-11e9-8730-ccad8927844d.png)
![Capture d’écran de 2019-11-03 23-23-02](https://user-images.githubusercontent.com/29262866/68093025-8d8c3580-fe91-11e9-83f6-a455b424ae32.png)

**Comment by jubonhomme** [comment]
Je viens de voir la petite ligne en bas sous l'image ;)

> Qui viendrait déclencher l’affichage de plusieurs infobulles qui "expliques" l’interface ? Voir par exemple : https://introjs.com/

Oui ça correspond bien à l'idée d'apporter de l'info ciblée.

**Comment by louis-ev** [comment]
Je viens d’intégrer une bonne partie des changements évoqués ici.
À tester très bientôt :)

**Comment by louis-ev** [comment]
Je ferme car implémenté en très large partie dans do•doc 8.2. 
N’hésitez pas à créer un nouveau sujet suite à sa publication si il manque des choses.
