### ISSUE TITLE
pouvoir dupliquer ou télécharger un projet

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#398]
Voir https://forum.latelier-des-chercheurs.fr/t/dupliquer-un-projet-dans-dodoc/161/5

> Un bouton intitulé « DUPLIQUER » qui ouvre un encart qui propose de choisir le nom à donner à la copie, quand on ouvre un projet.

**Comment by jubonhomme** [comment]
Peut-on imaginer en complément du bouton "dupliquer", un autre bouton "télécharger" comme c'est le cas pour les médias ?
Ça me serait bien utile pour récupérer l'ensemble d'un projet dans le cas ou Do.doc est installé sur un serveur web ou je n'ai pas d'accès au dossier Dodoc2. Je peux le faire en téléchargeant les médias un par un mais c'est plus long ;)

**Comment by louis-ev** [comment]
Oui, c’est une bonne idée ! Je modifie le nom de l’issue pour inclure ça.

**Comment by louis-ev** [comment]
Ajouté !
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1948417/70979979-cdf6ea00-20b2-11ea-80bc-26a977ec3f23.png">

**Comment by jubonhomme** [comment]
Génial !
