### ISSUE TITLE
simplifier l’ajout d’une image de couverture

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#399]
proposer de sélectionner un média depuis le menu « éditer le projet » 
Si un projet ne contient pas d’image de couverture, il affiche une mention AJOUTER UNE IMAGE DE COUVERTURE à la place de l’image. Au clic, ça propose d’importer une image ou de la sélectionner parmi celles de la bibliothèque. Menu accessible en cliquant sur MODIFIER.

**Comment by louis-ev** [comment]
![image](https://user-images.githubusercontent.com/1948417/67777770-7cdb5a00-fa62-11e9-80d4-902aa50e5051.png)

**Comment by jpclerc39** [comment]
ou si aucune image, en générer une automatiquement à partir des X premières (ou dernières) vignettes du projet, qui seraient en mode miniatures pour rentrer dans les dimensions du cadre

**Comment by louis-ev** [comment]
Penser aussi à avoir l’option "Choisir comme image de couverture" depuis la modale EditMedia

**Comment by louis-ev** [comment]
En cours, pour le menu permettant de choisir un média image comme image de couverture :  
<img width="711" alt="image" src="https://user-images.githubusercontent.com/1948417/70836015-31f18800-1dff-11ea-81a5-cdaea122e745.png">

Possibilité de choisir une image dans les images des autres projets aussi (du moment qu’on y a accès, avec ou sans mdp).

**Comment by louis-ev** [comment]
> ou si aucune image, en générer une automatiquement à partir des X premières (ou dernières) vignettes du projet, qui seraient en mode miniatures pour rentrer dans les dimensions du cadre

@jpclerc39  à voir pour cette idée de miniatures… j’ai peur que ça fasse des visuels un peu compliqués à comprendre mais à voir. Le plus simple je pense serait qu’à la première capture, la première image se voit instaurée en image de couverture s’il n’y en a pas déjà, et si ça ne convient pas l’utilisateur puisse très rapidement en changer. non ?

**Comment by louis-ev** [comment]
Ajouté également : la possibilité de choisir facilement dans les médias lors de la création ou l’édition d’un auteur.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1948417/70836879-f60bf200-1e01-11ea-8f51-c8bdf8adbe32.png">
