### ISSUE TITLE
Ajout information contact sur fiche auteur

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#400]
Dans la fiche auteur, ajouter une information complémentaire (mail ou autre) pour contacter un auteur

**Comment by louis-ev** [comment]
Peut-on recenser les options de texte qui seraient utiles ? 
- liens sites
- liens mail
- gras (?)
- italique (?)

Est-ce que cocher des badges / compétences aurait du sens ?

À terme j’aimerai aussi ajouter la possibilité d’entrer un mot de passe à la création d’un auteur pour éviter que d’autres personnes puissent s’identifier à la place de l’auteur…

**Comment by jpclerc39** [comment]
un mail oui
le lien web pourrait être un lien openbadge 
> Est-ce que cocher des badges / compétences aurait du sens ?
sans faire une usine à gaz, ça prendrait une dimension très intéressante avec les compétences identifiées, et un filtre associé, c'est un rêve de repérer très vite des compétences, à l'image des mots clefs présents
> À terme j’aimerai aussi ajouter la possibilité d’entrer un mot de passe à la création d’un auteur pour éviter que d’autres personnes puissent s’identifier à la place de l’auteur…
oui bonne idée

**Comment by louis-ev** [comment]
Je pense que c’est plus raisonnable de repousser ce sujet aux prochains développement, ça demande un peu de finesse et on est dans une logique de finalisation de do•doc 9 là :) 
Je repousse !

**Comment by jubonhomme** [comment]
Je ferme celle ci car le champ email est maintenant actif et les open badge sont en doublon avec #589
