### ISSUE TITLE
Ajout champ "Légende" pour un contenu TEXTE

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#401]
à l'identique des images et contenu pdf, permettre d'ajouter une légende au contenu "TEXTE", et avoir un descriptif plus clair dans la vue projet

**Comment by louis-ev** [comment]
Ha ! On avait le champ légende pour un bloc texte mais on l’a retiré car des utilisateurs trouvaient ça confus.
Avez-vous un exemple d’un cas de figure qui nécessite ce champ là ?

**Comment by jpclerc39** [comment]
> Ha ! On avait le champ légende pour un bloc texte mais on l’a retiré car des utilisateurs trouvaient ça confus.
> Avez-vous un exemple d’un cas de figure qui nécessite ce champ là ?

ah je ne savais pas, dans mon cas c'est juste identifier plus facilement des fiches "types" avec des légendes qui évoqueraient le contenu (liens web / description projet / brouillon)

**Comment by louis-ev** [comment]
Juste pour revenir rapidement là-dessus : je trouve que c’est confus d’avoir à la fois du texte et des légendes (même si les situations que tu évoques me paraissent justifiées). Je propose qu’on laisse ça de côté pour l’instant, ça ne me paraît pas gênant en l’état. Qu’en penses-tu ?

**Comment by sarahgarcin** [comment]
De mon côté, je trouvais ça confus aussi avant, mais là ça fait plusieurs fois que ça me manque. 
Exemple d'utilisation: quand je documente mes ateliers, j'écris en légende la date et le numéro de l'atelier, ce qui me permet de me repérer facilement. Ça serait bien utile qu'il y ait une légende sur le texte aussi dans ce contexte. 
Par contre je pense qu'il ne faut pas afficher cette légende dans la publication. 
Peut-être le mot légende est mal choisi, et il faudrait l'appeler "commentaire" par exemple

**Comment by louis-ev** [comment]
Je suis globalement d’accord mais je vois pas pourquoi ce champ n’apparaitrait pas dans la publication page à page pour les médias texte, alors qu’il apparait pour tous les autres médias… Je me demande si faudrait juste pas une case pour masquer les légendes dans la publi page à page, voir les réécrire.

**Comment by sarahgarcin** [comment]
Oui pour une case "afficher / masquer la légende" !

**Comment by jubonhomme** [comment]
Le champ légende existe pour un média "Texte"

A fermer ?
