### ISSUE TITLE
do•doc ne s’ouvre pas dans Safari 9

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#402]
@sarahgarcin : à debugger

**Comment by louis-ev** [comment]
On dépend du bon vouloir du dev du projet vue-plyr, qui n’a pas l’air décidé à utiliser plyr en version compatible (avec ie9 et 10).
À moins de se passer de vue-plyr pour utiliser plyr, je ne vois pas comment faire (et n’ayant pas accès à une machine sous safari 9, c’est bien galère à tester…).

Je crois qu’il faudrait abandonner les vieux navigateurs, et recommander aux gens de passer sur un firefox récent @sarahgarcin .

**Comment by louis-ev** [comment]
Pas de solution en vue… je ferme.

**Comment by jubonhomme** [comment]
A fermer ?
