### ISSUE TITLE
liste de mots clefs existants

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#403]
je n'ai pas vu la suggestion, mais donner la possibilité de choisir parmi des mots clef déjà existants serait intéressante

**Comment by jubonhomme** [comment]
Normalement il y a déjà une autosuggestion des mots clés, quand tu commences à taper une lettre dans  "mots clés" les mots clés en rapport sont proposés.
La liste s'affiche aussi lorsque tu filtres les médias.
Avoir une liste complète peut vite prendre de la place dès qu'il y a beaucoup de mots clés.

**Comment by louis-ev** [comment]
Actuellement la suggestion de mot-clé pour un média ne prend pas en compte les mots-clés de médias rattachés à un projet qui lui-même ne contient pas de mot-clé (erreur stupide dans l’écriture du code…), voir https://github.com/l-atelier-des-chercheurs/dodoc/issues/381
C’est corrigé pour do•doc 8.2.

La suggestion s’affiche en tapant au moins une lettre pour éviter une liste extrêmement longue, tout à fait. Cela étant on pourrait imaginer afficher la liste en cliquant sur un bouton "afficher tous les mots-clés" par exemple, pour avoir une idée de ce qui a déjà été attribué, non ?

Autre question : mélange-t’on les mots-clés de projets et de médias dans la suggestion ? cela a t’il un sens ?

**Comment by jpclerc39** [comment]
@jubonhomme oups oui tu as raison
@louis-ev 

> "afficher tous les mots-clés" par exemple, pour avoir une idée de ce qui a déjà été attribué, non ?

avoir une liste (à voir comment condenser la vue) de mots déjà existants éviterait d'avoir des mots clefs trop proches, ou de recréer de nouveaux inutilement

> mélange-t’on les mots-clés de projets et de médias dans la suggestion ? cela a t’il un sens ?

je dirais qu'il faut séparer (par couleur bien définie?), des mots clefs projets seraient plus en rapport avec une activité, une action,  et des mots clefs médias sur l'objet lui même, mais je pense qu'il faudrait, à la manière des auteurs, une petite interface qui permettent de créer / modifier les mots clefs de façon globale, ne serait-ce que pour les faute de frappe

**Comment by jubonhomme** [comment]
Je pense au contraire qu'une liste de mots est moins efficace qu'une autosuggestion.

Je m'explique, si j'ai une longue liste de mots clés (ce qui est le cas puisque j'utilise le potentiel des filtres et des tags),  j'ai du mal à retrouver le mot clé à l'intérieur de cette liste pour savoir s'il y est déjà... les élèves surtout jeunes ont encore plus de mal. 
Le risque est qu'ils ressaisissent un mot clé sans même le chercher ou sans l'avoir retrouver.

> éviterait d'avoir des mots clefs trop proches, ou de recréer de nouveaux inutilement

@jpclerc39 qu'entends tu par "trop proches" ? 
Orthographe / pluriel / Casse ? exemple : Laser / Lasercut / Découpe Laser / découpe laser / découpeuse laser...
ou trop proches au niveau du sens : exemple : Bois / MDF / Médium / contreplaqué...

Dans le premier cas l'autosuggestion est beaucoup plus simple et plus efficace  : je pense et tape "laser" et je vois s'afficher en dessous les mots clé déjà utilisés avec "laser", je choisi celui qui va bien dans les quelques propositions.
Le deuxième cas est plus complexe, cela revient au [Thésaurus](https://fr.wikipedia.org/wiki/Th%C3%A9saurus) et à la suggestion de mots qui sont proches par le sens ou le domaine, ça correspond aussi à l'art des algorithmes de Google ou Amazon de proposer au plus juste ce à quoi tu penses avant même que tu tapes la première lettre de ta recherche ;)
Exemple : je tape laser et on me suggère : découpe, dxf, gravure, épilation ;) ...

Pour ce deuxième cas l'autosuggestion en prenant les première lettres tapées ne sert à rien, mais une liste de plus de 50 mots clés non plus.

Je pense que la liste de base doit être pensée et travaillée en amont et saisie directement comme mots clés sur des "documents exemples" afin qu'ils apparaissent sous forme d'autosuggestion lorsque l'on en a besoin.

**Comment by jubonhomme** [comment]
> une petite interface qui permettent de créer / modifier les mots clefs de façon globale, ne serait-ce que pour les faute de frappe
@jpclerc39 C'est le même soucis qu'avec les auteurs, les mots clés ne sont pas liés à un média par une base de données mais sont en toutes lettres dans les métadonnées du média.
Donc si on veut modifier UN mot clé pour une faute de frappe, il faut retourner dans chaque média tagger avec ce mot clé, l'enlever et ajouter celui corrigé. Ce n'est pas une modification sur un mot globalement mais une suppression / ajout pour chaque média.

Encore une fois, l'avantage va à l'autosuggestion pour éviter l'erreur de frappe.

**Comment by jubonhomme** [comment]
@louis-ev  Je suis pour le mélange des mots clés projet et média
Je trouve très judicieuse la solution de filtre en double classement et affichage : 

- arborescence dossier/fichier pour le filtre par projets 
- chronologiques pour le filtre médias

Les tags mots clés permettent d'ajouter un niveau supplémentaire qui n'est pas justement dépendant de ce 1er filtre / affichage.

**Comment by jpclerc39** [comment]
> Dans le premier cas l'autosuggestion est beaucoup plus simple et plus efficace : je pense et tape "laser" et je vois s'afficher en dessous les mots clé déjà utilisés avec "laser", je choisi celui qui va bien dans les quelques propositions.

@jubonhomme  je pensais au premier cas en fait :-)

ok pour la modification des mots clefs trop délicate, préparer les mots clefs les plus réprésentatifs est un petit boulot au début mais bien utile ensuite

**Comment by louis-ev** [comment]
Note pour do•doc v9 : la liste des mots-clés dépend des médias chargés depuis l’ouverture de do•doc. Il faudrait stocker qqpart côté serveur tous les mots-clés utilisés, au fur et à mesure où l’appli les stocke. À réfléchir mais c’est pas très intuitif pour les utilisateurs.

**Comment by louis-ev** [comment]
Il y a toujours ce soucis de liste des mots clés suggérés : elle se base sur les mots clés déjà vu par le client et non sur l’ensemble des mots clés utilisés dans tous les projets et médias. C’est un point mineur mais potentiellement gênant pour un contributeur qui ne travaille que dans son projet et rate peut être du coup les suggestions provenant de médias qu’il n’a pas consulté et qui se trouvent ailleurs...
Garder une liste a jour des mots clés utilisés partout aurait donc du sens, mais introduit une nouvelle brique technique qui n’existe pas : le stockage pourrait se faire hors du dossier de contenus car ce n’est pas vraiment du contenu. Il faudrait qu’il soit persistent d’un lancement à un autre.

**Comment by jubonhomme** [comment]
Je vois mieux... il faudrait un dossier comme pour _authors ou _publications mais pour stocker les mots clés

**Comment by louis-ev** [comment]
Sauf que ça serait du contenu généré, et pas très intéressant pour les utilisateurs… À moins qu’on imagine que la liste puisse être "préparée" en amont, mais ça pose d’autres questions.
Je pencherai plutôt sur un stockage dans l’appli même, et pas dans le dossier de stockage. En consultant médias et projets do•doc récupère les mots-clés et les mets de côté pour envoyer la liste des suggestions, par exemple.
Mais c’est beaucoup de codes pour peu de choses… donc peut-être qu’on ferme pour l’instant et si le sujet revient on ouvrira une nouvelle issue :)

**Comment by jubonhomme** [comment]
Juste une dernière question : la suggestion des mots clés propose t elle tous les mots clés ou seulement les mots clés vu par l'auteur comme pour la liste ?
Si ça propose tout en suggestion, perso ça me suffit.

**Comment by louis-ev** [comment]
Ça propose uniquement ce que le navigateur (ou l’appli) a chargé.

Page d’accueil de do•doc : seuls les projets sont chargés (donc leurs mots-clés aussi).
Ouverture d’un projet : les médias du projet sont chargés (donc leurs mots-clés aussi).
Ouverture d’une autre projet : idem.
