### ISSUE TITLE
Depuis la vue filtrée médias, voir le nom du projet en ouvrant le média

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#404]
si on filtre par médias, il faudrait pouvoir retrouver le projet associé quand on a ouvert le média (photo ou autre), car sauf erreur on ne sait pas dire à quel projet il est lié

**Comment by jubonhomme** [comment]
C'est peu visible mais l'info existe déjà quand on clique sur "partager", l'url comporte l'arborescence du projet / média.

@louis-ev  : Est-ce possible de le mettre dans les métadonnées à la création du média et de le faire afficher dans les propriétés du média :

TYPE
**PROJET :............**
CRÉATION
IMPORTATION
ÉDITION
LÉGENDE

**Comment by jpclerc39** [comment]
je ne l'avais pas vu effectivement @jubonhomme , c'était bien l'idée de le mettre comme tu le proposes

**Comment by louis-ev** [comment]
Ajouté pour do•doc 8.2. 
Merci pour les retours et suggestion.

**Comment by louis-ev** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/1948417/70836681-52badd00-1e01-11ea-8593-d6b8f5ef323f.png">

Question : est-ce que ça serait utile qu’un clic sur le nom du projet ferme la fenêtre du média et amène directement au projet ?

**Comment by jubonhomme** [comment]
En répondant rapidement je dirais bonne idée, ça permettrait en passant par le filtre média de passer à un affichage de tous les médias et une recherche visuelle rapide pour revenir en cliquant sur le nom du projet à l'affichage précédent par dossier.
Si oui, il faudrait que le nom du projet soit identifié comme cliquable : par une couleur / type hyperlien / souligné / bouton avec une flèche... ? 

Et pourquoi pas avoir la même chose dans l'autre sens ? 
Je suis dans un dossier projet ... j'ouvre un média, je clique sur la date de "création" du média.... j'arrive dans l'affichage chronologique "média" à la date indiquée. 

Ce qui reviendra à avoir un rappel du "bouton glissière"  pour le mode d'affichage Projet/Média directement dans les paramètres du média sans repasser par la page racine de dodoc.

On pourrait également imaginer un affichage par dates à l'intérieur du projet ? Avec un bouton glissière " dates" au lieu de "médias" ?
Exemple : 
![affichage_date_projet](https://user-images.githubusercontent.com/29262866/70838223-8ac51e80-1e07-11ea-905e-b7aad1e16be0.png)

**Comment by louis-ev** [comment]
Oulala ça déborde carrément du cadre de cette issue mais pleins de bonnes idées :)

>  Si oui, il faudrait que le nom du projet soit identifié comme cliquable : par une couleur / type hyperlien / souligné / bouton avec une flèche... ?

Ok !

> affichage par dates 

Et pourquoi pas en faire le mode par défaut ? ça permettrait de structurer un peu la liste de médias, qui est très vite très dense…

**Comment by jubonhomme** [comment]
> Oulala ça déborde carrément du cadre de cette issue mais pleins de bonnes idées :)

Désolé je m'emporte vite ;)

> Et pourquoi pas en faire le mode par défaut ? ça permettrait de structurer un peu la liste de médias, qui est très vite très dense…

Pourquoi pas par défaut en effet ce serait moins compact.

**Comment by louis-ev** [comment]
Ok. Ça amène une nouvelle question un peu complexe à gérer : 
- sur la page d’un projet par défaut les médias sont classés par l’ordre d’importation dans do•doc.
- sur la page d’accueil en mode "tous les médias" ceux-ci sont classés par ordre de création (par exemple, date de prise de vue d’une photo plutôt que quand elle a été ajoutée)

Du coup c’est très étrange que les deux ordres ne correspondent pas si la date est mise en avant dans la page projet. Du coup ma question : est-ce pertinent de pouvoir organiser les médias par ordre de création ou par ordre d’importation ? de pouvoir choisir sur ces deux pages comment ils sont placés ? Ou ça ajoute trop de confusion et il faudrait juste se cantonner à un ordre possible (date de création ou d’importation dans do•doc). 

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/1948417/70891941-7e4bec00-1fe8-11ea-9a15-7521325a53ab.png">

**Comment by louis-ev** [comment]
N’hésitez pas à intervenir ici avant que je m’attaque à ce soucis — la question de l’ordre des médias. Peut-être que c’est comme pour les projets : l’ordre est réglable ? C’est le plus logique à priori.

**Comment by jubonhomme** [comment]
D'après ce que je retrouve ci dessus tu peux clôturer ce post non (= affichage du nom de dossier OK) ? ou bien le renommer en Ordre des médias ...

**Comment by jubonhomme** [comment]
A fermer
