### ISSUE TITLE
Modifier la vignette d'un média vidéo

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#406]
La vignette d'un média vidéo correspond à la première image de la vidéo.
Donc si la vidéo commence par un fondu en ouverture la vignette est noire.
Ce n'est pas toujours très explicite ;)
Exemple :
![vignette_video](https://user-images.githubusercontent.com/29262866/68489466-7067b600-0247-11ea-8370-80584a1e8141.jpg)

Serait -il possible de choisir l'image qui sert de vignette depuis l'interface Dodoc ?

**Comment by louis-ev** [comment]
Possible mais long… ça demande de construire une interface qui permette de naviguer dans la vidéo et de choisir un élément.
En attendant, peut-on imaginer prendre l’image du milieu par exemple ?

**Comment by jubonhomme** [comment]
Oui, ce n'est pas forcement le choix qui m'importe en fait.
Pour une simple captation vidéo c'est moins gênant, mais après montage la première image d'une vidéo est souvent en fondu. 
C'est surtout pour éviter ça, après ça me va avec l'image du milieu ou du quart... du 8e.. c'est comme tu peux.

Par curiosité, comment la vignette est techniquement produite ? ffmpeg ???

**Comment by louis-ev** [comment]
Prendre l’image du milieu paraît + adapté.

@jubonhomme oui tout à fait, ffmpeg extrait la première image :)

**Comment by louis-ev** [comment]
On change le comportement de ffmpeg ? Les aperçus sont fais avec l’image du milieu plutôt ?
Une interface qui permet de choisir me semble compliquée pour la v9.

**Comment by jubonhomme** [comment]
Oui pour l'image du milieu, l'important était surtout d'éviter la première image qui peut être noire dans le cas d'une ouverture en fondu. 
C'est plus pour toujours avoir un visuel, donc prendre une image au milieu devrait fonctionner.

**Comment by louis-ev** [comment]
Hmm, petit soucis avec des webm enregistrés dans l’interface de capture qui n’indiquent pas de durée — impossible d’utiliser leur vignette dans ce cas…
Ça complique pas mal le code, il faut utiliser en priorité l’image à 50% et basculer sur celle à 0% (00:00:00) si pas dispo, puis rien si pas dispo.

**Comment by louis-ev** [comment]
Corrigé.
