### ISSUE TITLE
ajouter une icône de recherche en haut

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#407]
pourquoi ne pas ajouter une icône recherche en haut qui permettrait de saisir tout ou partie du nom d'un projet, afin de filtrer la vue sur ces derniers, cela permettrait de les retrouver plus facilement

**Comment by louis-ev** [comment]
Oui, bonne idée ! 

À voir où : c’est une fonctionnalité plutôt secondaire, utile uniquement quand un do•doc commence à bien se remplir. Doit-elle être légèrement grisée comme c’est le cas des indications sous le bouton CRÉER UN PROJET ? (qui sont d’ailleurs pas suffisament contrastés pour être bien lisibles, à corriger)

![image](https://user-images.githubusercontent.com/1948417/68682371-512d9900-0565-11ea-9b91-c9ab304ffd21.png)

**Comment by jpclerc39** [comment]
> Oui, bonne idée !
> 
> À voir où : c’est une fonctionnalité plutôt secondaire, utile uniquement quand un do•doc commence à bien se remplir. Doit-elle être légèrement grisée comme c’est le cas des indications sous le bouton CRÉER UN PROJET ? (qui sont d’ailleurs pas suffisament contrastés pour être bien lisibles, à corriger)

soit en haut à droite "par convention" comme beaucoup de sites, mais peut-être trop loin du groupe de boutons d'actions, ainsi la position serait plus logiquement en dessous du bouton comme tu dis, au niveau des différents filtres, avec une meilleure visibilité

**Comment by louis-ev** [comment]
Implémenté ainsi : 
<img width="767" alt="image" src="https://user-images.githubusercontent.com/1948417/70819235-fe4e3800-1dd5-11ea-9b61-cc84cafebf29.png">

Prêt pour la bêta de do•doc 8.2 qui sort bientôt.
