### ISSUE TITLE
Inverser l'image de la caméra

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#411]
En voyant ce tweet :
https://twitter.com/DelphineThib/status/1195388751079518209/photo/3
et pour avoir déjà eu ce cas, lorsque la caméra est fixée sur un pied en face pour ne pas gêner la manipulation de l'utilisateur, l'image est à l'envers.
Serait-il possible d'avoir un bouton pour pivoter de 180° la caméra dans les paramètres de réglages avant la prise de vue ? ([comme sur OBS studio](https://www.youtube.com/watch?v=20qsPKr6fcw) )
![cam_dodoc](https://user-images.githubusercontent.com/29262866/68979903-2f4f4300-07ff-11ea-9a61-2155794b6b9e.png)

**Comment by louis-ev** [comment]
Je me demande si on a pas déjà une issue ouverte à ce sujet… 
Le soucis c’est que on peut bien pivoter l’affichage de 180 degrés, mais le flux enregistré (photo ou vidéo) ne sera pas pivoté…

À tester néanmoins, voir si ça fonctionne (et pas que pour la preview, aussi pour l’enregistrement) : https://github.com/muaz-khan/RecordRTC/issues/545
et https://www.webrtc-experiment.com/RecordRTC/simple-demos/video-mirror-recording.html

**Comment by jubonhomme** [comment]
Exact je viens de le retrouver, j'avais mal cherché
https://github.com/l-atelier-des-chercheurs/dodoc/issues/314

**Comment by louis-ev** [comment]
Je cale ça pour do•doc 9.
Je sais toujours pas comment je vais faire (surtout pour l’enregistrement vidéo) mais on trouvera bien :)

**Comment by jubonhomme** [comment]
ça pourrait se régler en appliquant la recette "Effets vidéo" / Pivoter

ça n'est pas en live mais ça fonctionne déjà si besoin d'avoir la vidéo dans l'autre sens (avec du texte par exemple)
Par contre : 
A la première rotation le format devient vertical avec la vidéo sur toute la hauteur : OK
![Capture d’écran de 2020-04-15 22-41-09](https://user-images.githubusercontent.com/29262866/79386458-71291480-7f6a-11ea-872d-6fd26328ae08.png)


A la deuxième rotation (en appliquant sur le résultat du premier effet vidéo :  on obtient une vidéo avec une rotation mais toujours dans un format vertical.
![Capture d’écran de 2020-04-15 22-41-14](https://user-images.githubusercontent.com/29262866/79386469-77b78c00-7f6a-11ea-9787-b9f25c1c6318.png)

Proposition : 
Avoir directement un troisième choix dans l'effet vidéo  **Pivoter :** 
- dans le sens des aiguilles d'une montre 
- dans le sens inverse des aiguilles d'une montre
- à 180°

ça pourrait fonctionner simplement sans rajouter beaucoup de code puisque j'imagine que les filtres Pivoter sont définis avec un angle de rotation.

**Comment by jubonhomme** [comment]
Losslesscut le permet aussi !
#350 
#408 
#352

**Comment by jubonhomme** [comment]
A fermer  :)

**Comment by louis-ev** [comment]
Oui ! ça fait plaisir :) 

Dispo à partir de do•doc 9.0.22

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/1948417/102898564-feadf400-4469-11eb-87ef-2fae7d34294c.png">
