### ISSUE TITLE
réécrire distantflux

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#417]
Avec peerjs ? Pour rétablir le partage des flux audio et vidéo.

**Comment by louis-ev** [comment]
À priori distantflux fonctionne et plutôt bien mais il faut virer adapter.js
Ce qui risque de casser la compatibilité avec des anciennes tablettes.

**Comment by jubonhomme** [comment]
doublon avec #448 ?

**Comment by jubonhomme** [comment]
A fermer pour cause de doublon avec #448

**Comment by jubonhomme** [comment]
A fermer.
Je continue les proposition sur flux distant dans l'autre issue #448
