### ISSUE TITLE
changer l’emplacement du bouton METTRE À JOUR

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#418]
Pour qu’il ne soit jamais invisible

<img width="283" alt="image" src="https://user-images.githubusercontent.com/1948417/71195777-e9b6e780-228e-11ea-982a-9d844fb0214d.png">

<img width="272" alt="image" src="https://user-images.githubusercontent.com/1948417/71195778-ea4f7e00-228e-11ea-81f4-ab61cb122e95.png">

**Comment by jubonhomme** [comment]
à fusionner avec #386

**Comment by louis-ev** [comment]
Duplicate of #386
