### ISSUE TITLE
liste des animations : n’afficher que celles du projet en question

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#419]

**Comment by louis-ev** [comment]
Tout du moins faire ressortir celle du projet en cours.

**Comment by jubonhomme** [comment]
Amélioration de la liste des animations : lien avec #387

**Comment by jubonhomme** [comment]
La logique de la liste des animations me questionne.

C'est dans l'outil capture comme pour les photo vidéo son

Mais ça ne produit pas de médias dans le projet directement, et même si le projet est verrouillé par un utilisateur l'animation qui est réalisée dans ce projet est visible et modifiable par tout le monde.
Ça ressemble plus à une recette sur ce point mais avec encore moins d'option pour les accès car une animation n'est ni un média ni une publication et donc pas de mot clé ou d'auteur possible.

Ça pourrait être utile de relier une animation à un projet et un auteur comme une recette et la verrouiller pour que d'autres personnes ne puissent pas la modifier ou la voir.

Je me demande donc si la place d'Animation ne serait pas dans la marmite ? qui ouvrirait une fenêtre de capture dédié à l'animation pour la recette
Avec la recette image par image ?? soit je glisse des médias soit je capture avec animation dans une nouvelle fenêtre

**Comment by louis-ev** [comment]
Implémenté, à venir. @jubonhomme j’entends bien ta réflexion, ça vaudrait une issue dédiée je pense parce que je ne suis pas certain que ça soit plus simple pour les personnes qui veulent faire des animations. Bien que ça m’arrange point de vue base de code : je dois dupliquer pas mal de modifs pour les deux modes stopmotions, c’est pas très fluide !

**Comment by jubonhomme** [comment]
Ok pour une autre issue dédiée sur le lien entre capture animation / projet / recette.

Tu peux fermer celle ci
