### ISSUE TITLE
la date d'édition du projet évolue en fonction de son contenu

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#420]
salut
je fais déjà joujou avec la 8.2.2 dev ;-) 
une réflexion plus qu'une demande, est-qu'il ne faut pas dans le cas d'une copie de projet remettre la date de création à celle du jour ? car on n'aurait plus de repère réel du démarrage d'un projet, les médias restant intacts.

**Comment by louis-ev** [comment]
Bonne idée oui !
Je regarde si j’ai le temps d’intégrer ça dans la 8.2 ou dans une suivante.

**Comment by louis-ev** [comment]
Le temps de le dire c’est en place :)

Par contre j’ai une question sans réponse : la date "d’édition" d’un projet est-elle mise à jour lorsqu’un des médias qu’il contient change ? (ajouté/modifié ou supprimé ?)
Qu’est-ce qui semble le plus logique ?

**Comment by jpclerc39** [comment]
ah j'ai vu, super, ça me semble bien comme ça merci, et pour ta question, je dirais à priori oui, la date d'édition du projet évolue en fonction du contenu lui-même modifié. Et cela permettra de poser des filtres plus précis (derniers projets modifié par exemple dans la recherche)

**Comment by jubonhomme** [comment]
Je viens de vérifier, ça fonctionne déjà bien... chaque modif dans un projet pousse une mise à jour de la date d'édition.
A fermer !
