### ISSUE TITLE
traduction "mot de passe" quand interface EN

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#421]
salut
en 8.2.2 dev, je l'ai vu par hasard, le terme "mot de passe" avec l'interface en langue anglaise reste en français ;-)

![image](https://user-images.githubusercontent.com/57361822/71312483-d0976d80-242b-11ea-8818-583e10ca17dd.png)

**Comment by louis-ev** [comment]
Corrigé ! Merci :)
