### ISSUE TITLE
en édition auteur, permettre le déclenchement webcam pour le fichier image de la personne

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#422]
hello
maintenant que l'on peut éditer un auteur (merci d'avoir ajouté ça), pouvoir déclencher la webcam pour prendre une photo de l'auteur en "live" pour illustrer son profil peut être une fonctionnalité sympa.

**Comment by louis-ev** [comment]
Ça fait un moment qu’on y pense oui, mais un peu délicat techniquement… Pour la version 9 ?

**Comment by louis-ev** [comment]
(il faudrait pouvoir également le faire sur les projets)

**Comment by louis-ev** [comment]
Donc améliorer imageselect : 

![image](https://user-images.githubusercontent.com/1948417/73278075-55c03000-41eb-11ea-9144-2c2555871b22.png)

En gros, trois choix possibles : importer une image, en sélectionner une, ou bien en capturer une.

**Comment by jubonhomme** [comment]
Depuis un ordi, lorsqu'on choisit "importer un fichier image" ça ouvre uniquement l'explorateur de fichier pour sélectionner un fichier image.
Mais lorsqu'on est sur un appareil mobile, si on clic sur "importer un fichier image" plusieurs appli sont proposées dont des appli photos qui permettent de prendre une photo directement utilisée pour le portrait de l'auteur. Donc ça fonctionne déjà sur smartphone et tablette.

Pour la version ordi, on pourrait effectivement avoir un troisième bouton "capturer un portrait" ou "prendre une photo" qui utilise le mode "capturer / photo" de Dodoc qui existe déjà mais dans une utilisation minimaliste "One shot" sous forme de Popup.

![portrait](https://user-images.githubusercontent.com/29262866/79507100-65575400-8037-11ea-8aaa-1f5bff5d245c.png)

**Comment by jubonhomme** [comment]
Une fois qu'on clique sur le futur bouton "prendre une photo", la même fenêtre "capturer / photo" que celle du bloc modifiable Récit pourrait faire l'affaire  

![image](https://user-images.githubusercontent.com/29262866/85185383-06f75d80-b294-11ea-9174-f4f984f0a503.png)

**Comment by louis-ev** [comment]
L’idée est chouette, ça serait assez logique et pas forcément très compliqué.
Je regarde.

**Comment by louis-ev** [comment]
À tester ! Dispo pour les projets, les auteurs et pour le mode fond vert

<img width="373" alt="image" src="https://user-images.githubusercontent.com/1948417/112475705-63cafb80-8d71-11eb-9f13-29bbc3ce223a.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1948417/112475711-64639200-8d71-11eb-90aa-b5402a3c1b9a.png">

Pour l’instant ça utilise la fenêtre d’edition donc c’est pas grand, à améliorer après vos retours :)

**Comment by jubonhomme** [comment]
C'est déjà un très bon début.
ça fait le job comme on dit ;)

Après si on peut avoir une fenêtre qui ne soit pas tout en hauteur ça sera plus beau... mais ça fonctionne déjà

**Comment by louis-ev** [comment]
En fait j’aurai voulu reprendre la fenêtre modale de capture (qui existe pour les réponses en page à page) mais mon moteur de modale ne gère pas une fenêtre modale dans une fenêtre modale… Donc pas possible sans modifier le moteur et ça a des conséquences assez importantes.
Je pense que c’est pas mal pour une v1 oui :)
J’ouvre une issue pour la v2 !
