### ISSUE TITLE
popup indiquant la légende du document

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#423]
hello
petite suggestion, un popup sur le passage de la souris sur la légende, montrant le contenu "legende" complet (si coupé) d'un média, sans avoir à l'ouvrir =, si faisable ;-)
![2019-12-28 15_24_31-do•doc](https://user-images.githubusercontent.com/57361822/71545028-7f84fd80-2986-11ea-9e00-ddf0879bffa8.png)

**Comment by louis-ev** [comment]
Quelque chose comme ça ? 

<img width="169" alt="image" src="https://user-images.githubusercontent.com/1948417/71592148-61a6cc80-2b2f-11ea-8a5b-28be2fbb46df.png">

<img width="165" alt="image" src="https://user-images.githubusercontent.com/1948417/71592150-623f6300-2b2f-11ea-83fa-27a9297fc6ad.png">

**Comment by jpclerc39** [comment]
top ! déjà implémenté en plus dans la 8.2.3 merci ;-)
