### ISSUE TITLE
Pouvoir créer des dossiers réunissant des projets

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#424]

**Comment by louis-ev** [comment]
regarder comment c’est fait : 
- sur iOS
- sur Android
- sur Nintendo DS

**Comment by jpclerc39** [comment]
pour parler de la fonctionnalité, elle est à mon sens importante, pouvoir en quelque sorte catégoriser ,dans notre cas on a par exemple des docs machines (procédures, imprimantes 3d, sublimation, laser, améliorations, fichiers divers etc), où on utilise les QRcodes à coté des machines numérique pour retrouver la doc très vite et y ajouter aussi très facilement du contenu. Il y a parallèlement à ça des docs plus orientées projets persos de membres ou projets commun aux membres du fablab.

coté visualisation, oui, une vue un peu comme android où on a un mini aperçu sous forme vignette des applications dans un dossier principal.

**Comment by louis-ev** [comment]
Une checkbox en haut à droite des projets pour pouvoir les sélectionner et créer ou les ajouter à un dossier. À tester aussi pour le traitement par lot pour médias.

**Comment by louis-ev** [comment]
Rapport d’avancement de cette fonctionnalité ici : https://forum.latelier-des-chercheurs.fr/t/journal-du-developpement-de-do-doc-version-9/204/7
Test possible ici : https://test.dodoc.fr/

@jpclerc39 qu’en penses-tu ?

**Comment by jpclerc39** [comment]
> Rapport d’avancement de cette fonctionnalité ici : https://forum.latelier-des-chercheurs.fr/t/journal-du-developpement-de-do-doc-version-9/204/7
> Test possible ici : https://test.dodoc.fr/
> @jpclerc39 qu’en penses-tu ?

c'est excellent ! regroupement intelligemment disposé, et très clair niveau design, et possibilité de créer dés le début dans un dossier projet ou non, vu aussi la sélection multiple, impressionné  !  (encore), est-ce qu'on peut créer / supprimer sur l'url ? merci déjà pour ce boulot

**Comment by louis-ev** [comment]
Merci pour les retours, content d’avoir tapé juste :)

>  (encore), est-ce qu'on peut créer / supprimer sur l'url ? merci déjà pour ce boulot

J’ai pas compris, tu peux préciser ?

**Comment by jpclerc39** [comment]
> Merci pour les retours, content d’avoir tapé juste :)
> 
> > (encore), est-ce qu'on peut créer / supprimer sur l'url ? merci déjà pour ce boulot
> 
> J’ai pas compris, tu peux préciser ?

oui pas clair désolé, je demandais si cette url https://test.dodoc.fr/ était seulement pour les développeurs, ou si je/on peut créer un projet test, supprimer sans casser de trucs

**Comment by louis-ev** [comment]
Alors, voici un petit topo de notre cuisine interne :
- https://test.dodoc.fr/ est seulement pour des tests, même si on s’en sert parfois en atelier quand on a pas le temps de mettre en place un do•doc dédié. Tu peux sans problème créer/supprimer des choses, à priori les contenus sensibles sont protégés par mdp (même si c’est pas toujours le cas…). Donc le mieux est de ne supprimer que ce que tu as créé !
- on déploie un certain nombre d’autres do•doc sur nos serveurs (par exemple https://pailleron.dodoc.fr/ pour des ateliers au collège Pailleron menés par @sarahgarcin ). Ils sont généralement protégés par mot de passe global.

Pour des questions de responsabilité légale et de coût d’hébergement, on ne souhaite pour l’instant pas héberger les contenus de la communauté mais seulement des personnes avec lesquelles on échange directement. Si tu souhaites te lancer dans la création d’un do•doc en ligne sur serveur dédié (prévoir 10 euros par mois en hébergement + un nom de domaine)  n’hésite pas à poster sur le forum cette demande et je prendrai le temps de compiler un tuto.

**Comment by jpclerc39** [comment]
merci des infos, ok pour le test.dodoc.fr
coté tuto pourquoi pas! j'ai un dédié de base chez kimsufi (dont le nom est bien trouvé...) qui permettrait sûrement de l’héberger, pour l'instant dodoc tourne au fablab sur un bon vieux windows ...

**Comment by louis-ev** [comment]
Ça marche. Avec un peu d’huile de coude tu devrais pouvoir transférer tout ça dans ton dédié et le rendre accessible sur un domaine dédié :)
Par contre il faut une bonne connexion internet, notamment pour les vidéos. En local le débit est généralement bien meilleur, donc c’est un facteur à prendre en compte.
