### ISSUE TITLE
bug affichage double des infos bulles

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#425]
L'affichage des infos bulles est double sur la version 8.2.3, j'ai vérifié sur la version 8.2.2 et il y a le même bug sous linux Ubuntu 18.04
Sur la version 8.1.2 je n'ai pas ce problème.
![bug_affichage_double](https://user-images.githubusercontent.com/29262866/71603941-916dc880-2b5f-11ea-81aa-b995de8a8ba3.png)

**Comment by jpclerc39** [comment]
ah oui pas repéré celui-ci, idem 8.2.3 cela s'affiche un peu différemment sur mon W7
![bug_infobulle](https://user-images.githubusercontent.com/57361822/71604087-4902da80-2b60-11ea-8c12-88846590158e.png)

**Comment by louis-ev** [comment]
Le module qui gère les popups (en noir) a été mis à jour et son comportement a changé. J’ai corrigé ça.
