### ISSUE TITLE
Filtre médias couleur et déplacement au click

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#426]
juste deux avis à prendre ou rejeter sur le filtre médias:
- le fond noir fait tristounet 
![image](https://user-images.githubusercontent.com/57361822/71621449-910d1600-2bcf-11ea-9590-f534827d133a.png)
- et un comportement un peu perturbant, selon que l'on sélectionne un type de médias dans le filtre médias en cliquant dessus, le pavé correspondant se déplace mais pas au même endroit

**Comment by louis-ev** [comment]
> le fond noir fait tristounet

C’est pas faux :)

> et un comportement un peu perturbant, selon que l'on sélectionne un type de médias dans le filtre médias en cliquant dessus, le pavé correspondant se déplace mais pas au même endroit

Pas sur d’avoir bien compris… qu’est-ce qui bouge ? possible d’avoir des captures d’écran ?

**Comment by jpclerc39** [comment]
en fait pour la deuxième remarque, cela bouge parce que les auteurs se mettent dynamiquement en même temps et tout se cale pour rentrer dans le cadre blanc, mais c'est un fonctionnement normal je pense en fait.
