### ISSUE TITLE
Traduction en anglais, deux phrases encore en FR

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#427]
bonne année pour commencer! et que ce formidable outil continue d'évoluer grâce à ses programmeurs & contributeurs
et pour bien commencer l'année, j'ai retrouvé deux petites phrases en FR qui font de la résistance (vu dans toutes les langues) 
![image](https://user-images.githubusercontent.com/57361822/71643484-94c99700-2cba-11ea-8f67-73f6a4dc8d1e.png)

**Comment by louis-ev** [comment]
Merci ! Corrigé pour la prochaine version (stable ?) de la 8.2
Bonne année également :)
