### ISSUE TITLE
Popup pour sortir d'un projet ouvert

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#429]
toute dernière soumission -je pense- à mon niveau sur cette release 8.2.3 dev, on dirait qu'il y a un petit décalage de popup sur le retour en arrière quand on est sur un projet (à moins que ce soit mon affichage), le popup "retour au projet" s'affiche sur le nom (pas clickable) et pas sur le passage du bouton, et peut-être faudrait-il le mettre au pluriel car on revient sur le tableau de bord. (le popup est peut-être peu important en fait et même pas adéquat si on est rentré sur le projet via une recherche média) 
![image](https://user-images.githubusercontent.com/57361822/71680805-5a7bfa80-2d8b-11ea-8de7-15b9fe2e725f.png)

**Comment by louis-ev** [comment]
En fait cette indication est pensée pour aider à revenir au projet quand on est dans la page capture.
Le nom du projet est dans ce cas clickable, et permet d’y revenir (le bouton retour aussi). Sur la page d’un projet il est inopérant puisqu’on y est déjà.
Le popup ne devrait pas apparait sur la page Projet, je peux empêcher ça.

**Comment by jubonhomme** [comment]
A fermer ?
Je ne vois plus de popup
