### ISSUE TITLE
changer le mode d’organisation des recettes / publications

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#436]
Ne plus les lister par type, mais penser à un affichage plus souple : lié aux projets par exemple, ou en indiquant des publications qui peuvent servir de gabarits, etc.

**Comment by louis-ev** [comment]
@sarahgarcin un avis là-dessus ?

**Comment by sarahgarcin** [comment]
pas d'idée à réfléchir très bientôt avec croquis !

**Comment by jubonhomme** [comment]
Je complète ici car je pense que c'est lié.

Quand on ouvre la marmite, seule les trois dernières créations de chaque recette s'affiche...
sauf dans dans le cas d'un modèle de recette récit ou page à page (cf capture en dessous ) les 3 dernières s'affichent mais aussi toutes les recettes qui suivent un de ces 3 derniers. Donc potentiellement beaucoup plus si beaucoup de réponses par exemple.

Autre chose : je trouve qu'on gagnerait en lisibilité si on pouvait déplier / replier toutes les recettes qui suivent un modèle, actuellement il y a une indentation mais elles sont toutes affichées, on pourrait les masquer par défaut sous la recette modèle qui a le même titre et les déplier si on cherche à accéder à une recette qui suit ce modèle.
Ça pourrait régler en même temps la question au dessus.

Et toujours sur l'affichage dans les recettes : 
Si on clique sur "tout afficher" en dessous pour déplier toutes les créations on ne peut pas les replier... sauf si on recharge la page. Ça pourrait être bien de pouvoir les replier à nouveaux

![image](https://user-images.githubusercontent.com/29262866/99645136-1fd88a80-2a4f-11eb-8960-4cba57ef440e.png)

**Comment by louis-ev** [comment]
Un sujet plus à jour centralise déjà ces discussions, je ferme ici.
