### ISSUE TITLE
placer un chat basique pour échanger avec les autres personnes

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#437]
hello
j'ai ouvert l'accès dodoc à l'extérieur via une règle de routage, pour quelques membres de confiance du fablab contributeurs de projets/contenus/docs
y a t'il moyen d'avoir plus d'info que le "anonyme" dans l'état tout au dessus (ip par exemple), que je sache par exemple si c'est une connexion interne au fablab ou en mode extérieur (ou il y a des logs peut-être quelque part) 
![image](https://user-images.githubusercontent.com/57361822/72220755-489d1300-3554-11ea-8e85-aa77b17435f9.png)
merci

**Comment by louis-ev** [comment]
Il n’y a pas de logs non, et c’est vrai que cette fonctionnalité est très limité encore.
"anonyme" signifie que la personne ne s’est pas identifié en tant qu’auteur.
Dans la prochaine version il y aura un interrupteur pour obliger les gens à s’identifier avant de pouvoir créeer/modifier des contenus, mais je n’ai pas trop réfléchi à d’autres choses. Je pensais aussi ajouter un petit chat simplifié comme on peut trouver dans un framapad.
On peut imaginer afficher l’adresse IP de la personne qui se connecte à un endroit (au survol ? au click) sur un "anonyme", ou d’autres choses, n’hésite pas si tu as des idées/besoins.

**Comment by jpclerc39** [comment]
si tu as déjà prévu une option pour l'authentification obligatoire c'est déjà très bien, c'est un besoin important, tout en gardant la simplicité d'usage. 

afficher l'ip et comme c'est un peu technique, il ne faudrait pas que ça "pollue" l'affichage pour les utilisateurs lambda, pour le positionner dans un endroit approprié

**Comment by jpclerc39** [comment]
tu parles de framapad, on est pas loin du média texte en mode collaboratif là ,-)

**Comment by louis-ev** [comment]
A vrai dire je garde quelques surprises de ce côté là pour la version 9 :)

**Comment by jubonhomme** [comment]
Effectivement, avec :
-  avec plusieurs utilisateurs en mode collaboratif synchrone
- **un enregistrement des révisions et un historique dynamique**
- un chat basique

on a un Etherpad ;)

Dans ces trois propositions, la plus intéressante à mon goût serait l'enregistrement de versions et l'historique dynamique (comme sur framapad) pour pouvoir revenir à des versions antérieures si on efface/modifie du texte sans le vouloir. Le "ctr Z" n'est quelques fois pas suffisant.
C'est une bonne sécurité lorsque les accès en modification sont ouverts à tous les utilisateurs.

**Comment by jubonhomme** [comment]
A fermer... le chat est fonctionnel !

**Comment by louis-ev** [comment]
Héhé :) Je ferme !
On reparlera des révisions une autre fois
