### ISSUE TITLE
idée: ajout mode tri/affichage des projets

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#438]
il y a bien une recherche par nom de projet, mais je me disais que cela pourrait être intéressant de pouvoir filtrer par nom alphabétique, ou dernière modification, avec une petite barre d'outils comme déjà fait au niveaux des filtres

**Comment by louis-ev** [comment]
Changer l’ordre c’est ça ? Régler un ordre alphabétique, par date de dernière modification ou par date de création, c’est bien ça ?

**Comment by jpclerc39** [comment]
> Changer l’ordre c’est ça ? 

oui

>Régler un ordre alphabétique, par date de dernière modification ou par date de création, c’est bien ça ?

oui (bis) :-)

**Comment by jpclerc39** [comment]
petit update :-)

**Comment by louis-ev** [comment]
Je repousse également pour plus tard :)

**Comment by louis-ev** [comment]
Mis en place une première version, à tester sur https://test.dodoc.fr/

Pas encore d’ordre alphabétique, c’est plus délicat donc ça sera pour dodoc 10 je pense :)

![image](https://user-images.githubusercontent.com/1948417/115387979-a13d7000-a1db-11eb-89ca-8446188981d5.png)

![image](https://user-images.githubusercontent.com/1948417/115387982-a1d60680-a1db-11eb-8979-a1b6cdb9fc56.png)

**Comment by jpclerc39** [comment]
> Mis en place une première version, à tester sur https://test.dodoc.fr/
> 
> Pas encore d’ordre alphabétique, c’est plus délicat donc ça sera pour dodoc 10 je pense :)
> 
> ![image](https://user-images.githubusercontent.com/1948417/115387979-a13d7000-a1db-11eb-89ca-8446188981d5.png)
> 
> ![image](https://user-images.githubusercontent.com/1948417/115387982-a1d60680-a1db-11eb-8979-a1b6cdb9fc56.png)

super déjà merci

**Comment by jubonhomme** [comment]
Une idée pour mettre en avant des projets : ajouter la possibilité de favoris pour les projets comme c'est le cas pour les médias ou épingler comme pour les messages du chat.

On pourrait épingler/mettre en favoris un projet qui serait mis en avant dans l'affichage

**Comment by jubonhomme** [comment]
Je ferme celui-ci, tout est en place
Tri alphabétique / dernière modification / date de création  
et possibilité d'épingler les projets en "finalisé" pour qu'ils remontent en premier.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/b86ff87f-797c-4182-9fd9-de1873dc6914)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c81ee05b-4186-42bc-bcca-2816677b6512)
