### ISSUE TITLE
idée: permettre pour le filtre mot clef de combiner plusieurs mots clefs

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#439]
avec ma vision fablab, améliorer la recherche en cliquant sur plusieurs mots clefs permettrait de mieux  retrouver certains projets, pour l'instant on ne filtre que sur un à la fois.
par exemple "impression 3d" et "arduino" pour les projets combinant ces deux technologies

**Comment by louis-ev** [comment]
Est-ce que c’est un règlage (filtre ET / filtre OU) ou ça te semble pertinent de changer par le comportement pour tous les utilisateurs ?

**Comment by jubonhomme** [comment]
Comme un type de média est forcement unique le filtre OU est logique 
ex : je coche image et vidéo -> je vois tous les médias de type image OU type vidéo

Pour les auteurs, même si un médias peut avoir plusieurs auteurs, je trouve que la sélection d'un seul auteur à la fois dans le filtre est préférable -> Filtre OU

Mais pour les mots clés je trouverai plus logique d'avoir un filtre ET 
ex de @jpclerc39 : je recherche "impression 3d" et "arduino" pour les projets combinant ces deux technologies

Pour avoir le OU dans les mots clé il suffit d'en avoir cocher un seul à la fois et de les rechercher à la suite et pas en même temps
Ex : je cherche en premier "impression 3D" -> je vois tous les médias avec ce mot clé
puis je coche aussi "arduino" -> je vois les médias qui ont les deux mots clés (ET)
et je décoche "impression  3D" en laissant "arduino" coché -> je vois tous les médias avec le mot clé "arduino"

**Comment by louis-ev** [comment]
Si je résume, tu proposes de passer le filtre **Mots-Clés** en ET en laissant les autres en OU ?
Je suis plutôt d’accord mais crains que ça soit un peu confus, peut-être qu’il faudrait une indication pour signaler que le comportement est pas tout à fait le même ?

**Comment by jubonhomme** [comment]
Le filtre "Type" est forcement OU car un média ne peut pas être de deux types à la fois. Perso je laisserai la possibilité d'en cocher plusieurs car pour ajouter dans une recette on peut choisir de filtrer plusieurs types à la fois... c'est bien pratique comme ça
mais voir les propositions pour celui ci en particulier dans #558

Si on ne peut cocher qu'un seul auteur ça ne pose pas de souci de compréhension non plus à mon avis... -> filtre OU 

Mais je comprends ta remarque sur le filtre "mot clé" qui peut être mal interprété si on laisse la possibilité de cocher plusieurs mots clés.
C'est la même logique que pour les différents filtres entre eux qui fonctionnent ensemble en "ET"
Le filtre favori ET le filtre auteur ET le filtre mot clé ET le filtre Type

Donc même si ça ressemble au filtre Type dans la façon de pouvoir en sélectionner plusieurs je ne pense pas que ça pose de difficultés de logique car le filtre global est justement dans cette logique "ET".... ça rejoint d’ailleurs la demande de @jpclerc39 

S'il faut une indication de ET pour le filtre mot clé, il faudrait trouver une astuce pour que ça soit visible aussi pour le ET entre les différents filtres.

**Comment by jubonhomme** [comment]
Je pense qu'on peut fermer ici @jpclerc39 ?
Les filtres sur la v10 fonctionnent assez bien.
C'est beaucoup plus lisible et complet au niveau des métadonnées des projets, et donc des filtres

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/edf6d7f2-67cf-4745-b0be-0b055861d2d0)

**Comment by louis-ev** [comment]
Un petit souci quand même que j’ai remarqué l’autre jour : Si on est sur un
écran pas spécialement haut ou qu’on a énormément de mots-clés, la liste
présentée est très très longue et oblige à se scroller tout en bas pour
pouvoir la consulter intégralement. Il faudrait améliorer un peu
l’interface. Peut-être que le menu ne suit pas quand on scroll ?

**Comment by louis-ev** [comment]
Corrigé tout ça
