### ISSUE TITLE
pouvoir obliger à être identifié pour créer/éditer des contenus

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#440]
Avec un règlage à modifier dans le panneau "règlages".

**Comment by jpclerc39** [comment]
intéressant, en complément de la demande d'affichage d'ip (message "anonyme")/ savoir si quelqu'un est connecté

**Comment by louis-ev** [comment]
Possible en créant/modifiant un fichier `meta.txt` à la racine du dossier dodoc qui contient : 
```
force_login: false

----
```

**Comment by louis-ev** [comment]
Une fenêtre dans le panneau réglage uniquement accessible aux admins est à venir pour la v10

**Comment by jubonhomme** [comment]
A fermer

**Comment by jubonhomme** [comment]
Effectif sur la V10

![image](https://user-images.githubusercontent.com/29262866/222924905-e3795baa-2e61-4a5f-a76a-8ec0348b2e4d.png)
