### ISSUE TITLE
exporter une publication page à page en JPG

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#441]
C’est parfois + pratique de sortir un JPG plutôt qu’un PDF (exemple : un poster pour partager sur les réseaux sociaux, mettre sur un site).

**Comment by jubonhomme** [comment]
C'est possible par le bouton créer / type "image" / page

Très utile aussi pour faire des pages de titrage à insérer dans une vidéo !

A fermer !

![image](https://user-images.githubusercontent.com/29262866/85184414-06f55e80-b290-11ea-8c93-057997bc8712.png)
