### ISSUE TITLE
améliorer enregistrement du CSS custom sur les publi page

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#442]
Retour de @sarahgarcin : 
- le css quand on est plusieurs sur la même plubli ça bug pas mal, ça s'efface quand tu écris par exemple

--> peut-être qu’il faudrait marcher en mode "array" ? plutôt que du custom 100%, il y a peut-être un intermédiaire à trouver avec des champs en array, à ajouter

**Comment by sarahgarcin** [comment]
Oui peut-être en mode array, c'est mieux. 
Aussi en terme de design le texte très petit et pas simple à utiliser.

**Comment by louis-ev** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/1948417/112332853-60286d80-8cba-11eb-8c4b-8f63b7de73ee.png">

Refonte il ya  quelques temps déjà, je ferme.
