### ISSUE TITLE
propriétés CSS s’affichent mal

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#443]
De @sarah : - y a plusieurs propriétés css qui  s'affichent mal
Il me faudrait + d’info, tu peux préciser ?

**Comment by sarahgarcin** [comment]
Par exemple: "border: 1px solid red;" sur un cadre de texte. L'affichage de la bordure était assez aléatoire (un coup à gauche, un coup à droite), un bug d'affichage donc. C'était sur les PC de la salle informatique, sous Windows 7 sur Firefox. Après test sur mon MacBook Pro avec une bonne connexion internet: sur chrome ça marche très bien, par contre je retrouve ce bug sous firefox (cf pj)
![Screen Shot 2020-01-17 at 18 54 30](https://user-images.githubusercontent.com/4678296/72634472-f5afcb00-395a-11ea-9972-b8cf27341ae3.png)

**Comment by louis-ev** [comment]
j’arrive pas à reproduire ce bug… Tu peux me faire un topo + précis ? c’est que border qui marchait pas bien ?

![image](https://user-images.githubusercontent.com/1948417/73013594-edeb9d00-3e18-11ea-9fcd-6db246bb5805.png)

**Comment by louis-ev** [comment]
up @sarahgarcin  :)

**Comment by sarahgarcin** [comment]
je ne sais pas trop quoi te dire de plus. 
sur les tablettes il y avait plein de propriétés qui s'affichaient mal ou pas du tout (background et border surtout)
sur mon ordi il y a seulement la propriété border qui plante comme sur ma capture d'écran.

**Comment by louis-ev** [comment]
Quel navigateur ?

**Comment by sarahgarcin** [comment]
j'ai tout détaillé dans le post au dessus: 
Par exemple: "border: 1px solid red;" sur un cadre de texte. L'affichage de la bordure était assez aléatoire (un coup à gauche, un coup à droite), un bug d'affichage donc. C'était sur les PC de la salle informatique, sous Windows 7 sur Firefox. 
Après test sur mon MacBook Pro avec une bonne connexion internet
- sur chrome ça marche très bien
- par contre je retrouve ce bug sous firefox (cf pj)

**Comment by louis-ev** [comment]
Sur firefox 86 et dans electron je n’ai pas ce soucis :
<img width="479" alt="image" src="https://user-images.githubusercontent.com/1948417/112351892-9241cb80-8cca-11eb-937e-8cbab8b225bb.png">
<img width="537" alt="image" src="https://user-images.githubusercontent.com/1948417/112351894-92da6200-8cca-11eb-988a-210513821ce4.png">

Je ferme, si tu as besoin rouvre que je regarde.

**Comment by sarahgarcin** [comment]
ah j'ai compris ! 
c'est un bug d'affichage lié au zoom, 
Suivant le niveau de zoom, certains éléments disparaissent comme la bordure par exemple (quand on dézoom, en dessous de 0.7)
![Screen Shot 2021-03-25 at 08 58 13](https://user-images.githubusercontent.com/4678296/112438779-97ddf680-8d48-11eb-90d9-6f1a1dfd7122.png)
Par contre à la création du PDF aucun soucis
C'est pas un bug très important

**Comment by louis-ev** [comment]
Je pense qu’on est fasse à un soucis du navigateur qui n’arrive pas à bien rendre des éléments très fins.
Je retire la milestone, on verra + tard.

**Comment by jubonhomme** [comment]
A fermer ?
