### ISSUE TITLE
recette page : changer l’ordre des pages

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#444]
de @sarahgarcin  : - ça serait hyper pratique de pouvoir changer la position des pages 

(à voir si ça fait pas doublon avec une autre issue)

**Comment by jubonhomme** [comment]
J'ai trouvé une issue à fermer !
Sauf que le bouton "déplacer" n’apparaît qu'au survol sinon c'est tout noir
Faudrait juste modifier les couleurs des trois boutons  : dupliquer / supprimer / déplacer pour qu'ils soient visibles
