### ISSUE TITLE
suppression de page dans la publi

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#445]
@sarahgarcin  : - on a supprimé des pages sans faire exprès... Donc peut être trouver un moyen de versionner ou de revenir en arrière 

Versionner est pas évident car ça voudrait dire dupliquer le dossier qui contient le contenu… Peut-être qu’une version d’un contenu (projet, publi ou autre) finit par un caractère spécial avec un chiffre (genre `-#1`), comme une copie qui serait lu à la place de l’original ou des versions précédentes.

Exemple : un dossier **mon-livre** qui correspond à un recette page à page **Mon Livre**.
Versionning : duplication de **mon-livre** vers **mon-livre-#2**. À la lecture des dossiers, seuls les contenu de mon-livre-#2 sont lus. C’est faisable mais ça complique pas mal le back…

Alternative plus simple pour la publi : restaurer une page supprimée (+ rendre plus difficile la suppression de page). Pour restaurer une page : lister les médias d’un publi, identifier ceux qui ne sont rattachés à aucune page, avoir un encart qqpart qui propose de restaurer la page qui contient tels médias. Peut-être que cet encart se trouve à proximité d’une vue "planche-contact" qui montre toutes les pages et permet la réorganisation des unes par rapport aux autres ?

**Comment by jubonhomme** [comment]
Yes ça aussi on peut fermer !!
