### ISSUE TITLE
page capture : sélectionner l’écran comme source 

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#447]
À tester ici : https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/
Ça devrait pas être très compliqué à ajouter.

Idéallement avoir aussi le son dans l’enregistrement.

**Comment by jpclerc39** [comment]
bonne idée! à voir si cela fonctionne bien avec un navigateur mobile

**Comment by louis-ev** [comment]
D’après https://developer.mozilla.org/fr/docs/Web/API/Screen_Capture_API faut pas y compter pour l’instant malheureusement : 

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/1948417/72795127-66960200-3c3d-11ea-8175-6cb1bfe39460.png">

**Comment by jubonhomme** [comment]
Fonctionne bien sur la version 9.0.2 sur linux.

Mais n'existe pas sur une installation serveur... ce n'est pas possible juste pour le moment ou ça ne sera jamais possible ?

**Comment by louis-ev** [comment]
Ça n’est pas encore possible mais l’API existe côté navigateurs. Il faudrait juste revoir le code du module de capture pour l’intégrer.
Ce code est d’ailleurs l’un des modules les plus anciens de dodoc et mériterait une refonte notamment pour suivre les derniers standards stabilisés (quitte à abandonner la compatibilité avec des navigateurs pas à jour depuis plus d’un an).

**Comment by jubonhomme** [comment]
A fermer

Fonctionnel depuis la version 9.021

Sur serveur
![image](https://user-images.githubusercontent.com/29262866/102909212-eabdbe80-4478-11eb-9fed-709271affe40.png)


sur poste de travail
![image](https://user-images.githubusercontent.com/29262866/102909619-864f2f00-4479-11eb-99bb-399859ecce7d.png)

**Comment by louis-ev** [comment]
Mais oui !
Je ferme, plus que 117 issues ;)
