### ISSUE TITLE
recette page: supprimer le padding-bottom sur le cadre des textes

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#450]
Il y a (je suppose) un petit padding-bottom sur les cadres des textes qui empêche de coller en bas les textes sur les marges.

**Comment by louis-ev** [comment]
Je ne vois pas ce soucis.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/1948417/112332369-f8722280-8cb9-11eb-8fcf-8e17f45431e6.png">

<img width="458" alt="image" src="https://user-images.githubusercontent.com/1948417/112332375-f9a34f80-8cb9-11eb-8db6-b11e888d4a29.png">

Je ferme, n’hésite pas à rouvrir si besoin :)

**Comment by sarahgarcin** [comment]
C'est bon, tu as dû régler ça en ajoutant la possibilité de faire dépasser les blocs dans les marges
