### ISSUE TITLE
recette page: un gabarit particulier pour la couverture

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#452]
Avoir des réglages différents pour la couverture (la première page)
Par exemple pouvoir supprimer les marges et les numéros de pages.

**Comment by jubonhomme** [comment]
C'est Ok pour les numéros de pages
![image](https://user-images.githubusercontent.com/29262866/230771582-d3188d8f-a638-44c7-8e51-150a75d19356.png)

Pour les marges, c'est un affichage au dessus des médias mais il est possible de faire déborder les médias. 

A fermer ?

**Comment by louis-ev** [comment]
On peut fermer oui !
