### ISSUE TITLE
suggestion: affichage sur les médias (et ailleurs) d'information taille fichier 

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#453]
une info qui peut être en popup ou autre: la taille d'un média, utile avant de se lancer dans un téléchargement et/ou avoir une notion de l'encombrement  (on voit la taille à l'upload mais plus après).

et plus largement une notion d'espace pris par un ou des projets, pour la partie "gestion"

**Comment by louis-ev** [comment]
C’est pas idiot oui… Indiquer le poids des médias avant de les télécharger me paraît très pertinent.

Pour la taille des projets, utile aussi oui… Par contre c’est une information assez secondaire, peut-être à afficher après un click ? Options avancées ? Peut-être que "télécharger" et "dupliquer" sont aussi des options secondaires, davantage liés à l’administration et donc dans le même menu (replié par défaut, dont le bouton pour l’ouvrir est uniquement sur la page d’un projet) ?

Par exemple : 

<img width="379" alt="image" src="https://user-images.githubusercontent.com/1948417/72747743-cc3eab80-3bb5-11ea-95a4-141d757a6478.png">

**Comment by jpclerc39** [comment]
> Peut-être que "télécharger" et "dupliquer" sont aussi des options secondaires, davantage liés à l’administration et donc dans le même menu

oui pour économiser la place, et ces manips ne sont pas quotidiennes

**Comment by jubonhomme** [comment]
+1 pour l'affichage de la taille des fichiers et dossiers

Et oui aussi pour "options avancées" afin de simplifier l'interface

**Comment by louis-ev** [comment]
C’est en cours.

J’ai repris le picto "ajuster" pour le bouton "options avancées" : 

![image](https://user-images.githubusercontent.com/1948417/74341644-5ab6df00-4da8-11ea-8e10-3554596fb9ed.png)

![image](https://user-images.githubusercontent.com/1948417/74341647-5be80c00-4da8-11ea-8c2f-68da61ac6c65.png)

**Comment by jubonhomme** [comment]
Pour la partie affichage de la taille des médias c'est finalisé

Reste à afficher la taille des projets si besoin

**Comment by louis-ev** [comment]
Ça risque de consommer trop de ressources (si on veut que la taille soit fiable il faut la recalculer à chaque modification, soit potentiellement plusieurs fois par secondes). Ou alors on met un bouton qui va demander au serveur. Mais alors jte raconte pas le boulot pour une micro-fonctionnalité…

**Comment by jubonhomme** [comment]
OK, c'est pas indispensable en effet... donc on peut fermer cette issue
