### ISSUE TITLE
recette page: bugs à l'export du pdf

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#454]
Le rendu n'est pas exactement le même entre l'aperçu et l'export pdf. 
Certains éléments texte sont coupés et certains éléments n'ont pas exactement la bonne position.
@louis-ev tu peux regarder dans la publi Banlieuz'art (exemple sur la page 4 ou sur la page 16)

**Comment by louis-ev** [comment]
Tadaaaaa 
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1948417/72795908-b0331c80-3c3e-11ea-99f2-cdaf46b91f56.png">

Solution : j’ai ajouté l’argument suivant à puppeteer : --font-render-hinting=none sur les conseils de https://github.com/thecodingmachine/gotenberg/pull/163

Vérifier donc que la qualité du rendu typo est bonne, mais à priori c’est pas mal.

**Comment by louis-ev** [comment]
(déployé sur test.dodoc.fr )
