### ISSUE TITLE
Médias Images : SVG pas d'aperçu

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#455]
on génère des .SVG au fablab (en lien avec des créations pour découpe fil chaud) mais ils ne s'affichent pas dans le visualiseur interne, conçu sous Inkscape, j'en met un en exemple
[colibri.zip](https://github.com/l-atelier-des-chercheurs/dodoc/files/4111728/colibri.zip)

**Comment by louis-ev** [comment]
J’ai personnellement un aperçu mais sur fond noir (donc invisible). C’est bien ça ?

**Comment by louis-ev** [comment]
Corrigé ! À voir s’il y a un sautre soucis sur Linux. En théorie jusqu‘à maintenant la transparence de PNG ou SVG donnait lieu à un fond noir, maintenant ce sera un fond blanc.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/1948417/73273670-af712c00-41e4-11ea-9cd1-88d89c6e60e8.png">

devient 

<img width="165" alt="image" src="https://user-images.githubusercontent.com/1948417/73273681-b5670d00-41e4-11ea-85a1-a12b56f52504.png">
