### ISSUE TITLE
Mode capture : bouton non visible sur écran smartphone

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#458]
Lorsque l'on utilise un smartphone, le bouton déclencheur du mode de capture (photo, vidéo, son...) est bien visible en format vertical : 
![screenshot-20200123-152446-samsung-internet](https://user-images.githubusercontent.com/29262866/73124188-b99eea80-3f98-11ea-9772-8fcbaef4a5d5.jpg)

Mais lorsqu'on bascule en mode horizontal, le bouton est hors de portée, même avec un scroll vers le bas.
idem pour le bouton "réglage"
![screenshot-20200123-152432-samsung-internet](https://user-images.githubusercontent.com/29262866/73124210-0aaede80-3f99-11ea-90aa-2c51aaded989.jpg)

Pour une photo on peut verrouiller la rotation de l'écran en mode vertical, prendre une photo et ensuite la faire pivoter (ajuster/pivoter vers la droite) pour la remettre en paysage.

La deuxième solution est de passer par le mode "importer" ouvrir l'app photo du smartphone et de faire la capture depuis cette application avant de revenir dans dodoc.

Peut-on imaginer sur les petits écrans que les boutons soient simplement basculés mais restent à leur emplacement (comme sur les appli photos/vidéo voir par exemple sur Open Camera https://dodoc.reseau-canope.fr/amelioration-bug/media/video-20200125-172742-c5q*webm*txt?display=standalone)
Proposition : 
![boutondeclencheurdroite](https://user-images.githubusercontent.com/29262866/73124745-11d8eb00-3f9f-11ea-8c48-ac859a645dc1.jpg)

L'avantage serait aussi d'avoir le bouton déclencheur mieux placé pour prendre la photo.

De même, le bandeau du haut pourrait être aussi réduit en mode capture car seul le bouton retour est nécessaire, le reste n'est déjà pas visible (nom du dossier) ni utile pour une capture.

**Comment by louis-ev** [comment]
Alors :
> Peut-on imaginer sur les petits écrans que les boutons soient simplement basculés mais restent à leur emplacement (comme sur les appli photos/vidéo voir par exemple sur Open Camera 

Malheureusement c’est beaucoup plus délicat que ça en a l’air car la rotation s’applique par défaut et l’interface change de manière assez importante d’un mode à un autre (avec les options qui s’affichent) — la validation de contenus demande aussi un changement important.

La page de capture + panneau stopmotion est un des modules les plus lourds, délicat à modifier. Ça risque de prendre vraiment beaucoup de temps de changer sa mise en page radicalement comme ça (même si ça n’en a pas l’air).

Je me demande s’il n’y a pas une approche intermédiaire à trouver. Déjà, réduire la barre du haut sur les petits écrans. Ensuite, supprimer les marges s’il y en a. Placer les pictos de changement de mode dans un menu qui peut se replier pour prendre moins de place. Que penses-tu de ce genre de compromis ?

**Comment by jubonhomme** [comment]
Oui, c'est comme tu peux.
C'est juste une proposition en regardant un peu comment les autres appli photos géraient les petits écrans en mode paysage.
Mais je me doute qu'avoir une interface qui passe sur toutes tailles d'écrans et utilisable avec du tactile comme avec un mobidoc est un exercice complexe.

Si tu arrives à replier le bandeau du haut pour que le bouton remonte et soit accessible ça sera déjà très bien.
Pour l'instant j'ai trouvé l'astuce d'"afficher la version ordinateur " dans le navigateur... c'est tout petit mais c'est utilisable.

**Comment by louis-ev** [comment]
On est pas mal avec la nouvelle page de capture non ?

**Comment by louis-ev** [comment]
Je ferme :)
