### ISSUE TITLE
recette page à page : améliorer le système de placement des médias dans la page  

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#459]
Pouvoir drag/drop au bon endroit directement.
Ou sinon, ajouter à un endroit visible

**Comment by louis-ev** [comment]
Amélioré : les médias se calent en haut à gauche de la zone vue.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/1948417/112334901-13de2d00-8cbc-11eb-9c00-d43a124bd24c.png">

Le glissé-déposé directement au bon endroit serait pas mal, à voir pour la v10 ?

**Comment by jubonhomme** [comment]
@paulinegourlet m'a montré que le glissé-déposé sur la V10 se fait maintenant dans le menu mais pas sur la page. 

Pouvoir déposer au bon endroit directement dans la page serait plus intuitif

**Comment by louis-ev** [comment]
Clairement oui.
Et quand on ajoute depuis le menu, on fait comment à ton avis ? Si on est à la souris, ça "charge" dans la souris et ça "dépose" là ou on clic ? Ou ça place au centre de l'écran ?

**Comment by jubonhomme** [comment]
Je pense qu'il faut rester simple, surtout pour que ça reste identique sur une interface tactile.

Donc un clic sur le picto image et un autre sur l'image que l'on veut ajouter et elle se place sur la page, en haut à gauche ou au centre.
Et le glisser déposer depuis la partie collecter directement sur la page au bon endroit, sans devoir déposer dans le menu.

Ce qui serait bien aussi c'est de pouvoir retrouver la possibilité de déposer plusieurs images à la suite sans revenir à la page à chaque fois. J'aimais bien le système des flèches vertes sur la V9.
Est-ce que si on clic sur le picto "image" du menu ça pourrait ouvrir une fenêtre comme actuellement et avoir les flèches comme la V9 pour ajouter les images.

![image](https://user-images.githubusercontent.com/29262866/230949516-53691442-0323-45ca-a9aa-18d1960da021.png)

ou avec un +

![image](https://user-images.githubusercontent.com/29262866/230950515-123f585c-4789-45cd-be82-0bf5dea80a64.png)

**Comment by louis-ev** [comment]
Je vais tenter d'ajouter le glissé déposé au bon endroit de la page, et l'ajout sur la zone ou on se trouve quand on passe par le bouton.

**Comment by louis-ev** [comment]
Euh en fait je l'avais en partie déjà fait, mais commenté dans mon code o_0
Et je sais pas pourquoi c'est inactif.
… faut vraiment qu'on termine cette v10 ! 2 ans de développement ça rend fou 😄

**Comment by louis-ev** [comment]
Ok il a fallu réécrire le truc :)
Le média se place maintenant sur la zone qu'on a sous les yeux, à partir du moment ou elle est bien à droite et en-dessous du coin supérieur gauche (règle un peu arbitraire, peut-être pas utile ?).

Autre chose : j'ai modifié la mise en page pour que le menu d'édition soit une barre à gauche, et pas en superposition. C'était pas si pratique, et on pouvait pas utiliser l'espace disponible en dessous del'encart car souvent très petit.

<img width="1728" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/f2b0c45e-005e-4709-9b7a-a0c22b539ecc">

Je pense ajouter un bouton pour plier/déplier la barre de gauche, et il faudrait bien la retravailler. 10.1 ?

**Comment by louis-ev** [comment]
J'ai ajouté le fait qu'un média placé prends une taille plus importante, et qui prends en compte l'échelle : si on est bcp dézoomé, le média/la forme sera plus grande.

**Comment by jubonhomme** [comment]
A fermer ?

**Comment by louis-ev** [comment]
He bien il y a pas encore le glissé/déposé à l'endroit voulu pour l'import. Tu crois qu'on peut s'en passer ?
