### ISSUE TITLE
suggestion: pour un média PDF, mettre en aperçu la première page pour la vignette

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#460]
dans le cas de PDF, montrer la première page en tant qu'aperçu dans la vignette

**Comment by jpclerc39** [comment]
je m'auto commente, sur cette demande, car en utilisant dococ,  je pense à une possibilité dans la lecture du pdf dans le visualiseur interne de dire "choisir pour vignette" sur la première **ou** n'importe laquelle des pages du pdf

**Comment by louis-ev** [comment]
Hmm je pense qu’on peut commencer par voir la première page — mais ça pourrait être une option intéressante. Le plus délicat sera déjà d’avoir un aperçu :)

**Comment by jpclerc39** [comment]
très bien déjà si première page

**Comment by jubonhomme** [comment]
ImageMagick peut le faire...
http://blog.passeurs-de-savoirs.fr/2011/06/generer-des-miniatures-de-fichiers-pdf-sur-son-site.html

Mais j'imagine que cette solution n'est pas possible sur dodoc.. il faut rechercher quoi exactement ?
avec ffmpeg ? ou une lib js ?

**Comment by louis-ev** [comment]
Je pense que Électron et puppeteer peuvent le faire — c’est juste pas mal de boulot pour une fonctionnalité assez mineure donc pas en haut du panier :)

**Comment by louis-ev** [comment]
J’ai fais quelques tests :
<img width="153" alt="image" src="https://user-images.githubusercontent.com/1948417/112342938-f8c2eb80-8cc2-11eb-9f3d-fb2303b31572.png">

C’est pas fou fou car il y a l’interface du lecteur PDF. Je sais pas comment la masquer, c’est un plugin donc géré très particulièrement. Ça dépanne, à voir pour la v10 pour faire mieux.

**Comment by louis-ev** [comment]
Bon, y a pas moyen de faire la même chose pour la version en ligne car le paquet puppeteer peut pas ouvrir le PDF de la même manière.
C’est pas vraiment au point encore.

**Comment by jubonhomme** [comment]
On peut fermer celle ci non ?

**Comment by jubonhomme** [comment]
Je ferme ici, on pourra en ouvrir une autre pour la gestion des pdf sur la version local ou serveur
