### ISSUE TITLE
Pouvoir mettre en pause une capture vidéo

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#463]
La possibilité de faire des pauses dans une capture vidéo et de reprendre la capture à l'aide d'un bouton serait intéressante pour faire du tourné-monté, sans avoir besoin de passer obligatoirement par la capture de plusieurs séquences et la recette "montage vidéo".
Comme le mode capture "animation" et la recette "animation image par image" sont complémentaires, on pourrait utiliser la pause pour tourner directement UNE seule séquence avec deux ou trois plans.

Est-ce possible ?
Open Camera l'a ajouté il y a quelques temps ([cf forum](https://sourceforge.net/p/opencamera/discussion/general/thread/64a84720/?limit=25)) dispo depuis la version 7 d'android.

La solution peut être de filmer avec l'application Open Camera depuis une tablette et d'importer ensuite la vidéo depuis Dodoc. Ou passer par "Importer" et choisir l'App Open camera. Mais impossible de faire une pause sur la tablette depuis une télécommande... et donc ça bouge lorsqu'on touche l'écran. Avec Dodoc on pourrait utiliser un raccourci clavier.

Exemple avec le bouton pause : 
![video_pause](https://user-images.githubusercontent.com/29262866/73495547-0d556d80-43b7-11ea-9db9-a04c15109ac5.png)

et lorsque la pause est active, bouton pour reprendre la capture en plus du bouton arrêt : 
![video_reprise](https://user-images.githubusercontent.com/29262866/73496202-58bc4b80-43b8-11ea-88ca-d1b936fb4587.png)

**Comment by louis-ev** [comment]
Chouette idée :)
ça sera pas compatible avec notre boitier à 3 boutons mais on pourrait imaginer un autre raccourci clavier effectivement. Une préférence ?

**Comment by louis-ev** [comment]
À tester : https://www.webrtc-experiment.com/RecordRTC/simple-demos/onStateChanged.html
Ça fonctionne bien chez toi ?

**Comment by jubonhomme** [comment]
C'est exactement ce qu'il faut, ça fonctionne très bien en effet !

Et oui pour les mobidocs, avec les 3 boutons ça ne passe pas, je pense que c'est aussi pour la même raison qu'Open Camera ne le propose pas non plus de commande à partir des 3 seuls boutons des kits piétons micro-casque.
A partir d'un ordinateur ce sera assez facile, quitte à ajouter un 4e bouton "pause" sur un mobidoc.
Sur tablette par contre il faudra un clavier bluetooth pour avoir la commande... mais ce sera possible.
As tu possibilité sur les tablettes et smartphones d'utiliser les raccourci volume +/- et déclencheur des kit piétons ?

Raccourci avec "P" si ce n'est pas déjà utilisé, ça marche pour le fr et en.

**Comment by louis-ev** [comment]
> As tu possibilité sur les tablettes et smartphones d'utiliser les raccourci volume +/- et déclencheur des kit piétons ?

Je sais pas si c’est possible… À tester : https://codepen.io/louis-ev-the-scripter/pen/yLydpZb?editors=1111
L’événement volumeupbutton devrait changer le fond de la page.

**Comment by jubonhomme** [comment]
J'ai essayé depuis firefox sur une tablette android 9 avec le bouton volume up mais ça ne fonctionne pas... j'arrive à changer la couleur avec un clic sur l'écran mais pas avec les boutons.

**Comment by louis-ev** [comment]
Argh :/
Ça doit pas être possible malheureusement…

**Comment by jubonhomme** [comment]
Ok, ce n'est pas non plus indispensable d'avoir la commande depuis les boutons du kit oreillette. 

Si la pause durant une captation vidéo est possible et que l'on peut assigner un raccourci clavier on aura déjà l'essentiel.
Et sur tablette, on pourra toujours utiliser un clavier Bluetooth et avoir le raccourci clavier de disponible sans avoir à toucher l'écran. Ou encore utiliser la tablette comme webcam sans fil depuis l'ordi avec l'option "Accès à distance" si elle refonctionne.

**Comment by jubonhomme** [comment]
je remonte un coup cette demande... pour une mise en place même basique comme ce que tu proposais ici 
_À tester : https://www.webrtc-experiment.com/RecordRTC/simple-demos/onStateChanged.html_

Pour les raccourcis avec les boutons sur une tablette c'est pas indispensable

**Comment by jubonhomme** [comment]
@louis-ev comme tu es en plein dans le code de capture... si tu peux ajouter la pause à la vidéo.

**Comment by jubonhomme** [comment]
A fermer

**Comment by louis-ev** [comment]
Pour référence 
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1948417/102898691-2b620b80-446a-11eb-86db-2b40677cb9c5.png">

dispo à partir de do•doc 9.0.21-dev 
à tester ici : test.dodoc.fr
et en version appli hors ligne : https://forum.latelier-des-chercheurs.fr/t/journal-du-developpement-de-do-doc-version-9/204/52
