### ISSUE TITLE
Affichage image sur votre site

### ISSUE THREAD

**Issue by RomainLalande** [l-atelier-des-chercheurs/dodoc#465]
Bonjour, 
Sur le site oueb il y a un petit soucis d'affichage des image dans la doc : https://latelier-des-chercheurs.fr/docs/station-de-documentation . Une question de droit du dossier dans lequel elles sont rangées peut être ? 
Belle journée  :-) 
Romain

**Comment by RomainLalande** [comment]
Je crois que c'est lié en fait à votre espace de partage de doc, les fichiers sources de découpe laser ne sont plus non plus téléchargeables :-)

**Comment by louis-ev** [comment]
Salut Romain

à priori c’est carrément l’hébergement des images qui a sauté…
Il faut qu’on refasse un tour sur la doc pour rétablir tout ça, on s’en occupe au plus vite. 
Merci pour l’info en tout cas :)

**Comment by louis-ev** [comment]
Au fait je les ai rétablis ! ça marche pour toi ?

Pour la doc de do•doc ou des Cahiers c’est pas le cas mais vu qu’on doit la réécrire de toute façon…
