### ISSUE TITLE
suggestion: recherche média filtre par extension

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#467]
pour éviter de multiplier les filtres coté médias, une possibilité peut-être de proposer de saisir l'extension des fichiers recherchés (et même leur nom) dans une petit boîte de dialogue, à l'identique des noms de projet.
Exemple: je cherchais tous les *.STL dans tous les projets et j'ai du mettre "autre" pour les retrouver au milieu des autres

**Comment by jubonhomme** [comment]
Le type .STL a été ajouté

A fermer
