### ISSUE TITLE
Idée: ajout sur un projet d'un champ "description"

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#469]
quand on crée un projet, on pourrait l'expliquer/le résumer en quelques lignes, avec un champ descriptif situé au niveau du nom du projet lui-même, je trouve que ça manque. Mettre cette description dans un média texte ne permet pas facilement de retrouver cette info liée au projet lui-même.

**Comment by jubonhomme** [comment]
@jpclerc39  : tu penses à un affichage comme l'[Opendoc](http://www.lopendoc.org/) par exemple ?

**Comment by jpclerc39** [comment]
> @jpclerc39 : tu penses à un affichage comme l'[Opendoc](http://www.lopendoc.org/) par exemple ?

oui c'est ça :-) sans prendre autant de place  sur la vignette mais sous la description, ou peut-être un genre de popup qui s'afficherait quand on passe la souris au dessus du projet

**Comment by jubonhomme** [comment]
La description du projet existe dans la version 10 de dodoc.

Je ferme donc cette issue
