### ISSUE TITLE
gérer les niveaux "entrée son" depuis do•doc

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#470]
Sur linux aucun soucis pour gérer les niveaux d'entrée micro et sortie casque/haut parleur directement dans les menus de mon PC... et de choisir si le son sort dans le micro casque, les HP ou encore la sortie HDMI si vidéoprojecteur.

Mais sous windows 10.... comment dire...  grrr  je viens de passer une demi heure à trouver comment régler le niveau d'entrée du micro dans des sous menus obscurs des paramètres sons.

D'où ma demande : serait-il possible d'avoir un réglage du niveau d'entrée du micro directement dans le menu "Réglages" de l'outil capture ? Un peu à la manière des appli de visioconférence, sans passer par les paramètres du PC ou l'appli de la webcam.

Cela permettrait de visualiser le graph dans la capture son et de réajuster directement dans les réglages à gauche si le son est trop fort ou trop bas.

**Comment by louis-ev** [comment]
Je crois bien que non : il n’y a pas cette possibilité dans les standards.
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

Par contre il semble exister une propriété `autoGainControl` qui `modify the volume of the input from the mic`. Un truc à tester potentiellement ?
Voir l’article : https://blog.addpipe.com/audio-constraints-getusermedia/

**Comment by jubonhomme** [comment]
D'après ce que j'ai compris de l'article que tu cites, les navigateurs web appliquent tous par défaut une "réduction de bruit" mais pour l'"autoGainControl" seul Chrome semble l'activer par défaut alors que firefox lui le désactive par défaut. 
Après je ne suis pas un grand fan des volumes automatiques. C'est souvent le cas sur les tablettes, par exemple Imovie sur Ipad l'utilise... et ça amplifie tous les sons parasites alors qu'il suffit souvent d'approcher le micro de la source.  
Je préfère encore avoir un curseur pour monter ou baisser en ragardant ce que cela donne sur le vumètre.
Donc s'il n'y a pas de possibilité d'afficher un contrôle de l'entrée son comme c'est le cas pour la sortie (ex : player son), je préfère encore ne pas utiliser le niveau auto et aller dans les paramètres sons de l'OS pour ajuster proprement.
Mais peut-être que pour de jeunes élèves ça pourrait servir. A voir si avec une case à cocher "niveau automatique" dans les paramètres serait utile...
