### ISSUE TITLE
Correction Bouton "Réglages" dans menu capture

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#471]
Idem : coquille dans le bouton "Réglages" de l'outil capture : 
"Réglages" et non pas "Règlages"

Je ne sais pas si tu l'as corrigé en même temps que le premier.

**Comment by jubonhomme** [comment]
Je m'auto-réponds, c'est déjà corrigé dans test.dodoc.fr...je ferme le fil

**Comment by louis-ev** [comment]
Oui j’avais fais une recherche sur tous les fichiers pour voir si l’erreur se trouvait aussi ailleurs :)

**Comment by louis-ev** [comment]
Merci à toi en tout cas !
