### ISSUE TITLE
Zone de sélection dans la marmite

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#472]
Au survole d'un fichier dans la marmite toute la zone semble sélectionnable, une main apparaît à la place du pointeur flèche, mais en réalité seul un clic sur ouvrir fonctionne 

![zone-marmite](https://user-images.githubusercontent.com/29262866/75098990-d4c34100-55bc-11ea-834e-ca4bd6b25aca.png)

Il faudrait soit supprimer la main au survol du nom ou au contraire rendre actif le clic sur le nom.

**Comment by louis-ev** [comment]
Oui, c’est en cours d’amélioration :)
Tu peux retester maintenant ? j’ai bossé dessus en pointillé pendant cette semaine.

**Comment by jubonhomme** [comment]
Oui ça fonctionne mieux comme ça
