### ISSUE TITLE
Revenir à la vignette initiale d'un projet

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#473]
A chaque fois que l'on clique sur un projet avec mot de passe l'affichage change pour signaler qu'il faut remplir le champ "mot de passe"... et c'est très bien ;)
Mais cet affichage reste tant qu'on ne recharge pas la page du navigateur. Du coup cela "charge" l'affichage à l'écran.
![projet-mdp](https://user-images.githubusercontent.com/29262866/75099154-b3635480-55be-11ea-9002-e13960bdf399.png)

Il faudrait revenir à la vignette initiale du dossier : 
- dès que l'on sélectionne un nouveau dossier par un autre clic
ou
- dès que la souris n'est plus dessus / au survol
ou 
- autre idée ?

**Comment by louis-ev** [comment]
En recliquant sur le bouton tu peux refermer le menu… mais on peut aussi indiquer qu’un seul menu mdp est ouvert à chaque instant, pas bête. Tu penses que ça serait utile ?

**Comment by jubonhomme** [comment]
J'avais essayé de recliquer sur le titre du projet ou sur la case à cocher... mais pas sur le  bouton "mot de passe".
Oui, je trouve qu'un seul ouvert à la fois allège l'affichage.

**Comment by louis-ev** [comment]
En fait je ne peux pas facilement limiter à un seul ouvert à la fois… Par contre rendre toute la case cliquable pour ouvrir/ferme le menu marche déjà bien, donc je pense que ça suffit.

J’ajoute aussi l’ouverture automatique si le mot de passe est le bon, y a pas vraiment de raison de rester sur l’accueil alors qu’on souhaite manifester accéder au projet.

**Comment by jubonhomme** [comment]
Avec les affichages en rouge pour ouvrir et les verrous pour les contributions ou "mot de passe requis" en noir c'est assez clair

Je ferme !
