### ISSUE TITLE
dossier d’auteurs

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#474]
de Olivier :
> En l’absence de système NFC, sur une instance en ligne, la gestion des auteurs pose un problème de lecture à l’écran, particulièrement pour les jeunes lecteurs, surtout sur tablette : retrouver son prénom/pseudo dans une liste dépassant les 25 auteurs (l’ajout d’un avatar n’étant pas forcément aidant à l’échelle d’une classe entière). Actuellement on parvient à simplifier l’exercice en faisant précéder les prénoms/pseudos des élèves d’une même classe/école d’un « mot-clé » permettant de regrouper les auteurs dans la liste (par exemple Hou Toto ; Hou Titi ; Hou Tutu …). Est-il envisageable de regrouper des auteurs en « dossier » ou de créer un dossier dans lequel s’inscrire comme nouvel auteur ?

**Comment by louis-ev** [comment]
Oui !
En attendant voici déjà un champ de recherche.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1948417/112196708-99ee6b00-8c0b-11eb-8a72-28189f28cec6.png">

**Comment by louis-ev** [comment]
Je reporte pour dodoc 10, qui prendra davantage en compte des instances utilisées par beaucoup de personnes.

**Comment by louis-ev** [comment]
Faut-il rajouter des choses pour la v10 ?
Mot-clé sur les auteurs, recherche par nom dans la liste des auteurs ?
Un avis @jubonhomme  ?

On garde les groupes pour la 10.1 ?

**Comment by jubonhomme** [comment]
Si c'est pas trop de travail, un champ de recherche par nom des auteurs ça m'aiderait bien pour retrouver parmi les 180 comptes de l'instance.
Le reste n'est pas prioritaire

**Comment by jubonhomme** [comment]
Un point sur l'avancement des groupes auteurs. 
Dans la 10.0.8 les groupes sont présents
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0340f605-e8f3-4af5-8ec0-cf4df2ad8175)

Et il y a aussi une recherche possible : 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/a4f2bf00-e8e5-4f31-a0e8-65da43a4e091)

**Comment by louis-ev** [comment]
Yes. Pour la 10.1, pouvoir chercher par groupe pourrait être utile.
En attendant, on est pas mal pour la v10 je pense :)

**Comment by louis-ev** [comment]
Ajout de filtre par groupe d'auteur sur page Auteurs.

**Comment by jubonhomme** [comment]
La recherche d'auteur / Les groupes / Le filtre par groupe sont présents sur la V11.

Je pense que ça répond à la demande de départ 
On ferme ici ?
