### ISSUE TITLE
Pouvoir dupliquer une image dans une animation

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#478]
Pour l'instant nous pouvons supprimer une image dans le mode capture "animation" en cliquant sur une image de la série et sur "Supprimer cette image".

Mais serait-il possible d'avoir une option "Dupliquer cette image" afin de pouvoir allonger le temps juste sur cette image lors de la création de la vidéo.

**Comment by jubonhomme** [comment]
A fermer !
#524

**Comment by louis-ev** [comment]
Ha mais j’ai pas mis cette option dans le mode stop-motion capture, juste dans la recette… T’es sur ?

**Comment by jubonhomme** [comment]
Exact ;)
Je me suis un peu emporté...
Question du coup : Est ce que le code de la recette peut resservir pour la capture ?

**Comment by louis-ev** [comment]
C’est pas tout à fait la même logique : côté recette la duplication se passe comme si tu remettais l’image dans la recette.
Côté capture je pense qu’il faudrait un autre système qui est plutôt une instruction sur l’image qui dit "celle-ci doit durer 4* la durée de base"

**Comment by jubonhomme** [comment]
Pour le moment il existe deux moyens  de faire du stop motion : 
soit passer par la capture qui facilite la prise de vue (pelure oignon / rendu et test au fur et à mesure) mais pas de montage / modification possible simplement.
soit passer par la recette image par image : super pour le montage avec duplication / insertion de page titre / déplacement des images.... mais on ne peut piocher que dans les images capturées par le mode "capture / photo" ou importées. Pas d'accès aux série du dossier stopmotion.

Je viens de penser à une piste qui pourrait être utile : 
Récupérer les images de la capture directement dans un projet pour les réutiliser dans la recette image par image.

Exemple : 
j'ouvre l'outil capture / animation
je fais une série d'images avec les outils de capture : pelure d'oignons - choix de la caméra - ...
Au lieu d'exporter en film avec le bouton créer,  je clic sur exporter les images et j'ai une liste déroulante avec les noms de projets vers lesquels exporter la série d'images.
Je choisis mon projet et clic sur exporter.

J'ouvre la recette image par image et j'importe le lot d'images depuis le projet
je peux dupliquer / déplacer les images / ajouter des pages titres.... dans la recette et finaliser mon montage avant la création du film.

On garderait ainsi le meilleur de chaque partie sans en faire une usine à gaz.
Garder le mode capture / animation simple et faire le montage et les modifs dans la recette image par image.

Il ne manque "que" la possibilité de passer plus simplement les images du dossier "stopmotion" dans un projet puis une recette.

Qu'en pensez vous ?
@louis-ev   PixnWave

**Comment by louis-ev** [comment]
Hmm donc pas d’ajout de fonctionnalité "avancée" dans la page de capture, ces fonctionnalités se situeraient dans la recette stopmotion donc…

![image](https://user-images.githubusercontent.com/1948417/91469234-69bc3500-e893-11ea-9cd0-eed19c8b338d.png)

et les options avancées : règlage du nbre d’images par seconde et "exporter chaque image vers le projet" (ou un autre intitulé à trouver).

**Comment by jubonhomme** [comment]
Oui c'est ça... conserver la simplicité d'usage de l'outil capture, je laisserai même le nombre d'image par sec comme il est pour une meilleur accessibilité et visibilité... je fais souvent plusieurs essais avec différente vitesse avant d'exporter vraiment.

Et au clic sur Créer  : nouvelle fenêtre (sur le même modèle que le bouton créer de la recette page à page)

Exporter la création 
Pour récupérer une vidéo ou une série d'images, cliquez sur le bouton ci-dessous :

Type : (menu déroulant)
Vidéo
Série d'images

bouton créer (vert)

Télécharger 
Ajouter au projet (Menu déroulant)

Créer

**Comment by louis-ev** [comment]
Ça me plaît bien ! 
Vidéo ou série d'image ? Tu fais comment la différence ?
Un export en GIF ?

**Comment by jubonhomme** [comment]
Type vidéo = export en mp4 comme actuellement avec le bouton créer

Type série d'images = export de chaque image de la série en png vers un projet ( en doublon du stockage des images dans le dossier caché stopmotion ) 
Comme ça on garde un export rapide en vidéo mp4 pour réutiliser dans une recette "Montage vidéo".
Mais on peut aussi récupérer les images dans le projet comme si on utilisait le mode "capture / photo" en boucle pour utiliser les images dans la recette "image par image".

Là on parle bien de l'export à partir du bouton créer de l'outil capture / animation

L'export en GIF... je le proposerai bien comme type d'export de la recette "image par image"
Créer :
Cliquez sur le bouton pour lancer la création d’une seule vidéo à partir des images ajoutées à la recette.
Nombre d'image par seconde...
**Type :** 
Vidéo
GIF animé



Type

**Comment by jubonhomme** [comment]
Sinon je viens de penser à une autre solution... peut-être plus cohérente

Afin de ne pas importer une série de plusieurs dizaines ou centaines d'images dans un projet pour les rebasculer juste après dans la recette image par image... on pourrait à la place avoir la possibilité d'importer une série d'images directement dans la recette.

Exemple : j'ouvre la recette image par image
je clic sur créer pour faire une nouvelle recette et je peux importer des images depuis les projets avec la flèche verte
comme actuellement
![imageparimage](https://user-images.githubusercontent.com/29262866/91564293-b578e800-e940-11ea-92cc-b53c93c25795.png)



et je peux aussi importer une série de photo directement depuis la liste des animations
![proposition_liste_animation](https://user-images.githubusercontent.com/29262866/91564219-95e1bf80-e940-11ea-96d4-8f9e3e062b1c.png)


De cette façon les images restent stockées dans le dossier _/stopmotion et on vient chercher (importer) une animation complète pour un montage avec les outils avancés dans la recette image par image

Peut-on au niveau du code avoir accès à ces images de la même façon que celles contenues dans les projets ?

C'est dommage d'avoir une partie des médias réalisés à partir de l'outil capture qui ne soient pas réutilisables au même niveau que les autres médias des projets dans les recettes alors que ce sont les mêmes types de médias (png).

J'imagine pourtant que le code qui génère la vidéo dans Capture / animation est similaire à celui de la recette image par image...

**Comment by louis-ev** [comment]
Oui, c’est plutôt une bonne idée ! J’ai juste un peu peur qu’on trouve jamais cette option… elle me parait assez difficile à trouver. L’idéal serait d’avoir un bouton pour switcher direct vers une nouvelle recette en fait, non ?

**Comment by jubonhomme** [comment]
Oui côté interface il faudrait que ce soit accessible plus facilement que par l'outil capture / animation.... c'était pour expliquer la source

**Comment by louis-ev** [comment]
Ok ça marche, oui je comprends.

**Comment by jubonhomme** [comment]
Mais il me semble intéressant de pourvoir avoir comme source les images de l'outil Animation dans la recette Image par image.
Les deux sont très liés, ça a encore plus de sens que les images des projets je trouve.
Sauf dans le cas d'un diaporama de photos que l'on transforme en vidéo, mais pour faire un stopmotion à partir de la recette image par image les images de la capture / animation sont indispensables.

Il reste à trouver comment les faire apparaître clairement lorsqu'on est dans la recette image par image (comme pour les images des dossiers projets dans le volet à gauche)

Avec un nouveau bouton "importer" comme le menu de page à page ?
![image](https://user-images.githubusercontent.com/29262866/91567397-58336580-e945-11ea-8077-d34423ce6afc.png)

**Comment by louis-ev** [comment]
@jubonhomme chantier complex, car le back aura besoin d’être augmenté pour importer tout un stopmotion dans la recette correspondante. On reporte à plus tard ?

**Comment by jubonhomme** [comment]
Oui ce n'est pas prioritaire

**Comment by jubonhomme** [comment]
Je découvre cette application qui ressemble pas mal à la capture de dodoc 
https://github.com/brick-a-brack/eagle-animation?tab=readme-ov-file

Il y a la possibilité quand on clique sur une image de la masquer ou de la dupliquer, peut-être une piste pour cette issue.

**Comment by JeFabrique-MaterielPeda** [comment]
Hello les amis,Intéressant comme option. MaisJ’ai voulu tester avec mon iPhone et pour une question de mauvais UX, je ne peux pas quitter le réglage de la caméra et donc utiliser l’appli en ligne. En effet pour accéder à la croix, je dois descendre artificiellement la page (la croix est caché sous la ligne d’adresse), et quand je relâche pour cliquer sur la croix elle remonte et s’escamote de Du coup l’appli en l’état n’est pas responsive. Ce qui est à mon sens un critère important vu que le smartphone reste la façon la plus intuitive et simple de faire du stop Motion. A moins que tu arrives à modifier le code pour régler ce problème Louis…------Catherine VilleretJe Fabrique mon Matériel PédagogiqueFabrique des Communs PédagogiquesTiers-Lieux Edu06 75 08 11 56Le 10 oct. 2024 à 08:12, jubonhomme ***@***.***> a écrit :﻿
Je découvre cette application qui ressemble pas mal à la capture de dodoc
https://github.com/brick-a-brack/eagle-animation?tab=readme-ov-file
Il y a la possibilité quand on clique sur une image de la masquer ou de la dupliquer, peut-être une piste pour cette issue.

**Comment by jubonhomme** [comment]
Mon idée n'est pas de reprendre l'application car je trouve dodoc beaucoup mieux ;)
Mais c'est juste pour aller voir dans leur code comment ils gèrent la duplication ou masquage des images. C'est fait sous electron donc j'imagine avec ffmpeg derrière aussi... donc peut-être une idée pour l'ajouter dans dodoc, en lien avec cette issue.
Mais ça dépasse mes compétences pour inspecter leur code.

**Comment by louis-ev** [comment]
Avec le nouveau module stopmotion de la v10 (et v11), c'est assez simple dans le code d'indiquer qu'une image reste plus longtemps que les autres (en multiple, x2, x3, etc. parce qu'en secondes, ça demanderait un code nettement plus compliqué). Donc si il s'agit de "faire durer" une image plus longtemps, sans problème. Je veux bien voir un screenshot de comment ça se passe sur ce logiciel, pour inspiration (ou des croquis, si tu as une idée @jubonhomme !).

On peut "dupliquer" l'affichage visuel (plusieurs vignettes côte à côte, autant de fois qu'on souhaite) mais niveau lisibilité c'est pas génial. Ou alors il faudrait un picto pour indiquer qu'il s'agit de répétitions de la même ?
Sinon, on indique un "x2" directement sur l'image, par exemple.

Avec le nouveau code, il serait aussi assez simple de déplacer les images dans la liste : je peux déplacer l'image 10 en position 1, ou dupliquer la 10, la copie se place en 11, que je peux déplacer en 5.
Mais je suis pas sur de voir l'intérêt ?

Bref, dites-moi ce qui vous semble pertinent ! 
Je sais qu'Olivier travaille avec pas mal de classes sur le stopmotion – je lui envoie le sujet pour qu'il intervienne si il a une idée.

**Comment by jubonhomme** [comment]
C'est ajouté et fonctionnel sur dodoc 11.1.5

![image](https://github.com/user-attachments/assets/4e912847-a1c9-45e6-8258-d26259172cd3)
![image](https://github.com/user-attachments/assets/5d010bb0-d36e-4db0-a19a-8b59d69f8c51)
![image](https://github.com/user-attachments/assets/37e00715-407d-48fb-8fd2-f035ba9b6a32)
