### ISSUE TITLE
Sur un accès en ligne, conserver le nom d'auteur lors d'une actualisation de la page

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#480]
Serait-il possible de conserver le nom de l'auteur lorsqu'on actualise la page dans une instance dodoc en ligne ?
Un système de cache qui conserve jusqu'à la fermeture de l'onglet du navigateur par exemple.

**Comment by jubonhomme** [comment]
C'est fonctionnel !
Je ferme

**Comment by louis-ev** [comment]
Top, merci :)
