### ISSUE TITLE
Problèmes d'affichage de certaines fonctionnalités dans la publi 

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#484]
Réduire la taille / le texte ("contour" - "fond" >> supprimer couleur)
Notamment pour les blocs en haut :
<img width="474" alt="Screenshot 2020-04-27 15 21 38" src="https://user-images.githubusercontent.com/7995654/80378099-722c4100-889c-11ea-8337-86a5f0b44e76.png">

**Comment by louis-ev** [comment]
En fait je pense qu’il faut placer ce bloc ailleurs, peut-être à un endroit fixe.
Je vais rajouter des options (épaisseur des traits pour les svg, etc.) et il va poser de plus en plus de problème. Il lui faudrait un endroit dédié, un endroit ou il y aura aussi l’éditeur de CSS.
Peut être consolider le panneau de création de blocs :

CRÉER
- texte
- ellipse
- etc.

MODIFIER
- …
-…

<img width="240" alt="image" src="https://user-images.githubusercontent.com/1948417/80475380-14a1fe00-8949-11ea-9418-93459faaba82.png">

?

**Comment by paulinegourlet** [comment]
Oui ça paraît pas idiot parce que là c'est sûr que plein de fois le css est pas accessible non plus.
Mais le pb de ton bloc de formes (j'allais ouvrir une issue là-dessus) c'est que ça bouffe une place folle sur la publi (lorsqu'on est pas en plein écran). 
Est-ce que tout ça n'est pas rangé avec les boutons ronds à droite ?

**Comment by louis-ev** [comment]
Ha ouai mais on a un problème alors, plus on aura d’options et plus on aura besoin de place…
Il faut ouvrir le panneau en plus grand si tu veux plus de place !
Je vais tester des trucs.

**Comment by jubonhomme** [comment]
L'affichage des fonctionnalité est maintenant dans un bloc fixe à gauche.

A fermer
