### ISSUE TITLE
Revoir la couleur / positionnement du filtre projet.

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#485]
<img width="407" alt="Screenshot 2020-04-27 15 14 17" src="https://user-images.githubusercontent.com/7995654/80379089-ea473680-889d-11ea-9778-ae67201bcb83.png">

**Comment by louis-ev** [comment]
Euh oui ? Proposition ? Quel est le problème ?

**Comment by paulinegourlet** [comment]
Bah c'est un peu violent noir comme ça et ça ressort trop je trouve.
Je peux faire des propositions oui.

**Comment by louis-ev** [comment]
Il faut que ça soit hyper visible, vu que ça masque du contenu que tu pourrais chercher des yeux. Personnellement les premières fois je me suis demandé pourquoi y avait pas plus de projets pendant une seconde. S’il est moins flagrant il faut ajouter d’autres éléments pour rappeler qu’il y a plus.

On peut aussi tenter une autre approche : **Afficher en premier mes projets** 
Comme dans la marmite

<img width="838" alt="image" src="https://user-images.githubusercontent.com/1948417/80479980-2d61e200-8950-11ea-8b4a-348f79322c30.png">

puis au clic tu vois la suite

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1948417/80479988-318dff80-8950-11ea-9d83-ba5ee1ad7143.png">

**Comment by jubonhomme** [comment]
Refonte de la présentation des projets et des publications dans la V10

A fermer ?
