### ISSUE TITLE
Ajouter transparence pour les formes

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#486]
Pour les palettes de couleurs qui n'ont pas d'option de transparence.
<img width="260" alt="Screenshot 2020-04-27 15 20 12" src="https://user-images.githubusercontent.com/7995654/80379177-05b24180-889e-11ea-9ab8-58ae2e8d868b.png">

**Comment by louis-ev** [comment]
Argh y a pas par défaut dans un color picker natif.
Ni transparent, ni "aucun".
Va falloir en implémenter un custom.

**Comment by louis-ev** [comment]
Celui-ci ? http://vue-color.surge.sh/
En version Chrome ?

**Comment by paulinegourlet** [comment]
Oui pas mal -- est-ce qu'il y a une pipette ? pour sélectionner une couleur qui est déjà sur ton doc / dans un média?

**Comment by louis-ev** [comment]
Non… La pipette, c’est au niveau OS.
Deux possibilités donc : 
- on utilise un autre picker comme vue-color mais sans pipette (mais avec un rendu homogène sur tous les OS
- on passe par le picker natif, et on ajoute un petit slider pour la transparence et activer/désactiver

Après c’est pas très compliqué d’avoir dans le picker vue-color les couleurs déjà utilisées dans le doc (quelque soient les pages). Mais on pourra pas faire ça avec le input natif… Enfin si, mais ça risque d’être bricolé.

**Comment by jubonhomme** [comment]
Avec la v10 et la nouvelle gestion des formes et des couleurs ça fonctionne bien de mon côté.

![image](https://user-images.githubusercontent.com/29262866/230771066-3d9962ee-3d4c-4643-b8fd-0e9a4ab2c765.png)

A fermer ?
