### ISSUE TITLE
Zone cliquable / pointeur survol titre dans Chat

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#487]
Je me fais avoir 1 fois sur 2... 
Lorsque l'on passe la souris sur un titre de recette (pages à pages ou autres)  le pointeur se transforme en main comme pour cliquer... et non, c'est pas actif ! 
Il n'y a que sur le bouton "ouvrir" en rouge à droite  qui fonctionne.... logique !

Il faudrait à mon avis supprimer la main au survol du titre et ne laisser que le bouton rouge qui modifie le pointeur en main .... ou alors laisser tout cliquable... mais le bouton serait alors un peu inutile.

**Comment by louis-ev** [comment]
Héhé :)
Vu la taille du bouton, autant avoir toute la tuile cliquable, comme pour les projets !

**Comment by jubonhomme** [comment]
En effet ça marche bien mieux avec la tuile cliquable sur la surface totale...

Du coup on peut appliquer la même chose pour le Chat ? 
-> zone cliquable sur la tuile du titre de la discussion et pas seulement le bouton "ouvrir" à droite,  qui n'est pas très visible en plus... beaucoup moins que le titre du fil

J'actualise le titre de l'issue

**Comment by louis-ev** [comment]
Pour te répondre, la raison pour laquelle je n’ai pas fais ça comme ça est liée à une fonctionnalité un peu masquée : si tu cliques sur le compteur de non lu ça "lit" automatiquement tous les messages (pour le faire passer à 0 rapidement sans avoir à ouvrir le chat).

<img width="284" alt="image" src="https://user-images.githubusercontent.com/1948417/98113898-9f3d5a00-1ea4-11eb-8da9-2d2e5703e166.png">

Ça me semblait pratique à l’époque où j’ai ajouté ça mais je suis plus trop sur… Tu en penses quoi ?

**Comment by jubonhomme** [comment]
Perso si je clique sur le compteur je m'attends plus à ce que ça ouvre directement le message non lu... 

Ex : Je clique... ça ouvre et ça descend directement au dernier message non lu 

... mais pourquoi pas juste une remise à zéro sans ouverture

Autre chose :  pour l'instant à chaque ouverture ça ouvre tout au début (en masquant les plus anciens) mais peut-être que là aussi l'ouverture peut se faire directement au dernier message, c'est un fil de discussion... je ne vois pas trop l'intérêt de reprendre tout en haut si je n'ai pas lu les deux derniers.

Pour revenir à la question de départ je ne pense pas que le compteur cliquable soit incompatible avec le fait que le titre du fil de discussion le soit aussi.
Les deux peuvent fonctionner non ?
Je clique sur le titre ça ouvre en bas
Je clique sur le compteur ça remet à zéro sans ouvrir

C'est un problème de place et d'espacement ?

**Comment by louis-ev** [comment]
Je pense que tu as raison on va faire plus simple : clique sur le rectangle (n’importe où) = ouverture. La fonctionnalité que j’évoque est vraiment pas clair et indispensable.
Mais la raison pour laquelle je préfère éviter d’avoir clic compteur + clic tuile est que le compteur est pas grand, on peut imaginer qu’on peut se planter facilement à ouvrir un chat en essayant de cliquer sur le compteur et inversement.

> Autre chose : pour l'instant à chaque ouverture ça ouvre tout au début (en masquant les plus anciens) mais peut-être que là aussi l'ouverture peut se faire directement au dernier message, c'est un fil de discussion... je ne vois pas trop l'intérêt de reprendre tout en haut si je n'ai pas lu les deux derniers.

Ha mais non c’est pas normal !
Ça devrait afficher comme ça : 

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/1948417/98155929-56eb5f80-1ed7-11eb-9e7c-5dcd917d2273.png">

Ça scroll vers *dernier message lu*, qui indique là où on s’est arrêté de lire. Si c’est pas comme ça chez toi je veux bien une issue avec le navigateur en question.
