### ISSUE TITLE
Remplacer le texte "Mot de passe requis" par un Picto

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#488]
Afin de rendre plus homogène la lecture et gagner un peu de place...

Proposition avec ce picto
https://fr.freepik.com/icones-gratuites/mot-passe_790496.htm

Avant
![picto_motdepasse_1](https://user-images.githubusercontent.com/29262866/80417926-e08df500-88d6-11ea-8119-8e72c0c9d642.png)

Après... (peu être avec une couleur différente)
![picto_motdepasse](https://user-images.githubusercontent.com/29262866/80417823-afadc000-88d6-11ea-8eb0-010e95942e00.png)

**Comment by louis-ev** [comment]
Je vois bien l’idée, par contre le fond rouge fait que ça ressemble beaucoup au bouton ouvrir. Peut-être qu’il y a une autre couleur qui signale : "pas ouvrable, protégé par un mot de passe".

**Comment by jubonhomme** [comment]
Oui pour une autre couleur, ou en bicolore

Je viens de voir aussi qu'il y a beaucoup de texte pour "Accès limité aux auteurs"

Donc deux boutons, mais le verrou me rappelle le droit ou non de modification.
Peut être avec la flèche du bouton ouvrir à la place...
Je te laisse proposer quelque chose de plus juste... j'ai fait des tests comme ça

exemple pour mot de passe et pour auteur :
![bouton_ouverture](https://user-images.githubusercontent.com/29262866/80545856-9b3ff500-89b4-11ea-9a65-9df0fad4a2df.png)

**Comment by jubonhomme** [comment]
Je ferme cette issue car la V10 sera bien différente.

**Comment by louis-ev** [comment]
Absolument oui, merci @jubonhomme :)
D'ailleurs je pense que dès que les premières versions alpha de dodoc 10 sortent ça aurait du sens de trier les issues pour mettre de côté celles qui concernent dodoc 9. Pas forcément les fermer mais au moins leur attribuer un *label* pour bien les identifier : *dodoc 9* *dodoc 10*. Qu'en penses-tu ?

**Comment by jubonhomme** [comment]
Oui c'est un peu ce que je commençais à faire... je fais un premier passage sur les issues en regardant celles qui sont corrigées dans la dernière version 9.3.5 et ce qui n'est plus d'actualité. Mais certaines sont à conserver pour donner la feuille de route pour la V10. Donc oui pour mettre un label dodoc 9 et un dodoc 10
