### ISSUE TITLE
Cohérence Sélection / Ouverture des dossiers / projets

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#490]
Quand je clique sur le nom d'un dossier ça sélectionne les projets (coche verte) mais pas le dossier lui même. 
Quand je clique sur le nom d'un projet ça ouvre le projet, ça ne le sélectionne pas. 
Par contre la case à cocher pour sélectionner un projet dans un dossier s'affiche au survol quasi au dessus du bouton ouvrir... pas simple de viser juste. Sur tablette la case n’apparaît pas au départ... et comme il n'y a pas de survol je ne vois pas la case.. il faut un appui long pour la faire apparaître.
Mais si je clique au bon endroit sans voir la case je peux directement sélectionner le projet.

A quoi sert la case de sélection du dossier ? je ne comprends pas bien son fonctionnement.

Je me pose la question si pour rendre plus cohérent l'ensemble il ne faudrait pas utiliser les titres comme seul moyen de sélection et réserver les boutons rouges à l'ouverture... 
- je clique sur un titre (projet ou dossier ) > ça sélectionne
- je clique sur un bouton rouge > ça ouvre.
- mettre en rouge également le bouton ouvrir en haut à droite des dossiers

En même temps le clic sur l'ensemble d'une grande tuile projet pour ouvrir est très pratique...
Sachant qu'on ouvre plus souvent qu'on ne doit sélectionner...

Une autre idée à proposer ??

edit : En revenant sur l'interface avec l'outil développeur de firefox je m’aperçois que ce que je perçois comme un "bouton ouvrir" en rouge n'est en réalité qu'un picto "consultation par tout le monde", comme le picto "verrou ouvert ou fermé" pour la modification possible ou non. Alors que le mot  "ouvrir" du dossier est bien un bouton.
Bref...Je n'ai pas de solution satisfaisante pour l'instant...

**Comment by louis-ev** [comment]
Une alternative peut-être + simple : un bouton "mode sélection" qqpart qui permet d’activer ce mode, où quand on clic sur les projets ils ne s’ouvrent pas, ils se sélectionnent (ou se déselectionnent).

C’est bien que tu lances le sujet, voyons à l’usage à quel point la sélection est importante et si les dossiers remplissent leur fonction en l’état.

**Comment by jubonhomme** [comment]
Refonte de l'interface sur la V10
suppression des dossiers
possibilité de créer des "espaces"
