### ISSUE TITLE
Zoomer dans la visualisation d'un média image

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#493]
bonjour
intégration possible d'un petit zoom dans la visu d'une image, pour éviter de la télécharger et agrandir ? avec la molette souris par ex, je trouve que ça manque
bien sûr la résolution conditionnera la qualité...

**Comment by louis-ev** [comment]
Bonne idée oui ! Je regarde ce qui existe et qui fonctionne aussi bien sur souris qu’en tactile

**Comment by jubonhomme** [comment]
J'allais faire la même demande... et je vois qu'il y a déjà une issue.
Donc un petit up pour avoir un zoom comme pour l'affichage des recettes, 
soit avec un +/- 
![image](https://user-images.githubusercontent.com/29262866/119982193-d6996280-bfbe-11eb-90e9-726efb702a7d.png)


ou une barre avec curseur
![image](https://user-images.githubusercontent.com/29262866/119982081-afdb2c00-bfbe-11eb-9ee4-e0cd80f76ed0.png)

![image](https://user-images.githubusercontent.com/29262866/119981664-2deb0300-bfbe-11eb-85f5-95063372b1bb.png)

**Comment by louis-ev** [comment]
Comme ça par exemple ? On active le zoom en cliquant sur un bouton, et ensuite c'est au doigt ou à la souris qu'on se déplace dans l'image ? https://codepen.io/galulex/full/eNZRVq

**Comment by jubonhomme** [comment]
Oui comme ça mais effectivement avec un bouton pour activer et surtout pas automatique c'est très pénible

**Comment by jubonhomme** [comment]
C'est ajouté dans la 10.0.8

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/57ae392c-d4bf-4a11-a350-5c82af9210a7)
