### ISSUE TITLE
Navigateur / OSX el capitane

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#495]
- ouverture do.doc sur serveur via Chrome Version 81.0.4044.138 (Build officiel) (64 bits)
    - pas de caméra 

- ouverture do.doc sur serveur via  Firefox 76.0.1 (64 bits)
    - Problème affichage pdf / page principal et document page à page

- ouverture do.doc sur serveur via safari Version 11.1.2 (11605.3.8.1)
    - problème capture vidéo / son / forme

**Comment by louis-ev** [comment]
Bonjour !

peux-tu tenter de reproduire ces bugs sur https://test.dodoc.fr/ ?

- j’ai bien la caméra sur Chrome (dernière version, soit la 83)

- aperçu PDF ok sur Firefox

- capture Safari : à ma connaissance Safari ne permet pas l’enregistrement de vidéos (et c’est un navigateur pas mal en retard sur Firefox et Chrome pour les fonctionnalités liées à la capture). L’enregistrement du son devrait quand meme marcher… De mon côté sur Safari 13 je n’arrive pas à avoir le flux vidéo, étrange. Il faudrait reconstruire le code de la page de Capture maintenant que le standard est mieux défini, ce n’était pas le cas il y a 2 ou 3 ans.

**Comment by PixnWave** [comment]
j'ai retrouver le bug sur https://test.dodoc.fr/ via Chrome en version Version 83.0.4103.61 même après avoir réinitialiser le navigateur et fais la mise à jour.
- il ne me demande pas l’accès camera
- j'ai la demande pour le son mais pas d'animation graphique disponible

Sur safari seul la prise de photo fonctionne et stop motion de façon étrange 

Sur Firefox seul forme ne semble pas fonctionner

toutes les traces numérique des tests sont disponibles là https://test.dodoc.fr/cnc

**Comment by louis-ev** [comment]
Très étrange le soucis avec Chrome…
Je ne sais pas comment débugger ça vu que tout marche ici.
Tu es sur Windows ? Linux ?

**Comment by PixnWave** [comment]
je teste sur linux 18.04 et OSX El Capitane mais sur cette issue je ne parle que de El Capitane

**Comment by louis-ev** [comment]
Je n’ai pas ce soucis sur Mojave + Chrome 83.
Tu peux ouvrir l’inspecteur web et copier/coller ce qu’il affiche en chargeant cette page ?

Comme ceci : 
![image](https://user-images.githubusercontent.com/1948417/83149563-890fbe80-a0fa-11ea-9237-1fc093640972.png)

**Comment by PixnWave** [comment]
![dodoc bug video chrome sur osx el capitane](https://user-images.githubusercontent.com/27885587/83153424-38e72b00-a0ff-11ea-9f17-64d50858ab17.jpg)

**Comment by louis-ev** [comment]
Ça fonctionne chez moi :/
Question bête mais tu utilises quoi comme caméra ?

**Comment by PixnWave** [comment]
iSight intégrée ...

**Comment by PixnWave** [comment]
iMac 24" mi 2007 iMac 7.1

**Comment by louis-ev** [comment]
Tu peux me confirmer que tu as la caméra ici ? 
https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by PixnWave** [comment]
![isight](https://user-images.githubusercontent.com/27885587/83159246-0bea4680-a106-11ea-874d-5ae373dbbed7.jpg)

**Comment by louis-ev** [comment]
Alors je sèche… désolé.
Il faudrait réécrire le code de la capture maintenant que les standards sont bien définis mais là tout de suite j’ai pas d’explication ou de solution.

**Comment by PixnWave** [comment]
ok

**Comment by jubonhomme** [comment]
A tester avec la nouvelle version de capture sur dodoc 9.0.22

ça devrait mieux passer...

**Comment by jubonhomme** [comment]
A fermer ?
