### ISSUE TITLE
Recette Récit

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#496]
**• Meilleure organisation des contenus dans la liste des récits**
- au lieu de _réponse à “NOM RECIT”_ > [nom_auteur] NOM RECIT
- parent (1 couleur ou graisse ? / 1 alinéa ?) : le modèle / enfants : toutes les réponses ((dé)pliables)
- faire figurer le nom de l'auteur en premier (colonne de la table Liste des récits)
- pouvoir retrouver l'url de ton récit-réponse (affichage du code généré/ URL)

**• Partie Réponse**
- repérage de la progression (barre de progression ? pourcentage ?)
- Affichage d'un menu / sommaire et des sections dans la marge
- replis des sections (h1 ou h2?)
- un seul clic sur icône (écrire, capturer, etc.) / suppression du bouton "répondre"
- comment "valider" une réponse pour des questions fermées ?
Voir screenshot 1 ci-dessous, l'icône "write" prête à confusion.

**• Gestion des relances et des notifications**
- par email ?

**• partie modèle dans do•doc**
- option dans Bloc éditable : limiter le nombre de médias attendus
- possibilité de faire des blocs questions à choix multiples (cf. screenshot 2 ci-dessous)

____
1. <img width="751" alt="Screenshot 2020-05-19 16 53 04" src="https://user-images.githubusercontent.com/7995654/82342122-896cd300-99f1-11ea-8489-32ff0a828999.png">

2. <img width="561" alt="Screenshot 2020-05-19 17 05 17" src="https://user-images.githubusercontent.com/7995654/82343507-3dbb2900-99f3-11ea-95b9-5b6a43b4ef04.png">

**Comment by paulinegourlet** [comment]
Test téléphone : 
ça marche au top !

Petit détail d'affichage pour la capture : voir le bouton capture sur screenshots ci-dessous.

**Comment by louis-ev** [comment]
C'est clair. Une autre époque !
