### ISSUE TITLE
bouton "envoyer" décalé à droite 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#498]
Lors d'une création d'une vidéo par recette : son sur image / son sur vidéo / montage vidéo 
le bouton envoyer est décalé à droite et coupé.

![bouton enregistrer](https://user-images.githubusercontent.com/29262866/82361704-8088fb00-9a0b-11ea-95c7-3368c7efecf4.png)

**Comment by louis-ev** [comment]
Il me semble que cela ne se produit que sur firefox, non ? Tu peux confirmer ?

**Comment by jubonhomme** [comment]
Exact ! 
Sur Chrome sous ubuntu pas de problème

**Comment by jubonhomme** [comment]
C'est tout bon 

Je ferme !
