### ISSUE TITLE
Bouton "enlever"

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#499]
Bonjour, 
Le bouton "enlever" ne fonctionne pas sur firefox 76.0.1 (64 bits) pour ubuntu ni sur chromium Version 81.0.4044.138 (Build officiel) snap (64 bits)

Document page à page

**Comment by jubonhomme** [comment]
Sur quelle version de dodoc es-tu ?
Sur l'instance : test.dodoc.fr version 9.0.11.dev  ça fonctionne bien. 
Mais il y a quelques jours ça ne fonctionnait pas non plus, le bouton n'était plus actif, depuis Louis a fait des corrections.
Peut-être qu'une simple mise à jour corrigerait le problème...

**Comment by PixnWave** [comment]
je suis sce serveur https://www.do.doc.pixnwave.fr/

**Comment by jubonhomme** [comment]
En regardant dans le code source de la page je vois bien version 9.0.11.dev mais si tu n'as pas fait de mise à jour depuis une semaine c'est peut-être corrigé depuis.
Arrives-tu à lancer une mise à jour ?

**Comment by PixnWave** [comment]
Je suis entrain de chercher s'il y a une procédure pour pas tout casser

**Comment by PixnWave** [comment]
sudo apt-get update
sudo apt upgrade
?

**Comment by jubonhomme** [comment]
Oui ce serait dommage ;)... Louis a sûrement la solution...
Mais comme test.dodoc.fr fonctionne bien et présentait le même problème il y a peu de temps, je pense qu'avec une mise jour le problème sera réglé.
Par contre je n'ai jamais installé la version serveur... je ne pourrai pas t'aider plus sur cette question

Et Louis n'a pas terminé cette partie dans la doc ;)
https://forum.latelier-des-chercheurs.fr/t/installer-do-doc-sur-un-serveur-dedie/210
> Mettre à jour et changer de branche
> À venir

**Comment by PixnWave** [comment]
j'ai fais un git pull mais je n'observe pas de changement malgré pm2 reload dodoc...

**Comment by louis-ev** [comment]
Bonjour ! 
j’ai complété le tuto avec `Mettre à jour et changer de branche` :)

**Comment by louis-ev** [comment]
Et effectivement, pour revenir à la question, le bouton supprimer ne fonctionnait plus. Je l’ai rétabli.
À noter que nous sommes actuellement en phase de grosses modifications donc il y a des risques que des choses soient cassés… N’hésitez pas à nous les remonter si vous en trouvez !

**Comment by louis-ev** [comment]
Du coup je ferme cette issue car c’est tout bon sur https://test.dodoc.fr/ mais n’hésitez pas à la rouvrir si le soucis persiste chez vous.
