### ISSUE TITLE
Image dans page à page

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#500]
Après avoir réaliser une rotation de 90 degré sur une image elle ne semble plus pouvoir ce déplacer librement dans l'espace de la page.

**Comment by PixnWave** [comment]
l'image devient flou ou se pixelise en réduisant l'image

**Comment by louis-ev** [comment]
Il me faut plus de détail sur la deuxième question (pour la première voir https://github.com/l-atelier-des-chercheurs/dodoc/issues/358 pour plus d’explications) — ce bug ne me dit rien.
Comment le reproduire sur https://test.dodoc.fr/ ?

**Comment by PixnWave** [comment]
un exemple est là https://test.dodoc.fr/cnc

**Comment by louis-ev** [comment]
Ok je le vois. C’est lié à la manière dont sont calculés les images (pour des questions d’optimisation). C’est la largeur qui fait foie, donc si tu redimensionnes pour créer une bande très fine ça se comporte pas bien… Je vais désactiver ce script, il est + gênant qu’autre chose.

**Comment by jubonhomme** [comment]
A fermer ?

**Comment by louis-ev** [comment]
Oui, corrigé depuis un bon moment. Merci !
