### ISSUE TITLE
Modèle et duplication page

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#501]
Lorsque je duplique une page elle apparaît vide
même chose avec modèle

**Comment by PixnWave** [comment]
le bouton des fonctions suppression duplication déplacer de page n’apparaît qu'au survol de la souris

**Comment by louis-ev** [comment]
Ok pour la duplication, bug suite à une modification du code serveur.
Pour les boutons c’est corrigé depuis ce matin :)

**Comment by PixnWave** [comment]
moi j'ai toujours le problème sur https://test.dodoc.fr/cnc

**Comment by louis-ev** [comment]
Oui, je ne déploie pas systématiquement chaque modification — comme tu le sais ça prend du temps :)
C’est sur dodoc2-dev-node néanmoins (et la duplication de page devrait être aussi corrigée).

**Comment by jubonhomme** [comment]
Tout refonctionne normalement
A fermer !
