### ISSUE TITLE
Ajouter le bouton page 

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#502]
dans le menu créer de page à page pour ne pas avoir a revenir à la liste des pages

**Comment by louis-ev** [comment]
Euh j’ai pas compris. Avec des captures d’écran ?

**Comment by louis-ev** [comment]
Manque d'infos et pas mal de changements dans l'interface de la recette Page a Page, n'hésite pas à relancer ce sujet si besoin.
