### ISSUE TITLE
Bouton "Plein écran"

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#503]
Le bouton "Plein écran" ne fonctionne pas.

**Comment by jubonhomme** [comment]
Le bouton plein écran fonctionne à nouveau.

Par contre si on est en plein écran dans un page à page, la fenêtre du nouveau mode "capturer" du menu est en arrière plan et donc non visible.
Il faudrait la monter au dessus du plein écran pour y avoir accès sans devoir sortir du plein écran

**Comment by louis-ev** [comment]
Ha oui non c’est pire que ça : le plein écran se fait en sélectionnant un bloc à passer en plein écran. Dans notre cas, c’est le bloc "marmite". Hors les fenêtre modales apparaissent à la racine du HTML et ne sont pas dans le bloc marmite (de manière à ne pas subir ses propriétés de style). Donc les fenêtre modales ne sont pas visibles en plein écran (comme pour la barre du haut par exemple).

Pas beaucoup de choix que de changer le comportement du bouton plein écran pour juste passer toute l’interface de do•doc en plein écran et pas juste le bloc marmite, et peut-être permettre le repli complet du panneau "projet" pour pouvoir avoir un vrai plein écran sur la marmite. Qu’en penses-tu ?

**Comment by jubonhomme** [comment]
Le mode plein écran s'applique maintenant à toute l'interface de dodoc, c'est fonctionnel

A fermer
