### ISSUE TITLE
"Télécharger une version web"

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#504]
Bonjour,
Je n'arrive pas à faire fonctionner "**Télécharger une version web**" sur mon serveur https://do.doc.pixnwave.fr/ via firefox alors que cela semble fonctionner via Chromium..
cependant le résultat est surprenant ;-) https://media-quartier-est.pixnwave.fr/

je n'ai pas observer ce bug sur https://test.dodoc.fr/

**Comment by louis-ev** [comment]
Réparé, correctif intégré à sur dodoc2-dev-node

**Comment by louis-ev** [comment]
Je ferme, tu peux rouvrir si pas résolu pour toi :)
