### ISSUE TITLE
Placement du bandeau outils texte lors d'une sélection

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#506]
Lorsque l'on saisit du texte dans un bloc texte de la recette page à page, le bandeau avec les outils est placé au dessus du bloc de texte.
Mais lors d'une sélection sur le texte le bandeau se déplace pour venir au plus proche.. l'idée est bonne mais c'est souvent trop proche, quelques fois même au par dessus le texte à modifier.

Je trouve qu'il serait plus simple de le laisser toujours en haut du bloc.

Un avis ?
Exemple en vidéo : https://test.dodoc.fr/test-dodoc-9-1/media/outil-texte-selection*webm*txt

**Comment by jubonhomme** [comment]
C'est corrigé on dirait... à fermer

**Comment by louis-ev** [comment]
Affirmatif :) Merci pour ta vigilance.
