### ISSUE TITLE
La roboto mono ne s'affiche pas dans l'interface simplifiée des récits / ni dans les publi (dans do•doc)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#509]
Le texte s'écrit en Fira.

**Comment by louis-ev** [comment]
Ok.
Tu peux me donner des URL pour exemple ?

**Comment by paulinegourlet** [comment]
https://test.dodoc.fr/_publications/test-gabarit-tle-v2/

**Comment by louis-ev** [comment]
Ok j’ai trouvé, un soucis lié à la gestion des noms des familles typo dans quill.
Résolu.
