### ISSUE TITLE
QR Code -> MDP Auteur via android

### ISSUE THREAD

**Issue by Pixflowave** [l-atelier-des-chercheurs/dodoc#510]
Bonjour, 
Petite session ce matin, mes collègues ont eu des difficultés pour ce connecter via Android.
Il est nécessaire de se reconnecter comme auteur ce qui ne semble pas bien fonctionner.

**Comment by louis-ev** [comment]
Hello
il me faudrait + de détails pour pouvoir comprendre où ça coince… Étape par étape + captures d’écran si possible, et un seul soucis par issue.
Merci !

**Comment by PixnWave** [comment]
a mon sens c'est le même sujet ... l'affichage du bloc auteur n'est pas super sur android et étant en visio je n'ai pas su les guider pour se reconnecter sur leur compte déjà connecter sur leur PC. Je vais tenter de fabriquer des captures d'écran.

**Comment by jubonhomme** [comment]
Je viens de faire un test de connexion depuis un smartphone sur android, ça passe pas si mal.
@Pixflowave Est-ce que tu rencontres toujours un problème sur ce point ?

**Comment by jubonhomme** [comment]
A fermer je pense, la version 10 a été complètement revu sur cette partie aussi
@Pixflowave, tu peux confirmer qu'on peut fermer cette issue ?
