### ISSUE TITLE
Police

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#511]
....
est-il possible d'ajouter des Polices ?

**Comment by louis-ev** [comment]
Non, pas pour l’instant.
Je peux en ajouter manuellement dans le code en attendant, si elles sont libres et au format woff/woff2.

**Comment by PixnWave** [comment]
https://www.theleagueofmoveabletype.com/ a priori ce lien fournit des polices libres et au format woff/woff2 perso j'utilise Raleway ou Orbitron 

celle-ci serait sympa mais j'ai peur qu'il n'y ai pas de woff/woff2 https://graphism.fr/datalegreya-une-police-de-caractere-qui-associe-la-data-et-la-typo/

**Comment by jubonhomme** [comment]
Je viens de voir passer un article sur une police adaptée pour la déficience visuelle.
http://www.luciole-vision.com/

Je sais que Louis est Typophile ;)
et il appréciera aussi le fait que cette police est sous licence libre, au format TTF ou au format woff sur demande !
 _"Des versions spécifiques pour les webdesigners (webfonts) sont disponibles sur demande. "_

Perso je la trouve plutôt réussie et assez proche de la police ubuntu que j'utilise assez souvent.

Une idée pour rendre do•doc plus lisible pour tous.

**Comment by louis-ev** [comment]
Ha mais c’est une excellent idée ! Je connais d’ailleurs le dessinateur de caractère qui en est l’auteur (Laurent Bourcellier), qui est aussi compétent que sympa :)

Par contre je ne vois pas de WOFF, où vois-tu qu’il est sur demande ?

**Comment by jubonhomme** [comment]
C'est indiqué juste sous les téléchargements

Télécharger le caractère typographique

Le caractère Luciole est disponible au téléchargement sous licence Creative Commons Attribution. Vous pouvez l'utiliser et le diffuser gratuitement, y compris pour des usages commerciaux. Il vous suffit de le télécharger et de placer les fichiers dans le dossier Polices (ou Fonts) adéquat de votre ordinateur.

    Télécharger Regular
    Télécharger Bold
    Télécharger Italic
    Télécharger Bold Italic
    Télécharger Licence

Installation sur Windows : placer les fichiers dans C:\Windows\Fonts (puis redémarrer)
Installation sur Mac : placer les fichiers dans Bibliothèque\Fonts (puis redémarrer)
**Des versions spécifiques pour les webdesigners (webfonts) sont disponibles sur demande.**

**Comment by louis-ev** [comment]
Effectivement ! J’avais fais un recherche dans la page pour "woff" et rien trouvé.
J’envoie une mail !

**Comment by jubonhomme** [comment]
J'ai retrouvé aussi cette demande en lien #328

**Comment by sarahgarcin** [comment]
On pourrait implémenter encore des nouvelles typos pour la sortie de la version 9.

Si je résume: 
- open dyslexic : https://github.com/antijingoist/open-dyslexic
- luciole : http://www.luciole-vision.com/ (envoyer un mail pour demander les fichiers woff) 

on pourrait aussi rajouter des classiques: 
- Liberation Sans : https://www.fontsquirrel.com/fonts/liberation-sans
- Liberation Serif : https://www.fontsquirrel.com/fonts/liberation-serif
- Déjà vu sans : https://www.fontsquirrel.com/fonts/dejavu-sans
- Déjà vu serif : https://www.fontsquirrel.com/fonts/dejavu-serif


d'autre propositions ?

**Comment by PixnWave** [comment]
https://github.com/l-atelier-des-chercheurs/dodoc/issues/511#issuecomment-645902458 ?

**Comment by sarahgarcin** [comment]
ah oui merci @PixnWave j'avais raté ce comment !

**Comment by PixnWave** [comment]
je ne sais si c'est possible ou même souhaitable je vous laisse en juger

**Comment by jubonhomme** [comment]
Nous utilisons aussi assez souvent Belle Allure : https://www.jeanboyault.fr/belle-allure/

Mais je ne vois pas de format WOFF

**Comment by sarahgarcin** [comment]
@louis c'est bon pour toi à mettre dans la v9 ?

**Comment by louis-ev** [comment]
**Belle Allure** : je ne vois pas de WOFF ni de license (celle que je vois sur https://www.myfonts.com/fonts/jbfoundry/belle-allure?tab=licensing indique plutôt qu’elle n’est pas libre). Impossible à intégrer du coup.

**OpenDyslexic** : ok !
<img width="320" alt="image" src="https://user-images.githubusercontent.com/1948417/112486855-8e6e8180-8d7c-11eb-9f2a-f02dbf3c823f.png">

**Luciole** : sous license CC BY : http://www.typographies.fr/N/luciole/Read%20Me.txt
Je ne sais pas si nous pouvons l’intégrer en respectant cette licence ?
D’autre part les fichiers en ligne sont des TTF, il nous faudrait des woff et woff2 directement générés depuis le fichier source pour avoir un résultat optimal. Je vais contacter Laurent Bourcellier pour lui demander, comme je le connais.

**Comment by jubonhomme** [comment]
Belle allure est aussi en téléchargement gratuit sur son site 
https://www.jeanboyault.fr/belle-allure/

C'est effectivement étrange d'avoir un site en téléchargement payant et un autre gratuit.

Je peux essayer de le contacter. 
C'est une police qui est particulièrement intéressante pour les élèves de cycle 2

**Comment by louis-ev** [comment]
> Je peux essayer de le contacter.

Ok ça marche. Tu peux lui indiquer que la license de do•doc est la suivante : https://github.com/l-atelier-des-chercheurs/dodoc/blob/dodoc2-master/LICENSE.md
Et qu’on peut ajouter une mention avec les fichiers sources, dans le README et dans la page de documentation (en cours de rédaction).

**Comment by louis-ev** [comment]
Intégration Luciole ok.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/1948417/112973576-ca755e00-9151-11eb-8e87-fc4f06d92d6f.png">

**Comment by louis-ev** [comment]
Où en est-on sur Belle Allure @jubonhomme ? On patiente ?

**Comment by jubonhomme** [comment]
Je n'ai pas encore eu de réponse pour le moment pour le WOFF.

**Comment by jubonhomme** [comment]
Voir réponse sur ton mail... si tu as le temps de les ajouter.

**Comment by louis-ev** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1948417/114524271-5ce32a80-9c45-11eb-9947-23a99103d9c3.png">

Ça a l’air de bien fonctionner. Je met à jour test.dodoc.fr

**Comment by louis-ev** [comment]
Validé par le créateur de la fonte. Je ferme.
