### ISSUE TITLE
git pull - > 502 Bad Gateway

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#515]
Bonsoir,
la dernière mise a jour a tout cassé ...

**Comment by PixnWave** [comment]
> dodoc@9.0.16-dev debug /home/pixnwave/dodoc-mqe/dodoc
> node --inspect . --debug --debug --verbose

Debugger listening on ws://127.0.0.1:9229/f8f6a0ee-6c58-4f06-a289-2f0626ac6441
For help see https://nodejs.org/en/docs/inspector
INDEX / found override settings.json
module.js:538
    throw err;
    ^

Error: Cannot find module 'csv-writer'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pixnwave/dodoc-mqe/dodoc/core/changelog.js:4:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dodoc@9.0.16-dev debug: `node --inspect . --debug --debug --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dodoc@9.0.16-dev debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pixnwave/.npm/_logs/2020-06-25T19_08_59_794Z-debug.log

**Comment by PixnWave** [comment]
git pull
remote: Enumerating objects: 561, done.
remote: Counting objects: 100% (369/369), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 234 (delta 173), reused 166 (delta 113), pack-reused 0
Receiving objects: 100% (234/234), 43.97 KiB | 494.00 KiB/s, done.
Resolving deltas: 100% (173/173), completed with 49 local objects.
From https://github.com/l-atelier-des-chercheurs/dodoc
   534e4923..9b9c12cb  dodoc2-dev-node  -> origin/dodoc2-dev-node
   80e33287..468b99fb  dodoc2-dev       -> origin/dodoc2-dev
   78bf240a..2f89bc5f  dodoc2-dev-linux -> origin/dodoc2-dev-linux
Updating 534e4923..9b9c12cb
Fast-forward
 .gitignore                                         |    1 +
 core/auth.js                                       |    3 +-
 core/changelog.js                                  |   70 +
 core/file.js                                       |   69 +-
 core/sockets.js                                    |  220 +-
 index.pug                                          |    3 +-
 package-lock.json                                  | 3137 +++++++++++++++++++-
 package.json                                       |    4 +-
 public/src/adc-core/custom-socketio.js             |    9 +
 public/src/vue/CaptureView.vue                     |   35 +-
 public/src/vue/Chats.vue                           |    2 +-
 public/src/vue/FullDodoc.vue                       |   11 +-
 public/src/vue/ListView.vue                        |    4 +-
 public/src/vue/Publication.vue                     |   44 +-
 public/src/vue/Publications.vue                    |   53 +-
 public/src/vue/TopBar.vue                          |   73 +
 public/src/vue/app.js                              |   71 +-
 public/src/vue/components/modals/BaseModal.vue     |    7 +-
 public/src/vue/components/modals/EditMedia.vue     |   64 +-
 public/src/vue/components/modals/SettingsModal.vue |  109 +-
 .../components/publication_templates/Carreau.vue   |  177 +-
 .../publication_templates/DrawingPad.vue           |    1 -
 .../publication_templates/PagePublication.vue      |    1 -
 .../PagePublicationSinglePage.vue                  |    2 -
 .../vue/components/publication_templates/Story.vue |    1 -
 .../subcomponents/PublicationButtons.vue           |    9 +-
 public/src/vue/components/splitpane/Pane.vue       |   24 -
 public/src/vue/components/splitpane/Resizer.vue    |   34 -
 public/src/vue/components/subcomponents/Author.vue |    8 +-
 .../vue/components/subcomponents/AuthorsInput.vue  |    2 +-
 .../vue/components/subcomponents/CreateAuthor.vue  |    2 +-
 .../vue/components/subcomponents/EditAuthor.vue    |   44 +-
 .../subcomponents/MediaPublicationReply.vue        |    1 +
 .../subcomponents/PublicationDisplayButtons.vue    |   71 -
 .../components/subcomponents/PublicationFooter.vue |   93 +-
 public/src/vue/less/_modal.less                    |    2 +-
 public/src/vue/locale_strings.js                   |   69 +
 public/src/vue/style.less                          |   32 +-
 38 files changed, 4026 insertions(+), 536 deletions(-)
 create mode 100644 core/changelog.js
 delete mode 100644 public/src/vue/components/splitpane/Pane.vue
 delete mode 100644 public/src/vue/components/splitpane/Resizer.vue

**Comment by louis-ev** [comment]
Bonjour 
Effectivement il manque une ligne de commande dans la doc : si des dépendances ont été ajoutés pour le serveur (dans le message d’erreur c’est csv-writer et csv-parser en l’occurrence) alors il faut aussi lancer un npm install dans le dossier principal avant de relancer dodoc !

Désolé pour cet oubli...

**Comment by louis-ev** [comment]
Je vais compléter la doc.

**Comment by PixnWave** [comment]
Merci c'est super trop géniale et en plus on peut déjà modifier les mots de passes des utilisateurs déjà inscrit... #Total Respect

**Comment by louis-ev** [comment]
Doc corrigée !

**Comment by PixnWave** [comment]
`pixnwave@localhost:~/dodoc-mqe/dodoc$ npm install

> ffmpeg-static@4.2.7 install /home/pixnwave/dodoc-mqe/dodoc/node_modules/ffmpeg-static
> node install.js

/home/pixnwave/dodoc-mqe/dodoc/node_modules/ffmpeg-static/install.js:52
  url = new URL(url)
  ^

ReferenceError: URL is not defined
    at normalizeS3Url (/home/pixnwave/dodoc-mqe/dodoc/node_modules/ffmpeg-static/install.js:52:3)
    at Object.<anonymous> (/home/pixnwave/dodoc-mqe/dodoc/node_modules/ffmpeg-static/install.js:61:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffmpeg-static@4.2.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffmpeg-static@4.2.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pixnwave/.npm/_logs/2020-12-21T23_03_55_297Z-debug.log
`
`> dodoc@9.0.22-dev debug /home/pixnwave/dodoc-mqe/dodoc
> node --inspect . --debug --debug --verbose

Debugger listening on ws://127.0.0.1:9229/4671fbc1-5589-476f-b106-199a32ada057
For help see https://nodejs.org/en/docs/inspector
INDEX / found override settings.json
/home/pixnwave/dodoc-mqe/dodoc/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pixnwave/dodoc-mqe/dodoc/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dodoc@9.0.22-dev debug: `node --inspect . --debug --debug --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dodoc@9.0.22-dev debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pixnwave/.npm/_logs/2020-12-21T23_10_30_669Z-debug.log
`

Bonjour la derniére mise à jour n'a pas fonctionnée..

**Comment by louis-ev** [comment]
Hello Erwan,

le soucis vient de la mise à jour de node.js : à partir de la version 9.0.21-dev do•doc utilise la dernière version stable de node.js `12.18.3`

La mise à jour est sans danger. Il te faut : 

1. supprimer toutes les dépendances de do•doc `rm -rf node_modules`
2. bien utiliser node.js version 12.18.3 (vérifier en écrivante `node -v`). Si ce n’est pas le cas et que tu as suivi le tuto sur le forum, tu dois avoir `nvm` d’installé. Il faut écrire `nvm install 12.18.3` puis `nvm use 12.18.3`
3. relancer un `npm install`

Refaire la manip dans le dossier **/public**.

Dis-moi si c’est bon maintenant. Ça devrait bien booster la partie server et sécuriser un peu plus ton server.

**Comment by PixnWave** [comment]
Hello j'ai réussi mais j'ai du réinstaller mettre à jour pm2 vers pm2@4.5.1 mais c'est bon je suis en 
do•doc version 9.0.22-dev 
Merci

**Comment by louis-ev** [comment]
Super :)
Oui il faut recréer les taches sous pm2, qui enregistre la version de node à utiliser quand tu les créer. La mise à jour a du te forcer à recréer tes taches pm2, non ?

**Comment by PixnWave** [comment]
pm2 ls

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 4.5.1
Local PM2 version: 4.4.0

⇆ PM2+ activated | Instance Name: localhost-0392 | Dash: https://app.pm2.io/#/r/evdxe6sw5iz0l2z
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ dodoc              │ fork     │ 1    │ online    │ 0%       │ 47.9mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
pixnwave@localhost:~$ pm2 update
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 4.5.1
Local PM2 version: 4.4.0

[PM2] [v] Modules Stopped
[PM2] Applying action deleteProcessId on app [all](ids: 0)
[PM2] [dodoc](0) ✓
[PM2] [v] All Applications Stopped
[PM2] [v] Agent Stopped
[PM2] [v] PM2 Daemon Stopped
[PM2] Spawning PM2 daemon with pm2_home=/home/pixnwave/.pm2
[PM2] Restoring processes located in /home/pixnwave/.pm2/dump.pm2
[PM2] Process /home/pixnwave/.nvm/versions/node/v12.18.3/bin/npm restored
>>>>>>>>>> PM2 updated
⇆ PM2+ activated | Instance Name: localhost-0392 | Dash: https://app.pm2.io/#/r/evdxe6sw5iz0l2z
┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ dodoc    │ default     │ 0.35.2  │ fork    │ 68459    │ 0s     │ 0    │ online    │ 0%       │ 38.8mb   │ pixnwave │ disabled │
└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

J'avais oublié de faire pm2 update...

**Comment by PixnWave** [comment]
> Super :)
> Oui il faut recréer les taches sous pm2, qui enregistre la version de node à utiliser quand tu les créer. La mise à jour a du te forcer à recréer tes taches pm2, non ?

oui
