### ISSUE TITLE
Ecran vert marmite

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#516]
Pour ouvrir le volet marmite : 
si un clic : ouverture sur une moitié d'écran
si double clic :  ouverture sur la largeur de l'écran (très bien !)

Mais juste un écran vert ... bug d'affichage
![image](https://user-images.githubusercontent.com/29262866/85946629-f3a85a00-b945-11ea-8f23-0cd163acf2a4.png)

**Comment by louis-ev** [comment]
Hmm j’avais pas prévu le double clic effectivement !

**Comment by jubonhomme** [comment]
Je ferme, le problème est réglé dans la nouvelle version de la marmite (9.0.26)
