### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#517]
J'ai un souci avec les PDF. Ils ne s'affichent plus dans les documents pages à pages et ils se téléchargent quand on veut les afficher dans les médias...

**Comment by jubonhomme** [comment]
Tu es sur ta version serveur ?
Depuis quel navigateur ?

Sur l'instance de test.dodoc.fr tout semble fonctionner
Exemple
https://test.dodoc.fr/presentation-28-mai-atelier-canope-57/media/test-svg-20200629-222853-4aq*pdf*txt

**Comment by PixnWave** [comment]
nop firefoxe linux
https://test.dodoc.fr/presentation-28-mai-atelier-canope-57/media/capture-decran-de-2020-06-29-22-34-39*png*txt

**Comment by PixnWave** [comment]
https://test.dodoc.fr/presentation-28-mai-atelier-canope-57/media/capture-decran-de-2020-06-29-22-38-07*png*txt

**Comment by jubonhomme** [comment]
Sur Ubuntu 18.04 et 20.04 avec firefox 77.0.1, je n'ai pas de problème.
As-tu des soucis sur d'autres sites avec la visionneuse de pdf de firefox ?
Il me semble que ça vient de firefox plus que de do•doc non ?

**Comment by PixnWave** [comment]
Je suis sur 18.04 avec firefox 77.0.1 (64 bits) c'est bizarre... je vais voir... effectivement j'ai ce souci uniquement sur firefox

**Comment by louis-ev** [comment]
Oui, j’ai eu ce retour de plusieurs personnes qui utilisent Firefox.
Voir ici : https://apemobile.zendesk.com/hc/en-us/articles/115001569212-PDF-files-are-downloading-instead-of-displaying-in-web-browser-or-opening-in-a-new-tab

**Comment by PixnWave** [comment]
Merci c'est réglé super

**Comment by jubonhomme** [comment]
Issue à fermer !
