### ISSUE TITLE
Bug affichage bouton Chat

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#518]
Sur firefox ça dépasse : 
![image](https://user-images.githubusercontent.com/29262866/86168950-29ea0300-bb19-11ea-8a83-edb410437e95.png)

Sur chrome ça ne rentre pas : 
![image](https://user-images.githubusercontent.com/29262866/86169004-40905a00-bb19-11ea-9bc8-368dac7f682a.png)

Vive les standards du web hein ;)

**Comment by louis-ev** [comment]
Oui… C’est le même soucis pour les champs qui comportent un champ d’entrée + petit suffixe (genre XX px)

**Comment by louis-ev** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1948417/98262770-4940e300-1f86-11eb-95e4-c0e49d58d769.png">

Normalement c’est ok sur firefox :)
