### ISSUE TITLE
Auteur et attribut: test do•doc version 9.0.17-dev sur une 8.5

### ISSUE THREAD

**Issue by jpclerc39** [l-atelier-des-chercheurs/dodoc#520]
hello
bon je teste, j'ai installé la v 9.0.17-dev en upgradant une v8.2.5
c'est sûrement normal (mais bon j'essai) les auteurs existants ne connaissent pas le rôle contributeur, et c'est seulement quand je crée un nouveau compte que j'ai l'option, compte lucie et test sur la capture.
et si je veux passer un compte ancien en admin (jean-philippe sur la capture), je ne peux pas éditer le meta car pas de champ existant, à moins qu'on puisse sans risque le modifier (pas encore essayé)
voilà juste pour info 
![2020-07-19 18_26_50-do•doc](https://user-images.githubusercontent.com/57361822/87879978-601af400-c9ee-11ea-8124-f33bd6de24fc.png)

**Comment by louis-ev** [comment]
Oui, tu peux modifier le fichier `meta.txt` pour lui ajouter un champ `role: admin` !

Voici le contenu d’un fichier meta.txt valide : 

```
name: Louis Eveillard

----

date_created: 20200608_190137

----

role: admin

----

```

**Comment by louis-ev** [comment]
Normalement en cliquant sur le petit crayon à côté de Jean-Philippe tu devrais avoir un menu déroulant pour le passer en contributeur, ça fonctionne bien ?

Le choix admin n’est possible que si tu es loggé en tant qu’auteur qui est admin. Tu peux créer un autre compte admin ou convertir un auteur en admin. Le premier admin ne peut pas être créé par dodoc pour des questions de sécurité : il faut modifier un fichier meta.txt d’un auteur existant en `role: admin` puis relancer dodoc. Si tu as une meilleure idée pour faire ça plus simplement, ça m’intéresse ! Je pensais par exemple au premier lancement de do•doc, proposer ou forcer la création d’un compte admin avec ou sans mot de passe (en fonction des lieux).

**Comment by jubonhomme** [comment]
Question : 
Que se passe t -il  si c'est une mise à jour de dodoc en installant une nouvelle version, la création d'un compte admin sera obligatoire ? 
- dans le cas où un compte admin existe déjà
- dans le cas où il n'y a pas de compte admin dans les auteurs

L'idéal serait de vérifier la présence d'un compte admin et d'en créer un s'il n'est pas déjà existant... obliger la création d'au moins un compte mais pas de créer de doublon à chaque mise à jour

**Comment by louis-ev** [comment]
Il y a création d'un compte admin qu'en cas d'installation de zéro, pas dans le cas d'une mise à jour.
A vrai dire dodoc ne sait pas si il est installé suite à une mise à jour, il sait juste qu'un dossier dodoc2 existe déjà et l'utilise donc. S'il n'y a pas d'admin impossible de savoir si c'est volontaire ou non, et en créer un créerait un risque de sécurité : quelqu'un pourrait s'en servir pour accéder à des contenus qu'il ne devrait pas pouvoir consulter.

Dans le cas de mise à jour de dodoc 8, il faudra donc créer un admin "à la main", c'est à dire en passant par le dossier dodoc2 et en ajoutant le champ rôle: admin a un auteur existant. Mais tout cela est optionnel, on peut très bien continuer à utiliser dodoc sans admin.
