### ISSUE TITLE
son récits sur iPhone

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#523]
Bonjour,
Pas de lecture du son depuis cette marmite récit : https://do.doc.pixnwave.fr/_publications/la-ben-compagnie/
Bien à vous

**Comment by PixnWave** [comment]
Navigateur Firefox, Chrome et Safari tout est à jour / iPhone SE (2nd)

**Comment by louis-ev** [comment]
Tu veux dire sur les 5 pistes sonores en bas de page ? Pourtant chez moi j’arrive à les écouter ?

**Comment by PixnWave** [comment]
sur IOS...

**Comment by louis-ev** [comment]
Il s’agit de fichiers `.wav` : le soucis de lecture doit venir de là.

**Comment by louis-ev** [comment]
Enregistrés dans la page de capture ou avec le dictaphone de l’iphone ?

**Comment by PixnWave** [comment]
oui

**Comment by jubonhomme** [comment]
@PixnWave quand tu parles de la capture via Iphone c'est bien par "importer" ? 
Il me semblait que la capture sur Iphone était impossible (grisée), et qu'on passe par "Importer" qui ouvre le dictaphone ou l'appareil photo de l'iphone.

@louis-ev  si le wav pose problème, on ne peut pas choisir un autre format pour l'enregistrement ? 
Il me semble que pour la vidéo tu avait modifié le format de "je ne sais plus quoi "en webm

**Comment by PixnWave** [comment]
Je n'ai pas fait la prise de son ... je viens de faire le test en fait avec mon iphone impossible d'accéder au dictaphone il faut passer par parcourir qui ouvre fichier donc j'ai exporter du dictaphone vers fichier... mais ça fonctionne sur récit ici en lecture sur iphone ...https://do.doc.pixnwave.fr/_publications/recit-n-16/
mais là un seul fonctionne http://media-quartier-est.artefacts.coop/ export via document page à page... 3 source dont 2 iphones les sons qui ne marche pas en lecture sur l'iphone

**Comment by jubonhomme** [comment]
C'est ce qui me semblait pour la capture.. l'iphone ne donne pas l'accès.
Est ce que tu importes les sons comme média dans un projet puis import dans le page ou page ou tu les ajoutes directement dans le page à page par le menu "importer" ?
J'ai pas d'iphone pour tester... ce qui est étrange c'est que ni firefox ni chrome ne les lisent...le player du son s'affiche quand même ou il n'y a rien à l'affichage ?
sur ordi linux tout passe bien

**Comment by jubonhomme** [comment]
@PixnWave Est ce que tu peux tester d'importer un son dans un projet en tant que média et de le lire sur un iphone ? 
On pourra vérifier que ça vient bien du format de fichier lui même et pas de l'intégration dans la page

**Comment by PixnWave** [comment]
un son qui vient d'un iphone ? c'est ce que j'ai fais là https://do.doc.pixnwave.fr/_publications/recit-n-16/

**Comment by jubonhomme** [comment]
Quel est le format du fichier son dans le projet  ?

Peux tu lire celui ci ?
https://test.dodoc.fr/sons/media/audio-20201105-234807-9z9*wav*txt

**Comment by jubonhomme** [comment]
Si tu as un son en wav comme média dans un projet et que tu passes par ajuster / optimiser 
![image](https://user-images.githubusercontent.com/29262866/98305533-55e32c80-1fc2-11eb-8c76-6271b7394cae.png)


tu auras le son en mp3 qui devrais être pris en charge...
C'est peut-être le wav qui ne passe pas

**Comment by jubonhomme** [comment]
Le son tout en bas de  http://media-quartier-est.artefacts.coop/
Aboulahmada Nayah et ma copine Shahynes  est bien un fichier .wav

**Comment by PixnWave** [comment]
Je n'ai pas pu lire le fichier 

Je teste l'optimisation

**Comment by PixnWave** [comment]
Optimisation ça marche impeccable 

Je le fais systématiquement pour les vidéos. Je n'ai pas pensé à le faire pour le son
pardon pour le dérangement 

@+

**Comment by jubonhomme** [comment]
C'est toujours utile de connaître l'origine du problème... maintenant j'aurais aussi l'astuce de l'optimisation pour les iphones ;)

**Comment by louis-ev** [comment]
> Je le fais systématiquement pour les vidéos. Je n'ai pas pensé à le faire pour le son
pardon pour le dérangement

C’est nouveau l’optimisation du son, j’ai ajouté ça il y a quelques semaines seulement :)
Content que ça serve !
