### ISSUE TITLE
Recette Image par Image

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#524]
Bonjour,
est-il possible de pouvoir modifier l'ordre des images comme dans récit ?
Bien à vous

**Comment by louis-ev** [comment]
Pas encore non mais je le met dans la to-do pour do•doc 9.

**Comment by louis-ev** [comment]
Implémenté ! J’en ai profité pour ajouté aussi l’option de duplication, pour pouvoir laisser des images visibles + longtemps.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/1948417/91325647-bf291100-e7c3-11ea-9420-4f3680aab2d7.png">

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1948417/91325654-c05a3e00-e7c3-11ea-9a98-74fbbd9059dc.png">

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1948417/91325659-c0f2d480-e7c3-11ea-95d7-cdd55c2fba55.png">

Qu’en penses-tu @PixnWave ?

**Comment by PixnWave** [comment]
que du bien.. ;-) je regarde ... a propos de duplication... il me semble qu'il faudrait pouvoir distinguer duplication et copier car pour l'instant les textes que je duplique pour récuperer la forme sont toujours lier mais c'est peut-être une autre issue..

**Comment by louis-ev** [comment]
Absolument oui :) Je me demande si on l’a pas déjà d’ailleurs… Si tu veux la créer, be my guest!

Je vais pousser cette modif sur `dodoc2-dev-node` si tu veux pouvoir la rappatrier sur ta version en ligne.

**Comment by jubonhomme** [comment]
Et sur test.dodoc.fr please ;).... moi aussi je veux bien tester

**Comment by PixnWave** [comment]
ok super je viens enfin de réussir a trouver le temps de faire la mise à jour.
pardon est-il possible d'avoir la même fonction que sur les pages pour déplacer l'image a un numéro précis ?

**Comment by louis-ev** [comment]
Oui :)

<img width="729" alt="image" src="https://user-images.githubusercontent.com/1948417/93222156-f0678200-f76e-11ea-9d9f-8bbf75fa8eb5.png">
