### ISSUE TITLE
duplication et copier 

### ISSUE THREAD

**Issue by Pixflowave** [l-atelier-des-chercheurs/dodoc#526]
est-il possible de distinguer "copier" et "dupliquer" pour chaque éléments ?

**Comment by louis-ev** [comment]
C’est à dire ? Pour quels éléments ? 
Je crois que j’utilise les deux termes interchangeablement en fait, la copie de média d’un projet = la duplication d’un média d’une recette (que ce soit pour un média lié ou un média intégré).

**Comment by PixnWave** [comment]
Dans certain cas les éléments sont lier textes par exemple ce qui pose probléme si on veut juste pouvoir copier la forme

**Comment by louis-ev** [comment]
Ok. J’aurai besoin d’un cas concret avec captures d’écran pour mieux voir ce qui pose problème, tu peux faire ça ?

**Comment by PixnWave** [comment]
![Capture d’écran de 2020-09-14 23-46-10](https://user-images.githubusercontent.com/27885587/93141819-22cc9d00-f6e5-11ea-8a3c-ccc9c46cfecf.png)
- premier exemple le texte créé directement  dans la page peut être modifier indépendamment de la source
- le second créé dans la médiathèque est lier

**Comment by louis-ev** [comment]
Oui, la petite chaine au survol indique un média lié. Que proposes-tu pour améliorer ça du coup ?
On pensait avec Erwan V. proposer un bouton pour pouvoir transformer un média "lié" en un média "local" à la recette.
Peut-être qu’il faudrait aussi expliquer les différences entre les deux qqpart.

**Comment by PixnWave** [comment]
il faudrait effectivement pouvoir lier/délier le média et avoir un bouton édite

**Comment by louis-ev** [comment]
Plus applicable sur la v10, n'hésite pas à rouvrir si besoin :)
