### ISSUE TITLE
créér Texte Capture Importe -> Médiathéque

### ISSUE THREAD

**Issue by Pixflowave** [l-atelier-des-chercheurs/dodoc#532]
Bonsoir,
Pourquoi les éléments créé directement dans la page n'apparaissent-ils pas dans la médiathèque du projet ?

**Comment by PixnWave** [comment]
![Capture d’écran de 2020-09-14 23-46-10](https://user-images.githubusercontent.com/27885587/93141607-c9646e00-f6e4-11ea-9bf5-d60ee3b93a97.png)

**Comment by louis-ev** [comment]
Il y a de nombreux cas de figure où ces médias n’ont de sens que dans la recette et pas dans un projet — de nombreux retours que c’était laborieux de devoir créer un bloc texte dans un projet pour écrire 1 titre ou une seule phrase pour l’importer dans une recette ensuite. D’autre part je n’ai aucune certitude sur le projet dans lequel stocker ces médias, parfois une recette est créée pour servir d’exemple ou de modèle et les médias qu’elle contient ne correspondent à aucun projet. C’est plus souple comme ça, même si ça peut mener à des situations parfois confuse j’en ai conscience. 
Qu’en penses-tu ?

**Comment by PixnWave** [comment]
J'avais pas vu que l'on pouvait créer des recettes sans projet...
est-il possible d'ajouter l’élément créer dans la page a une médiathèque de projet afin de pouvoir le réutiliser ?

**Comment by louis-ev** [comment]
Oui, à venir. Pouvoir basculer un média dans le sens inverse et le copier dans un dossier.

**Comment by louis-ev** [comment]
Changement trop important pour pouvoir le finaliser avant la sortie de la v9, je le passe en v10.

**Comment by jubonhomme** [comment]
Les textes sont maintenant directement dans une publication et ne sont plus visibles dans les médias. 
Il est déjà possible de dupliquer un bloc de texte et de le déplacer vers une autre page.

A fermer ?
