### ISSUE TITLE
Dessin

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#533]
Le calque média ne fonctionne pas...

**Comment by louis-ev** [comment]
Effectivement. Je regarde.

**Comment by louis-ev** [comment]
3f18d241

**Comment by louis-ev** [comment]
Maj sur https://test.dodoc.fr/

**Comment by louis-ev** [comment]
Tu peux retester @PixnWave et me dire ? Tester d’importer un média d’un projet ou d’un placer un directement dans un dessin sur un calque média. 
Tester sous https://test.dodoc.fr/

**Comment by jubonhomme** [comment]
ça fonctionne bien pour le calque média (ajout par capture / import / texte) sur calque existant et sur un nouveau calque média

A fermer
