### ISSUE TITLE
Bug lien hypertext

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#534]
Si on clique sur le bouton pour créer un lien hypertexte dans l'outil texte directement dans une recette page à page, on ne peut pas rentrer l'URL 
![image](https://user-images.githubusercontent.com/29262866/93322305-74734580-f813-11ea-914e-56d1cae58633.png)

![image](https://user-images.githubusercontent.com/29262866/93322377-88b74280-f813-11ea-8da7-c8efbc806d03.png)

Edit : Idem pour les formules de maths, problème d'affichage de la popup ?

**Comment by jubonhomme** [comment]
C'est peut-être pas grand chose pour réparer ce bug d'affichage de fenêtre ?

**Comment by louis-ev** [comment]
J’ai pas de solution simple… idéalement il faudrait que les options d’édition ne soient pas directement le bloc mais plutôt liés à la fenêtre (voir dans le panneau latéral gauche, et que ça fasse disparaitre les autres options ?) mais quilljs est pas du tout prévu pour ça, ça complexifie énormément le code. J’ai pas de solution simple…

**Comment by jubonhomme** [comment]
Je viens de m'apercevoir que le fonctionnement du menu est différent entre l'outil texte des projets et le bloc texte directement dans une recette. 
Les boutons sont grisés par défaut et si la fonction est appliqués elle  passe en noir pour le texte des blocs.

Alors que dans l'outil texte des projets c'est toujours noir.

De même la fenêtre pour le lien hypertexte n'est pas la même... et celle en gris avec écrit https://quilljs.com est en fait fonctionnelle... il suffit de taper l'URL à la place de https://quilljs.com et ça marche. C'est juste qu'il faudrait remplacer ce texte par "ajouter l'URL" et faire entrer.

**Comment by jubonhomme** [comment]
Dans la v10 on retrouve aussi un problème d'affichage qui complique la saisie des URL des liens
Est-ce qu'il serait possible de déplacer la fenestre de saisie dans le bandeau de gauche ?
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/60b405b4-6463-4d72-85cb-641f2b788c74)

**Comment by jubonhomme** [comment]
Je remonte cette issue.
Si on ajoute par copier coller un lien hypertexte dans un bloc de texte il est bien reconnu.
Par contre on n'a pas de possibilité de l'ajouter directement par le bouton dans le menu de gauche, le bouton semble inactif.

**Comment by jubonhomme** [comment]
Un nouveau retour sur cette fonctionnalité qui ne marche plus.
Si tu arrives à dépanner...

**Comment by jubonhomme** [comment]
Ça refonctionne !

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4c046c34-ed68-4d8c-bf50-f4be7f955aff)

**Comment by louis-ev** [comment]
Euh attends ça devrait pas faire ça :

<img width="524" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/71ffce4f-7655-4fff-aab8-b205431bf182">

<img width="627" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/1984e797-8b52-4d2e-a224-cf088d711564">

Normalement ?

**Comment by jubonhomme** [comment]
Alors oui pour le deuxième exemple dans un page à page mais pour le premier sous firefox le bloc est au dessus

**Comment by louis-ev** [comment]
Je viens de tester dans test10, et ça s'affiche bien comme dans mon message sous firefox. Tu peux me confirmer que ça le fait aussi chez toi ?

**Comment by jubonhomme** [comment]
Dans un page à page dans dodoc sur ma machine

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0c1b7eb7-8423-4667-aaaf-35dbe13e0f3f)

dans un récit sur firefox

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/f4508876-cae8-4585-9ef4-b904b79cd0a0)


et dans chrome

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/fb82a474-0bcc-4b84-8025-c91e5cd2bf1e)

**Comment by jubonhomme** [comment]
ça m'a fait trouvé un autre bug lié ?
Quand je fais une sélection des mots à la souris si je suis en plein écran ça ferme l'édition du bloc de texte
voir ici à la 21s
https://test10.dodoc.fr/+espace/hors-saison?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100,%22focus%22%3A%22video-1699568648365-jrd.webm.meta.txt%22%7D%5D

**Comment by louis-ev** [comment]
J'ai bien pas ça sur ma machine : 
<img width="673" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/cf43275d-fbf7-4781-833a-e874c0fc4f2c">

Un soucis de CSS ? Tu peux retester maintenant ?

**Comment by jubonhomme** [comment]
J'ai ça maintenant sur ma machine
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/634edd0c-e4f6-4768-963b-faee5d07bb37)


Mais si je passe sur le navigateur en partage j'ai ça 


![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/57d6ecb2-8e84-4802-9597-c285c0a8723b)

**Comment by louis-ev** [comment]
Je ne trouve aucune explication… Tu es certain d'utiliser une version qui a moins de 2 jours ? Si oui alors si ça gêne pas d'un point de vue fonctionnalité je propose de reporter à 10.1

**Comment by jubonhomme** [comment]
Oui j'ai mis à jour encore ce matin.
Mais ça ne pose pas de problème d'utilisation, c'est juste le champ à remplir qui n'est pas exactement au même endroit mais rien de gênant.

**Comment by jubonhomme** [comment]
ça fonctionne bien
Je ferme ici et on ouvre à nouveau si besoin de simplifier les interfaces suivant les retours
