### ISSUE TITLE
Bug fenêtre CSS page à page

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#536]
Si on ouvre la fenêtre CSS pour ajouter une mise en forme dans page à page, les touches flèches gauches droites et supp ont une action sur le média mais pas dans sur le texte du CSS. 

Exemple : 

j'ouvre le CSS
je tape : 
`border-radius: 200px;`
et je veux supprimer le 200px pour mettre 100px
je sélectionne 200 et si je clique sur la touche "suppr" il me demande si je veux supprimer le média.

Pour le moment je sélectionne 200 et je tape directement 100... mais c'est pas très intuitif.

Idem si on utilise les flèches G D pour se déplacer dans le texte du CSS ça déplace le média

**Comment by louis-ev** [comment]
Corrigé hier, à venir dans dodoc 9.0.18-dev donc

**Comment by louis-ev** [comment]
Je ferme.
