### ISSUE TITLE
Bug Java

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#538]
Message d'erreur sur une installation de dodoc 9.017 dev sur windws 10
![thumbnail_IMG_8186](https://user-images.githubusercontent.com/29262866/95997372-016de680-0e34-11eb-9646-ce15b221b1b5.jpg)

**Comment by louis-ev** [comment]
Peux-tu tenter une installation de la version stable de do•doc ? Pas de soucis ?
Je ne me souviens pas avoir changé le code serveur qui gère les ports au démarrage de do•doc… normalement il prend un port non occupé.

**Comment by jubonhomme** [comment]
La version 9.017 a fini par passer mais j'ai du réinstaller dodoc sur tous les postes windows qui ont "subi" les dernières grosses mises à jour windows 10. 
Je pense que ça vient de windows 10 et ses mises à jour inter---minables.
Sur mon poste en windows 10 la version 9.017 s'est installée mais j'ai eu ensuite des problèmes de caméra qui n'affichait plus rien dans le mode "capture".... et l'outil texte qui n'était plus synchrone avec une tablette ... et puis j'ai craqué et redémarré sous linux pour régler tout ça ;)
Mais je refais des tests demain sur une autre machine.

**Comment by jubonhomme** [comment]
J'ai refait des tests sur 3 machines sous win10....  acune version de dodoc (9.017 / 9.02 / 8.2.5) n'arrivent à lancer la capture. 

Je pense que ça vient bien de la mise à jour de win10 ! 
Les versions antérieures de dodoc ne posaient pas de soucis mais elles ont disparues à la mise à jour importante de win10. 
Je dois réinstaller dodoc mais ça plante avec le message d'erreur ci dessus, puis ça passe quand même mais la capture ne fonctionne pas.
Sur linux aucun soucis.

**Comment by jubonhomme** [comment]
Test de dodoc 9.0.17 sur une autre machine win 10 version 1903 :
Pas de message d'erreur à l'installation mais toujours pas d'accès à la caméra (qui fonctionne sans problème avec jitsi)
La LED s'allume mais pas d'image ... voir une vidéo ici : 
https://test.dodoc.fr/test-acces/media/video-20201018-113939-sak*webm*txt?display=standalone

**Comment by louis-ev** [comment]
Je suspecte un soucis d'implémentation pour Électron. Je vais faire la mise à jour d'Electron bientôt pour la v9 de toute façon, en espérant que ça résolve un peu tout en même temps...

**Comment by jubonhomme** [comment]
Je viens d'essayer une nouvelle possibilité : la caméra virtuelle d'OBS studio passe très bien.... comme pour la capture d'écran.
Si ça peut t'aider à identifier le problème.

**Comment by louis-ev** [comment]
Ha c’est trop bête de devoir complexifier comme ça…
Si je te sors une version windows avec le dernier electron rapido, tu auras le temps de tester ?

**Comment by jubonhomme** [comment]
Oui je peux tester rapido... 
cf mail perso
Merci !

**Comment by louis-ev** [comment]
Non, c’est relativement rapide si y a pas de bugs. Par contre en mettant à jour electron il y a souvent des suprises + changement de version de node — c’est plus long.

**Comment by louis-ev** [comment]
Où en est-on là dessus au fait @jubonhomme ?

**Comment by louis-ev** [comment]
Je ferme, n'hésite pas à rouvrir si besoin !
