### ISSUE TITLE
Bug import de médias 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#539]
Lors de l'import de médias, si le réseau est instable et que le serveur se déconnecte un temps, ça arrête et bloque toutes les importations d'images.
Il faudrait trouver un moyen pour que lorsque la connexion est de nouveau active, l'import des médias reprennent là où il en est.
J'ai testé: ça ne change rien si on est auteur ou pas, si le dossier est protégé par un mot de passe ou pas, ça semble vraiment dû à une mauvaise connexion internet

**Comment by sarahgarcin** [comment]
Je reviens sur ce que j'ai dit avec un réseau stable et dossier protégé par un mot de passe tout en étant auteur, ça bug quand même. Si j'enlève le mot de passe du dossier, ça fonctionne par contre

**Comment by louis-ev** [comment]
Le soucis est probablement lié à la manière de valider/interdire l'upload : j'envoie l'identifiant socketio avec les fichiers, mais si tu te déco/reco ton identifiant et autorisation peut donc changer.
A la place il faudrait un genre de token js, j'ai pas fouillé mais l'identifiant socketio devrait pas servir à ça.
Quelque chose comme : si un utilisateur est autorisé à éditer un contenu alors il reçoit (en code, invisible) un mot de passe génèré qui correspond à une autorisation de modification du dossier et de son contenu.

**Comment by louis-ev** [comment]
Je désactive la vérification qui pose problème. Elle concerne le dépot de médias dans les projets.
Il faudrait revoir le système d’authentification pour qu’il ne repose pas sur socketio mais utilise un token JS.

Si quelqu’un a des pistes là-dessus je veux bien de l’aide à ce sujet :)
