### ISSUE TITLE
Bug export web sur PC

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#542]
À l'export web d'un document page à page, l'index.html est vide.
Bug repéré sur PC (Firefox ? Edge ?)

Testé sur OSX, Firefox et ça fonctionne

**Comment by jubonhomme** [comment]
Tester sur Ubuntu 20.04 et dodoc 9.0.17 tout fonctionne bien aussi

**Comment by louis-ev** [comment]
@sarahgarcin si tu parles du bug sur le PC d'une participante du workshop, c'est parce qu'elle ouvrait le fichier index.html alors qu'elle avait pas décompressé le zip
