### ISSUE TITLE
Suggestion : Affichage d'une grille dans l'outil capture

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#543]
Je remonte une demande collective suite à la session d'atelier sur le Stopmotion avec des enseignants.

Avoir une grille à afficher ou masquer dans l'interface de la capture Photo / vidéo / animation pour avoir un repère visuel pour le cadrage et horizontal
![image](https://user-images.githubusercontent.com/29262866/96643521-f7625100-1327-11eb-9b89-3959a1a61599.png)

Avec un bouton glissière "grille" pour afficher et masquer dans le bandeau de gauche
Un peu comme pour le page à page mais pour avoir un repère en 3X3 ou 

Ou autre proposition :  
un picto de grille à cliquer : départ Aucune grille > un clic > grille 3X3 > un clic > grille quadrillage comme page à page> un clic > aucune grille > etc en boucle

**Comment by louis-ev** [comment]
Bonne idée oui ! Et j'aime bien l'idée du clic qui bascule entre des modes de grille. Valable dans tous les modes visuels donc !

**Comment by jubonhomme** [comment]
La version de la grille 3X3 fonctionne très bien pour les modes capture Photo / vidéo / Animation et s'adapte maintenant bien à la taille de l'image.

Par contre sur une tablette ou smartphone, la grille ne suit pas la rotation de l'écran si passage de vertical à horizontal ou inverse.
Il faut sortir de la capture faire la rotation de la tablette et revenir dans la capture pour que ce soit pris en compte.
Idem si c'est en utilisant droidcam ou distantflux... la rotation de l'image n'est pas suivit par la grille sur l'ordi avec l'interface principale, la grille reste dans sa première configuration.

**Comment by jubonhomme** [comment]
Je propose de fermer cette issue sur l'ajout d'une grille.

J'ouvrirai une nouvelle si besoin pour la rotation sur mobile... mais ce n'est pas forcément trop gênant, la plupart du temps la tablette est en format horizontal et sur un support.

A fermer ?

**Comment by jubonhomme** [comment]
On ferme celle ci ?

**Comment by jubonhomme** [comment]
Je propose de fermer celle ci et d'en ouvrir une autre si besoin pour la rotation sur mobile

A fermer
