### ISSUE TITLE
Veille sécurité

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#544]
Bonjour,

petite news NPM sécurité je ne savais pas ou l'inscrire

 https://securite.developpez.com/actu/309772/Quatre-packages-npm-trouves-en-train-d-ouvrir-des-shells-sur-des-systemes-Linux-et-Windows-Tout-ordinateur-avec-l-un-de-ces-packages-installes-doit-etre-considere-comme-totalement-compromis/

**Comment by louis-ev** [comment]
Aucun de ces paquets n’est utilisé par do•doc, l’objectif est d’utiliser surtout des dépendances éprouvée et réputée. Il y a toujours un risque néanmoins, donc si jamais tu vois passer à nouveau des infos de ce type n’hésite pas à le signaler ici :)
