### ISSUE TITLE
Bloce dessin

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#545]
BonjourL
Le partage en ligne donne ce résultat. est-ce normal ? est-t il possible de modifier l'épaisseur du dessin libre et d'avoir un affichage en mode récit ?
https://do.doc.pixnwave.fr/_publications/bloc-dessin-n-5/
bien à vous

**Comment by louis-ev** [comment]
> Le partage en ligne donne ce résultat. est-ce normal ? 

C’est un bug, je regarderai

>est-t il possible de modifier l'épaisseur du dessin libre

Oui, tu peux créer une issue spécifique ou voir si ça rejoint une autre ?

> un affichage en mode récit ?

Tu parles de la version simplifiée ou d’autre chose ?

**Comment by PixnWave** [comment]
je n'avais pas vu qu'il était possible de créer une image avec bloc dessin et de l'exporter vers média puis de l'importer dans un récit...

**Comment by jubonhomme** [comment]
@PixnWave  on peut aussi exporter une seule page en format png d'une recette page à page : créer / type image (une seule page)
... ça fonctionne exactement comme dessin (formes / flèches / médias) mais sans les dessins libres

**Comment by jubonhomme** [comment]
Tout fonctionne pour l'épaisseur du trait de dessin libre
https://test.dodoc.fr/_publications/selection/

A fermer

**Comment by louis-ev** [comment]
Ici par exemple ? https://do.doc.pixnwave.fr/_publications/bloc-dessin-n-5/
Oui c’est lié au système de navigation et zoom…
C’est assez laborieux tout ça, le HTML est pas fait pour ça et du coup le code est bien bien complex…

**Comment by jubonhomme** [comment]
Oui, comme sur test.dodoc aussi : https://test.dodoc.fr/_publications/selection/

Même en réduisant le zoom à 30% sur firefox ou chome cette barre apparaît quand même
![image](https://user-images.githubusercontent.com/29262866/98539015-ed2ed500-228b-11eb-8e75-cee7c6f637ac.png)

**Comment by PixnWave** [comment]
Attention il y avait un trait dans le dessin...

**Comment by louis-ev** [comment]
A priori résolu avec les derniers changements, à rouvrir si besoin.
