### ISSUE TITLE
Suggestion d'améliorations de la fenêtre "Auteur"

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#546]
1) Sous le menu déroulant "Rôles", précisez la différence entre chaque rôle
2) Par défaut, replier le champ email qui est optionnel (= gain de place = plus clair)

**Comment by jubonhomme** [comment]
Les comptes auteurs sont maintenant tous contributeurs.
Les rôles sont définis dans chaque espace / projet

Un auteur peut être référent ou contributeur, les rôles sont rappelés au niveau des espaces et des projets

L'adresse mail peut-être obligatoire ou optionnelle, le réglage se fait au niveau de la plateforme dodoc par l'Admin.
C'est identifié par un point rouge si le champ est obligatoire.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/37320ef4-1718-461c-89c0-c25908a9b3c3)
