### ISSUE TITLE
Bug lors de la création d'un document page à page de type modèle

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#548]
![Screen Shot 2020-11-03 at 13 00 28](https://user-images.githubusercontent.com/4678296/97993017-ce3fc700-1de3-11eb-8dc9-a73fea8dad40.png)
Si dans un document modèle on ajoute un média présent dans un projet, le média n'apparait pas lors de la génération d'un document réponse

**Comment by louis-ev** [comment]
Tu es sure que ce projet "test" existe bien ? je le vois pas ce do•doc… En local je n’ai pas le soucis que tu décris en tout cas.

**Comment by jubonhomme** [comment]
Oui j'ai le même Bug sur la version de dodoc 9.0.16 sur serveur (Canopé)
Les médias ne s'affichent pas dans le document à remplir mais par contre ils sont bien présents dans la version finale une fois que l'on verrouille et publie le page à page

Mais ça fonctionne bien sur la version test.dodoc.fr ... 

![image](https://user-images.githubusercontent.com/29262866/98047872-fc95c480-1e2c-11eb-9968-05bc6436396b.png)


Un autre petit détail mais dans la recette page à page le bouton indique "VERROUILLEZ ET PUBLIEZ VOTRE RECIT"

Peut-être remplacer "RECIT" par "DOCUMENT"

![image](https://user-images.githubusercontent.com/29262866/98048328-bb51e480-1e2d-11eb-8118-9c8fca496ebf.png)

**Comment by sarahgarcin** [comment]
Je viens de refaire un test complet sur dodoc installé sur le serveur d'ecriredanslaville = 
do•doc version 9.0.18-dev 

Les médias importés depuis un projet ne s'affiche pas (et je suis sûre qu'ils existent) par contre les médias importés directement dans le document s'affiche bien (cf capture d'écran).
Pour ma part lorsque je verrouille et publie le document, ça ne fonctionne toujours pas j'ai le même rendu.

![Screen Shot 2020-11-04 at 08 54 52](https://user-images.githubusercontent.com/4678296/98084352-f8dd5e80-1e7b-11eb-8fb1-226b5eec314d.png)

**Comment by louis-ev** [comment]
Je comprend pas : y a pas de projet intitulé "test" dans ce do•doc, ils viennent d’où ?

Si je met une image du projet "Exemple de projet" il s’affiche bien
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1948417/98156370-0294af80-1ed8-11eb-872a-cc36e5a63676.png">

**Comment by jubonhomme** [comment]
J'ai refait des tests sur la version 9.0.25
Les images (des projets ou ajoutés en direct) s'affichent correctement dans le documents à remplir.

A fermer ?
