### ISSUE TITLE
Mini bug d'affichage lors du partage d'un document type modèle

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#549]
![Screen Shot 2020-11-03 at 13 04 13](https://user-images.githubusercontent.com/4678296/97993322-32fb2180-1de4-11eb-979e-99fcc84e494a.png)

Lors de la création d'un lien de partage d'un document page à page de type modèle, le bouton cette recette est un modèle reste visible.

**Comment by louis-ev** [comment]
Très juste ! Je corrige.

**Comment by louis-ev** [comment]
(c’est plus un oubli qu’un bug :D )

Corrigé !

**Comment by sarahgarcin** [comment]
Tu as mis en ligne sur test.dodoc.fr ? 
Je ne vois pas la modif !

**Comment by louis-ev** [comment]
Non, je finis une tournée de maj et je met à jour :)
