### ISSUE TITLE
Dans le chat, les deux fenêtres ne se supperposent pas

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#550]
![Screen Shot 2020-11-03 at 13 15 10](https://user-images.githubusercontent.com/4678296/97993461-65a51a00-1de4-11eb-8598-95d85bcf55c6.png)
Firefox, écran 13 pouces, 1280 x 800px

**Comment by louis-ev** [comment]
Oui c’est voulu :) Gênant ?

**Comment by sarahgarcin** [comment]
oui sur mon petit écran c'est pas hyper ergonomique !

**Comment by louis-ev** [comment]
Mon idée c’etait de permettre de garder un oeil sur les autres discussions pour voir si y avait des notifs.

C’est vrai qu’en virant la marge on lit mieux 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/1948417/98045077-331d1080-1e28-11eb-9cea-e7d767ee501c.png">

mais on peut plus garder un oeil sur les autres discussions du coup… dommage non ?

**Comment by jubonhomme** [comment]
si il y a les notifications en haut c'est moins gênant non ?
On est rarement dans plusieurs fil de discussions à la fois

**Comment by sarahgarcin** [comment]
je suis totalement d'accord avec @jubonhomme

**Comment by louis-ev** [comment]
Ok je modifie ça.
