### ISSUE TITLE
notifications par mail si nouveau chat 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#551]
Avec possibilité de les désactiver

**Comment by louis-ev** [comment]
Il y en a déjà ici : 

<img width="251" alt="image" src="https://user-images.githubusercontent.com/1948417/98041794-cc492880-1e22-11eb-911a-e5ccf6d97c7a.png">

et là 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/1948417/98041799-ce12ec00-1e22-11eb-91ef-750f3e675521.png">

Il y en avait en plus une qui arrivait (en bas à gauche) pour chaque message posté dans un channel, en live, mais c’était vite gênant. Tu pensais à quoi ?

**Comment by sarahgarcin** [comment]
oui je pensais à en bas à gauche en live, mais effectivement ça devait être gênant.
c'est juste qu'en haut on ne comprend pas bien que c'est lié au chat (remarque de joël)

**Comment by jubonhomme** [comment]
Et si le rond rouge en haut reprenait  la forme de bulle du chat ?

**Comment by louis-ev** [comment]
Bonne idée ! Comme ça ? Dans la bulle ça fait un peu serré (surtout si on a 10 ou 100 notifications).

<img width="610" alt="image" src="https://user-images.githubusercontent.com/1948417/98113603-35bd4b80-1ea4-11eb-85dd-1eedd3110df2.png">

**Comment by sarahgarcin** [comment]
Oui c'est super ça !

**Comment by jubonhomme** [comment]
J'ai jamais eu autant de notifications ;)
mais oui c'est encore mieux comme ça... et c'est raccord avec celui de gauche avec le picto auteurs connectés : 1 compteur + picto

**Comment by jubonhomme** [comment]
Je reviens sur la question des notifications, des collègues m'ont fait la remarque hier.

Peut-on imaginer recevoir une notification par mail si ce champ est renseigné dans la fiche auteur ? 
Idem pour des notifications lors d'ajout ou modification dans un projet ?

**Comment by louis-ev** [comment]
On peut imaginer oui. Ajouter la brique "mail" (notifications, récupération mdp ou autre) n’est pas une mince affaire, c’est un chantier conséquent… pas sur que ça vienne dans la v9 vu tout ce qu’il y a déjà à faire, sauf si c’est raccord avec un projet en cours (mais pour l’instant c’est pas trop le cas).

**Comment by jubonhomme** [comment]
Oui c'est pas la priorité, pour l'instant on a décidé de faire un message par mail ou réseau interne (teams) pour notifier un besoin d'aller sur dodoc.
Mais ça aurait un intérêt je pense...
A garder sous le coude
