### ISSUE TITLE
Supprimer un document archivé (notamment un modèle)

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#553]
Lorsqu'on verrouille et publie un récit, cela crée un nouveau document dérivé du modèle qui est considéré comme archivé et qui ne peut donc pas être supprimé. On en peut pas non plus supprimer le modèle utilisé pour ce document. Ça me semble un peu problématique. 
Quel système pourrait-on mettre en place pour donner la possibilité de supprimer à la fois les documents archivés et le modèle lié, sans qu'un esprit malicieux d'élève par exemple puisse le faire ?

(Là je suis dans le cas où j'ai fait des tests et je me retrouve avec plein de documents que je ne peux pas supprimer…)

**Comment by louis-ev** [comment]
Être admin ? Seul un admin peut interagir avec un doc verrouillé.

**Comment by jubonhomme** [comment]
Question bête : pourquoi un récit ou un page à page qui suit un modèle est archivé / verrouillé  et pas simplement Publié comme on le fait avec une recette classique ?
Si c'était simplement publié avec une règle du type 'seul les auteurs peuvent modifier' ça règle le problème non ?

De toute façon si un Auteur modifie la recette modèle, toutes les recettes suivant ce modèle sont modifiées... même si elles sont déjà publiées et verrouillées. Donc ça n'est pas vraiment figé et non modifiable. 
C'est surtout l'Auteur qui suit le modèle qui est bloqué et non sa publication qui continue de se modifier suivant le modèle.

Mais j'imagine qu'il y avait une idée précise pour vouloir figer les publications... 
c'est pour utiliser récit comme un questionnaire ou les personnes ne peuvent répondre qu'une fois et ne pas revenir dessus ?

**Comment by louis-ev** [comment]
>  c'est pour utiliser récit comme un questionnaire ou les personnes ne peuvent répondre qu'une fois et ne pas revenir dessus ?

Exact. Une manière de valider un état à un instant T.
Dans une recette classique y a pas réellement de statut "publié" pour cette raison. Je vois pas bien le soucis en fait…

**Comment by jubonhomme** [comment]
Si le but est de l'utiliser comme un retour de questionnaire alors l'auteur de la recette modèle devrait pouvoir créer des pdf à partir des réponses (recette qui suivent ce modèle) hors c'est verrouillé pour lui. Il ne peut que les consulter dans dodoc sans pouvoir les exporter, ni les supprimer.... je ne trouve pas ça logique.
Si je fais un questionnaire, une fois que les personnes ont répondu c'est moi qui gère les réponses (export / suppression /...) et pas les répondants chacun de son côté avec sa réponse.

**Comment by jubonhomme** [comment]
L'archivage ne me semble plus possible avec la version 11 de dodoc.

A fermer ?
