### ISSUE TITLE
Bug - Auteur Récit - Page à page qui suit un modèle

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#554]
Si on clique sur se déconnecter dans le bandeau d'une recette récit qui suit un modèle (idem pour le page à page)
![image](https://user-images.githubusercontent.com/29262866/98120705-96ea1c80-1eae-11eb-8c47-ccc57b704d1a.png)

le bandeau du haut devient vide 
![image](https://user-images.githubusercontent.com/29262866/98120809-bc772600-1eae-11eb-8db1-d6e280b225da.png)

...et le récit n'as plus d'auteur même une fois validé

![image](https://user-images.githubusercontent.com/29262866/98120937-e92b3d80-1eae-11eb-8b67-82572004071c.png)

Si on recommence une nouvelle recette à partir du lien du modèle on n'est toujours pas identifié dans la page qui s'ouvre alors qu'on l'était dans l'instance principale.

cf vidéo
https://test.dodoc.fr/test-dodoc-9-1/media/bug-recit-auteur*webm*txt?display=standalone

Il faut s'identifier à nouveau à partir de la racine de dodoc pour que ça refonctionne.

Il faudrait pouvoir se reconnecter à partir du bandeau dans la page récit qui suit un modèle

**Comment by louis-ev** [comment]
En fait quand tu te déconnectes ça créer une nouvelle réponse, non ?

**Comment by jubonhomme** [comment]
Je ferme cette issue, le fonctionnement des modèles de la V10 est sous une autre forme
