### ISSUE TITLE
Effet vidéo

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#557]
es t’il possible d'avoir une boucle vdéo A/R ou boucle ?

**Comment by jubonhomme** [comment]
Tu parles d'une option de lecture en boucle dans le player vidéo ?

![](https://image.flaticon.com/icons/png/512/32/32161.png)

**Comment by PixnWave** [comment]
avant / arrière / avant / arrière

**Comment by PixnWave** [comment]
Oui

**Comment by PixnWave** [comment]
par exemple pour cette vidéo http://www.néguentropie.art/

**Comment by jubonhomme** [comment]
Avec une simple option lecture en boucle on pourrait le faire.
et pour une boucle A/R
recette "effet vidéo" / "effet" inverser le début et la fin   puis  recette "montage vidéo" on colle les 2 et on lit le résultat en boucle simple

**Comment by jubonhomme** [comment]
D'après ce que je comprends ce n'est pas un player mais juste une balise .videocontrols
https://www.w3schools.com/TAgs/tag_video.asp

Donc ça doit sûrement être possible avec l'attribut  <video loop> 
https://www.w3schools.com/TAgs/att_video_loop.asp

Je laisse @louis-ev confirmer et voir si c'est possible pour dodoc.

**Comment by jubonhomme** [comment]
Je pense que ça rejoint aussi #249

**Comment by louis-ev** [comment]
Effectivement faire boucler une vidéo ou la lancer automatiquement au chargement de la page est un attribut à ajouter à une balise vidéo. Ça pourrait être une option réglable dans le doc page à page et le bloc dessin.

Le GIF est bcp moins bien optimisé mais dans le fichier même il peut y avoir l’instruction lui disant de boucler. Si export GIF il y a, où le met-on ? Car si on importe un fichier vidéo qu’on aimerait passer en GIF c’est bizarre de devoir le mettre dans une recette non ? Je me demande si on devrait pas aussi avoir une option pour télécharger des images en version allégées (résolution plus faible).

**Comment by jubonhomme** [comment]
Question : Est-ce que l'attribut "boucler" pourrait-être placer directement dans le menu du lecteur vidéo et être modifiable lors de la lecture (comme VLC par exemple) et non définitif comme une balise dans le code de la page ?
De cette façon un visiteur peut lire une vidéo en boucle même si elle n'est pas définie en boucle par l'auteur et inversement arrêter la lecture en boucle s'il le souhaite.
En tant qu'auteur, on ajoute une vidéo dans un Récit ou une page de page à page et dans le lecteur vidéo on clique sur le bouton boucle.

Pour moi le GIF est une autre question, je l'évoquais ici car la question de départ de @PixnWave est plutôt celle de l'ajout d'un GIF animé sur sa recette récit. 
Si dodoc peut utiliser quelques images depuis animation / montage vidéo / ou image par image pour générer un GIF animé super... mais je pense que c'est différent de la question de lire une vidéo en boucle dans un doc

**Comment by PixnWave** [comment]
Alors moi c'était pour un vidéo dans un document page à page je n'avais pas pensé au gif

**Comment by jubonhomme** [comment]
@PixnWave : l'ajout de GIF est fonctionnel dans un doc page à page comme dans un Récit.
Exemple : https://test.dodoc.fr/_publications/gif/
Ton Gif est ici https://test.dodoc.fr/test-dodoc-9-1/media/neguentropie*gif*txt

Ce que j'ai voulu dire c'est que tout dépend du résultat attendu.
Soit c'est plutôt du type GIF animé ( vidéo très courte ) qui tourne en boucle sur un document et autant mettre un GIF.
L'import d'un gif est déjà possible. Il reste donc à savoir si ça un intérêt de pourvoir générer un GIF à partir d'une recette image par image par exemple (ou recette "Montage" ou Effets Vidéo"... Je pense que cette fonctionnalité pourrait servir.

Mais pour une vidéo plus lourde ça pourrait servir de faire des lectures en boucle... mais ces deux solutions sont distinctes à mon avis

**Comment by jubonhomme** [comment]
Ça y est : la lecture en boucle est dans les options des publications depuis la version 9.018.dev
![image](https://user-images.githubusercontent.com/29262866/101151455-f65c5900-3621-11eb-8198-8aa41e90cba1.png)


A fermer !
