### ISSUE TITLE
Filtre et recherche

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#558]
**filtres pour les médias :** 
- ajout des fichiers .STL ou avoir une recherche directe en tapant le nom de l'extension #467
- ajout d'une case "tout" pour éviter d'avoir toute les cases décocher et pourtant tout voir comme quand tout est coché

Exemple : Donne le même résultat : 44 médias  

![image](https://user-images.githubusercontent.com/29262866/98453529-6af2c380-215a-11eb-86da-38ad12b6743a.png)
![image](https://user-images.githubusercontent.com/29262866/98453520-5282a900-215a-11eb-8583-c9bff90a3019.png)

Proposition : 
 "tout" est coché par défaut et le reste est grisé par exemple, et dès que l'on coche un autre type le "tout" passe en grisé et les autres type sont visible ... si on recoche "tout" les autres repassent en grisé - idem si on ne coche aucun type, tout redevient coché.
Exemple : 
à l'ouverture du filtre
![barre filtre-gris](https://user-images.githubusercontent.com/29262866/98453680-4ac40400-215c-11eb-9631-7c694833dcf6.png)

si un type est coché
![barre filtre-image](https://user-images.githubusercontent.com/29262866/98453681-4c8dc780-215c-11eb-9a31-c9a2a7eb52c3.png)

- Rendre le filtre type de médias identique dans la home de dodoc à celle du filtre média dans les projets
Pour le moment on ne peut choisir qu'un type de média dans la home de dodoc

- Permettre un filtre multiple sur les mots clés #439

**Comment by louis-ev** [comment]
Il y a STL s’il existe des STL à filtrer. Pas le cas chez toi ?

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1948417/98933776-64a97200-24e1-11eb-
8b34-7515532e1cb5.png">

> Rendre le filtre type de médias identique dans la home de dodoc à celle du filtre média dans les projets
Pour le moment on ne peut choisir qu'un type de média dans la home de dodoc

Le filtre de la page d’accueil est + malin que celui des projets : il évolue pour afficher uniquement les sélections qui ont du sens. Exemple si choix d’un auteur :

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1948417/98933936-9f130f00-24e1-11eb-814d-1a03d1c35a36.png">

Pratique car permettant de ne jamais tomber sur des résultats vide (enfin sauf avec le filtre "fav" qui est mal codé).
Je trouve ça très utile, je serai plutôt tenté de rapatrier ça côté projet mais tu as pas l’air convaincu.

Pour le bouton "TOUT" ça parait logique oui :)

**Comment by jubonhomme** [comment]
Oui, pour les STL, c'est parce que j'en avais pas dans le dossier sur lequel j'ai fait la capture.
Et je me suis rendu compte que récemment que c'était dans le filtre " type".

Oui aussi pour que le filtre propose de façon intelligente ce qui existe.
Mais dans le filtre "type" des projets je peux sélectionner plusieurs types à la fois : filtre OU 
Alors que dans le filtre "type" de l'accueil dès que je clique sur un type les autres disparraissent... donc je ne peux pas en sélectionner plusieurs.

Pour garder le meilleur des 2 comme tu proposes : 
Sur l'accueil et dans les projets, le filtre "type" est intelligent et ne propose que les types présents dans le projet et évolue en fonction des autres filtres. Mais on pourrait sélectionner plusieurs "type" 
Dans ton exemple : Je pourrais choisir image et vidéo par exemple
![image](https://user-images.githubusercontent.com/29262866/98938877-dfc25680-24e8-11eb-8889-83da8ba30e9d.png)

Si c'est comme dans "type" accueil, si je coche image tous les autres disparaissent.

Je suis pas sur d'être clair...

**Comment by jubonhomme** [comment]
Je ferme ici car les filtres de la V10 utilisent les métadonnées des projets et n'affichent plus les médias seuls.
