### ISSUE TITLE
La vue tous les médias sur https://test.dodoc.fr/ fait planter do•doc

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#559]

**Comment by louis-ev** [comment]
ai effacé le dossier _thumbs mais ça fait tj planter.
Un média dans un projet qui ferait planter toute l’instance ?

**Comment by louis-ev** [comment]
(évidemment ça le fait pas en local, ça serait pas drôle sinon)

**Comment by jubonhomme** [comment]
Aïe ... peut être ma faute

Je me rappelle d'avoir eu un souci de plantage sur un doc texte ou j'avais coller un iframe pour test
J'essaie de retrouver le bon qui plante

Sorry

**Comment by louis-ev** [comment]
Soucis venant d’un STL de 70mo…
Voir #560 
Je ferme.
