### ISSUE TITLE
Affichage Auteurs dans tuile projet

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#561]
Si on ajoute un certain nombre d'auteurs, la tuile s'aaaaallllllonnnnnnngeeeee.

Je caricature un peu avec un exemple : 
![image](https://user-images.githubusercontent.com/29262866/98680076-300eac80-2361-11eb-9f95-42101b4e6b34.png)

Mais c'est presque le cas sur l'instance de Canopé où certains projets sont modifiables par l'ensemble des médiateurs  et en lecture pour les classes... plus de 20 personnes en modif

Peut être un avoir un affichage des premiers noms seulement pour limiter la taille ? Comme pour l'édition des paramètres du projet 
![image](https://user-images.githubusercontent.com/29262866/98680489-c6db6900-2361-11eb-82bb-ff7021ee8876.png)

**Comment by louis-ev** [comment]
Je vois bien le soucis mais la tuile entière étant clickable, c’est pas simple ! Et en même temps si j’en masque qqun ça peut être gênant.
Pareil sur les mots-clés du coup non ?

**Comment by jubonhomme** [comment]
Exact... je n'avais pas pensé aux mots clés mais c'est pareil...sauf que je ne pense pas qu'on aurait le même cas d'un nombre de mot clé trop important. Mais sur les auteurs comme ça permet de limiter l'accès au dossier c'est déjà le cas, et comme les personnes ont renseigné un nom d'auteur assez long pour certains ça prend de la place.

![image](https://user-images.githubusercontent.com/29262866/98942155-e3a4a780-24ed-11eb-92fb-b0a40b0d8ca3.png)

**Comment by louis-ev** [comment]
Je suis un peu embêté, tant que la tuile entière est clickable j’ai pas de solution simple qui fonctionne dans tous les cas…
Si on affiche que les premiers, il faut absolument avoir un bouton pour les voir en totalité.
@jubonhomme ok pour garder ça pour la v10 ?

**Comment by louis-ev** [comment]
Je reporte, @jubonhomme n’hésite pas à revenir là-dessus avant si ça te parait urgent.

**Comment by jubonhomme** [comment]
Est ce qu'on peut imaginer avoir un bouton auteur dépliable comme pour la création du projet ?
![image](https://user-images.githubusercontent.com/29262866/112336214-2dcc3f80-8cbd-11eb-82d4-4daf4265f7f6.png)
Mais qui serait replié par défaut

Idem pour les mots clés

Du coup les tuiles ont toutes la même dimension

**Comment by jubonhomme** [comment]
C'est fait sur la V10, ça tient sur une seule ligne avec un barre de défilement si besoin.
Merci !
Les noms sont remplacés par les vignettes auteurs avec les deux premières lettres du nom.

Pour les espaces : 

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0bd814de-6f81-4cf3-8839-7cbf3bc34b59)

Et les projets : 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/e6564acc-7a80-45d4-a1a0-8bf3ad127804)
