### ISSUE TITLE
Effet Vidéo pivoter

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#562]
Bonjour,
Est-il possible de ne pas avoir le fond noir lors d'une rotation ?
https://test.dodoc.fr/_publications/document-page-a-page-n-47/

**Comment by jubonhomme** [comment]
Bonjour,
Il faudrait que le format après rotation soit plein cadre. Pour le moment à chaque rotation la vidéo est reprise en plus petit avec la bonne orientation mais reste dans le format d'origine de la vidéo.
Exemple: si la vidéo de départ est en format vertical, la vidéo après rotation sera à l'horizontale mais toujours dans un format verticale. Et si on refait le filtre une deuxième fois la vidéo repasse en verticale mais encore en plus petit...
Je l'ai ajouté à la suite...
https://test.dodoc.fr/_publications/document-page-a-page-n-47/

Dans l'idéal il faudrait juste pivoter la vidéo mais sans la réduire dans l'ancien format.
Une vidéo format vertical devient une vidéo format horizontal.

ça rejoint l'issue #411

**Comment by louis-ev** [comment]
Résolu.
Ça garde la résolution originale, donc l’option "qualité" n’est plus présente dans la fenêtre création : 

<img width="434" alt="image" src="https://user-images.githubusercontent.com/1948417/112193333-141cf080-8c08-11eb-8f94-7b30cddc3e86.png">

![Uploading image.png…]()
