### ISSUE TITLE
nouvelle page de capture

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#563]
Création d’une nouvelle page de capture pour des questions de compatibilité et simplifier la maintenance/reprise du code (le composant actuel fait plus de 2000 lignes en tout !).

À tester sur test.dodoc.fr, ouvrir un projet où vous avez les droits d’édition et cliquer sur **Capturer 2 (bêta)**
<img width="887" alt="image" src="https://user-images.githubusercontent.com/1948417/99110505-c6093800-25ea-11eb-85eb-0de2857095d9.png">

à tester : 
- un bouton "refresh devices" pour recharger les devices connectés (sans avoir à quitter revenir si on branche une webcam entre deux par exemple) et détecter les résolutions dispo.
- le générateur de résolutions disponibles
- le fonctionnement sur un maximum d’appareils : android, iOS, portables, etc.

Merci !

**Comment by louis-ev** [comment]
Test sur iPhone : pas de caméra arrière.

**Comment by jubonhomme** [comment]
Test sur webcam logitech C920 sous firefox 82.0 et  Ubuntu 20.04
Tout fonctionne : 
Bouton Video input 
Bouton Audio input
Scan for ....
Choix de la résolution
Update

![image](https://user-images.githubusercontent.com/29262866/99125991-90257d00-2605-11eb-94b2-ed757dc13c41.png)

**Comment by jubonhomme** [comment]
Test avec Droidcam sous Chromium (Version 86.0.4240.198 (Build officiel) snap (64 bits)) et Ubuntu 20.04

Le premier coup ça fonctionne 
![image](https://user-images.githubusercontent.com/29262866/99126244-0cb85b80-2606-11eb-8844-4d164df6f4db.png)

Et ensuite je n'arrive pas à passer à la webcam dans le choix de la caméra... ça revient toujours sur Droidcam et pourtant le scan for... trouve la bien webcam c920.
Et si je change de résolution sans changer de caméra au niveau du bouton ça passe de l'une à l'autre quand même.
C'est comme si la liste des résolutions prenait les différentes sources et affichait les résolutions des deux en même temps.
 
voir ici https://test.dodoc.fr/capture-beta-test/media/droidcam-test-capture2*webm*txt

**Comment by jubonhomme** [comment]
Test avec Droidcam + webcam C920 sous firefox 82.0 et Ubuntu 20.04 

Note au passage : les cams virtuelles fonctionnent bien sous firefox... bonne nouvelle !

C'est le contraire de Chromium....
Je vérifie avant dans l'ancienne interface tout marche correctement.
Je passe sur la nouvelle beta : 
Les deux apparaissent bien dans les sources (Droidcam + C920)
Mais ça revient toujours sur la webcam quelque soit la résolution choisit.

![image](https://user-images.githubusercontent.com/29262866/99128005-fa402100-2609-11eb-94b9-b024a7dbfe81.png)


Sauf si je débranche la webcam alors je reviens bien sur la Droidcam, comme c'est la seule ça la force en entrée
![image](https://user-images.githubusercontent.com/29262866/99128108-425f4380-260a-11eb-8b83-e20a20e3dc37.png)

**Comment by jubonhomme** [comment]
Test avec Droidcam + webcam C920 + OBS sous Chromium et Ubuntu 20.04

OBS passe aussi ! 

![image](https://user-images.githubusercontent.com/29262866/99128793-0d53f080-260c-11eb-9154-595b7d3632fb.png)

Par contre idem ça mélange les deux sources.
Pour repasser à Droidcam je suis obligé de choisir la résolution et non la source par le bouton "caméra" qui revient sur OBS à chaque fois.

![image](https://user-images.githubusercontent.com/29262866/99128889-52782280-260c-11eb-8619-370c34c0eda5.png)

**Comment by jubonhomme** [comment]
Test avec OBS sous Firefox et Ubuntu 20.04
Firefox ne trouve pas OBS :(

**Comment by jubonhomme** [comment]
Sur un Smartphone android (Lineage OS) 
Les 2 caméras apparaissent dans le liste mais seule la caméra avant fonctionne.

**Comment by paulinegourlet** [comment]
> Sur un Smartphone android (Lineage OS)
> Les 2 caméras apparaissent dans le liste mais seule la caméra avant fonctionne.

Idem pour moi (moi j'ai 4 caméras arrières qui apparaissent (j'ai trois lentilles) et aucune ne marche)

**Comment by paulinegourlet** [comment]
Sur MacBookPro (0S 10.14) > webcam native ok, changement de résolution ok
Seul pb (mineur) > l'image est en miroir.

**Comment by louis-ev** [comment]
Ok, merci pour les retous !
L’idéal est de comparer à l’interface actuelle de do•doc : est-ce que ça marchait avant ?

j’ai ajouté un bouton 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/1948417/99149631-80eb1180-268f-11eb-8d40-b6e20ca8aa88.png">
pour avoir les infos des appareils détectés.

Si vous pouvz copier coller ce que ça vous affiche ça me sera aussi utile :)

**Comment by jubonhomme** [comment]
Pour résumer les tests, ce qui passait avant passe aussi sur la nouvelle interface si on travaille avec une seule source "camera".
Dès qu'il y a plusieurs sources je n'arrive pas à basculer de l'une à l'autre avec le bouton "camera". C'est lui qui pose le plus de problème. 
Dans la liste des résolutions tout se mélange entre les différentes sources.

**Comment by jubonhomme** [comment]
Je reprends le fil ici c'est plus simple et visible par tous.

Les bonnes nouvelles en premier ;)
Je n'ai plus aucun soucis de prise en charge de caméra, sur aucun appareil : tablette (android) / smartphone (android)  / ordi (win10 et ubuntu) et sur tous les navigateurs...même Fennec sur Lineage OS  ;)
Toutes les caméras, même virtuelles passent ! webcam intégré au portable / webcam externe (C920) / droidcam / OBS virtual cam
sur tablette et smartphone caméra avant et arrière.

Je pense avoir essayé tout ce que je pouvais (j'ai pas d'IOS ) et plus rien ne résiste à dodoc !

Bravo !!

L'interface reste toujours aussi simple et efficace que la V1.

Juste quelques remarques pour les écrans de smartphones... si tu arrives à faire des miracles avec le CSS

- l'ancienne interface n'était quasi pas utilisable sur mon smartphone car le bouton déclencheur n'était pas accessible.. sauf en descendant mais du coup l'image était coupé en haut.
![image](https://user-images.githubusercontent.com/29262866/99889855-60a3ef80-2c59-11eb-815f-a5d698964377.png)


![image](https://user-images.githubusercontent.com/29262866/99889860-6c8fb180-2c59-11eb-9576-8bdf2c91a79f.png)


- sur la nouvelle les boutons sont toujours visibles... et on peut toujours déclencher sans problème

![image](https://user-images.githubusercontent.com/29262866/99889885-b4163d80-2c59-11eb-8761-b91d4b4056ae.png)


![image](https://user-images.githubusercontent.com/29262866/99889888-be383c00-2c59-11eb-83bd-0f0992feac10.png)

Mais l'affichage est quand même très réduit, même en passant en plein écran.
Est-ce qu'il serait possible pour les petits écrans de smartphone de nettoyer encore un peu pour gagner de la place, surtout pour le mode paysage.

Si possible quand on rentre de le mode capture : 

- replier le bandeau du haut (ou le rendre transparent comme pour les boutons en dessous) et ne conserver visible que le bouton de sortie de la capture (à gauche) et le bouton de menu (à droite), le bandeau pourrait se déplier ( ou revenir opaque ) si on touche la zone en haut de l'image par exemple.. ou sur le bouton menu. Le bandeau représente presque 1/4 de la hauteur de l'image pour les deux boutons qui se trouvent sur les extrémités. (3 si on compte le bouton "dodoc")

- replier encore les boutons de la marmite et du chat... ils sont plus gros et au dessus des boutons de l'interface de capture, et ils ne sont pas indispensable dans ce mode de capture. Si on peut garder juste un petit bout de couleur vert et rouge et si on passe dans la zone ça se déplie pour faire apparaitre les boutons en entier.

- rendre transparent le bandeau du bas et réduire le bouton de capture à un simple rond (comme sur la V1).
Je préférait les boutons déclencheurs de la V1

Dans la V1 sur smartphone les boutons étaient réduit à un picto lors de la capture en mode vertical ET aussi en mode paysage. Dans la V2 c'est le cas en portrait mais si on passe en paysage les boutons reprennent leur grand format. Je viens de voir que c'est le cas aussi sur l'ordi, si on réduit la fenêtre en hauteur les boutons ne se réduisent pas comme la V1 le fait.

L'idée serait de garder la disposition des blocs pour ne pas casser l'interface, tu m'avais déjà expliqué que ça doit rester la même pour tout les supports et je suis d'accord avec ça. Mais il si c'est possible de modifier un peu les éléments quand on est sur un petit écran ça serait plus confortable. Un peu comme les boutons qui se réduisent en picto seul 
Pour le moment l'interface la plus utilisable sur mon smartphone reste l'option "version ordinateur", la taille des boutons est encore acceptable et c'est plus lisible.

![image](https://user-images.githubusercontent.com/29262866/99890412-2c333200-2c5f-11eb-9c32-3ed4339cfd88.png)

**Comment by jubonhomme** [comment]
Je verrai bien un picto différent pour bien différencier la capture photo et vidéo
comme ceux là ( appli Open camera) qui passent en rouge quand la capture est lancée.
![image](https://user-images.githubusercontent.com/29262866/99890914-78cd3c00-2c64-11eb-8544-427c23c075ea.png)

![image](https://user-images.githubusercontent.com/29262866/99890924-97cbce00-2c64-11eb-9fdc-669686fcaf98.png)

**Comment by louis-ev** [comment]
Hello ! 
grand merci pour ces idées et retours 👍 
Les améliorations d’interface ne sont pas ma priorité, j’essaye d’abord d’arriver à parité avec la version actuelle de la capture pour pouvoir la substituer sans perte :)
Ça sera nettement plus facile de faire des améliorations comme tu évoques avec cette interface et ce code. Youpi :)

**Comment by jubonhomme** [comment]
Nouveaux tests sur ios 14.6 
Avec Safari et Firefox la capture photo / vidéo / son fonctionne

Avec Chrome la capture photo fonctionne, mais le son bloque... du coup la vidéo aussi.
J'ai testé en local et en ligne sur test.dodoc.fr
L'accès au micro est bon je vois le graph à l'enregistrement... mais quand je visualise je n'ai plus rien... le son n'est pas enregistré.
exemple ici : 
https://test.dodoc.fr/bug-montage-video/media/audio-20210601-110516-5wl*wav*txt

**Comment by louis-ev** [comment]
Ha ? Très curieux car c’est le même moteur (celui de Safari) qui affiche l’affichage et les fonctionnalité web sur iOS.
Chrome iOS ne se comporte pas pareil donc, c’est vraiment bizarre.

**Comment by jubonhomme** [comment]
Oui juste pour le son

**Comment by louis-ev** [comment]
Ok. Merci pour le debug.

**Comment by jubonhomme** [comment]
Je pense qu'on peut aussi fermer celle-ci. 
On pourra toujours en ouvrir une nouvelle pour des tests sur la V10 pour ne pas tout mélanger.

**Comment by jubonhomme** [comment]
Tout semble fonctionner sur la V10.
Même l'interface sur petit écran est plus accessible

Je ferme donc ici et on ouvrira d'autres issues en fonction des besoins sur un bug en particulier
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/341e1894-759d-41d0-a0bc-f4950e59e590)
