### ISSUE TITLE
Mode capture Ligne

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#564]
Un petit bug d'affichage : 
Si le "Seuil ligne/luminosité " > 9 l'affichage passe sur deux lignes

![image](https://user-images.githubusercontent.com/29262866/100348893-e3c19e80-2fe7-11eb-987c-600a25de5ce1.png)

Et une densité de lignes trop importante fait figer le mode capture... va jusqu'à planter

**Comment by louis-ev** [comment]
Ok oui, je regarde ça. Merci pour le retour.

**Comment by louis-ev** [comment]
J’ai corrigé / revu les paramètres dispo. À tester :)

**Comment by jubonhomme** [comment]
Les problèmes de plantages semblent réglés.

Deux nouvelles remarques :
Les autres boutons sont un peu trop masqués derrière les lignes et sont peu visibles.
![image](https://user-images.githubusercontent.com/29262866/100654299-e1de3f00-3349-11eb-8ef0-acbfdf528a2b.png)

Le bouton déclencheur est raccordé au retardateur par défaut...

**Comment by jubonhomme** [comment]
Dans le mode ligne (et forme) le volet des réglages est réduit en largeur par rapport aux autres modes de capture (photo / vidéo / son / animation)
![image](https://user-images.githubusercontent.com/29262866/100658473-68e1e600-334f-11eb-9eb6-096701d93715.png)

**Comment by louis-ev** [comment]
Étrange… dans quel navigateur ? sous ubuntu ?

**Comment by jubonhomme** [comment]
Oui sous Firefox sous Ubuntu.
Exact, sous Chrome ça passe bien avec la même taille sur chaque outil

Je vérifierai sous win10 et firefox

**Comment by jubonhomme** [comment]
tout est réglé... boutons, volet, paramètres... 
Je ferme
