### ISSUE TITLE
Sortie d'un enregistrement ou d'une prévisualisation

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#565]
Si on est en cours d'enregistrement  ou dans  la prévisualisation d'une vidéo / un son / une animation 
![image](https://user-images.githubusercontent.com/29262866/100350347-0785e400-2fea-11eb-8af5-19cee66019c6.png)

et que l'on clique sur le bouton "Retour " ou "dodoc" ou "nom du projet" en haut à gauche de l'écran, on sort directement en perdant l'enregistrement.

Il faudrait une pop up d'alerte : "voulez vous sortir de cette capture ? Si oui, vous perdrez l'enregistrement en cours" Rester  Sortir" 

Ou autre solution plus radicale : enlever le bandeau du haut dans le mode capture.. mais on perd l'info du projet dans lequel on est et l'auteur.
Sinon juste désactiver et griser les boutons de gauche... mais pas très cohérent vu la place qu'ils prennent.

**Comment by louis-ev** [comment]
Ajouté ! J’ai bloqué aussi le rechargement de l’onglet si enregistrement en cours ou validation d’un média.
Tu peux tester ? Il ya pas mal de cas de figure (annulation d’une capture, démarrage/arrêt intempestif d’une animation, etc.).
C’est sur https://test.dodoc.fr/

**Comment by jubonhomme** [comment]
Pour la partie capture je pense que tout est bon :+1: 
super pour le rechargement de l'onglet ! Je n'y avais pas pensé.


Par contre je viens de voir qu'il y a le même problème si on passe par "importer" au lieu de "capture" et qu'on lance un upload, on peut cliquer à l'extérieur et sur un autre bouton ... le chargement se fait quand même au final mais en arrière plan, on n'a pas plus d'info sur l'avancement. 
Est-ce qu'il ne serait pas mieux de verrouiller le panneau de chargement et ne pas pouvoir en sortir sans avoir un message comme pour le rechargement de l'onglet ?
Ou de pouvoir revenir sur cette fenêtre ?
![image](https://user-images.githubusercontent.com/29262866/100779572-de5dbd00-3408-11eb-994d-03eb4e07ff85.png)


Qu'en penses-tu ?

**Comment by jubonhomme** [comment]
Reste encore un cas dans la capture :
![image](https://user-images.githubusercontent.com/29262866/101095145-c7ac9700-35bd-11eb-8cfe-ba0123c211ca.png)

Si je génère une vidéo dans "animation" on peut encore voir le bandeau avec le déclencheur / retardateur / time laps et lancer d'autre prise de vue en arrière plan.

Il faudrait masquer ou désactiver ce bandeau du bas comme tu as fait pour ceux du haut
