### ISSUE TITLE
Affichage mot de passe

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#566]
Le picto pour l'affichage des mots de passe varie en fonction de la taille de la boite... une histoire de " c’est la flexbox !" si j'ai bien retenu ;)
flex: none   pour la dernière cellule

![image](https://user-images.githubusercontent.com/29262866/100367093-0365c080-3002-11eb-9bcf-66618ab54a3b.png)

![image](https://user-images.githubusercontent.com/29262866/100367192-255f4300-3002-11eb-973b-4ea88c4572b1.png)

De plus la couleur jaune sur fond gris n'est pas très visible même en grand 
![image](https://user-images.githubusercontent.com/29262866/100367343-60617680-3002-11eb-8636-f694a5e79260.png)

Je pense qu'une version barrée en noir serait plus visible (comme sur firefox par exemple)
![image](https://user-images.githubusercontent.com/29262866/100367621-c3eba400-3002-11eb-9d76-1c79cbbe9ced.png)
![image](https://user-images.githubusercontent.com/29262866/100367653-d36aed00-3002-11eb-9086-dc8a8aac4698.png)

**Comment by louis-ev** [comment]
Un peu la flemme de redessiner un picto, en attendant j’ai fais ça 👍 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/1948417/100457840-08d70f80-30c3-11eb-9e07-34025bb1b2cd.png">

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1948417/100457838-07a5e280-30c3-11eb-8090-9c17179702d0.png">

mieux ?

**Comment by jubonhomme** [comment]
Parfait !

**Comment by jubonhomme** [comment]
Un dernier détail : 
Le texte qui s'affiche au survol du bouton est toujours "révéler le mot de passe".
Est ce qu'il est possible d'avoir les 2 propositions en fonction du contexte ? ou bien c'est 1 bouton = 1 info bulle ?

- bouton noir = révéler le mot de passe 
- bouton blanc = masquer le mot de passe

**Comment by louis-ev** [comment]
À venir

**Comment by jubonhomme** [comment]
Fait dans la version 9.019
