### ISSUE TITLE
Bouton déclencheur et retardateur

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#568]
J'ouvre une nouvelle issue

Le bouton déclencheur est raccordé au retardateur par défaut...

Edit : En fait c'est le cas de tous les modes : Photo / vidéo /son ... si on déclenche le retardateur est mis par défaut

Edit 2 : Si on lance une photo avec retardateur et que l'on passe au mode vidéo dans l'intervalle de temps du retardateur ça déclenche la vidéo ;)

Idem pour le passage photo / animation

Il faudrait enlever les boutons du haut lorsque le décompte du retardateur est enclenché, comme lorsqu'on lance une vidéo ou un son, les boutons disparaissent.

**Comment by louis-ev** [comment]
> Le bouton déclencheur est raccordé au retardateur par défaut...

Haha oui j’ai oublié un check ! Corrigé :)

> Edit 2 : Si on lance une photo avec retardateur et que l'on passe au mode vidéo dans l'intervalle de temps du retardateur ça déclenche la vidéo ;)

Je bloque le changement de mode, et j’ajoute un bouton pour annuler le retardateur ! Merci pour les retours.

**Comment by jubonhomme** [comment]
Corrigé !
Je ferme
