### ISSUE TITLE
Créer un lien direct pour les dossiers

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#575]
Les dossiers n'ont pas d'URL directe... et donc pas de code QR associé.

Exemple : Le dossier FÉE sur https://test.dodoc.fr/
![image](https://user-images.githubusercontent.com/29262866/104138328-b36d6e00-53a3-11eb-8ae2-f5c3ce63fbfe.png)

L'URL est celle de la racine https://test.dodoc.fr/

Est-ce qu'il est possible d'avoir une URL du type https://test.dodoc.fr/FEE ?
Et que le bouton du code QR affiche ce lien direct ?

URL = adresse_racine/nom_dossier

C'est une métadonnée des projets mais j'imagine que la requête pour les afficher pourrait servir à construire une url.

On pourrait ainsi transmettre un lien direct vers un dossier et non pas uniquement à la racine ou pour un projet.

ça pourrait être très utile sur des dodoc avec un grand nombre de projets / dossiers afin de communiquer ce lien précis, un peu comme si c'était une instance de dodoc particulière. 
Exemple : Je crée le dossier FÉE et je range tout mes projets dans ce dossier et je communique le lien vers ce dossier 
... les personnes arrivent directement dans mon dossier et voient l'ensemble des projets du dossier mais pas directement tous ceux du home (racine de dodoc) ou un seul en particulier

Un avis ??

**Comment by louis-ev** [comment]
> Est-ce qu'il est possible d'avoir une URL du type https://test.dodoc.fr/FEE ?
> Et que le bouton du code QR affiche ce lien direct ?

Techniquement non, `/FEE` voudrait dire qu’il existe un projet qui s’appelle FEE, ce qui n’est pas le cas.

Par contre on peut imaginer `/?folder=FEE` ou un truc comme ça.
Je regarde.

**Comment by jubonhomme** [comment]
> Par contre on peut imaginer /?folder=FEE ou un truc comme ça.
Oui exact, c'est pas le nom mais la recherche... mais au moins il y a une URL à communiquer qui ouvre directement le dossier.
Ce serait parfait !

**Comment by louis-ev** [comment]
Implémenté ! 
https://test.dodoc.fr/?folder=THE%20DO%E2%80%A2DOC%20FILE

**Comment by jubonhomme** [comment]
et en plus avec le code QR qui va avec ;) !!
Juste génial comme toujours

Je ferme !
