### ISSUE TITLE
Affichage réduit - Liste des animations

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#577]
Si on fait un grand nombre de photos pour une animation (c'est souvent le cas pour du stopmotion ou un time lapse) la liste des animations affiche toutes les images de la première et les autres se retrouvent loin derrière, même très très loin ;)
![image](https://user-images.githubusercontent.com/29262866/104778155-36643f00-577d-11eb-876b-dc85c8a7c574.png)

Est-ce qu'il serait possible d'afficher uniquement les deux premières lignes (=8 photos) pour avoir une sorte d’aperçu de la séquence ? Comme il y a le nombre de photos indiquées juste au dessus et que ça s'ouvre très vite si on charge l'animation, je pense que ça serait plus lisible si on voyait l'ensemble des animations avec uniquement les 8 premières images de chaque.
pour se rapprocher de cet affichage :
![image](https://user-images.githubusercontent.com/29262866/104778566-dde17180-577d-11eb-9baa-1d1cb6fc00a1.png)

Qu'en penses-tu ?

**Comment by louis-ev** [comment]
Oui très bonne idée ! C’est pas très lisible en l’état.

J’ai revu et je propose la disposition suivante : 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/1948417/105505298-15de3c80-5cc9-11eb-843a-fe2a923d6509.png">

Beaucoup plus lisible et simple je trouve, qu’en penses-tu ?

J’ai préféré afficher la première image en grand. On peut imaginer avoir un petit caroussel simple (flèche gauche/flèche droite) pour consulter les images 2, 3, 4 etc. si on a besoin avant de sélectionner. Mais pas sur de l’utilité, ça vaut le coup de développer ça ?

**Comment by jubonhomme** [comment]
Oui super !
Le carrousel n'est à mon avis pas nécessaire, en tout cas pas interactif.
Par contre avoir juste un visuel de carrousel pour comprendre que c'est bien une série d'images...un truc comme ça avec la première image sur le dessus en visuel

<img width="183" alt="picto_vlog" src="https://user-images.githubusercontent.com/29262866/105512065-efbc9a80-5cd0-11eb-8f4d-b2c11b97f00a.png">

**Comment by jubonhomme** [comment]
Pour l'avoir utilisé encore aujourd'hui, je pense qu'il ne faut pas surcharger ce volet 'liste des animations" avec des boutons gauche / droite. On voit l'image, la date avec le nombre de photos... c'est suffisant je trouve pour identifier une animation. La suite peut très bien se faire justement dans l'interface de l'animation pour passer les images, le temps de chargement est assez rapide.
Un clic on ouvre l'animation en grand et si au pire c'est pas la bonne on referme en deux clics.

Par contre ça pourrait être utile de se déplacer dans un séquence d'images chargées avec les flèches gauche / droite. Pour l'instant seul le clic sur une image fonctionne
![image](https://user-images.githubusercontent.com/29262866/113209427-5af78f80-9273-11eb-8efa-e3bff1adb0fe.png)



Et si l'image dans la liste des animations pouvait être aussi cliquable comme le bouton "charger" pour ouvrir l'animation ça pourrait simplifier l'usage.
