### ISSUE TITLE
Bug recette "Effets vidéo" sur V 9.0.23 serveur

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#581]
Sur la version 9.0.23 sur serveur (test.dodoc.fr et Canopé) la recette "effets vidéo" plante

![image](https://user-images.githubusercontent.com/29262866/106518681-8b70b680-64da-11eb-9d90-c0c617084ec9.png)

**Comment by jubonhomme** [comment]
C'est corrigé sur la version 9.0.24 on dirait bien...
Je te laisse confirmer et fermer

**Comment by louis-ev** [comment]
Indeed
