### ISSUE TITLE
Texte <code>

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#583]
Bonjour, je constate un fond noir lorsque j’insère du code dans un bloc texte que j'arrive pas à supprimer.

https://do.doc.pixnwave.fr/_publications/projection-buckminster-fuller/

**Comment by jubonhomme** [comment]
ça n'est pas plutôt à cause d'un fond transparent ?
J'ai déjà eu le cas sur des SVG avec un fond transparent
Exemple avec celui ci : https://test.dodoc.fr/presentation-do-doc/media/module-engrenage*svg*txt

La vignette s'affiche correctement car en png ou en jpg je pense, mais le svg est sur fond gris foncé.

**Comment by PixnWave** [comment]
non voici la source https://observablehq.com/@fil/triangular-tiling-of-icosahedron?oetm_referrer=https%3A%2F%2Fdo.doc.pixnwave.fr%2F_publications%2Fprojection-buckminster-fuller%2F&oetm_route=%2F%40fil%2Ftriangular-tiling-of-icosahedron

**Comment by jubonhomme** [comment]
Oui, j'ai suivi le lien en bas de l'animation... j'ai souvent utilisé la projection de Fuller avec les élèves... j'ai pas pu m'empêcher de suivre ton lien. Je découvre en même temps ce site https://observablehq.com/ .. Merci pour cette découverte ;)

Pour ce qui est du fond je pense que c'est quand même à cause d'une gestion différente de la transparence du svg sur dodoc.
Il ne doit pas y avoir d'ajout de fond blanc par défaut.

@louis-ev a sûrement une explication.

**Comment by PixnWave** [comment]
je travail a partir du travail de Philippe Rivière qui fait partie de la coop Artéfatcs https://illisible.net/philippe-riviere

**Comment by jubonhomme** [comment]
Magique ! Merci

**Comment by PixnWave** [comment]
http://neguentropie.art/

**Comment by jubonhomme** [comment]
Celui-ci je m'en rappelle pour le GIF ;) ... mais je n'avais pas vu le reste

**Comment by jubonhomme** [comment]
J'ai trouvé ça  : 
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="500px" height="500px" viewBox="0 0 500 500" **enable-background=**"new 0 0 500 500" xml:space="preserve">

**Comment by PixnWave** [comment]
n'a pas fonctionné il me semble https://test.dodoc.fr/cnc/media/text-20210217_182249-vak*md*txt

**Comment by jubonhomme** [comment]
exact je viens de voir ça : https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/enable-background

**Comment by jubonhomme** [comment]
Je pense que ça n'est pas dans l'iframe que ça se place mais directement dans le code du style du svg au tout début dans viewbox

Mais je n'ose pas toucher au code sur la page de la source
https://observablehq.com/@fil/triangular-tiling-of-icosahedron?oetm_referrer=&oetm_route=%2F%40fil%2Ftriangular-tiling-of-icosahedron

map = {
  const svg = d3.create("svg").attr("viewBox", [**0, 0,** width, height]);

**Comment by jubonhomme** [comment]
Bon ben c'est encore plus simple que ça... 

En fait il ne faut pas mettre la balise iframe dans un bloc de code (noir) dans l'outil texte mais il faut juste le mettre en tant que texte seul.
Exemple : le premier dans une partie de texte "code" et le second en texte seul
https://test.dodoc.fr/_publications/test-data/

**Comment by PixnWave** [comment]
j'étais rendu là
https://observablehq.com/@observablehq/troubleshooting-embedding

**Comment by PixnWave** [comment]
> Je pense que ça n'est pas dans l'iframe que ça se place mais directement dans le code du style du svg au tout début dans viewbox
> 
> Mais je n'ose pas toucher au code sur la page de la source
> https://observablehq.com/@fil/triangular-tiling-of-icosahedron?oetm_referrer=&oetm_route=%2F%40fil%2Ftriangular-tiling-of-icosahedron
> 
> map = {
> const svg = d3.create("svg").attr("viewBox", [**0, 0,** width, height]);

le code est ouvert pour que tu puisse le modifier si tu veux garder une modif tu appui sur fork

**Comment by jubonhomme** [comment]
J'aurais appris un truc ce soir et découvert quelques sites !
Mais la réponse était juste sous les yeux...

**Comment by PixnWave** [comment]
arf en fait avec l'option bucky ça ne marche plus 
<iframe width="100%" height="677" frameborder="0"
  src="https://observablehq.com/embed/@fil/triangular-tiling-of-icosahedron?cells=viewof+n%2Cviewof+bucky%2Cmap"></iframe>

**Comment by jubonhomme** [comment]
Pourtant ici ça fonctionne https://test.dodoc.fr/_publications/test-data

**Comment by louis-ev** [comment]
J’ai pas suivi tous vos échanges mais un petit mot pour vous dire qu’à un moment il faudra faire sauter la possibilité de placer du code HTML/JS dans les blocs de texte, car cela pose des risques de sécurité (quelqu’un qui injecte un script chez d’autres personnes connectés à do•doc par exemple). 

Pour les iframes il peut y avoir des exceptions car le risque est moindre (vu qu’ils sont isolés de la page qui fait appel à eux) mais il faut que je me renseigne.

Si quelqu’un a des connaissances à ce sujet ça pourrait être bien utile !

**Comment by jubonhomme** [comment]
Malheureusement je n'ai pas les connaissances... mais @PixnWave sait peut-être comment le site https://observablehq.com/demo gère l'insertion de code ?

**Comment by PixnWave** [comment]
Je ne sais pas j'ai fais la demande à @fil.
Sinon j'ai essayai avec ce code
<iframe style="overflow: hidden;" src="http://experiences.math.cnrs.fr/simulations/sd-Lorenz3D/index.html" height="550" width="100%" frameborder="0" scrolling="no"></iframe>

mais ça ne fonctionne pas 
ici ça fonctionne https://hackmd.io/@Erwan/BkN_R6sW_

**Comment by jubonhomme** [comment]
ça ne passe pas avec l'URL d'origine.
Mais ça passe avec la seconde : https://hackmd.io/@Erwan/BkN_R6sW_

https://test.dodoc.fr/cnc/media/text-20210218_145134-0um*md*txt
Voir ici https://test.dodoc.fr/_publications/test-data2/

**Comment by PixnWave** [comment]
> J’ai pas suivi tous vos échanges mais un petit mot pour vous dire qu’à un moment il faudra faire sauter la possibilité de placer du code HTML/JS dans les blocs de texte, car cela pose des risques de sécurité (quelqu’un qui injecte un script chez d’autres personnes connectés à do•doc par exemple).s
> 
> Pour les iframes il peut y avoir des exceptions car le risque est moindre (vu qu’ils sont isolés de la page qui fait appel à eux) mais il faut que je me renseigne.
> 
> Si quelqu’un a des connaissances à ce sujet ça pourrait être bien utile !

Bonjour Louis,
Je n'ai pas besoin du bloc code mais l'iframe c'est sympa.

Petite erreur de ma part @fil n''est que simple utilisateur d'observableHQ mais il me dit que ça fonctionne comme un blog avec le code qui s’exécute sur nos machines.

**Comment by PixnWave** [comment]
Before we embark, it’s worth briefly considering: Why bother learning D3? And why learn here in Observable?
https://observablehq.com/@d3/learn-d3?collection=@d3/learn-d3

**Comment by jubonhomme** [comment]
@PixnWave  : issue à fermer ?
Il y a déjà d'autres issues sur la question des iframes  #389

**Comment by PixnWave** [comment]
oui
