### ISSUE TITLE
[Interface] Améliorer le design de la marmite 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#584]

**Comment by louis-ev** [comment]
Refonte en cours, à tester ici : https://test.dodoc.fr/

Quelques captures :
<img width="909" alt="image" src="https://user-images.githubusercontent.com/1948417/111809780-a3a76400-88d5-11eb-9741-ca097d4e692f.png">
<img width="875" alt="image" src="https://user-images.githubusercontent.com/1948417/111809813-a904ae80-88d5-11eb-95cb-5caeead89559.png">

**Comment by jubonhomme** [comment]
Quelques remarques et pistes pour commencer sur la partie Marmite :

L'idée de séparer en deux le volet marmite me plaît bien, on sépare la "création d'une nouvelle recette" et "l'explorateur de recettes en cours"... je trouve ça plus clair 

Pour la partie explorateur de recettes, je garderais l'affichage de "la date" et  "rattachée au projet", ça me semble important de le voir directement sans avoir à cliquer un par un les boutons "plus d'infos". Sachant que le bouton "plus d'infos" fait déjà la taille de la date c'est presque aussi simple de mettre la date et de supprimer le "plus d'infos".
Le nombre de médias n'est à mon avis pas si important, je l'enlèverais aussi.

J'enlèverais aussi  le champ "Modèle" qui prend beaucoup de place alors qu'il n'est pas utilisé si souvent. En regardant la plateforme de Canopé et celle de test, la grande majorité des recettes sont des recettes simples (ni modèle / ni qui suit un modèle). voir la suite pour rendre visible cette info quand même.

J'aimerais bien regrouper la recette "modèle" et "recette qui suit le modèle" à la suite. 
Par exemple en mettant le nom de la recette avec une couleur différente et juste en dessous toutes les recettes qui suivent ce modèle en italique avec une petite flèche devant. Si on a aucune recette qui suit c'est juste en couleur et dès qu'il y a une recette qui suit ce modèle le nom est en couleur et en gras.
Ça éviterai de disperser les recettes qui sont liées. Je trouverais ça plus lisible
Exemple : Je fais un récit comme modèle pour un questionnaire et je vois en dessous toutes les réponses à la suite 

**Mon Récit modèle**   "v / ^" (bouton pour déplier / replier les recettes qui suivent ce modèle)
-> Ma réponse Récit 1
-> Ma réponse Récit 2

En ajoutant un bouton pour déplier et replier les recettes qui suivent le modèle on gagnerait de la place en hauteur.
Si j'ai un Récit modèle et 20 réponses, les réponses sont repliées par défaut, on gagne 20 lignes dans l'affichage et on voit beaucoup plus rapidement les autres recettes. Si je veux ouvrir ma recette qui suit un modèle, je vois en **Gras** le nom du modèle et j'ai un clic sur le bouton déplier pour voir les recettes qui suivent ce modèle et je retrouve directement la mienne en dessous.

**Comment by jubonhomme** [comment]
Je trouve que le terme de "Gabarit" est assez compliqué pour des jeunes élèves.

Et la formule "Recettes créées"  se confond avec "Créer une Recette"

![image](https://user-images.githubusercontent.com/29262866/111849042-fcdeba00-890c-11eb-8655-91823fca3a52.png)

 Proposition   : 
Créer une nouvelle Recette /   Afficher les Recettes

**Comment by jubonhomme** [comment]
Dans la partie Explorateur de Recette

![image](https://user-images.githubusercontent.com/29262866/111849948-2dbfee80-890f-11eb-81f7-a8429309e37d.png)

Je trouve qu'il manque un filtre avec les gabarits de recettes.
Exemple je cherche toutes les recettes "page à page"

ça pourrait ressembler à l'affichage des outils de la capture
![image](https://user-images.githubusercontent.com/29262866/111849815-d15ccf00-890e-11eb-9b4e-0924be8b92b8.png)

Mais avec les pictos des recettes.

**Comment by louis-ev** [comment]
V2 !

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1948417/112024017-1150cb80-8b34-11eb-9720-e5c3686264c6.png">

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/1948417/112024014-10b83500-8b34-11eb-8243-890df18bcda2.png">

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/1948417/112024026-13b32580-8b34-11eb-9c03-8ad11253a650.png">

<img width="986" alt="image" src="https://user-images.githubusercontent.com/1948417/112024019-1281f880-8b34-11eb-9239-e9ecca1d58d3.png">

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1948417/112024031-144bbc00-8b34-11eb-86f7-ce9d192d6475.png">

<img width="977" alt="image" src="https://user-images.githubusercontent.com/1948417/112024037-157ce900-8b34-11eb-8f61-488fd144aa57.png">

**Comment by louis-ev** [comment]
Je m’interroge sur l’emplacement du filtre pour les type de recette.
Il y a trop de filtres à des endroits différents actuellement. Ça m’a l’air trop compliqué et confus.

À tester sur https://test.dodoc.fr/

**Comment by louis-ev** [comment]
Question : faut-il faire apparaitre dans la liste les recette réponses comme les autres recettes (c’est le cas maintenant) ou les afficher uniquement en cliquant sur le bouton **RÉPONSES : 1** d’un modèle (comme avant) ? Ça complique le filtre "afficher uniquement mes recettes" et les autres, car si on a une réponse à un modèle qu’on a pas créé c’est pas très intuitif.

**Comment by louis-ev** [comment]
J’avais complètement raté ta réponse, c’est vraiment pas pratique ces discussions mono-fils sur un sujet complexe…

> Quelques remarques et pistes pour commencer sur la partie Marmite :
> 
> L'idée de séparer en deux le volet marmite me plaît bien, on sépare la "création d'une nouvelle recette" et "l'explorateur de recettes en cours"... je trouve ça plus clair

Ok top 

> 
> Pour la partie explorateur de recettes, je garderais l'affichage de "la date" et "rattachée au projet", ça me semble important de le voir directement sans avoir à cliquer un par un les boutons "plus d'infos". Sachant que le bouton "plus d'infos" fait déjà la taille de la date c'est presque aussi simple de mettre la date et de supprimer le "plus d'infos".

Le plus d’infos me parait indispensable, notamment si à terme on affiche un aperçu du contenu des recettes (ce que j’envisage). 

> Le nombre de médias n'est à mon avis pas si important, je l'enlèverais aussi.

Dans mon expérience il est bien pratique pour identifier les publis "étoffés" des publis test (genre réponses jamais remplies ou finalisées). 

> 
> J'enlèverais aussi le champ "Modèle" qui prend beaucoup de place alors qu'il n'est pas utilisé si souvent. En regardant la plateforme de Canopé et celle de test, la grande majorité des recettes sont des recettes simples (ni modèle / ni qui suit un modèle). voir la suite pour rendre visible cette info quand même.

Le but est aussi de rendre plus visible cette fonctionnalité. Les instances que je suis (celles de fairlangue, de louise michel et autre) utilisent beaucoup cette fonctionnalité. Du coup je suis un peu coincé là-dessus, je pense que d’autres utilisateurs qui ne sont pas sur github auraient un avis inverse. 

> 
> J'aimerais bien regrouper la recette "modèle" et "recette qui suit le modèle" à la suite.
> Par exemple en mettant le nom de la recette avec une couleur différente et juste en dessous toutes les recettes qui suivent ce modèle en italique avec une petite flèche devant. Si on a aucune recette qui suit c'est juste en couleur et dès qu'il y a une recette qui suit ce modèle le nom est en couleur et en gras.

À tester maintenant du coup :)

> Ça éviterai de disperser les recettes qui sont liées. Je trouverais ça plus lisible
> Exemple : Je fais un récit comme modèle pour un questionnaire et je vois en dessous toutes les réponses à la suite
> 
> **Mon Récit modèle** "v / ^" (bouton pour déplier / replier les recettes qui suivent ce modèle)
> -> Ma réponse Récit 1
> -> Ma réponse Récit 2
> 
> En ajoutant un bouton pour déplier et replier les recettes qui suivent le modèle on gagnerait de la place en hauteur.
> Si j'ai un Récit modèle et 20 réponses, les réponses sont repliées par défaut, on gagne 20 lignes dans l'affichage et on voit beaucoup plus rapidement les autres recettes. Si je veux ouvrir ma recette qui suit un modèle, je vois en **Gras** le nom du modèle et j'ai un clic sur le bouton déplier pour voir les recettes qui suivent ce modèle et je retrouve directement la mienne en dessous.

Voir post précédent.

**Comment by louis-ev** [comment]
Nouvelle version à tester !
J’ai déplacé le menu "projet" vers les filtres en haut et ajouter le tri par type de recette. J’ai mis ce filtre en avant, juste au-dessus de la liste car on cherche souvent par type.

![image](https://user-images.githubusercontent.com/1948417/113154213-113d8380-9238-11eb-8799-8b9f7bc6fbc7.png)

**Comment by jubonhomme** [comment]
Cette version est plus claire et aérée que la V2. 

Quelques propositions : 
Pour le filtre type de recette, je trouve aussi que c'est une bonne place car on voit bien  ce que l'on sélectionne. Par contre pour des personnes qui ne connaissent pas bien les différents types il faut passer la souris au survol pour voir l'info car le picto n'est pas toujours évident en petit (j'ai la vue qui baisse ;) ) En regardant un peu le reste de l'interface je pense qu'on pourrait avoir le fonctionnement que le menu de la capture.
![image](https://user-images.githubusercontent.com/29262866/113212551-36051b80-9277-11eb-87d0-bbe984bcada0.png)

Si je clique sur un type le nom s'affiche mais les autres restent avec un picto seul. Il n'y a que celui qui est actif qui s'élargit un peu avec le nom. Mais j'ai l'impression que ça pourrait rentrer dans la largeur.

![image](https://user-images.githubusercontent.com/29262866/113213425-77e29180-9278-11eb-9aec-f9bea9dce202.png)

Surtout si le bloc dessin disparaît à terme ça laissera encore un peu de place

ATTENTION : Il y a deux infos bulles qui se superposent au survol du picto
![image](https://user-images.githubusercontent.com/29262866/113213927-166ef280-9279-11eb-9c77-55e0ca9bc190.png)

**Comment by jubonhomme** [comment]
Une autre chose qui me pose question c'est l'affichage du nombre de recettes dans chacun des types.
Si tout est désélectionné (= pas de filtre par type) on voit le nombre de chaque type  -> OK
Si on sélectionne un type de recette dans le filtre, les autres passent à "0" recette, c'est logique et en même temps ça me fait bizarre de voir affiché "0"... on a pas l'idée de cliquer dessus puisqu'on voit "0"... hors si on clique dessus le filtre bascule sur ce type et le nombre réapparaît.
Exemple en vidéo ici : https://test.dodoc.fr/album-a-compter/media/video-20210331-235220-ugm*webm*txt?display=standalone

L'info est redondante avec l'affichage qui est au dessus et qui je trouve est plus claire
exemple : il y a bien 25 recettes "bloc dessin" mais pas 0 recette montage vidéo dans toutes les recettes
![image](https://user-images.githubusercontent.com/29262866/113217013-84b5b400-927d-11eb-91b1-c5ddd84118cc.png)
La preuve
![image](https://user-images.githubusercontent.com/29262866/113217317-0f96ae80-927e-11eb-8ac1-d2ee1fdeceff.png)


Personnellement ce nombre dans chacun des boutons m'embrouille plus qu'autre chose. Donc je l'enlèverai bien en laissant juste l'info générale du dessus
![image](https://user-images.githubusercontent.com/29262866/113217731-9fd4f380-927e-11eb-8780-c83e7795d18f.png)

**Comment by louis-ev** [comment]
Ok !
Je viens de faire ce changement, bonne idée : 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1948417/113324081-fb52c000-9316-11eb-8d40-9d93eff4c4d7.png">

Pour le reste restons simple et voyons à l’usage si ça fonctionne comme prévu, ok ?

**Comment by sarahgarcin** [comment]
Super c'est top comme ça ! 
J'aurais juste 3 remarques: 
1) Le afficher "mes recettes" / "toutes les recettes" n'a pas trop de sens en menu déroulant (et prend beaucoup de place visuellement), est-ce que ça ne peut pas être des boutons radio ?
![Screen Shot 2021-04-02 at 11 52 20](https://user-images.githubusercontent.com/4678296/113405332-f559ef00-93a9-11eb-9357-2ab6df1519d7.png)

2) Dans la liste des publications, "accès limité…" prends beaucoup de place, il n'y a pas moyen de réduire un peu ça ? 
Par exemple en mettant un picto (genre cadenas), au survol il y a l'info "accès limité" et on a un autre bouton pour rentrer le mot de passe ou faire la demande d'auteur ?
![Screen Shot 2021-04-02 at 11 55 00](https://user-images.githubusercontent.com/4678296/113405548-4cf85a80-93aa-11eb-90e9-1587c7aea997.png)
![Screen Shot 2021-04-02 at 11 52 31](https://user-images.githubusercontent.com/4678296/113405336-f723b280-93a9-11eb-9c7e-161aede7c693.png)

3) Je ne trouve pas ça hyper clair l'information Modèle (même si c'est mieux qu'avant), on ne sait pas à quelle publication correspond cette info 
![Screen Shot 2021-04-02 at 11 52 36](https://user-images.githubusercontent.com/4678296/113405337-f7bc4900-93a9-11eb-919f-c52840424ccd.png)

**Comment by louis-ev** [comment]
> Le afficher "mes recettes" / "toutes les recettes" n'a pas trop de sens en menu déroulant (et prend beaucoup de place visuellement), est-ce que ça ne peut pas être des boutons radio ?

Ça commence à date ce changement, validé par plusieurs utilisateurs et sur la home y a déjà un bouton radio de ce type donc ça rajouterait de la confusion. À la place je propose de réduire sa taille :  

avant 
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/1948417/113887445-c71d4a80-97c1-11eb-989f-2019a9ce2121.png">

après
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1948417/113887674-fcc23380-97c1-11eb-966a-32ef8f891a81.png">

J’ai tenté des améliorations dans le panneau de recette mais je crois que je sèche un peu… Ça ira pour la v9 ou ça bloque la publication ?

**Comment by sarahgarcin** [comment]
Laissons comme ça :)

**Comment by louis-ev** [comment]
Pour gagner de la place, je supprime le message ACCÈS LIMITÉ AUX AUTEUR et MDP, il nous semble à @sarahgarcin et moi que c’est tout aussi clair :  

<img width="764" alt="image" src="https://user-images.githubusercontent.com/1948417/113994166-722b1400-9855-11eb-9c19-69b7ac8e50dc.png">

<img width="335" alt="image" src="https://user-images.githubusercontent.com/1948417/113994183-76573180-9855-11eb-8ac4-01a843665613.png">

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1948417/113994208-7d7e3f80-9855-11eb-8af5-1065dedada42.png">

devient 

<img width="416" alt="image" src="https://user-images.githubusercontent.com/1948417/113994564-c8985280-9855-11eb-8232-8f58b238e761.png">

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1948417/113994569-c930e900-9855-11eb-9c9c-31a338650eab.png">

**Comment by louis-ev** [comment]
Déployé sur test.dodoc.fr
