### ISSUE TITLE
Manque picto dessin libre

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#590]
![image](https://user-images.githubusercontent.com/29262866/112212708-99f76680-8c1d-11eb-91ca-4078b856c851.png)

Voir exemple  #571

**Comment by louis-ev** [comment]
Picto ajouté depuis hier, pas déployé encore :)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/1948417/112332012-af21d300-8cb9-11eb-8a1a-42f50d1f19bd.png">
