### ISSUE TITLE
Proposition : conserver les paramètres et l'affichage de la marmite de la dernière ouverture

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#591]
Si j'ouvre une conversation du chat dans le volet tout à droite -> je referme le volet du chat -> je le re-ouvre je retombe directement dans la conversation que j'avais ouverte. Très bien !

Si j'ai un projet ouvert dans le volet de gauche et que je déploie complètement le volet de la marmite et que je le referme je reste toujours dans ce projet Très bien aussi

Si j'ouvre la marmite, que je choisi "afficher les recettes" / Afficher seulement mes recettes  et que je referme le volet marmite, si je l'ouvre à nouveau je retombe toujours sur l'affichage de la création de recettes. Pas très pratique... je dois à chaque ouverture du volet repasser par toutes les étapes pour afficher ce que je veux voir par défaut : mes recettes

Je trouve qu'il serait plus intéressant de retrouver le dernier affichage de la marmite à chaque ouverture du volet.
Si j'ai sélectionné "afficher les recettes" / seulement mes recettes -> je retrouve cet affichage
Si j'ouvre une recette page à page et que je replie le volet marmite -> je retombe directement dans ce page à page si je déplie la marmite

**Comment by louis-ev** [comment]
D’un point de vue usage, je vois bien l’intérêt. Encore que je me demande si dans un usage partagé, fermer le panneau ne donne pas l’impression qu’on ferme tout en même temps, donc rouvrir directement à l’ouverture de la marmite me pose question.

D’un point de vue technique une recette peut consommer beaucoup de ressources (vidéos qui se chargent, se lisent, images en très haute def) donc si je peux décharger le panneau ça me parait plus raisonnable. Il faut donc un système qui enregistre et rouvre tout au déploiement du panneau et ça complexifie pas mal le code. On en rediscute mais faut vraiment être sur de ce besoin :)

**Comment by jubonhomme** [comment]
Je pense qu'on peut fermer cette issue 
Le fonctionnement des publications a été revu en profondeur
