### ISSUE TITLE
Suppression du picto dans l'explorateur de recettes

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#592]
Je trouve que le picto du type de recette est trop petit pour être lisible, même sur un écran d'ordi. Je n'ai pas testé sur tablette mais ça doit être encore plus petit.
Je garderai que le nom du type et supprimerai le picto, ça ferai un peu de place pour le texte.

![image](https://user-images.githubusercontent.com/29262866/112385585-15c1e380-8cf0-11eb-9885-e90d728053f4.png)

**Comment by louis-ev** [comment]
Nouvelle proposition : plus grands pictos, plus de colonne modèle (qui apparait plutôt sous la recette si besoin) : 
<img width="823" alt="image" src="https://user-images.githubusercontent.com/1948417/112491728-de4f4780-8d80-11eb-9390-37030d757e97.png">

**Comment by louis-ev** [comment]
Je te laisse me dire si c’est utile ou pas dans cette taille.

**Comment by louis-ev** [comment]
Sans : 
![Uploading image.png…]()

**Comment by jubonhomme** [comment]
En connaissant bien les pictos je les devines mais je pense pas que ce soit une aide visuelle. 
La solution sans picto et avec l'infos des modèles en dessous me parait plus intéressante, ça surligne un peu les recettes modèles.

**Comment by louis-ev** [comment]
Ok, je ferme.
Reste le filtre par gabarit du coup.
