### ISSUE TITLE
Couleur fond titre de la marmite

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#593]
Je ne sais pas si c'est juste "en travaux" ou si c'est voulu mais je préférai le fond vert du bandeau pour le texte de la marmite : 
 "La marmite : Mélangez des médias pour en créer de nouveaux ! "

![image](https://user-images.githubusercontent.com/29262866/112386033-a3053800-8cf0-11eb-8019-9c7a814c910f.png)

C'était plus en accord avec celui du chat par exemple
![image](https://user-images.githubusercontent.com/29262866/112386411-2a52ab80-8cf1-11eb-82c8-bcaa27ffec15.png)

Et j'ai beaucoup de mal à lire le texte en rouge sur fond vert du nombre de recettes du filtre
![image](https://user-images.githubusercontent.com/29262866/112386659-85849e00-8cf1-11eb-963b-7536a0e677dd.png)

**Comment by louis-ev** [comment]
Mieux ?

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/1948417/112620289-9be14580-8e28-11eb-9461-aa1062c498b5.png">

**Comment by louis-ev** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1948417/112621966-a7ce0700-8e2a-11eb-8a31-1ede6d6fc119.png">

**Comment by jubonhomme** [comment]
oui !
Mais du coup c'est le bouton rechercher qui pique les yeux

**Comment by louis-ev** [comment]
Non non tu as raison le mélange est pas heureux.

![image](https://user-images.githubusercontent.com/1948417/112855743-639f6880-90af-11eb-99ec-0e98ed9b4773.png)
