### ISSUE TITLE
Bouton glissière pour affichage marmite

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#594]
Afin de ne pas confondre le texte "créer une nouvelle recette" avec le bouton "créer"
![image](https://user-images.githubusercontent.com/29262866/112387850-91bd2b00-8cf2-11eb-92d7-e75492132b3f.png)

et 
![image](https://user-images.githubusercontent.com/29262866/112387879-a00b4700-8cf2-11eb-9c5e-a1b56e0d05f9.png)

Je pense qu'on pourrait utiliser un bouton glissière pour basculer entre créer / afficher les recettes.
Comme pour basculer l'affichage entre Projets / Médias
![image](https://user-images.githubusercontent.com/29262866/112388112-f4162b80-8cf2-11eb-8030-51ca36383536.png)

Un truc comme ça 
![image](https://user-images.githubusercontent.com/29262866/112388452-74d52780-8cf3-11eb-9d32-f7aa6fb26661.png)

**Comment by louis-ev** [comment]
Je préfère changer l’intitulé _créer une nouvelle recette_ plutôt : ce type de bouton indique clairement deux contenus différents, alors que celui que tu évoques est plutôt "deux modes de présentation différents du même contenu".
Il y a aussi l’idée dans cet interrupteur d’une fonctionnalité plus "expert", au second plan. Ici c’est pas secondaire, il faut vraiment que ça soit flagrant. Ça pourrait l’être encore plus d’ailleurs. Non ?

**Comment by jubonhomme** [comment]
En fait à l'usage je trouve ça plutôt logique. Tu as raison.

Je clique sur le bouton radio "créer une nouvelle recette" pour être dans ce menu / je sélectionne un type de recette et clique sur le bouton "créer" pour créer un page à page par exemple.

Pour que la sélection soit plus visible que le seul bouton radio on pourrait mettre un peu de couleur sur le cadre en entier ou sur le texte ?

**Comment by jubonhomme** [comment]
A fermer

**Comment by louis-ev** [comment]
Ha ! Je me demandais justement l’autre jour si on ne devrait pas mettre un bouton _afficher les recettes de ce type_ à côté du bouton CRÉER ici : 

![image](https://user-images.githubusercontent.com/1948417/123297239-ad191b80-d517-11eb-94b7-c9292c843043.png)

Qui activerait le filtre correspondant dans la liste des recettes. Utile ou pas à ton avis ?

**Comment by jubonhomme** [comment]
En voyant l'espace à droite du bouton ça donne envie...

Mais j'ai peur que le bouton radio au dessus perde encore en visibilité, je trouve que la séparation Créer / Afficher est plus claire comme cela. 
SI on remet un bouton qui bascule sur l'affichage de la liste on risque de se perdre dans la navigation.

De plus pour les autres recettes il n'y a pas vraiment de place
![image](https://user-images.githubusercontent.com/29262866/123324409-152b2a00-d537-11eb-9e2a-bdd7886ebf72.png)

La solution serait peut-être de grossir un peu la taille des pictos "filtres" au dessus de la liste ?
![image](https://user-images.githubusercontent.com/29262866/123325280-1f99f380-d538-11eb-8c78-cf7c643cf609.png)

**Comment by jubonhomme** [comment]
A fermer ?

**Comment by jubonhomme** [comment]
Ça fonctionne bien sur la version 9.3.5 actuelle et l'interface de publication de dodoc 10 sera bien différente.
