### ISSUE TITLE
Affichage "plus d'info" des recettes

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#596]
Est-ce que le bouton "plus d'infos" dans la vignette de la recette pourrait se transformer en bouton pour déplier / replier les infos 
Actuellement on peut déplier les infos mais pas les masquer
![image](https://user-images.githubusercontent.com/29262866/112389618-4f491d80-8cf5-11eb-8a2f-39aee48a8219.png)

Je vois bien à la place avoir le même comportement que le bouton "plus d'infos" de l'explorateur de recettes  : un clic les infos s'affichent / deuxième clic les infos sont masquées

![image](https://user-images.githubusercontent.com/29262866/112389480-1315bd00-8cf5-11eb-8e08-c4241d4a8d9c.png)

**Comment by louis-ev** [comment]
Et hop 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1948417/112501010-2c684900-8d89-11eb-8035-da21fffa5df1.png">

**Comment by jubonhomme** [comment]
Dernière petite demande sur ce sujet...
Est-ce que le bouton pourrait rester à la même place en haut ?
Je trouve ça plus simple de pouvoir replier sans avoir à descendre chercher le bouton qui s'est sauvé en bas.
![image](https://user-images.githubusercontent.com/29262866/112534493-6cd8be80-8dab-11eb-9027-e1667d5e0626.png)
