### ISSUE TITLE
Bug : Déplacement cadre dans page à page

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#597]
Depuis ce soir j'observe des bug dans la sélection et le déplacement des blocs dans le page à page

voir la vidéo : https://test.dodoc.fr/test-1/media/video-20210324-233201-0we*webm*txt?display=standalone

**Comment by louis-ev** [comment]
Peux-tu retester maintenant ?

**Comment by louis-ev** [comment]
Ok je vois.
Tu peux me faire un protocole à partir de 0 pour reproduire le bug ? Créer une publi, importer/créer un média, etc. ?

**Comment by louis-ev** [comment]
J’ai compris : tu passes la grille à 0, ce qui créer une division par l’infini dans le code qui place les médias.
Je corrige.

**Comment by jubonhomme** [comment]
Ouf !
Je n'arrivais pas à reproduire hier soir sur une nouvelle recette.
