### ISSUE TITLE
Texte (Page à Page)

### ISSUE THREAD

**Issue by Pixflowave** [l-atelier-des-chercheurs/dodoc#602]
Bonjour,
lorsque j'utilise le bloc texte du menu créer je me retrouve dans cette situation. Est-ce une mauvaise manipulation ?
![Capture du 2021-03-29 19-55-58](https://user-images.githubusercontent.com/27885587/112879052-f00a5500-90c8-11eb-9923-05dfc2b5652c.png)

**Comment by jubonhomme** [comment]
tu parles du haut de la fenêtre des outils qui est coupée ?

**Comment by jubonhomme** [comment]
Je dirais que ça vient de ta marge du haut qui est à presque à 0 et que la fenêtre du texte est placée tout en haut.
Si tu baisses la fenêtre pour écrire et que tu positionnes ta fenêtre de texte ensuite ça doit passer.

**Comment by PixnWave** [comment]
![Capture du 2021-03-29 22-17-51](https://user-images.githubusercontent.com/27885587/112894810-a166b600-90dc-11eb-9ba3-3a4273cc596e.png)

**Comment by PixnWave** [comment]
Faudrait pouvoir descendre la page plus bas...

**Comment by jubonhomme** [comment]
Voir le sujet ici : https://github.com/l-atelier-des-chercheurs/dodoc/issues/547#issuecomment-726031230

**Comment by jubonhomme** [comment]
c'est difficile de trancher entre :
avoir suffisamment de place au dessus pour la fenêtre
avoir trop de place en haut ce qui pousse la page en bas à l'ouverture

**Comment by PixnWave** [comment]
perso a chaque fois mais effectivement je fais comme tu as décrit c'était au cas ou..

**Comment by jubonhomme** [comment]
La V10 utilise maintenant un menu à gauche pour les blocs texte.
Je ferme cette issue
