### ISSUE TITLE
Affichage par défaut des filtres dans la marmite si ouverture d'un projet

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#604]
J'ouvre une nouvelle issue pour la rendre plus visible et poser la question à tous.
@sarahgarcin @paulinegourlet 
C'est en lien direct avec #584

Le filtre "projets" était séparé des filtres "mots-clés" et "auteurs".
@louis-ev les a rassemblé pour ne pas avoir des filtres éparpillés façon puzzle.
Avant : 
![image](https://user-images.githubusercontent.com/29262866/113220263-2e4b7400-9283-11eb-8108-6179a3df22cb.png)

Après : 
![image](https://user-images.githubusercontent.com/29262866/113220328-4ae7ac00-9283-11eb-9f3c-6faa98139577.png)

Mais le fonctionnement actuel me gêne.
On passe d'un affichage de la liste des recettes dans la marmite
![image](https://user-images.githubusercontent.com/29262866/113218881-92206d80-9280-11eb-9579-e9f02aabb864.png)

à cette fenêtre si on ouvre un projet dans le volet de gauche
![image](https://user-images.githubusercontent.com/29262866/113218800-74eb9f00-9280-11eb-8476-1436b37a976d.png)

Je comprends l'idée de filtrer les recettes en fonction du projet ouvert, mais en ouvrant par défaut l'affichage du filtre on voit principalement la liste de tous les mots clés, de tous les auteurs et de tous les projets sur la plateforme dodoc... et tout en bas la liste des recettes.
Du coup l'info principale de la liste des recettes est peu visible alors que la liste des filtres prend quasiment tout l'espace de la fenêtre pour en fait afficher qu'une seule info : le "nom du projet" qui est utilisé comme filtre.
Dans l'exemple ci dessus  : 
![image](https://user-images.githubusercontent.com/29262866/113219400-9d27cd80-9281-11eb-9eee-487e9b9d3929.png)

Mais cette info est déjà présente à l'écran dans les différents menus 
![image](https://user-images.githubusercontent.com/29262866/113219830-728a4480-9282-11eb-8307-8c29bb7bf0f0.png)

Et sur une plateforme d'une classe avec + 20 auteurs, des mots-clés et un nombre de projets assez important la fenêtre des filtres va être imposante à chaque fois.

Question : Est-ce que le filtre "Projets" est utile dans le volet de la marmite ?
Je ne sais pas trop comment faire mais si on rend plus évident le lien entre ce qui est ouvert à gauche dans les projets et la marmite il n'y aurait presque plus besoin de ce filtre.

Je le laisserais au moins replié par défaut pour conserver la priorité à l'affichage de la liste des recettes.

Ou une autre proposition : le regrouper avec le filtre "Afficher" 
- toutes les recettes
- seulement mes recettes
- les recettes du projet "ouvert"  (ou une autre formule pour désigner ce qui est ouvert à gauche )

On aurait une progression avec ce bouton à liste déroulante de "Toutes LES recettes" -> "toutes MES recettes " -> "toutes les recettes de MON projet" 
Et je trouve ça plus simple d'utiliser le volet de gauche pour sélectionner des projets que de chercher le nom écrit dans la longue liste du filtre (encore plus pour des élèves je pense)

Votre avis ?

**Comment by louis-ev** [comment]
Merci pour ton retour :)

Deux propositions complémentaire : 

- laisser le menu filtres replié s’il l’est et ajouté un petit interrupteur + discret 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1948417/113396970-a5c0f680-939c-11eb-89eb-55fca58df955.png">

- avoir un bouton dans le projet qui permet d’ouvrir la marmite et d’activer le filtre 
![Uploading image.png…]()

**Comment by sarahgarcin** [comment]
Je valide les propositions de @louis-ev et je suis totalement d'accord avec les remarques de @jubonhomme :)

**Comment by louis-ev** [comment]
L’alternative c’est de lister dans un menu dans chaque projet les recettes en lien. Mais c’est peut-être un changement pour la v10 plutôt :)

**Comment by jubonhomme** [comment]
Oui très bonne idée le bouton "recettes" directement dans le projet !
On est d'accord que ça filtre les recettes qui sont rattachées à ce projet, et pas toutes les recettes qui comportent un média de ce projet.

Mais je trouve ça très bien. En effet quand on exporte le document d'une recette page à page en pdf ou une vidéo issue d'une recette "montage vidéo" on l'exporte dans le projet et on voit ce nouveau média. Mais pour les récits par exemple ou le partage on ne voyait rien dans le projet en lui même. Là avec ce bouton on fait le lien avec ce qui reste dans la marmite mais qui est directement rattaché au projet. 
Les projets restent indépendant de la marmite, on peut toujours piocher les médias de différents projets pour une recette. Mais on comprend mieux le lien entre les dossiers de médias et les productions qui restent du côté de la marmite.

**Comment by jubonhomme** [comment]
Et oui aussi pour l'interrupteur discret dans la marmite pour filtrer avec le projet ouvert

**Comment by louis-ev** [comment]
Done !
À tester sur test.dodoc.fr :)

**Comment by jubonhomme** [comment]
Si je clique sur le bouton "recettes" dans un projet le volet marmite s'ouvre avec le filtre sur ce projet : OK
![image](https://user-images.githubusercontent.com/29262866/113783366-f08f9500-9733-11eb-9c9f-b3f9ff55db6d.png)


Mais si je désactive avec le bouton glissière il faut cliquer sur "supprimer tous les filtres..."
Pourquoi ne pas afficher directement toutes les recettes avec le bouton glissière ?

![image](https://user-images.githubusercontent.com/29262866/113783546-30567c80-9734-11eb-82bc-a02c72ac5469.png)

**Comment by jubonhomme** [comment]
J'ai toujours une deuxième infobulle qui vient masquer celle du nom de la recette
![image](https://user-images.githubusercontent.com/29262866/113784394-a5768180-9735-11eb-8954-4091c48d4b85.png)

**Comment by sarahgarcin** [comment]
j'ai testé et mêmes remarques que @jubonhomme

**Comment by jubonhomme** [comment]
Je viens de voir que le bouton "supprimer tous les filtres..."  se trouve tout en bas, en dessous de la liste des recettes.
On pourrait le remonter en haut à côté des filtres, parce qu'en bas on ne le voit pas beaucoup.
![image](https://user-images.githubusercontent.com/29262866/113785075-b7a4ef80-9736-11eb-8905-30f54a5ea9e8.png)

**Comment by louis-ev** [comment]
L’idée de le voir en bas : quand tu cherches une recette mais que tu as oublié qu’il y a un filtre ou que le filtre est pas le bon, arrivé en bas de la liste que tu puisses facilement voir l’ensemble de la liste.

Je propose une petite croix à côté du bouton filtres pour supprimer les filtres.

**Comment by louis-ev** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/1948417/113929337-3ca00f80-97f0-11eb-8720-01a67fc904a4.png">

**Comment by louis-ev** [comment]
Ajouté sur la page d’accueil pour les projets et médias, dans la bibliothèque de média et la liste des recettes.
À tester !

**Comment by jubonhomme** [comment]
Testé et approuvé !
Je trouve ça mieux qu'avant ou dès que le bouton filtre était replié ça fermait en même temps le filtre et donc on devait toujours le garder ouvert pour filtrer mais on perdait de la place en haut.

Très bien aussi le bouton glissière pour la liste de recettes en fonction du projet ouvert : 
si aucun projet ouvert : pas de bouton
si un projet ouvert : filtre automatique -> si on désélectionne on voit toutes les recettes mais on peut réactiver le filtre.

**Comment by louis-ev** [comment]
Super :)

J’ai juste pas pu faire ça facilement (il aurait fallu enregistrer le projet qui vient d’être fermé, ce que do•doc ne fait pas) : 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/1948417/113991455-c254a700-9852-11eb-899a-deeaaeedf850.png">

**Comment by louis-ev** [comment]
Je ferme du coup.
