### ISSUE TITLE
Bug : Télécharger une version web

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#610]
La fonction "Télécharger une version web" d'un document page à page est cassée.
Le téléchargement de l'archive est fonctionnel mais une fois l'archive décompressée, le fichier index.html ouvre une page vide.

**Comment by louis-ev** [comment]
Je confirme, merci pour le retour.

Question : j’ai isolé le changement à ces lignes là 
<img width="947" alt="image" src="https://user-images.githubusercontent.com/1948417/114422020-30340200-9bb6-11eb-917d-809d79d67895.png">

Mais ça voudrait dire que c’est cassé depuis 2 mois… possible @jubonhomme ?

**Comment by jubonhomme** [comment]
Sur la version 9.0.25 mise à jour le 8 février dernier de dodoc.reseau-canope ça fonctionne

**Comment by louis-ev** [comment]
Cassé effectivement le 26 février dans le commit suivant : https://github.com/l-atelier-des-chercheurs/dodoc/commit/4f6433ad4082bb2a9e9742e07180887673c5af2d
Corrigé à l’instant.
