### ISSUE TITLE
l’ordre des projets sur la page d’accueil place toujours les dossiers en premier

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#615]
Actuellement, l’organisation se fait d’abord par dossier par ordre alphabétique puis par projet par date de création.
Avant d’avoir un système de choix de l’ordre d’affichage (voir #438 ), je propose de simplier cette logique : 
- l’ordre est chronologique par date de création, du plus récent au plus ancien
- les dossiers utilisent comme date de référence la date la plus récente parmi celles des projets qu’ils contiennent

Qu’en pensez-vous ?

**Comment by louis-ev** [comment]
À tester sur https://test.dodoc.fr/ !
Voir aussi #438

**Comment by jubonhomme** [comment]
Je trouve ça plus simple et lisible que les dossiers suivent l'affichage chronologique des projets et qu'ils ne soient pas toujours en haut.

Par contre je trouve que le filtre par : édition / création et le plus récent / le plus ancien en premier ajoute trop de complexité.
Sachant qu'il y a déjà le filtre par 
- Seulement mes projets / tous les projets
- mots-clés / auteurs
- recherche par titre
Personnellement, je trouve que c'est suffisant pour afficher rapidement un "home" avec ce qui nous intéresse.

**Comment by louis-ev** [comment]
L’avantage c’est que ça permet de voir facilement tous les projets modifiés récemment par exemple, ce qui n’est pas possible avec un filtre. Et dans les médias, ça permettrait de les organiser par date de création (et non par date d’envoi), donc retrouver la date originale (EXIF) si prise de vue photo. Ça me parait assez complémentaire, et suffisamment au second plan pour ne pas gêner la navigation usuelle. À voir aussi en regard de #438. Tu penses que c’est vraiment problématique ?

**Comment by jubonhomme** [comment]
Problématique... non ! C'est effectivement au second plan et sous forme d'option d'affichage.
Pour mon usage de dodoc sur mon poste perso je ne pense pas utiliser ce filtre.
Mais pourquoi pas sur un dodoc serveur en collaboratif pour voir ce qui a été ajouté / modifié dernièrement. À voir à l'usage.

**Comment by louis-ev** [comment]
Ok. Dans ce cas je laisse et ça reste une fonctionnalité avancée, utile effectivement surtout quand il commence à y avoir pas mal de contenus (comme sur test.dodoc.fr ).
