### ISSUE TITLE
document page à page : la Belle Allure n’est plus liée 

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#618]
Modifications du CSS il y a 3 ans car à l’export PDF elle n’étaient pas là : https://github.com/l-atelier-des-chercheurs/dodoc/blob/6fe7595a9b233bfeef93d17bae28710fa1b3c737/public/src/vue/style.less#L4806

très probablement que sous electron et puppeteer ça soit supporté, tester en remettant cette propriété.

**Comment by jubonhomme** [comment]
Je confirme, dans le document texte ça fonctionne bien
![image](https://user-images.githubusercontent.com/29262866/116777113-e760c200-aa6c-11eb-96f0-46b1a2981026.png)

Mais dans le page à page les liaisons ne se font pas. Il y a aussi une coupure du haut des lettres
![image](https://user-images.githubusercontent.com/29262866/116777145-20993200-aa6d-11eb-8de4-2ea13828703f.png)

Mais c'est juste sur la première ligne du bloc texte, sur les suivantes ça passe
![image](https://user-images.githubusercontent.com/29262866/116777164-4e7e7680-aa6d-11eb-9fad-f7ecc2824818.png)

**Comment by louis-ev** [comment]
Argh. C’est du au fait que le texte est contenu dans son bloc. Il semble que la Belle allure a des capitales et des ascendantes particulièrement hautes. C’est embêtant :/

**Comment by louis-ev** [comment]
Je ne vois pas d’autres solutions qu’une exception : si typo = Belle Allure, alors ajouter une petite marge au-dessus de la première ligne pour  la descendre suffisamment.

**Comment by jubonhomme** [comment]
Et pour les liaisons tu as trouvé une solution ?

**Comment by louis-ev** [comment]
Je viens de désactiver la propriété CSS **font-variant-ligatures** sur test.dodoc.fr, pourras-tu tester avec toutes les typos @jubonhomme ? En local c’est OK pour la belle allure.

**Comment by jubonhomme** [comment]
OK donc pour Belle Allure ça marche
https://test.dodoc.fr/_publications/test-belle-allure-pdf/

**Comment by jubonhomme** [comment]
Mais pas en local sur ma version 9.1 sous linux 
![image](https://user-images.githubusercontent.com/29262866/116881346-731c4f00-ac23-11eb-8a77-44a394e3af08.png)

**Comment by louis-ev** [comment]
Euh ben c’est normal ? Tu fais pas tourner la 9.1.1-dev que je sache ? 😉

**Comment by jubonhomme** [comment]
Oui effectivement ;)

Mais en lisant ton post précédent : 
> En local c’est OK pour la belle allure.

J'ai cru un instant qu'en local il n'y avait pas de souci et que c'était juste sur la version serveur.

**Comment by louis-ev** [comment]
Ha pardon ! je voulais dire _après avoir fait cette modification en local sur ma machine, ça a l’air ok_ :D

**Comment by jubonhomme** [comment]
Je viens de refaire un test sur la 9.1.2 
![image](https://user-images.githubusercontent.com/29262866/120323792-2db47580-c2e6-11eb-8d4a-e97d6804d29e.png)

C'est bon !

A fermer !
