### ISSUE TITLE
Problème d'ajout de média dans la recette

### ISSUE THREAD

**Issue by glungtung** [l-atelier-des-chercheurs/dodoc#622]
Bonjour,
J'utilise dodoc 9.1.0 sur macos 11.2.3

Lorsque je rajoute un média dans ma recette récit, la flèche sur les médias disparait, et je ne peux plus ajouter d'autre média
Pour que ces flèches réapparaissent, j'ai constaté qu'en faisant défiler la fenêtre de récit tout en bas, ca fait réapparaitre les flèches sur les médias

avant d'ajouter un média, j'ai les flèches sur les média : 
<img width="1311" alt="Capture d’écran 2021-05-07 à 14 54 46" src="https://user-images.githubusercontent.com/457189/117440072-a83ae100-af44-11eb-92f4-9a20a90801b5.png">

après avoir ajouter un média, les flèches ont disparu
<img width="1311" alt="Capture d’écran 2021-05-07 à 14 54 54" src="https://user-images.githubusercontent.com/457189/117440153-bb4db100-af44-11eb-91eb-e6b11c0d2713.png">

**Comment by jubonhomme** [comment]
Confirmé aussi sous linux sur la version 9.1
Si on ajoute un média les flèches disparaissent sur les médias du projet.
Dès que l'on monte ou descend sur le récit et que l'on repasse sur une zone entre deux blocs les flèches reviennent.

Sur test.dodoc.fr les flèches reviennent immédiatement après avoir ajouter le média dans le récit.

**Comment by glungtung** [comment]
Sur test.dodoc.fr les flèches disparaissent de la même façon pour moi

**Comment by louis-ev** [comment]
Oui, je pense voir pourquoi. Je m’en occupe quand j’ai le temps.

**Comment by louis-ev** [comment]
Tenté de résoudre le soucis, ça devrait être moins capricieux.
À tester : tous les cas de figure un peu particuliers type : une recette "récit" en mode réponse avec des formats très particuliers à remplir.
Assez chaud à implémenter et tester… !

Je rapatrie tout ça sur dodoc2-master, et je publie sur test.dodoc.fr en version 9.1.2
