### ISSUE TITLE
utiliser la réalité augmenté

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#623]
Scénario envisageable : 
- des balises sont imprimées et associées à des médias (photos, vidéos, sons, etc.) présents dans un dodoc local ou en ligne
- en ouvrant dodoc puis en cliquant sur le bouton QR, il y a plusieurs modes : scan d’un code QR (actuel) ou mode "réalité augmenté" (AR) qui affiche le flux de la caméra arrière de la tablette ou du smartphone connecté.
- lorsqu’un code QR est trouvé ou une balise imprimée est repérée en AR, affichage du contenu tout en restant dans le mode de scan. Un bouton permet de changer de page et d’aller éditer le média dans la modale dédiée dans do•doc.

**Comment by louis-ev** [comment]
Voir les exemples suivants : https://stemkoski.github.io/AR-Examples/
![image](https://user-images.githubusercontent.com/1948417/117440368-407c9a00-af34-11eb-9be5-04da18888b2c.png)

**Comment by jubonhomme** [comment]
Exemple du projet eTAC
https://twitter.com/57play/status/1359359802124738560

On peut en discuter ;)

**Comment by louis-ev** [comment]
Ah mais oui avec plaisir !
Le scénario que j’ai décris est assez proche du mode "jukebox" qu’on évoquait et pourrait aussi bien s’applique à l’utilisation de balises NFC / RFID d’ailleurs :)

**Comment by jubonhomme** [comment]
A fermer aussi ou tu conserves pour infos ?

- Les balises et même détection de visages fonctionne (projet masques)
![image](https://user-images.githubusercontent.com/29262866/203161105-68ebcd3a-a8cd-4160-8e7a-a9351178687f.png)

- Les balises géographiques fonctionnent aussi (projet Balades sonores à Malakoff )
L'entrée dans un périmètre géographique d'un appareil mobile géolocalisé peut déclencher un média...
J'attends ça dans dodoc avec une recette cartographique ;)

-Réseau Canopé avait réalisé un projet avec des balises bluetooth low energie qui déclenchaient aussi des médias... ça pourrait aussi compléter les types de balises prises en charge, comme les puces NFC
