### ISSUE TITLE
Montage vidéo 9.1.0 Stable et 9.1.1 Dev

### ISSUE THREAD

**Issue by PixnWave** [l-atelier-des-chercheurs/dodoc#624]
Bonjour,
La fonction montage vidéo ne fonctionne pas. Cela provoque une déconnexion du serveur.
j'ai le même problème ici https://dmn.do.doc.pixnwave.fr/frontiere et là https://test.dodoc.fr/cnc

**Comment by PixnWave** [comment]
testé avec Firefox et Chromium

**Comment by louis-ev** [comment]
Je te confirme le soucis, qui semble être côté serveur (analyse du fichier généré avec ffmpeg). Je creuse et reviens vers toi.

**Comment by louis-ev** [comment]
0d3f41123e3cbcce7cc5f79f260517c809a47a07
C’est corrigé, ça fonctionne sur test.dodoc.fr et déployé sur les branches **dodoc2-dev** et **dodoc2-dev-node**.

Ce bug nous a échappé avant la sortie de la v9, il va falloir sortir rapidement cette v9.1.1 du coup.

**Comment by glungtung** [comment]
Bonjour,
Merci beaucoup pour ce correctif.
Je me demande pour quelle raison la recette _Montage vidéo Nº2 MK Patrik_ ne fonctionne pas, ca répond "_La vidéo n'a pu être créée_". 
Probablement il y a un lien avec le fait que ca assemble 15 vidéos, le résultat serait trop lourd ?
Car avec seulement 2 vidéos, ca fonctionne. 
<img width="584" alt="Capture d’écran 2021-05-14 à 15 29 47" src="https://user-images.githubusercontent.com/457189/118265156-d2068180-b4c9-11eb-8133-03d39d699204.png">
Merci

**Comment by louis-ev** [comment]
C’est bien possible… L’instance de test en ligne n’est pas terriblement puissante et vu la quantité de vidéos à convertir et vu leur qualité, ça ne m’étonne qu’à moitié.
Pour évite que do•doc soit surchargé par des compilations vidéos (ce qui arrive malheureusement relativement souvent) il y a un timeout de 10 minutes : une tâche vidéo qui ne s’est pas terminée après 10 minutes est annulée.

C’est pas idéal, à terme (et pour la v10 si on trouve le terrain et les financements pour bosser là-dessus) il faudrait plutôt pouvoir répartir la charge sur la machine pour que ça ne ralentisse pas autant le serveur, et pour pouvoir avoir une idée plus précise des tâches qui tournent, pouvoir les annuler et les mettre en pause, etc.

Peux-tu tester sur un do•doc en local, sur une machine relativement puissante ? Les serveurs VPS en ligne sont vraiment pas très véloces générallement.

**Comment by glungtung** [comment]
J'ai essayé de faire marcher la branche dodoc2-dev sur mon mac mais je n'ai pas réussi

J'ai eu un probleme avec ffmpeg que j'ai dû installer manuellement car j'avais ca :
npm ERR!     Invalid: lock file's ffmpeg-ffprobe-static@4.3.1-rc.6 does not satisfy ffmpeg-ffprobe-static@*

Et au final, apres avoir suivi le guide troubleshooting sur github, ca ne se lance toujours pas 
`App threw an error during load
/Users/guillaume/dev/dodoc/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guillaume/dev/dodoc/node_modules/fs-extra/lib/mkdirs/index.js:3:44`

**Comment by jubonhomme** [comment]
dodoc2-dev est une version pour serveur il me semble.

Pour une version sur poste il faut utiliser ces versions 9.1 téléchargeables ici :
https://forum.latelier-des-chercheurs.fr/t/do-doc-version-9/320

donc pour MacOS :  http://files.latelier-des-chercheurs.fr/do•doc-9.1.0.dmg

**Comment by glungtung** [comment]
Merci @jubonhomme En fait j'essaie d'utiliser la version dodoc2-dev pour avoir les derniers correctifs, plus récents que ce qu'on a sur la 9.1.0. La version serveur finit par -node dans son nom (comme dodoc2-dev-node)

**Comment by jubonhomme** [comment]
Exact, j'ai lu trop vite

**Comment by louis-ev** [comment]
@glungtung peux-tu me dire sur quelle version de node tu tournes ?

**Comment by glungtung** [comment]
v12.18.3

**Comment by louis-ev** [comment]
Peux-tu supprimer le fichier `package-lock.json` et relancer `npm install` ?

**Comment by glungtung** [comment]
@louis-ev après avoir supprimé package-lock.json et refais la procédure décrite dans le troubleshooting sur ce github, j'ai toujours la même erreur. Je ne suis pas familier de cet environnement node, et j'ai du mal à savoir comment trouver ce qui pose problème.

**Comment by louis-ev** [comment]
Je pense vraiment que ça vient du package-lock, je l’ai nettoyé ( 6f426881cbdca1001744c745d215620cccfc52bd ), peux-tu retenter un npm install dans le dossier principal (et pas dans /public) ?

**Comment by glungtung** [comment]
Je suis à la racine du projet
- j'ai eu une erreur `Error: Cannot find module 'which-pm-runs'`
- j'ai tenté un `export NODE_PATH=/usr/local/lib/node_modules` mais ca n'a rien changé
- j'ai installé à la main  `npm install which-pm-runs`
- il sembble qu'il y a une erreur (404) avec sharp : 

>   • electron-builder  version=22.10.5
>   • loaded configuration  file=package.json ("build" field)
>   • rebuilding native dependencies  dependencies=platform-folders@0.5.2, sharp@0.26.3 platform=darwin arch=x64
>   • install prebuilt binary  name=sharp version=0.26.3 platform=darwin arch=x64
>   • build native dependency from sources  name=sharp
>                                           version=0.26.3
>                                           platform=darwin
>                                           arch=x64
>                                           reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
>                                           error=prebuild-install info begin Prebuild-install version 6.0.1
>     prebuild-install WARN install prebuilt binaries enforced with --force!
>     prebuild-install WARN install prebuilt binaries may be out of date!
>     prebuild-install info looking for cached prebuild @ /Users/guillaume/.npm/_prebuilds/eb86db-sharp-v0.26.3-electron-v85-darwin-x64.tar.gz
>     prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.26.3/sharp-v0.26.3-electron-v85-darwin-x64.tar.gz
>     prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.26.3/sharp-v0.26.3-electron-v85-darwin-x64.tar.gz
>     prebuild-install WARN install No prebuilt binaries found (target=11.0.3 runtime=electron arch=x64 libc= platform=darwin)
> 

- j'ai installé sharp à la main `npm install sharp`, ca fonctionne mais ca me fait toujours l'erreur 404 sharp au moment du `npm install`
- quand je lance `npm start` j'ai toujours la même erreur que j'avais cité dans un message précédent

Est ce que ca vaut le coup que je tente sur un autre ordi ? un autre mac ? un linux ?

Merci pour ta patience et ta persévérance @louis-ev

**Comment by glungtung** [comment]
Salut, c'est un MBP de 2016 avec BigSur.
je continue d'essayer des choses mais pour l'instant j'ai toujours la même erreur avec fs-extra

**Comment by louis-ev** [comment]
Probablement Big Sur… tant que j’ai pas fais la maj je suis un peu désemparé pour t’aider :(

Peut-être un soucis de permission ? fs-extra modifie les fichiers, ça expliquerai des choses.
Trouver des exemples utilisant fs-extra et voir si ça fonctionne. Y a un dossier test ici : https://github.com/jprichardson/node-fs-extra
Ça se tente ?

**Comment by louis-ev** [comment]
Oui ça devrait !
Je vais exporter tout ça semaine pro :)

**Comment by louis-ev** [comment]
Et hop : https://forum.latelier-des-chercheurs.fr/t/do-doc-version-9/320

**Comment by louis-ev** [comment]
Du coup je ferme mais si besoin n’hésitez pas à rouvrir une nouvelle issue.
