### ISSUE TITLE
curseur vidéo bloqué

### ISSUE THREAD

**Issue by glungtung** [l-atelier-des-chercheurs/dodoc#625]
Bonjour,
Lorsque je lis ma vidéo capturée dans dodoc, mon curseur de temps ne bouge pas
Pourtant sur certaines vidéos (notamment une que j'ai importée), le curseur fonctionne correctement
Dans l'image ci dessous je suis à 00:08
<img width="1494" alt="Capture d’écran 2021-05-14 à 16 06 46" src="https://user-images.githubusercontent.com/457189/118269231-8951c700-b4cf-11eb-8c4d-c77cb86a2858.png">
Peut être est ce lié au format webm ?

**Comment by louis-ev** [comment]
Oui, c’est lié au fait que l’enregistrement avec les codecs du navigateur se fait de manière continue. Le fichier final ne connaît pas sa durée complète, et est donc incapable de gérer le curseur de la vidéo.
Pour corrigé ça, tu peux ouvrir le menu AJUSTER et cliquer sur OPTIMISER, ce qui recompilera une vidéo bien propre et compatible avec tous les appareils (mp4 en h264). Ce n’est pas fait d’office parce que ça consomme pas mal de ressources et ça pourrait mettre à genoux une machine peu puissante si plusieurs vidéos sont optimisées en même temps.
