### ISSUE TITLE
Bug ajustement de la vidéo 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#631]
Dans la bibliothèque de média, si je clique sur "Ajuster" puis "Optimiser la vidéo", après l'optimisation de la vidéo la fonction "Raccourcir" ne fonctionne pas. Il est possible de choisir une position de début et une position de fin, de valider le raccourcissement de la vidéo, le process se lance bien mais arrivé à terme, la vidéo n'a pas été raccourcie.
Testé dans l'autre sens: d'abord "Raccourcir la vidéo" puis "Optimiser la vidéo" et ça fonctionne.

**Comment by louis-ev** [comment]
Je ferme, si besoin rouvrir après test sur la v10 :)
