### ISSUE TITLE
Rendre la fonctionnalité traduction plus visible

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#635]
À l’arrivée, proposer de traduire l’interface de manière plus visible — la placer directment au niveau des boutons en haut à droite ? FR / EN / DE / etc. qui s’affiche ?

<img width="336" alt="image" src="https://user-images.githubusercontent.com/1948417/132025506-e4549b58-e924-4dc7-90f8-541dfb92b19a.png">

**Comment by jubonhomme** [comment]
A fermer ?
C'est fait sur la version 10
![image](https://user-images.githubusercontent.com/29262866/207713626-2aa6390f-e1a1-49df-b7fc-747e705134e4.png)

**Comment by jubonhomme** [comment]
A propos de la traduction, Christophe voulait te recontacter pour te proposer de réaliser la traduction de la v10 en allemand avec ses élèves

**Comment by louis-ev** [comment]
Je viens d'implémenter la fenêtre de sélection de langue
<img width="636" alt="image" src="https://user-images.githubusercontent.com/1948417/208446172-370c6148-a86a-42e2-bc34-8946c3ea4caa.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1948417/208446178-c36c3389-68ef-4941-ba5a-fb231498b48e.png">
<img width="601" alt="image" src="https://user-images.githubusercontent.com/1948417/208446184-7bec5213-89bf-4d1f-a54b-76c80ccbc408.png">

Du coup je ferme.
