### ISSUE TITLE
Problème aperçu STL

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#640]
Sur les dernières versions 9.1.2 pour postes de travail (Win ou linux) l'aperçu STL fonctionne bien en mode interactif mais pas l'aperçu image.
Du coup, c'est aussi non visible sur une recette page à page exportée en pdf

Par contre il n'y a pas ce problème sur une version "serveur" de dodoc

![image](https://user-images.githubusercontent.com/29262866/146187828-8d16a199-4395-4334-86b9-e2c35f11dcb5.png)

![image](https://user-images.githubusercontent.com/29262866/146187916-31ee4d8a-4f4f-43c2-be32-97d3958b17f2.png)

![image](https://user-images.githubusercontent.com/29262866/146187970-b9146ffd-ce09-4efe-8ddc-97be6ea76f83.png)

**Comment by jubonhomme** [comment]
Je viens de voir que ça vient probablement d'un problème de cadrage de l'objet.

Dans mon dodoc 9.1.4 en local, l'aperçu image est tout blanc mais si je passe en mode interactif et que je recule avec le zoom je finis par voir l'objet. 
![image](https://user-images.githubusercontent.com/29262866/164290069-95c5aefc-9392-46e4-ac23-54add5f49be3.png)


Sur test.dodoc l'aperçu image fonctionne mais est différent de l'aperçu image de la version locale. 
Voir ici pour les fichiers test : https://test.dodoc.fr/test-stl-1
On voit que sur la version interactive il faut aussi reculer avant de voir la pièce. Le fichier STL n'est pas bien centré sur la pièce
![image](https://user-images.githubusercontent.com/29262866/164289992-b9f48e9d-3ded-4668-b58d-9b87f9368ca2.png)


C'est donc peut-être simplement un réglage différent du cadrage par défaut de l'objet.

**Comment by louis-ev** [comment]
En fait la dépendance que j'utilise pour la version electron/appli est vue-3d-model : https://hujiulong.github.io/vue-3d-model/#/demo-basic
En ligne : node-stl-to-thumbnail : https://github.com/fakhrullah/node-stl-to-thumbnail

Il me semble que node-stl-to-thumbnail s'en sort mieux, non ?

**Comment by jubonhomme** [comment]
OK je comprends mieux pourquoi il y a une différence d'affichage.

J'ai enfin résolu le problème de cadrage en ouvrant les pièces sous tinkercad et en les enregistrant à nouveau pour les importer.
Le centrage se fait bien sur la pièce et la rotation dans l'outil interactif se fait correctement. Par contre l'affichage de l'aperçu image est toujours blanc en local.

Donc oui la version en ligne s'en sort bien mieux pour l'aperçu image, et c'est important car c'est cet aperçu qu'on voit en premier dans les recettes.

**Comment by jubonhomme** [comment]
A fermer ?
Si dodoc 10 utilise node-stl-to-thumbnail ça devrait fonctionner correctement.

**Comment by jubonhomme** [comment]
En lien avec #560

**Comment by jubonhomme** [comment]
je pensais fermer cette issue sur les stl mais je viens de trouver autre chose :)
Quand on utilise le mode 3D dans une publication on déplace la page en même temps.

A voir en vidéo ici 
https://test10.dodoc.fr/+espace/mon-projet?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100,%22focus%22%3A%22video-1689113254550-2q4-1.webm.meta.txt%22%7D%5D

**Comment by louis-ev** [comment]
Corrigé ! ça le faisait aussi avec la molette (zoom dans le modèle 3d + zoom dans la page), c'est corrigé aussi
