### ISSUE TITLE
barre d’information d’une recette : il y a deux fois l’option suppression

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#650]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1948417/157054280-9a482fa0-c950-4c51-9750-736fd0d00c24.png">

**Comment by jubonhomme** [comment]
A fermer ?

**Comment by jubonhomme** [comment]
![image](https://user-images.githubusercontent.com/29262866/202817924-0ab327f2-c5e8-420a-8e13-edbff2c9ca88.png)
