### ISSUE TITLE
Option raccourcir un média masque la barre de lecture

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#651]
Utilisation de l'outil : Ajuster / Raccourcir
voir le sujet sur le forum :
https://forum.latelier-des-chercheurs.fr/t/raccourcir-un-son-capture/365

Si le ratio de l'écran est très large, le bloc pour raccourcir un son ou une vidéo masque la barre de lecture. La barre de lecture n'est plus utilisable. Il faudrait empêcher la superposition.

![image](https://user-images.githubusercontent.com/29262866/157483049-3e5f62ee-a1fb-4dbc-8ab0-f7db5d3ad95c.png)

**Comment by jubonhomme** [comment]
Est-il possible de placer cette fenêtre popup en haut à gauche au lieu de la placer en bas ?

Le graph est moins important que la barre de lecture.
C'est peut-être le plus simple pour régler le problème sans trop se compliquer pour cette version 9

**Comment by louis-ev** [comment]
ça vaut le coup de faire un maj de dodoc 9 tu penses ? Facile à résoudre mais re-fabriquer les applis c'est assez long
