### ISSUE TITLE
pouvoir pivoter une image dans la recette modifier une image

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#654]

**Comment by FabLabEcoCentre** [comment]
Hello

Quand je vais dans "Modifier une image" je ne peux pas la pivoter : un symbole "interdit" apparait sur mon curseur si je vais sur ces deux boutons de rotation :'(

**Comment by jubonhomme** [comment]
Effectivement ces deux boutons verts sont inactifs. Mais j'ai l'impression que ça correspond plus à revenir en arrière et refaire une action (ctrl Z / ctrl Maj Z ) Non ?

**Comment by jubonhomme** [comment]
Est-ce qu'il est possible de reprendre directement le code de la publication page à page ?
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/8fd9198d-46e5-4941-a8bc-ad44f2efae58)

**Comment by jubonhomme** [comment]
Et tant qu'on y est reprendre aussi les fonctions miroir vertical et horizontal de la partie capter ?
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/374473f6-9a5e-4bc4-9cc0-601ec4961b8c)

**Comment by louis-ev** [comment]
Le code n'a rien à voir, j'utilise pas le même système…
Par contre retourne en miroir c'est très simple !
C'est la rotation qui complique

**Comment by louis-ev** [comment]
En fait le miroir c'est pas très simple, ça clash avec le recadrage.
Je crois qu'on va repousser 10.1…

**Comment by jubonhomme** [comment]
ok autant le faire proprement plus tard.

**Comment by jubonhomme** [comment]
un petit up pour cette fonctionnalité qui serait bien pratique.
Dans une publication page à page pas de problème on peut le faire directement dans la page.
Mais j'utilise maintenant beaucoup plus les récits que je trouve plus pratique pour de la publication en ligne.
Et sans la rotation dans la partie fabriquer c'est pas simple avec des images issues de tablettes qui n'ont pas la bonne orientation.
Si on pouvait au moins avoir la rotation par 90° comme dans la V9 sans forcément l'avoir au degré ce serait déjà pratique.

**Comment by louis-ev** [comment]
Ok, je me repenche là-dessus dans le mois.

**Comment by jubonhomme** [comment]
Une petite capture d'écran sur la version de test en cours
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/8d2ae320-8545-468c-ac69-e05431798391)

une image verticale rentre bien maintenant dans la fenêtre sans devoir descendre :+1: 

Si on peut gagner encore un peu de place en haut pour avoir une image de départ un peu plus grande ça serait parfait.
Les poignées sont assez discrètes en traits blancs, si tu as moyen de les mettre en jaune par exemple comme sur la v10 actuelle pour les rendre plus visibles.
Le deuxième écran avec les niveaux est très bien aussi.
Peut-être ajouter un "cran" sur les barres avec curseur à 100% pour revenir plus facilement à l'origine.

Dernière chose, est-ce que le fil d'ariane en haut "  1-Recadrer / 2-Ajuster / 3-Exporter" ne pourrait pas servir directement de boutons à la place de "Précédent / suivant" en dessous. 
On reprendrait l'idée des bouton "capter / collecter / fabriquer / publier " 
ça gagnerait la barre en dessous et on les regroupent tous les boutons en haut.

Exemple de navigation : 
dans le média je sélectionne Option / recadrer 
La fenêtre s'ouvre avec les boutons en haut en couleur avec   **1-Recadrer** / 2-Ajuster / 3-Exporter
Je recadre l'image et je peux cliquer directement sur ajuster ou exporter
si je clique sur ajuster j'arrive sur la deuxième fenêtre avec les curseurs, si je clique sur exporter ça affiche au milieu de la fenêtre (ou en haut à côté)  : 
Annuler / Enregistrer comme nouveau média / remplacer et supprimer l'original

**Comment by jubonhomme** [comment]
Un exemple de ratio proposés sur shotwell sous ubuntu
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0269c210-18c6-440a-9c3b-c37d0339a518)

**Comment by jubonhomme** [comment]
Un petit bug d'affichage des nombres dans le menu : le troisième chiffre n'est pas visible

La liste déroulante des ratio d'image pour le recadrage est en blanc sur fond gris clair et n'est donc pas lisible.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/1ff12bdb-d5a4-4c8a-9224-430a974f526b)

**Comment by jubonhomme** [comment]
Pour l'affichage des pourcentages c'est bon !
![image](https://github.com/user-attachments/assets/a240dc95-76d0-4c83-88f9-7c1b5001b608)
