### ISSUE TITLE
Créer Récit - mauvaise configuration droits

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#656]
Bonjour,

Pour une recette page à page avec :
- Qui peut contribuer : Seulement les auteurs 
- Consultation : Visible par tout le monde

Un utilisateur non autorisé pour les modifications peut quand même "créer" un export en pdf / partage / export web.

Par contre avec les mêmes réglages des droits sur un Récit c'est bloqué.
On ne peut donc pas créer le récit et récupérer l'URL de partage ou le code QR

![image](https://user-images.githubusercontent.com/29262866/160506269-4aabf74a-d38a-4d03-91b6-ea6f4a505163.png)

**Comment by louis-ev** [comment]
> Un utilisateur non autorisé pour les modifications peut quand même "créer" un export en pdf / partage / export web.

Tu es sur ? Sur test.dodoc, si je clic sur le bouton **créer** pour une recette page à page dont je ne suis pas auteur, ça me dit "Cette action n’est pas permise. Êtes-vous bien auteur de ce contenu et/ou possédez-vous le mot de passe associé ?"

Tu voudrais qu’un utilisateur non autorisé pour les modifications puisse quand même "créer" un export en pdf / partage / export web ?

**Comment by jubonhomme** [comment]
Bonjour,

Ce qui me semble logique c'est que si je sélectionne :
    Qui peut contribuer : Seulement les auteurs
    Consultation : Visible par tout le monde

Alors les personnes non autorisées ne peuvent pas modifier ma recette (Page à page / Récit / Montage vidéo...) mais par contre qu'elles puissent générer une nouvelle vue "Partage" ou un export PDF ou un export vidéo dans une autre qualité. Si je dis visible par tout le monde pour les recettes c'est surtout pour les exports, plus que pour un aperçu simple dans la marmite de dodoc.

**Comment by jubonhomme** [comment]
Je viens de refaire un test sur ce sujet des droits de création ou non de publications.
En fait même sur une recette page à page sur laquelle je n'ai pas de droit en modification et donc le bouton "Créer" n'est pas actif, je peux quand même avec le nom de la recette retrouver l'URL du partage en ligne.
Exemple en suivant la construction des URL  : https://test.dodoc.fr/_publications/nom-de-la-recette

Donc je vois comme solutions : 
- soit on enlève complètement le bouton "créer" dans le bandeau des recettes pour lesquelles on n'a pas le droit de modification. Mais que devient intérêt de donner la visibilité à une recette dans dodoc sans pouvoir donner accès à une vue propre de cette recette en pdf / partage ?

- soit on considère que "créer" une publication c'est juste un affichage différent de ce qu'on voit dans dodoc et que ça n'est pas une modification de la recette et de la publication elle même. Donc je peux bloquer la modification de mes recettes mais ça autorise les personnes qui ouvrent ma recette à créer le pdf ou le partage.

**Comment by jubonhomme** [comment]
Si la version 10 de dodoc sépare les remix et les publications (exports) se sera déjà plus simple pour gérer les droits. 
Les recettes remix peuvent être bloquer pour éviter les modifications
Les publications peuvent être accessibles sur dodoc (visible par tous) ainsi que ses différents exports (code QR / partage / pdf ...)

**Comment by jubonhomme** [comment]
gestion des droits entièrement revue sur la version 10
Je ferme
