### ISSUE TITLE
Légendes médias dans recette Récit

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#657]
Bonjour,

Serait-il possible d'avoir 

1- la possibilité de choisir l'alignement des images (gauche / centré / droite)  dans une recette récit, avec un petit menu qui s’afficherait au survol comme pour le texte 
![image](https://user-images.githubusercontent.com/29262866/160509821-6bdf8ce1-529f-434e-9614-01a925cb08e2.png)

Par défaut toutes les images sont alignées à gauche
![image](https://user-images.githubusercontent.com/29262866/160509745-7ea168a4-8e8f-4ecd-8c7e-af2923537cb3.png)

2- la possibilité de grossir l'image dans la version publiée en partage. Un clic sur l'image ça l'ouvre en plus grand dans une fenêtre et deuxième clic dessus ça revient à la taille initiale dans le récit. C'est le cas pour les vidéos avec les flèches du player pour l'avoir en plein écran, mais pas pour les images.

**Comment by jubonhomme** [comment]
Je reprends cette demande pour les recettes de publication sur la dodoc 10. 

- Avoir la possibilité d'aligner les images : à gauche / au centre / à droite
- Pouvoir mettre une image en plein écran en cliquant dessus et la réduire à sa taille d'origine avec un second clic

**Comment by louis-ev** [comment]
Yes ! excellente idée.

Petite question à ce sujet : quelle règle pour les légendes ? Reprendre les légendes rédigées dans la bibliothèque est-il une si bonne idée ?

Plusieurs possibilités/propositions : 
- ne pas reprendre la légende de la bibliothèque, pouvoir en rédiger une spécifique à chaque intégration du média dans une publi
- reprendre systématiquement celle de la bibli si celle de l'intégration n'existe pas
- comme actuellement, reprendre celle de la bibli et pour la modifier il faut se rendre dans la bibli, ce qui modifie pour toutes les intégrations
- afficher la légende du média + en option une deuxième légende, spécifique à l'intégration
- afficher uniquement celle de l'intégration, et à l'édition proposer de copier automatiquement le contenu depuis la légende dans la bibli

**Comment by jubonhomme** [comment]
Je renomme cette issue car les médias peuvent maintenant (V10) être alignés à gauche / centrés / alignés à droite

Reste donc LA question des légendes.

**Comment by louis-ev** [comment]
En place, à tester ! 
<img width="802" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/736b5271-db1a-492f-97d4-aef835c07af9">

<img width="349" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/bf998da9-7701-4dd7-8a6c-4bb74bb1c306">

<img width="573" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/f8ac46f6-5ac8-4250-b6b2-cc7874e83b59">

<img width="596" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/2e7e5c71-482b-4735-ad04-a250b9428ad5">

<img width="481" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/0934c551-1f97-4634-a3d4-f29564b2ff18">

**Comment by louis-ev** [comment]
je ferme
