### ISSUE TITLE
Option pour masquer les pages sur un partage

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#660]
Peut-on imaginer une option pour masquer la bordure des pages sur une recette page à page lorsque qu'on la partage en ligne ?

L'idée est de pouvoir avoir un rendu plus proche d'une page web et moins d'une page de document type pdf ou diaporama.

Exemple de publication :
https://dodoc.reseau-canope.fr/_publications/semaine-je-fabrique-mon-materiel-pedagogique-2022/

J'aimerai un rendu comme celui ci, assez proche d'une recette page à page ou récit mais sans les bordures
https://fabriqueedu.tierslieuxedu.org/
ou celui là https://fabriqueedu.tierslieuxedu.org/

**Comment by louis-ev** [comment]
Toujours applicable ?
