### ISSUE TITLE
Ajout d'une recette "Cartographie"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#661]
J'utilise assez souvent le service Umap pour faire des cartes personnalisées.

Pour intégrer des médias dans une carte Umap avec les fonds OSM, il faut en amont mettre les médias sur un serveur pour générer une URL à intégrer dans Umap.
Image -> serveur -> intégration dans Umap

Maintenant que nous possédons une instance de dodoc en ligne, les médias dans dodoc pourrait être utilisés directement dans Umap.
Mais en voyant le rendu cartographique de l'outil "Calepin" je me dis qu'ajouter une recette cartographique à dodoc serait vraiment intéressant dans plusieurs projets (exemple "classe dehors" Carto sensible avec sons ) et rendrait la cartographie encore plus simple.

On pourrait imaginer une recette proche de page à page mais avec le fond OSM à la place de la page.
On se déplace sur la carte / Zoom/dézoom  et on glisse les médias du projet sur le fond de carte.
On peut rajouter du texte et des tracés

![image](https://user-images.githubusercontent.com/29262866/161645247-d73309d1-2768-4ac7-a685-167bfd262994.png)

Cette recette cartographique pourrait ensuite être partagée directement par une URL en plein écran (comme Umap) ou intégrée comme un bloc dans un récit ou dans un page à page (comme une iframe de Umap)

Exemple d'une carte Umap dans une recette page à page
https://dodoc.reseau-canope.fr/_publications/semaine-je-fabrique-mon-materiel-pedagogique-2022/

**Comment by jubonhomme** [comment]
Et en rêvant un peu...
Les médias qui contiennent des métadonnées avec Coordonnées GPS se place sur la carte au bon endroit si on les ajoute (flèche verte) et on peut ensuite les déplacer sur la carte si besoin.

**Comment by louis-ev** [comment]
Merci pour la proposition détaillée :) 
J’y réfléchis depuis un moment, et Calepin m’a permi de bien tester tout ça.
Je test aussi protomaps en ce moment, un outil intéressant pour les devs et une alternative à OpenLayers (que j’utilise pour Calepin). Le soucis est que tout ça nécessite un accès internet, alors que l’idée est que dodoc puisse marcher entièrement hors ligne. Mais si c’est bien expliqué je pense pas que ça soit trop grave.

**Comment by jubonhomme** [comment]
Oui pour le temps / terrain / budget... 

Pour le côté connexion obligatoire, effectivement ça pourrait être un frein à certains projets.
Mais tous les projets de ce type sont des projets en ligne (Umap, Géoportail, etc...), sinon on pourrait imaginer importer une tuile d'OSM et ensuite travailler en hors connexion, un peu ce que permet QGIS par exemple. Mais il faut quand même avoir une connexion à un moment pour télécharger le fond géo-référencé.

Si je prends comme exemple des projets que j'ai fait, il y a deux types :
- l'image de fond est un simple JPG et je dessine dessus avec Inkscape par exemple, mais c'est fixe et plus pour impression.
- l'image de fond est une carte dynamique et j'utilise un service en ligne pour cartographier dessus, souvent Umap, le rendu est plus un partage de carte dynamique en ligne.

**Comment by jubonhomme** [comment]
Un petit retour de projet carto avec affichage de médias.
Un collègue cherchait un outil carto pour faire un atelier d'écriture collaborative sur une carte, façon cartographie sensible.
uMap correspondait presque au besoin mais cet outil n'est pas modifiable de façon synchrone.
Il a trouvé et utilisé "Facilmap" pour son atelier. C'est synchrone mais les possibilités de médias sont limités par rapport à uMap.

Une recette carto sur dodoc en modification synchrone et un rendu comme le projet Alice à Malakoff seraient justes parfait ;)

**Comment by louis-ev** [comment]
Un lien intéressant pour le "projet carto" : https://felt.com/product
L'interface a l'air chouette et bien fichue.

**Comment by jubonhomme** [comment]
Je ferme celui ci ;)
Tout ce qu'il y a dans mon premier post y est et même plus
