### ISSUE TITLE
Création de projets : simplifier la modale

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#665]
Déplacer la création de mots de clés et certaines autres options a la page projet, pour alléger la modale

**Comment by jubonhomme** [comment]
La fenêtre de création se limite au titre et à l'option "Privé", tout le reste est maintenant dans les métadonnées du projet sur le panneau de droite.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/dd6c345c-f2b5-42fe-8adf-2009cc19c8e6)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/3fb3c62c-327e-4ed8-94cc-c52299c2c085)

**Comment by jubonhomme** [comment]
A fermer ?
