### ISSUE TITLE
Gestion de la tranparence des PNG SVG

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#668]
Est-il possible d'ajouter la gestion de la transparence des images PNG ou SVG dans les recettes page à page, comme c'est le cas pour les textes ?

**Comment by jubonhomme** [comment]
C'est un peu la même demande que #703 je pense

**Comment by louis-ev** [comment]
En place sur la v9.3.7-dev (voir le sujet dédié sur le forum)

**Comment by jubonhomme** [comment]
Cool ça marche sur la V9... reste à le rajouter à la V10
![image](https://user-images.githubusercontent.com/29262866/222280763-231d5d27-cf7f-4205-a493-b5ddafefc346.png)
