### ISSUE TITLE
Bug son+video

### ISSUE THREAD

**Issue by olerun** [l-atelier-des-chercheurs/dodoc#675]
Bug constaté sur do•doc version 9.1.2-dev sur serveur, itéré sur la version 9.3.1-dev
Soient une vidéo1 de 5s et un son1 de 10s ; la recette son+vidéo permet d'obtenir une vidéo1 sonorisée avec un plan fixe final de 5s.
Impossible de conserver ce résultat lorsqu'on utilise la vidéo1 en début (ou milieu) d'une recette Montage vidéo : la piste son est décalée (retard de 5s) par rapport à la vidéo / les 5 dernières secondes de la piste son1 dépassent sur la vidéo2.
Exemple [ici](https://test.dodoc.fr/bug-son-video)

**Comment by jubonhomme** [comment]
A tester avec la nouvelle version 10 quand la recette montage sera active

**Comment by jubonhomme** [comment]
La recette est réactivée, à tester ici 
https://test10.dodoc.fr/

**Comment by louis-ev** [comment]
J'ai repris le code ffmpeg de la v9, il y a des très grandes chances pour que ce bug existe toujours.

Après un peu de recherche, la solution semble se trouver par ici : https://ffmpeg.org/ffmpeg-filters.html#apad

> Pad the end of an audio stream with silence.

**Comment by louis-ev** [comment]
Déployé sur test10.dodoc.fr la recette mix audio + vidéo avec `apad` dedans. à tester donc :)

**Comment by jubonhomme** [comment]
Ah mais il faut aussi la recette montage pour tester si ça décale le son dans le montage

**Comment by louis-ev** [comment]
Après le retour de la recette montage en v10, je confirme que le soucis est toujours là !
Argh.
Le flux audio et le flux vidéo ont des longueurs différentes.
La plupart des réponses que je trouve sur le net disent "utilisez le flag -shortest", ce qui revient à couper la fin du son ou de la vidéo la plus longue pour correspondre à la plus courte – mais c'est pas ce qu'on veut…
Du coup je suis un peu coincé, je n'arrive pas à trouver comment m'y prendre pour le moment.

**Comment by jubonhomme** [comment]
J'imagine que dodoc utilise les sources de la vidéo et du son mais pas directement l'export / résultat de ce premier montage. 
Est ce que si on force un premier rendu (export) de ce montage pour l'utiliser comme brique dans le montage avec d'autres vidéos ça ne répond pas au problème ?

**Comment by louis-ev** [comment]
En fait si : dodoc part du fichier mp4 généré par la recette mix audio et vidéo, et la réencode dans la résolution/bitrate demandés (pas encore réglable dans la v10, c'est que 1280*720 6000kbps pour l'instant) en format TS.
Puis quand toutes les sources ont été préparées en TS, assemblage en reencodant et en appliquant le filtre qui gère les transitions vidéo et audio.
Pour la première conversion je récupère la durée la plus longue entre l'audio et la vidéo et je règle la durée du fichier mm4 créé avec cette valeur — mais les pistes audio ou vidéo que contient ce fichier restent d'une durée différente, ce qui pose problème derrière.
Je créer déjà une piste "vide" de la bonne durée mais visiblement c'est pas la bonne solution.

**Comment by jubonhomme** [comment]
OK je vois mieux le processus.
Et si tu écris la durée la plus longue comme nouvelle durée dans les métadonnées de chacun des fichiers et du résultat ?
Est-il possible de régler la durée d'un média ou tu peux le faire que sur le résultat ?

**Comment by jubonhomme** [comment]
Et si on décale le son du deuxième avec la différence de temps qu'on a entre le plus long et le plus court temps des deux pistes (vidéo ou son) du fichier vidéo 
Exemple  
Dans ce cas, vous devez utiliser le filtre adelay pour décaler le son de la deuxième vidéo. La syntaxe du filtre adelay est la suivante :

adelay=offset=X:duration=Y

L'argument offset indique le décalage en secondes. L'argument duration indique la durée du décalage.

Par exemple, pour décaler le son de la deuxième vidéo de 5 secondes, vous utiliseriez la commande suivante :

ffmpeg -i video1.mp4 -i video2.mp4 -filter_complex "concat=n=2:v=input_video1,input_video2 | adelay=offset=5:duration=0" output.mp4

**Comment by louis-ev** [comment]
Merci pour les recherches :)

J'ai une meilleure solution pour la situation ou l'audio dure plus longtemps que la vidéo : 
```
        if (audio_stream.duration > video_stream.duration) {
          // audio is longer than video, we need to pad video
          const diff = audio_stream.duration - video_stream.duration;
          ffmpeg_cmd.addOptions([
            `-vf tpad=stop_mode=clone:stop_duration=${diff}`,
          ]);
        } else if (video_stream.duration > audio_stream.duration) {
          // video is longer than audio, we need to pad audio
          ffmpeg_cmd.addOptions(["-af apad"]);
        }
```

C'est à priori mieux que adelay – le son démarre bien en même temps que la vidéo.

Et si la vidéo dure plus longtemps que l'audio le filtre `apad` semble faire le taf, mais il faudrait bien tester tout ça. Tu auras le temps de tester différents cas de figure ?

**Comment by jubonhomme** [comment]
Aucun problème pour faire des tests... ça je sais faire ;)

**Comment by louis-ev** [comment]
Je fais une todo des tests alors :) 
- capter une photo
- capter un son d'1 seconde
- capter un son de 5 secondes
- capter une vidéo  d'1 seconde 
- capter une vidéo  de 5 seconde
- enregistrer un stopmotion de quelques secondes

Puis
- créer toutes les combinaisons possibles de ces médias 
- tester un assemblage de l'ensemble, vérifier que le son ne "déborde" jamais ni n'est coupé (pareil pour la vidéo)

À noter que le petit bout de code qui "pad" ne s'applique que pendant le montage et pas sur la recette _son sur une vidéo_, mais qu'à terme ça serait pas mal de le faire aussi pour fabriquer une vidéo plus "propre", si la personne souhaite l'exporter.

Merci merci !

**Comment by louis-ev** [comment]
Une autre info : je génère un dossier dans le cache au lancement d'un export (exemple `/var/folders/4r/xqhz225d4nb1m4xyc5byx4gc0000gn/T/dodoc_cache/video_1700212337749-mvt`) qui accueillera les fichiers temporaires, générés puis utilisés pour la composition finale. 

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/7ef76d67-7318-42e5-8557-baea12fb08da)

Sur dodoc 9 je ne supprimai jamais ce dossier et il n'avait pas un nom aléatoire, de manière à ce qu'en relancant l'export d'une publi si les fichiers temporaires existaient déjà il ne les recréait pas (exemple : tu changes l'ordre de deux éléments sur 20 ou tu rajoutes une transition, c'est pas utile de tout regénérer et ça fait économiser des ressources et du temps).

Le soucis que j'ai : si je ne vide jamais ce cache, il prends progressivement bcp de place. Si je le vide au lancement de dodoc (ce que je fais sur la v9 et la v10), ça résout en partie le soucis mais pas sur une instance en ligne qui peut tourner des mois sans redémarrer… Qu'en penses-tu ?

**Comment by jubonhomme** [comment]
Ah oui ça risque d'être pire que les dossiers de corbeille niveau stockage.
C'est possible de mettre un intervalle de temps qui automatise ça ?
exemple : je vide le cache tout les 10 jours ?

**Comment by louis-ev** [comment]
Non :(

**Comment by jubonhomme** [comment]
Je crois que je l'avais déjà posé comme question en plus

**Comment by louis-ev** [comment]
Enfin si, c'est possible, c'est juste que j'ai pas du tout cette logique encore.
On peut imaginer une routine qui tourne tous les soirs à 2 heure du mat (heure locale du server) et qui réalise des opérations comme celle là – qui n'interfère pas avec l'utilisateur donc.

Nettoyer le cache : 
- à la fermeture de dodoc
- au lancement de dodoc (au cas ou ça ne s'est pas bien fait à la fermeture, genre fermeture forcée)
- toutes les nuits à 2h du matin

Ce qui semble prendre en compte un usage serveur + appli.
Qu'en penses-tu ?

**Comment by jubonhomme** [comment]
Oui ça me parait bien avec cette combinaison des 2 systèmes.

**Comment by jubonhomme** [comment]
Je refais quelques tests à partir de ta liste de "todo test"

Fabriquer "son + vidéo" : ça fonctionne bien si le son est plus court ou si la vidéo est plus courte que le son. Dans les 2 cas la création fonctionne.

Fabriquer "Image + son" : ça marche très bien 
sauf un bug sur le % d'avancement
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c9bc87f5-8711-4042-8e60-f50964d2b76e)


Fabriquer Montage : 
Montage = image + vidéo 5s : ça marche
Montage = (image + son 1s) + (image + son 5s) : ça marche
Montage = (vidéo 5s + image ) + image  : ça marche

Mais dès qu'on utilise des vidéos issues de fabriquer son+vidéo ça plante encore : 
image + (vidéo 1s + son 5s) : ça plante
(vidéo 1s + son 5s) + image : ça plante

**Comment by louis-ev** [comment]
Je viens de tester ton lien et ça marche ???
Est-ce que ça plantait directement ou ça s'arrêtait à un pourcentage ?

**Comment by jubonhomme** [comment]
Je viens de retester ce même lien, de mon côté j'obtiens ça
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/376aa397-2de8-431f-a7cc-445a3355b572)

**Comment by louis-ev** [comment]
Je sais pas quoi te dire…

<img width="418" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/
1948417/6fee6816-0003-4a31-a813-ca9f23c33a40">

Tu peux me faire une vidéo de ce qu'il se passe ? Merci !

**Comment by jubonhomme** [comment]
https://test10.dodoc.fr/+espace/test-son-video?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100,%22focus%22%3A%22video-1711636949041-r1y.webm.meta.txt%22%7D%5D

**Comment by jubonhomme** [comment]
Je viens de charger le projet en local et ça passe.
J'ai essayé de reproduire avec un nouveau projet et tous les montages marchent aussi.

Je n'arrive plus à reproduire ce bug... tu as certainement corrigé

**Comment by louis-ev** [comment]
La mise à jour de ffmpeg a peut-être joué ? je ferme alors :)
