### ISSUE TITLE
dodoc V10 Auteur

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#684]
Un fil récap sur la partie AUTEUR de dodoc pour la feuille de route de la version 10 

Correction de bug
- identification NFC #667
- si on supprime une image vignette d'un auteur et qu'on enregistre ça tourne en boucle #639
- Problème d'affichage des tuiles projets si longue liste d'auteurs #561 

Demandes :
- Sous le menu déroulant "Rôles", précisez la différence entre chaque rôle #546
- Par défaut, replier le champ email qui est optionnel (= gain de place = plus clair) #546
- Ajout d'un champ pour le RGPD modifiable par les admins #494
- Création du compte admin à l'installation plus claire, par exemple un message pour signaler que le premier compte créé est admin #520 
- Système de récupération de mot de passe oublié #512 
- Rendre plus visible la "Recherche d'un auteur" #658
- dossiers auteurs / mot clé ? pour retrouver plus vite dans une liste d'auteur #474 
- Pouvoir s'identifier à partir d'un code QR et/ou avec NFC #330 
- Ajout d'Open badge dans la fiche auteur #589 #400 
- s'identifier à plusieurs auteurs sur une machine #475

**Comment by jubonhomme** [comment]
Je continue dans ce fil

**Comment by louis-ev** [comment]
Merci pour ce retour et ces propositions (en image !).

J'aurai bien évité d'avoir deux boutons dans la barre du haut, et je trouve toujours utile de pouvoir switcher "se connecter" "créer un compte" quand on réalise qu'on a déjà un compte ou qu'on ne s'est pas encore inscrit. mais je vois bien l’intérêt de fonctionner comme ça oui.

**Comment by jubonhomme** [comment]
Si on veux garder un seul bouton je préfère "Se connecter", c'est le cas qui arrivera le plus souvent. L’inscription c'est juste une fois.
On pourrait imaginer un seul bouton en haut avec "Se connecter" et le bouton glissière en bleu "Se connecter / Créer un compte" dans la fenêtre qui s'adapterait au niveau des champs à remplir si on glisse sur "Créer un compte"

**Comment by jubonhomme** [comment]
Je viens d'y repenser même si ce n'est pas forcément le bon moment, mais il faudrait garder en tête la possibilité d'interconnecter avec un système d'authentification de type annuaire académique / professionnel pour déployer dodoc sur un serveur et pouvoir utiliser les ID de personnes sur cet annuaire. 
Exemple connexion sur un ENT / un compte académique / Fédération ...

**Comment by louis-ev** [comment]
> la possibilité d'interconnecter avec un système d'authentification

J'y ai pensé oui, mais je ne maîtrise pas ces systèmes – on verra si/quand se présente la question :)
Vu que ça doit marcher hors-ligne aussi, la brique "auteur" native de dodoc sera toujours utile, mais elle pourrait être désactivée/remplacée si un autre système prend le relais.

> Si on veux garder un seul bouton je préfère "Se connecter"

Oui ok, faisons ça en attendant.

**Comment by jubonhomme** [comment]
Je continue dans ce fil sur le panneau de connexion

Est-ce que la liste des contributeur•rice•s a besoin d'être présente dans le volet de création de compte ?
Je vois l'utilité pour le volet "se connecter" pour cliquer sur son nom (utile si on oublie comment on s'est enregistré) mais je ne vois pas bien l'utilité dans l'autre volet. Ça gagnerai un peu de place et de clarté.

Et je mettrais bien en couleur (vert)  le bouton pour "créer" le compte 
![image](https://user-images.githubusercontent.com/29262866/211171503-bbbcb168-8c70-45a6-b4a5-f1fef53fe719.png)

**Comment by louis-ev** [comment]
TODO : liste des contributeurs devient un lien vers une page dédiée, plus pratique.
Ajouter un champ présentation pour un contributeur.
Ajouter un champ "localisation" avec carte OSM.

**Comment by jubonhomme** [comment]
Avoir une page individuelle plus détaillée (lien aussi avec OpenBadge)
Avoir une page générale des auteurs / structures

**Comment by louis-ev** [comment]
Est-ce que c'est ok de ce côté ? à part la localisation (qui peut arriver en 10.1) ?

**Comment by jubonhomme** [comment]
Oui, c'est bon pour ça

**Comment by jubonhomme** [comment]
on peut fermer ce fil récap à mon avis.
La plupart des issues sont fermées.
