### ISSUE TITLE
Simplifier l'export / la copie / l'impression des code QR

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#693]
Dans la version 9 de dodoc on peut très facilement partager du contenu par code QR en l'affichant à l'écran.

![image](https://user-images.githubusercontent.com/29262866/207975236-1ff584e1-4d8b-4c39-a95f-577a3d6728ed.png)

Il est possible de copier l'URL et de la coller dans un document.

Par contre si on veut imprimer le code QR pour le coller en version papier dans un document (cahier d'expérience / cahier d'élèves / affichage ...) ou si on veut simplement copier sous forme d'image pour le reprendre dans un autre document ça n'est pas simple.

Dans la version en ligne ou sur un navigateur, le clique droit permet d'enregistrer l'image
![image](https://user-images.githubusercontent.com/29262866/207976145-58da7a21-5e74-43e9-a148-45923b342bf3.png)

Par contre sur la version ordi le clique droit ne marche pas. Je contourne en copiant le lien URL et en le collant dans l'outil pour générer un code QR. J'obtiens une image que je peux télécharger.
![image](https://user-images.githubusercontent.com/29262866/207976624-c65b0ea0-125d-4d4e-83a7-f0a44b9163fc.png)

Les code QR peuvent uniquement servir à l'écran mais dans un certain nombre de cas j'observe les enseignants imprimer ces codes pour les coller sur un support physique (papier)
Est-ce qu'il serait possible de simplifier ça ?
Par exemple avec un bouton "copier l'image" sous le code QR comme pour le bouton copier sous le lien URL.

**Comment by louis-ev** [comment]
Sur la v10 il y a un bouton simple "télécharger ce code QR".
On peut imaginer aussi fabriquer un PDF à la volée, sur un format A4 par exemple, pour faciliter l'impression (comme le module "impression" de la carto en fait, avec jsPDF).
Ça aiderait ?

**Comment by louis-ev** [comment]
Cerise sur le serveur -> 10.1 :)

**Comment by jubonhomme** [comment]
Tout y est sauf la planche de code QR mais déjà dans une autre issue #979 

Je ferme donc ici
