### ISSUE TITLE
Affichage Publication dodoc v10

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#694]
Deux remarques concernant l'affichage sur la version 10 même si j'imagine que c'est en travaux ;)

<s>- Il me semblait que lorsque je cliquais sur un des boutons "Capturer/Collecter/Remixer/Publier" en bas de l'écran ça montait la fenêtre pour voir la page en question. Maintenant si je clique sur un bouton ça monte un peu la fenêtre juste assez pour voir qu'il y a quelque chose en dessous. La fenêtre ne remonte qu'au 2e clic</s>
 
![image](https://user-images.githubusercontent.com/29262866/208493238-efbccfe9-97b9-4796-8220-fad0de401ba3.png)

<s>- Si je ne suis pas connecté (= visiteur simple) sur un projet, je vois très bien la fenêtre descriptive du projet mais les publications ne sont pas visibles. Il manque un moyen de les mettre en valeur, surtout pour des personnes qui découvrent dodoc en visiteur et qui n'ont pas l'habitude de descendre sur cette page.</s>
![image](https://user-images.githubusercontent.com/29262866/208493851-5afb0a78-01a1-4cdc-b901-a30c253299e5.png)

**Comment by jubonhomme** [comment]
Autre remarque : 
Si je suis connecté je vois le nom du dossier en rappel dans le bandeau des boutons.
![image](https://user-images.githubusercontent.com/29262866/208550945-6596741c-974e-4105-bc2f-40b4f6d731de.png)

Mais si je ne suis pas connecté le bandeau des boutons disparaît, le nom du projet aussi. Ce serait bien de conserver le nom du projet visible pour que l'on identifie plus rapidement à quel projet correspondent les publications.

![image](https://user-images.githubusercontent.com/29262866/208551072-79819d54-ffa1-40f6-a1dc-b624ac9c4508.png)

**Comment by louis-ev** [comment]
J'avais raté ce retour. Je comprends, il faut voir parce que le reste de la barre horizontale est pas très pertinente pour les visiteurs. Je me note de tester ça :)

**Comment by jubonhomme** [comment]
Plus j'utilise la v10 et plus je me dis qu'on pourrait conserver le bandeau du haut dans l'affichage des pages.

![image](https://user-images.githubusercontent.com/29262866/213818665-bfbc5935-db00-4c05-b990-4412f28277e2.png)
![image](https://user-images.githubusercontent.com/29262866/213818722-d911adf2-db19-4e96-ab95-cd1eb788d1c4.png)

Je te rejoins sur la barre des menus qui n'est pas pertinente au dessus des publications pour une personne non connectée.
Par contre la barre du haut aurait l'avantage de revenir plus rapidement à un autre projet et indique aussi le fil d’Ariane pour se resituer les publications dans le projet.

**Comment by jubonhomme** [comment]
Je complète la proposition au dessus.

Actuellement, une personne non connectée voit la même chose qu'une personne connectée dans la partie de droite sur "visibilité", la seule différence est de ne pas pouvoir le modifier.
![image](https://user-images.githubusercontent.com/29262866/213944121-7cd84db2-3838-4195-a735-2743647dd070.png)

Je pense qu'on pourrait gagner de la place en supprimant cet affichage pour les non connectés. C'est plus un choix de la personne qui documente pour afficher ou non son projet et si oui dans quelle catégorie.
A la place, je reprendrais simplement le picto dans le fil d'ariane comme rappel de l'état du projet. En reprenant ce picto de la page générale projet on identifierait directement dans quelle catégorie de projet on se trouve.

En reprenant l'idée du post précédent on aurait toujours le bandeau du haut avec le fil d'ariane et la catégorie.

**Comment by louis-ev** [comment]
@jubonhomme peux-tu me dire ou on en est là-dessus ?

**Comment by jubonhomme** [comment]
On a bien avancé ;)

La fenêtre et le bandeau de publication sont clairs.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0009fa8a-538f-4c83-b0c9-c12a6cedefed)

- Mais quand on descend sur les publications on ne sait plus dans quel projet on se trouve.
D'où la proposition d'afficher dans le bandeau "publication" le nom du projet en rappel 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/66158a20-1be7-4165-b59a-5366c2120131)

- Quand on rentre dans une publication c'est mieux
On a le titre de la publication en haut dans le bandeau et le bouton pour partager. Très bien !
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/829ef2e4-a439-4881-8dad-91b21cd33917)



Quand on entre dans une page de la publication, le titre disparaît ainsi que le bouton partager, j'aurais presque laissé le bandeau en haut.
Le bouton de retour est aussi un peu trop discret. On pourrait le mettre en couleur pour mieux l'identifier
On peut se déplacer dans la page et même bien au delà, du coup on peut perdre assez facilement la page dans l'espace de la visualisation. Est-ce qu'on pourrait mettre une limite à la vue pour toujours voir la page ?
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/eb7d2409-908c-4ff2-b85b-aae6279d5087)

**Comment by jubonhomme** [comment]
Je pense qu'on peut fermer cette issue.
Il y a eu beaucoup d'évolutions et de nombreux points évoqués au dessus sont corrigés.
Le reste est trop général, on pourrait ouvrir d'autres issues plus spécifiques si besoin comme pour la zone de cadrage de la page pour ne pas se perdre dans l'espace de la fenêtre.

**Comment by louis-ev** [comment]
J'ai remis la barre de publication en haut : 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/c24b487f-eaa3-4902-bc4c-23232f9e73df)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/19caf25d-e55e-4646-8a33-675a007e12d8)

Je ferme, rouvrir si besoin :)
