### ISSUE TITLE
dodoc v10 Médias

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#698]
Un fil récap sur les médias de la partie "collecter"
Je liste ici ce qu'il reste à ajouter par rapport à la v9 et les demandes non encore fermées "issues" de la v9

<s>- Ajout d'une confirmation pour la suppression</s>
<s>- Ajout de boutons "précédent / suivant" pour naviguer plus facilement dans les médias lorsqu'on est dans la vue d'un média</s>
- Ajout des boutons "<s>télécharger / dupliquer </s> / partager"
- Ajout des mots clés
- Pouvoir <s>afficher les images en plein écran et</s> zoomer dessus
- Possibilité de faire quelques manipulations de base sur les images : bouton "modifier" qui envoie vers la partie remix ? #181 
- Flouter une partie d'une photo #326 
- Possibilité de découper les médias vidéos ou sons : bouton modifier qui envoie vers la partie remix ? #535

- Prise en charge des format STL (mode interactif) et des DXF #457 
- Sélection multiple de médias ( coche / touche ctrl / encadrement souris /... #456 
- Téléchargement d'une sélection #633 
-  Ajout de la géolocalisation dans les métadonnées pour une future recette cartographique ? #661 
-

**Comment by louis-ev** [comment]
Parfait merci ! Très utile :)

**Comment by jubonhomme** [comment]
Les vidéos en format vertical ne passe pas dans la fenêtre "collecter"

Exemple ici :
https://164.92.187.49:8080/projects/les-vosges/?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100,%22focus%22%3A%22projects%2Fles-vosges%2Fvid-20230121-135344-1.mp4.meta.txt%22%7D%5D

Dans une publication ça passe car on peut la centrer et la réduire à 33% par exemple.
https://164.92.187.49:8080/projects/les-vosges/?projectpanes=%5B%7B%22type%22%3A%22publish%22,%22size%22%3A100,%22folder%22%3A%22une-video%22%7D%5D

**Comment by louis-ev** [comment]
> Les vidéos en format vertical ne passent pas dans la fenêtre "collecter"

Tu peux retester ? J'ai remis [Plyr](https://plyr.io/).

> Ajout de boutons "précédent / suivant" pour naviguer plus facilement dans les médias lorsqu'on est dans la vue d'un média

Ajouté !

> dupliquer

À venir. Question : on reprends tous les champs meta tel quel ? Dans dodoc 9 je mettais juste à jour le champ "date_uploaded", la date d'envoi du fichier, pour reprendre la date actuelle. On refait pareil ?

> partager

Concrètement, l'url se met à jour automatiquement, je peux la reprendre et proposer aussi une URL vers le fichier direct (comme sur dodoc 9), avec la possibilité de demander à générer un code qr à partir de l'un ou l'autre.
Exemple : 
- https://164.92.187.49:8080/projects/les-vosges/?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100,%22focus%22%3A%22projects%2Fles-vosges%2Fvid-20230121-135344-1.mp4.meta.txt%22%7D%5D
- https://164.92.187.49:8080/projects/les-vosges/vid-20230121-135344.mp4

Ça fonctionne bien comme ça ?

**Comment by jubonhomme** [comment]
> Tu peux retester ? J'ai remis [Plyr](https://plyr.io/).

C'est tout bon !


> > Ajout de boutons "précédent / suivant" pour naviguer plus facilement dans les médias lorsqu'on est dans la vue d'un média
> 
> Ajouté !

Les boutons fonctionnent, est-ce qu'il est possible d'avoir les raccourcis clavier avec (flèche droite et gauche ) ?

> > dupliquer
> 
> À venir. Question : on reprends tous les champs meta tel quel ? Dans dodoc 9 je mettais juste à jour le champ "date_uploaded", la date d'envoi du fichier, pour reprendre la date actuelle. On refait pareil ?

Je dirais que oui tout pareil

idem pour le partage aussi

**Comment by louis-ev** [comment]
> Les boutons fonctionnent, est-ce qu'il est possible d'avoir les raccourcis clavier avec (flèche droite et gauche ) ?

Oui mais par contre je sais pas comment gérer si il y a plusieurs panneaux ouverts (par exemple, le panneau collecter et le panneau capture, ou les flèches changent le mode normalement…). Tu as une idée ?

**Comment by jubonhomme** [comment]
Si on prend en compte le panneau sur lequel est la souris ?

**Comment by jubonhomme** [comment]
Si on exclu les surfaces tactiles du fonctionnement avec des raccourcis clavier, on a toujours une souris ou un pad actif.
Donc le fonctionnement des flèches en fonction d'où se situe la souris ou le pointeur me semble le plus logique

**Comment by jubonhomme** [comment]
Les flèches pour passer d'un média à l'autre sont au dessus du bouton pour passer une image en plein écran

![image](https://user-images.githubusercontent.com/29262866/224487170-e715b8d9-b5f9-434c-992e-8d1abe643ae0.png)

**Comment by jubonhomme** [comment]
J'ajoute une remarque d'un collègue que je trouve intéressante pour protéger la casse involontaire d'une recette en supprimant involontairement un média utilisé.

Serait-il possible d'avoir un repérage visuel sur les médias qui sont utilisés dans une publication pour éviter de les supprimer en faisant du tri dans le panneau "collecter".
L'idée n'est pas de verrouiller la suppression mais bien de montrer que ce média est utilisé. 
Un peu comme sur la V9 ou l'on voit avec la flèche qui passe en orange quand le média est déjà dans une recette.
Soit avec un picto sur le média et/ou dans les métadonnées du média affichées à droite

Un exemple avec une petite étoile 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/2c9676ec-3cec-4a52-9461-debc4b6cf8a9)

**Comment by louis-ev** [comment]
> Serait-il possible d'avoir un repérage visuel sur les médias qui sont utilisés dans une publication pour éviter de les supprimer en faisant du tri dans le panneau "collecter".

J'avais raté cette idée, c'est un peu délicat pour que ça reste léger – notamment pour pas avoir à ouvrir toutes les publications pour avoir l'info, ce qui prendra beaucoup de ressources. Si l'info est stockée au niveau média, pas simple de retirer l'info à la suppression d'une publi. 
Alternative : lorsque suppression d'un média, dans la fenêtre de confirmation, chercher dans les publis si il est utilisé. Du coup cet appel (lourd) ne se fait qu'a cet endroit là. 
Pas mal de dev, v10.1 :)

Pour la v10, je dirai qu'il manque surtout le partage d'un média unique, en direct. Ou alors on considère que c'est dans uen publication, et on l'indique quelquepart (voir bouton pour créer rapido une publication public qui contient le média). Mais c'est peut-être pas l'idéal. ?

**Comment by louis-ev** [comment]
Je reporte à 10.1 ces discussions : pour partager un média, il faut l'inclure à une publication. Si les retours indiquent que c'est pas pratique, on fera autrement dans la 10.1.

**Comment by louis-ev** [comment]
Suggéré à l'instant : ajout des mots clés sur les médias, pouvoir filtrer par mot-clé.

**Comment by louis-ev** [comment]
On est presque à jour sur cette issue – peut-être que ce qui reste pourrait faire l'objet d'issues séparées ?

**Comment by jubonhomme** [comment]
Oui c'était pour regrouper un peu toutes les issues pour la V10 mais ça n'a plus vraiment de raison de garder cette issue "sommaire"

**Comment by jubonhomme** [comment]
Le partage direct de médias et les mots clés sont ajoutés, le reste est déjà dans des issues indépendantes.
Je ferme ce sommaire qui n'a plus vraiment d'utilité
