### ISSUE TITLE
Affichage curseur grille / bloc hors page / bouton ajouter une page dans publication uniquement pour les auteurs

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#702]
L'affichage de plusieurs éléments me semble plus correspondre à l'affichage pour les auteurs uniquement et pourraient être masqués pour les personnes non connectées : 
 - curseur de la grille
 - partie des blocs hors de la page
 - bouton "ajouter une page" 
 
A moins que ce soit voulu ?

![image](https://user-images.githubusercontent.com/29262866/214178307-30090c7d-4ce0-4a59-bdf9-0d9b143e9e9f.png)

![image](https://user-images.githubusercontent.com/29262866/214178149-edf41f6c-dddf-4f28-be66-18610cedd35b.png)

**Comment by louis-ev** [comment]
Ha oui non ce sont des oublis, je me le note !
