### ISSUE TITLE
Affichage sur petit écran 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#705]
Deux problèmes d'affichage sur petit écran : 

- chevauchement des textes dans le bandeau du haut
->  Il faudrait mieux passer sur 2 lignes

![image](https://user-images.githubusercontent.com/29262866/215293669-41814358-d429-44f2-a653-4e84da3de8ee.png)

- bandeau de gauche avec les boutons de déplacement des blocs écrasé par la fenêtre principale
-> Il faudrait mettre une largeur minimale au bandeau de gauche avec les boutons

![image](https://user-images.githubusercontent.com/29262866/215293758-9d6799ce-fed7-4733-ae9f-b2fc8c4cb05b.png)

**Comment by louis-ev** [comment]
>  -> Il faudrait mieux passer sur 2 lignes

J'aimerai vraiment éviter les écueils de la v9, avec un bandeau du haut qui prend pas mal de place sur mobile…
À voir si on ne peut pas réduire l'encombrement, voir simplifier ce fil d'ariane…

**Comment by jubonhomme** [comment]
Oui je te suis sur ce point.
Le logo dodoc en carré pourrait déjà gagner un peu de place sur mobile
![image](https://user-images.githubusercontent.com/29262866/222279440-97d4702a-25a7-44cf-ba30-5fbf4e9c3c6f.png)

On peut aussi gagner un peu de place en mettant un picto connecté avec la première lettre du nom à la place du nom d'auteur complet 

Idem pour le choix de la langue qui n'est pas forcément utile en continu

**Comment by louis-ev** [comment]
État des lieux un an après 😄 

écran large 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/d8953158-9aa9-4b39-845a-50016c0bdb70)

tablette
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/5f79950c-ac0f-490f-92dc-469c4c651292)

smartphone
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/6cc2bac2-1857-432b-83a4-62df2437ba0a)

**Comment by louis-ev** [comment]
Je réduis un peu la marge au-dessus/en-dessous pour faire une barre moins large
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/06a037e9-3a58-4314-9c01-a6d059c17176)

**Comment by louis-ev** [comment]
Autre possibilité pour désemcombrer : passer le fil d'ariane en seconde ligne. Peut-être une bonne idée aussi pour les plus grands écrans ? Qu'en pensez-vous ? @jubonhomme @JeFabrique-MaterielPeda ?

<img width="374" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/e6197e74-4de6-4468-a061-66b055bd1414">
<img width="1073" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/8d7da4bb-9e4c-4185-8bac-e05872627ba1">

**Comment by louis-ev** [comment]
Ok, alors je créer une branche avec cette modif (au cas ou) : dodoc2-next_topbar_breadcrumb
Et on verra en 10.1

**Comment by jubonhomme** [comment]
A fermer ?
