### ISSUE TITLE
Affichage capture panneau effets sous firefox

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#706]
Un bug à l'affichage du panneau des effets sous firefox

J'ai un décalage des titres et des curseurs

![image](https://user-images.githubusercontent.com/29262866/215361143-bcd08e05-fbb2-4a5e-a379-ec7d960126f2.png)

Sur chrome tout passe bien
![image](https://user-images.githubusercontent.com/29262866/215361264-f27e3473-6e6a-4c5d-811b-2048838bb6c5.png)

**Comment by louis-ev** [comment]
Corrigé

**Comment by jubonhomme** [comment]
Ok pour moi aussi
