### ISSUE TITLE
Capture son - bug sous firefox

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#707]
J'ai un problème de capture son sur firefox (ça marche bien sous chrome)

Le graph du son fonctionne bien et je vois que le micro fonctionne bien mais si j'essaie d'enregistrer j'ai ce message d'erreur

![image](https://user-images.githubusercontent.com/29262866/215361731-5bf28055-437d-4175-9d23-af3045e59555.png)

**Comment by louis-ev** [comment]
Résolu dans d1f3f782fe001b7b4554718ea3db7acbe39ca9d4

**Comment by jubonhomme** [comment]
C'est ok aussi sur mon firefox

Je ferme
