### ISSUE TITLE
Bug affichage Création de 1er bloc dans récit ou de 1er page dans publication

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#711]
Voir sujet dans le forum
https://forum.latelier-des-chercheurs.fr/t/etat-des-lieux-de-latelier-et-do-doc-version-10/395/111?u=julien

Normalement une fois que tu as créé une publication « Récit » tu devrais avoir un bouton + pour ajouter un 1er bloc avec un choix de texte ou de média

Sauf qu’il y a un bug et le bloc de texte n’apparaît pas directement. Ça fonctionne si on recharge la page. Ensuite ça marche bien mais l’affichage du premier bug.
Je t’ai ajouté sur ce projet si tu veux essayer de compléter le récit.

J’ai remarqué la même chose dans les recettes page à page. Lorsqu’on clique sur ajouter une page rien n’apparaît, du coup on clique plusieurs fois sans que rien ne se passe. Si on recharge la page (web) toutes les pages apparaissent enfin. Ensuite ça fonctionne normalement, c’est juste à la création.

Ce bug est présent sur Chrome et firefox.

**Comment by louis-ev** [comment]
Résolu dans 863890ef93c34190262c72ac796b5fedc313a602

Il manquait un caractère $ à un endroit stratégique :)

**Comment by jubonhomme** [comment]
J'ai toujours un bug sur la création d'une publication page à page
La première page n’apparaît que si on recharge la page après avoir ajouter une page
![image](https://user-images.githubusercontent.com/29262866/216791293-fdce88b1-0e27-466f-a952-aaa29d825500.png)

**Comment by louis-ev** [comment]
Tentative bis !

**Comment by jubonhomme** [comment]
J'attends que tu recharges pour tester ?

**Comment by jubonhomme** [comment]
C'est bon ça fonctionne !

**Comment by jubonhomme** [comment]
Est-ce qu'il ne serait pas plus rapide d'avoir directement une première page visible par défaut lorsqu'on crée une publication ?

**Comment by louis-ev** [comment]
Probablement oui, je change ça !

**Comment by jubonhomme** [comment]
C'était le fonctionnement de la V9, je trouvais ça plutôt bien

**Comment by jubonhomme** [comment]
Tout fonctionne !
Je ferme
