### ISSUE TITLE
Boutons panneaux capture Réglages / Effets

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#712]
Les boutons rouges sur fond rouge et noir sur bleu foncé sont peu visibles
![image](https://user-images.githubusercontent.com/29262866/216793911-1df78673-cdcf-4520-bc87-d95a6932ce73.png)

**Comment by jubonhomme** [comment]
Juste un petit coup de pinceau pour la couleur et on ferme ici ;)

**Comment by jubonhomme** [comment]
je remonte celui-ci qui doit pas être trop compliqué à finaliser pour le fermer ;)

**Comment by louis-ev** [comment]
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/2348e981-0365-4ae9-93f1-9dc9160fe113)

**Comment by jubonhomme** [comment]
Top pour les boutons de menu !

Mais quelques détails ;)

Est-ce qu'il est aussi possible de remettre en blanc les textes sur fond rouge ? 
Le noir sur fond rouge est moins lisible.

Et une dernière remarque sur le bouton Mise à jour qui est super important car il faut l'utiliser à chaque modification et je trouve qu'on le voit moins que le premier bouton du haut (sur cet appareil / dodoc distant qui sert assez rarement)

**Comment by louis-ev** [comment]
Couleur blanc ok, merci ça m'avait échappé.

J'ai viré le bouton update et on tente avec une maj automatique en changeant les réglages, c'est plus cohérent avec le panneau effets.

**Comment by louis-ev** [comment]
Si ça fonctionne bien chez toi tu pourras fermer ici ? Merci encore :)

**Comment by jubonhomme** [comment]
Très bien comme ça !
