### ISSUE TITLE
Agrandir les images ou médias dans les récits 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#715]
Sur les vignettes images des projets il y a un bouton en bas à gauche pour les agrandir en plein écran ou revenir à la page projet.
![image](https://user-images.githubusercontent.com/29262866/220754316-214b263d-15b6-49d5-a516-cc1250dd1b4d.png)

Est-ce qu'il serait possible d'ajouter ce même bouton sur les médias des récits ? 
Comme les récits sont principalement pour un affichage sur écran on pourrait agrandir une image si on veut la voir en grand et revenir à l'affichage du récit.

**Comment by jubonhomme** [comment]
Voir aussi celle-ci #493

**Comment by louis-ev** [comment]
Question : est-ce que toutes les images (apercu d'un projet sur la page projet, vu d'un média en grand dans le panneau collecter, vu d'une image issu d'un récit ou d'un page à page) possèdent cette capacité ? est-ce qu'il faut un composant qui est utilisé systématiquement et qui propose ça ? ça voudrait dire avoir ce bouton "plein écran" à ces endroits, et à l'ouverture du mode plein écran sur une image avoir l'option de zoomer dedans.

**Comment by jubonhomme** [comment]
Je pense que sur une version numérique on pourrait effectivement avoir ce bouton sur toutes les images un peu comme le player vidéo permet de voir la vidéo en grand.
Donc dans les publications : récit page à page / carto /...
mais aussi dans la vignette du projet ou les images dans "collecter"

Sur la version pdf par contre il faudrait que ce bouton soit masqué si possible

**Comment by louis-ev** [comment]
En place, à tester à la prochaine maj :)

**Comment by jubonhomme** [comment]
Ça fonctionne
![image](https://user-images.githubusercontent.com/29262866/222929285-e07c679b-e096-443a-a5ca-a8939e5c95a6.png)
