### ISSUE TITLE
Ajout image récit/page

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#719]
Je viens de faire une mise à jour sur mon ordi (11/03) et je n'ai plus la possibilité d'ajouter les médias dans une publication
Les boutons ont disparu

![image](https://user-images.githubusercontent.com/29262866/224507087-cc2283cf-efee-483b-b8ea-61ec78a20d84.png)

**Comment by jubonhomme** [comment]
J'ai le même bug sur ton instance de test. Impossible d'ajouter un médias sur une publication page à page

**Comment by louis-ev** [comment]
Il y'a peut être un scroll ?

**Comment by louis-ev** [comment]
Je te laisse fermer si c'est bon pour toi

**Comment by jubonhomme** [comment]
Le bouton n'est pas visible
![image](https://user-images.githubusercontent.com/29262866/224708855-24d18798-3338-495b-b059-5371d182e70c.png)

Mais je peux cliquer à l'endroit du bouton et ça marche

**Comment by louis-ev** [comment]
Erreur bête de CSS et pas bien vérifié, corrigé :)

**Comment by jubonhomme** [comment]
OK c'est tout bon
