### ISSUE TITLE
Projets invisibles sont affichés

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#721]
Les projets invisibles sont affichés alors que je ne suis pas connecté en ni auteur ni admin
https://164.92.187.49:8080/+projets-crees-precedemment

![image](https://user-images.githubusercontent.com/29262866/227913149-90450f90-d8bf-4c90-b477-d230644f8579.png)

**Comment by louis-ev** [comment]
Ça fait partie du chantier "visibilité", à résoudre oui.
Mais je m'interroge plus globalement sur la clarté des options proposées : brouillon / finalisé / invisible. 
Discussion entamé avec Catherine aussi.
ça fonctionne avec ces options tu penses ?

**Comment by jubonhomme** [comment]
Oui je trouvais plutôt bien cette présentation pour quelqu'un qui arrive en visiteur avec un affichage des projets finalisés tout en haut puis brouillons et les invisibles qui correspondent à des projets privés.
Et quand on est identifié on a ses projets encore haut dessus.

**Comment by jubonhomme** [comment]
Refonte des droits avec maintenant un statut de créateur (admin sur ce qu'on a créé),  de contributeur, de visiteur
