### ISSUE TITLE
Police coupée dans un titre

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#730]
J'ai fait un test de publication avec un titre et un bloc de texte en Belle Allure et le haut et la bas sont coupés

Voir ici 
https://test10.dodoc.fr/+do-doc-10-espace-de-demo-et-test/creer-une-publication?projectpanes=%5B%7B%22type%22%3A%22publish%22,%22size%22%3A100,%22folder%22%3A%22page-a-page%22%7D%5D

https://test10.dodoc.fr/+do-doc-10-espace-de-demo-et-test/creer-une-publication/publications/page-a-page?display=slides

**Comment by louis-ev** [comment]
Argh :/
Cette typo a des ascendantes et descendantes très hautes, je ne peux rien y faire sans que ça affecte toutes les typos et que ça soit du coup décalé pour toutes les autres…

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1948417/233590902-1843c173-62ca-4700-a349-99602b72cc35.png">

Je vais réfléchir à une solution mais c'est pas simple…

**Comment by jubonhomme** [comment]
Je ferme cette issue car une solution simple de contournement existe et est très vite trouvée par les élèves et enseignants : ajouter une ligne au dessus ou en dessous
