### ISSUE TITLE
Intégration vidéos Tubes éducation

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#731]
Je viens de trouver le moyen d'intégrer des URL depuis tubes.education à partir de l'URL !!!

Je prends une vidéo sur l'une des instances Peertube de Tubes Education

https://tube-institutionnel.apps.education.fr/w/1cf77db4-00f3-4eb0-8bff-cca46fa3f91c

Ce code ne fonctionne pas directement dans dodoc ou d'autres outils pour ajouter une vidéo à partir de l'URL

Par contre en remplaçant le "w" par "videos/embed" ça marche à tout les coups :+1: 

Exemple avec l'URL précédente : 
https://tube-institutionnel.apps.education.fr/videos/embed/1cf77db4-00f3-4eb0-8bff-cca46fa3f91c

Il faudrait donc pouvoir entrer l'URL de la vidéo et que dodoc transforme cette URL à la volée en remplaçant le w

Ça marche à priori pour toute les instances peertube

Un exemple dans dodoc 10
https://test10.dodoc.fr/+do-doc-10-espace-de-demo-et-test/les-outils-de-capture/publications/test-video-tubes?display=slides

**Comment by louis-ev** [comment]
Hahaha c'est précisément ce que je fais déjà ! 


```
      const video_id = url.split("/").at(-1);
      return "https://peertube.fr/videos/embed/" + video_id;
```

Je récupère la partie id de la vidéo, je génère une URL contenant /videos/embed : 
https://peertube.fr/w/wB6M6CHdfpWXpozVnqjbde
devient
https://peertube.fr/videos/embed/wB6M6CHdfpWXpozVnqjbde

Je ne fais ça que pour les URL qui contiennent le domaine `peertube.fr`.
Le soucis, c'est que je n'ai pas de liste des domaines peertube et il n'y a pas de logique universelle pour savoir si un domaine fait tourner peertube. Donc soit je met un réglage qui permet d'indiquer "cette url est une vidéo peertube" à indiquer en même temps qu'on colle une URL, soit on rentre une liste prédéfinie dans dodoc en dur pour indiquer toutes les instances connues de peertube.

**Comment by jubonhomme** [comment]
Ok, je réinvente le fil à couper le beurre ;) Mais j'apprends !


- Mettre à jour une liste des instances peertube fonctionnerait mais demanderait une mise à jour impossible à maintenir dans le temps. Le nombre d'instance est en augmentation importante... c'est vraiment un super outil que je retrouve dans de plus en plus de collectifs et réseaux.  

- Mettre un bouton pour indiquer que c'est une vidéo Peertube me conviendrait mais je pense que la majorité des personnes ne sauront pas identifier une "vidéo" peertube puisque cachée derrière un nom d'instance différent.

Donc question de novice ;) : Est-ce qu'on peut faire une reconnaissance automatique d'URL sans mettre de bouton "Peertube" mais en se basant sur les métadonnées HTML de la page ?
Du coup une vidéo sur une instance Peertube serait reconnue automatiquement comme à intégrer avec une URL type peertube : 
https://Mon-instance/w/code-vidéo

Le "W" servirait de repère pour couper l'URL pour récupérer le nom de l'instance (AVANT le /w/) et le code de la vidéo (APRES le /w/).

Donc ça donnerait : 
Je clic que le bouton d'intégration par une URL dans le menu de la publication : 
je sélectionne "autre plateforme vidéo" (pas youtube / pas viméo /...) 
je colle l'URL (avec le w) 
dodoc "interroge" la plateforme et vérifie que ça correspond à une URL type peertube et transforme l'URL avec videos/embed
Je vois la vidéo apparaître avant de valider l'intégration

Est-ce qu'il serait possible de supprimer le choix Youtube / vimeo / autre par une reconnaissance automatique  et ne laisser que "Ajouter une vidéo" ?

Exemple de métadonnées Html tsur tube éducation (maternelle)
view-source:https://tube-maternelle.apps.education.fr/

<!DOCTYPE html><html lang="fr" dir="ltr"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="theme-color" content="#fff">
    <meta property="og:platform" content="PeerTube">

C'est identique pour les CEMEA par exemple
https://videos.cemea.org/
<!DOCTYPE html><html lang="fr" dir="ltr"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="theme-color" content="#fff">
    <meta property="og:platform" content="PeerTube">

**Comment by jubonhomme** [comment]
En vérifiant le fonctionnement dodoc reconnait déjà le type de site pour youtube etc...

On pourrait donc laisser simplement "Adresse URL du site à intégrer"  avec le petit picto "i" et le champ de saisie en dessous

![image](https://user-images.githubusercontent.com/29262866/233611277-e8d35078-4987-49f7-9a63-85afaf145a68.png)

Et si je clique sur "i" j'ai les exemples pour les vidéos / umap / ...

**Comment by jubonhomme** [comment]
Ah !!!!   Je viens de trouver l'URL à utiliser dans le menu partager / intégration

Ce n'est pas la première URL visible dans le menu de partage
![image](https://user-images.githubusercontent.com/29262866/233623092-886ff5c1-a08a-4ef7-a73c-13efd94fada6.png)

Mais celle qui se trouve dans Partager / intégration ET en cochant "URL intégrée"
![image](https://user-images.githubusercontent.com/29262866/233623306-9eba9054-b6e7-4c94-8b76-fe50bf0b4649.png)

Celle-ci fonctionne bien... mais il faut le savoir. 
Si on peut la refaire automatiquement à partir d'un copier / coller de l'URL de la page ça serait plus simple et rapide.

**Comment by jubonhomme** [comment]
J'ai posté une demande sur le forum de Peertube
https://framacolibri.org/t/integration-video-par-url/17644

On verra s'il y a une astuce

**Comment by jubonhomme** [comment]
Une piste donnée sur le forum ci dessus...
j'arrive sur ça 
https://github.com/Chocobozzz/PeerTube/issues/94

Mais j'arrive à la limite de mes compétences ;)

**Comment by louis-ev** [comment]
Ha ! oEmbed c'est une bonne idée, et ça devrait bien améliorer le système d'incrustation de vidéos.
Ça veut dire envoyer une requête pour voir à quel type de contenus on a à faire, et réagir en fonction.

Une proposition : 
1. tu rentres un lien dans un champ
2. dodoc charge le contenu en arrière plan
3. en fonction de la réponse, dodoc t'indique si c'est un lien youtube, vimeo, peertube, ou autre, et affiche l'url d'intégration (corrigeable) et une prévisualisation iframe du résultat.

Plus de transparence, et plus souple.

**Comment by jubonhomme** [comment]
Tu as lu la réponse 
 https://framacolibri.org/t/integration-video-par-url/17644
John Livingston développe le plugin de Tchat pour Peertube.

Je ne connais pas oEmbed, c'est utilisable par dodoc ?

**Comment by louis-ev** [comment]
Par contre on pourra pas permettre les options suivantes simplement : 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/1948417/233650174-21107023-16d1-407f-9a29-112802963c41.png">

Vu que l'iframe est généré par dodoc, ses propriétés ne peuvent pas être modifiées (pour des raisons de sécurité, ou alors il faudrait reproduire les options proposées par peertube).

**Comment by louis-ev** [comment]
> Tu as lu la réponse
https://framacolibri.org/t/integration-video-par-url/17644
John Livingston développe le plugin de Tchat pour Peertube.

> Je ne connais pas oEmbed, c'est utilisable par dodoc ?

Oui, avec du temps :) 
À court terme je te propose qu'on affiche un petit selecteur qui permet de dire : cette url, c'est une vidéo peertube.
Si on reconnait du youtube.com/youtu.be, du vimeo.com, du peertube.fr ou du soundcloud.com, on place le sélecteur sur le site correspondant automatiquement (avec possibilité de corriger). Si on reconnait pas, on indique "Site internet", mais on peut corriger en "Peertube" pour que ça applique le même script d'intégration.

Qu'en penses-tu ?

**Comment by jubonhomme** [comment]
Avec l'outil actuel dans dodoc 10 ça fonctionne très bien avec uMap / CodiMD / Tubes (en prenant l'URL intégration) 

exemple ici : 

https://test10.dodoc.fr/+do-doc-10-espace-de-demo-et-test/creer-une-publication?projectpanes=%5B%7B%22type%22%3A%22publish%22,%22size%22%3A100,%22folder%22%3A%22page-a-page%22%7D%5D

**Comment by jubonhomme** [comment]
Fonctionne bien avec la bonne URL d'intégration.
