### ISSUE TITLE
export PDF avec Decktape ?

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#732]
Je pose ça ici comme une note

Vu sur Digislides

> Digislides (2 avril 2023) :
> - ajout d'un bouton Dupliquer la diapositive
> - ajout d'une option pour ajuster le texte sur la largeur de la diapositive
> **- ajout de l'export en PDF via [decktape](https://github.com/astefanutti/decktape)**

https://github.com/astefanutti/decktape

Peut-être une solution plus efficace pour l'export de pdf ?

**Comment by louis-ev** [comment]
Hmm ça utilise déjà puppeteer derrière, comme dodoc donc.
Intéressant leur manière de créer un pdf avec pdf-lib, et pas en laissant ça à puppeteer – création de 0 d'un pdf avec ses métadonnées, ajout des pages "à la mano" et des typos en dur dans le PDF. Ça paraît assez propre.
C'est pertinent pour un framework qui utilise reveal.js comme digislides. Moins pour dodoc, qui utilise son propre moteur de mise en page / présentation. Je garde sous le coude :)
