### ISSUE TITLE
Navigation : fermeture d'une publication

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#733]
Dans la version 9, le bouton pour fermer une publication et revenir à la liste des pages est bien visible
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4a614965-6c45-4270-8764-29431248272d)

Mais sur la V10 je trouve qu'il manque de visibilité 
J'ai fait un peu tester cette v10 et les utilisateurs cherchent aussi ou se trouve le bouton pour sortir d'une publication
Il y a une confusion sur le terme "fermer" en haut du panneau latéral, on pense que ce bouton sert à replier le panneau de menu.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/34bb2c59-9b07-47c8-8641-bb17d5ad02d0)

Peut-être qu'un bouton plus classique comme dans le panneau "collecter" pour fermer les médias serait plus simple à trouver.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/ff862b81-b744-4575-93f6-8ac448666a53)

**Comment by jubonhomme** [comment]
Idem pour ce bouton "retour au publication"
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/7a1ec1cb-b93c-4810-b426-93ece46e022e)

Pour celui ci je trouve que le bouton rond avec la flèche comme dans la V9 fonctionnerais assez bien
Proposition en image
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/9fe67acd-eea8-4198-aac3-6fcf1df6ecbd)

**Comment by jubonhomme** [comment]
Et pour remonter sur le projet le titre n'est pas identifié comme un bouton
Donc avec un petit picto pour indiquer qu'on peut cliquer pour remonter ce serait aussi plus simple

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4a51ca88-b45f-4a0c-a599-a8705da12875)

**Comment by jubonhomme** [comment]
C'est presque OK, peut-être grossir encore un peu le bouton
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/da661ef3-424a-445a-938c-f45205d13d85)


Et simplifier / rendre plus visible aussi la fermeture
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/dd63fbee-c24a-4459-8cae-ca960bec88eb)

**Comment by louis-ev** [comment]
Agrandi / résolu
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/a688fecc-476e-41a2-ad2d-9b863af58e00)

Bon par contre 4 flèches c'est vraiment pas génial…
Ça fonctionne mais bon.

**Comment by louis-ev** [comment]
Je reporte à 10.1, sauf si on trouve mieux avant :)

**Comment by jubonhomme** [comment]
Je reviens un peu sur cette issue en faisant du ménage.

Le bouton pour revenir à la liste des publications fonctionne très bien.

Par contre j'ai toujours un problème avec le bouton fermer 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/7073f000-3f99-41d4-96d8-d663e667a5e6)

Il sert à revenir à la vue d'ensemble des pages (donc fermer la page en cours) mais pas à fermer la publication.
Est-ce qu'un picto représentant plusieurs pages ne serait pas plus évident ?
En dessous on navigue dans les pages et le bouton au dessus permet l'affichage général de la publication avec un picto et avec le mot "retour" à la place de fermer ?
Par exemple celui-ci qui est déjà utilisé pour afficher la vue des médias
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/597d0610-937e-475f-8181-510d7940daff)

**Comment by louis-ev** [comment]
<img width="290" alt="image" src="https://github.com/user-attachments/assets/1644fe43-fcb6-47ae-b179-c96f38372db8" />

Petit ajustement à ce niveau là, c'est mieux ?

---

V10
![image](https://github.com/user-attachments/assets/6d03e2a7-6111-4191-b9ea-248d922688d4)

---

V11 
<img width="287" alt="image" src="https://github.com/user-attachments/assets/d091e696-0b3c-47a9-8d44-91941f0353b1" />

**Comment by jubonhomme** [comment]
Oui je trouve ça plus évident qu'on ne ferme pas la publication mais qu'on revient à la listes des pages
