### ISSUE TITLE
Ajout d'un bouton pour copier une URL de partage

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#735]
Les codes QR et adresses URL de partage sont actifs dans la V10, Top !
On peut en plus agrandir l'image du code QR en plein écran, très pratique.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/85460af5-9931-46b1-a195-72bfd16b4c98)

J'en profite pour demander une petite fonction pour copier plus facilement l'URL, 
si possible à côté de l'URL avec un picto de ce type : https://www.svgrepo.com/svg/450769/copy-to-clipboard

Sur certains sites il existe un bouton à côté pour copier une URL sans avoir besoin de faire un clic droit ou un appui long
Exemple sur nextcloud :
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4dca8475-f3cb-4a88-b9c1-c0d065c79f24)

ou BBB
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/cde73e59-da57-4288-bf29-2050c16c2b74)

**Comment by louis-ev** [comment]
Bonne idée oui !
J’hésitai à créer un champ URL modifiable, pour ajuster l’URL dans certains cas spécifiques et obtenir le code QR correspondant… (corriger le domaine si y a un soucis par exemple, retirer la partie après le "?" pour avoir un affichage type impression…) Mais c'est une utilisation très expert et j'ai l'impression que ça complexifierait pour tous les utilisateurs. Non ?
Je pense remettre une fonctionnalité "créer un code QR avec une URL ou du texte", peut être dans le panneau Remixer ?

**Comment by jubonhomme** [comment]
Si on peut copier l'URL directement à partir d'un bouton, on peut toujours le coller et le modifier par la suite.
Je pense qu'il faut rester le plus simple possible de ce côté là.
Personnellement c'est souvent ce que je fais, je copie l'URL dans la barre d'URL en sélectionnant tout car c'est plus simple et c'est après l'avoir collé dans un document par exemple que je nettoie l'URL.
Donc oui aussi pour retrouver l'outil pour générer des Code QR dans le panneau "Remixer"

**Comment by louis-ev** [comment]
Ok.
As-t'on besoin d'afficher l'intégralité de l'url ?

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/8ab63d8a-9e7d-4ffb-9daa-6aa161124e37)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/2892feeb-d145-4031-bd3e-c9044d5421c9)

+ bouton copier à droite

**Comment by jubonhomme** [comment]
Non pas besoin de l'intégralité si on a le bouton copier

**Comment by jubonhomme** [comment]
Si possibilité de mettre "..." à la fin de la partie visible de l'URL pour bien comprendre qu'elle est tronquée 

Et grossir un peu le picto copier 

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c58d11eb-59a4-4cb7-bc09-53e21b543e0c)
