### ISSUE TITLE
Sommaire du Récit dans une fenêtre flottante

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#736]
Je viens de tester le récit avec les sections, ça marche déjà pas si mal

Le sommaire serait à mon avis plus pratique dans une fenêtre flottante à gauche (comme le menu de zoom et de page dans la recette page à page)
ça éviterait qu'il ne soit plus visible quand on descend dans le récit
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/93fcf1cc-fbb7-4c7a-abef-54dbaeaad735)

**Comment by louis-ev** [comment]
Je l'ai rendu escamotable, peux-tu tester à nouveau ? 
Les raisons pour lesquelles je n'ai pas opté pour cette piste :
- que fait-on quand il n’y a pas la place de mettre les deux côte à côte ?
- que fait-on quand la largeur du récit est très importante (je vais remettre le réglage pour la définir) ?

**Comment by jubonhomme** [comment]
OK pour le laisser en haut pour que ça marche de la même façon sur les écrans de smartphones et/ou si le récit est en pleine largeur. 
Par contre je vois les flèches "Précédent / suivant" tout en bas en dessous du récit. 

Je pense qu'avec des flèches "ascenseurs" assez fines sur le côté pour remonter ou descendre d'un coup ça pourrait simplifier un peu.

**Comment by louis-ev** [comment]
<img width="1282" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/7779efba-b399-43e1-8d8a-e427a6dd8860">

Tu veux dire que les flèches "flottent" à gauche et à droite de la section, en permanence ? J'ai pas bien compris je crois

**Comment by jubonhomme** [comment]
oui c'est ça des flèches flottantes.
Après je ne sais pas ce qui est le plus pratique. 
- Des flèches gauche droite pour passer à la section suivante / précédente 
ou 
- des flèches haut bas pour monter ou descendre d'un coup.

Par exemple sur la Quizinière de Canopé qui est un peu sur la même forme de colonne, il y a une flèche pour remonter tout en haut.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/b5fdea3a-d2ce-471d-b6de-19cb4c0b81ad)

**Comment by jubonhomme** [comment]
Je n'ai pas eu de retour négatif sur ce point.
Le menu se replie et prend moins de place. Le garder en haut et non sur un côté permet la lecture sur une colonne même sur petit écran.
L'ajout des section permet une navigation sans trop descendre sur la page.

Je ferme donc ici et on réouvre si besoin
