### ISSUE TITLE
Ajout Machine à coudre / Brodeuse

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#737]
Je n'ai pas trouvé ou ajouter dans la liste des suggestions la machine à coudre et la brodeuse.
Peux-tu les ajouter à la liste des machines ?

Est-il possible dans une interface pour l'admin de sélectionner une partie de la liste des suggestions ?
Je pense qu'une partie des matériaux et machines seront utiles dans les fablab mais très rares dans une école par exemple.
L'idée serait donc d'avoir un liste commune à dodoc mais qu'on puisse localement simplifier l'affichage de cette liste en laissant que ce qui serait utilisé réellement.

**Comment by louis-ev** [comment]
Possible oui. On peut imaginer que les admins d’instance peuvent définir ces listes, tout en fournissant une liste existante. Un peu comme la gestion des typos.

Gros taf/bien définir les contours de cette fonctionnalité – question de traduction, est-ce qu'on supprimer ou désactive les termes par défaut, etc.

**Comment by jubonhomme** [comment]
Est-ce qu'en attendant de pouvoir faire des listes personnalisées il est possible de rajouter au moins la machine à coudre pour que le kit de fablab à l'école soit complet ?

**Comment by jubonhomme** [comment]
Les machines qui nous manquaient sont ajoutées.
https://github.com/l-atelier-des-chercheurs/dodoc/commit/dee3e534561fa9ad7637e6ae9564fde7f67a860b

Je ferme ici, on verra à l'usage si besoin d'une gestion plus fine de la liste par l'admin
