### ISSUE TITLE
Raccourcis Capture HS

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#739]
Tous les raccourcis qui fonctionne avec le boitier 3 boutons sont HS.

Je pense que c'est lié au retour de la possibilité d'ouvrir plusieurs panneaux en parallèles.

**Comment by louis-ev** [comment]
Je les avais enlevé en attendant une réécriture qui permette le multi-panneaux (dont j'ai avancé aussi la résolution de bugs de conflits sur les données). Je remet en attendant.
