### ISSUE TITLE
Version electron HS

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#740]
Sur ma session dodoc-next de mon ordi j'ai un écran blanc depuis la dernière mise à jour d'aujourd'hui.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/6f3371fe-b023-4e01-964a-0c3c4b6f4287)

J'ai ce message dans le terminal
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/28b2cd4e-af6b-4723-b29b-6a0ed34f9bda)

Par contre ça fonctionne si je l'ouvre avec un navigateur ( https://localhost:8080 )

**Comment by louis-ev** [comment]
Euh… ha ? J'ai rien changé qui explique cela… Tu utilises la version 18.15.0 de node par contre, ça pourrait expliquer ?
Passe bien sur la 16.14.2

**Comment by jubonhomme** [comment]
Oui en repassant bien par "nvm use"  et la 16.14.2 ça marche
