### ISSUE TITLE
Section récit, ascenseur

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#741]
Quand je partage un récit et que je descend en bas de la première section, je clique sur le bouton pour passer à la section suivante mais j'arrive en bas de la section.
Est-ce que ça pourrait remonter automatiquement en haut de la section suivante ?

**Comment by louis-ev** [comment]
C'est déjà le cas – mais ça marche pas bien si les sections font pas la bonne hauteur.
J'ai ajouté une petite routine pour "bloquer" la hauteur de la page le temps que le scroll remonte entièrement, à tester sur dodoc2-next

**Comment by jubonhomme** [comment]
Je viens de tester à nouveau et ça fonctionne bien
