### ISSUE TITLE
Filtre "Mes projets"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#742]
Dans la dernière version de la V9 et les débuts de la V10, si on arrivait connecté sur la plateforme dodoc on voyait directement en haut ses projets. 
Je trouvais vraiment pratique ce filtre d'affichage qui permet de reprendre et de travailler directement sur ses projets.

Est-il possible de rajouter un filtre pour avoir à nouveau ce classement qui fait remonter les projets où l'on est contributeur ?

**Comment by jubonhomme** [comment]
Je pensais aussi à une fonctionnalité pour pouvoir mettre des Espaces en haut de la page (épinglés ? Favoris ? Ordre ?)

Mais effectivement la logique de pousser ça dans les différents niveaux est bonne.

Exemple
si je suis admin de l'instance : je peux épingler des espaces
si je suis référents d'un espace : je peux épingler des projets
si je suis référent d'un projet : je peux épingler des publications

Mais je pense aussi que ce n'est pas la même chose que de retrouver les projets dans lesquels on contribue ou les derniers modifiés. 
On pourrait très bien laisser des espaces / projets / publications en premier pour les visiteurs parce qu'ils doivent être vu en priorité mais aussi pouvoir retourner assez rapidement dans un projet / publication en cours de modification.

Si on peut dissocier les 2 c'est bien.

Une fonctionnalité pour épingler / prioriser l'affichage
Une autre comme tu proposes pour filtrer nos contributions, avec un affichage possible par date des 5 derniers modifiés ?

**Comment by louis-ev** [comment]
J'ai implémenté (rapidement) pour la plate-forme fabriquedu.org : 
- les espaces épinglés par les admins d'instance

Dans les espaces, j'ai plutôt ajouté une section "Projets finalisés" : l'ordre est déterminé comme les autres projets, et ce sont les référents des projets qui choisissent leur statut (finalisé / en cours / privé). Du coup pas tout à fait la même logique qu'envisagé : est-ce que ça marche aussi ? C'est un soucis de pas pouvoir gérer l'ordre ? Et que ça ne soit pas le référent de l'espace qui soit en charge de cette section ?

Pour retrouver "Mes projets", on peut imaginer par exemple enregistrer une info "derniers projets modifiés" (ou "dernières publications modifiées" ?) au niveau de la fiche auteur, et un accès rapide sur la page d'accueil directement vers les 5 dernières entrées quand on est identifié, depuis n'importe quel appareil.
Concrètement, tu modifies un contenu -> on regarde si son chemin est dans la fiche auteur "modifié récemment". Si oui, on fait rien, si non, on l'ajoute. Du coup ça impact assez peu le serveur.

**Comment by jubonhomme** [comment]
Ça marche pas si mal ;)

Possibilité d'épingler des espaces sur page d'accueil / projets finalisés dans espace
Affichage des 5 derniers projets modifiés en page d'accueil si on est identifié. C'est vraiment pratique on a même pas besoin d'aller filtrer dans un espace.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/d19e61f8-3972-4c3d-8b78-50a9c556e59e)

**Comment by jubonhomme** [comment]
Je dirais bien de fermer cette issue, l'affichage de ses derniers projets est très pratique pour un auteur.

Mais par contre ça ne permet pas aux autres de voir les projets publiques d'un auteur en particulier.
Je trouve intéressant si l'info est déjà présente dans la fiche auteur de pouvoir afficher dans la page auteur ses projets.
On pourrait reprendre la présentation des espaces avec les projets / des projets avec les publications :
on affiche la vignette de l'auteur et les infos "Nom" "Présentation" "Localisation"... à côté à droite et en dessous on affiche ses projets comme si l'auteur était un espace, avec les filtres.
La page avec la liste des contributeurs serait une autre entrée dans les projets, un peu comme une page d'accueil avec des espaces "auteurs" et la page d'un auteur comme une page espace

**Comment by louis-ev** [comment]
Afficher ses projets dans la page auteur est techniquement délicat : il faudrait charger l'ensemble des projets de tous les espaces pour les trouver. On pourrait imaginer que cette liste se constitue lorsqu'un auteur créer un projet (on l'ajoute à la liste de ses projets, l'information étant stockée dans la fiche auteur), mais ça ne marche pas si un compte ajoute un autre compte à un projet. Du coup je suis un peu coincé…
 
J'ai ajouté "Liste des derniers projets que vous avez modifié" pour proposer une solution à mi-chemin (et qui n'impacte pas négativement les performances), mais j'ai bien conscience que ça manque. Comment faire… ?

**Comment by louis-ev** [comment]
Cela dit on peut facilement ajouter un filtre/une case à cocher "mes projets", qui agit comme un filtre sur la liste des espaces ou projets. Par contre on gère comment les espaces/projets dont la contribution est ouverte à tous ? Sont-ils affichés quand on coche "mes espaces" ou "mes projets" ?

**Comment by jubonhomme** [comment]
> Par contre on gère comment les espaces/projets dont la contribution est ouverte à tous ? Sont-ils affichés quand on coche "mes espaces" ou "mes projets" ?

Je ferai bien une distinction entre les projets ou l'on est référents-contributeurs et les projets ouverts à tous

Donc pourquoi pas afficher les 5 derniers modifiés sur l'écran d'accueil pour rapidement revenir sur ces projets sans même passer par les filtres. Mais on pourrait ajouter un bouton "voir plus" qui déplierait la liste de tous les projets où l'on est contributeurs-référents. 
Ou alors ça ouvre la page tous les projets avec ce filtre ?

Mais je mettrais de côté les projets ouverts à tous qui ne sont pas identifiables comme Mes projets par les utilisateurs

**Comment by louis-ev** [comment]
Afficher une case à cocher "Mes projets uniquement" à côté du champ de recherche dans une liste de projets (celle "tous les projets" en page d'accueil et "projets de l'espace" en page espace) pourrait fonctionner tu penses ?

<img width="1030" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/ac4b17c5-006f-42dc-9f67-a6f87ce3ce7c">

**Comment by jubonhomme** [comment]
J'hésite...
Mes projets uniquement (ou Mes projets) correspond à un filtre dans l'affichage de "Tous les projets"
Mais je pense que si on le place dans les filtres ça ne va pas être aussi pratique et rapide.
Je verrais presque un bouton unique "Les espaces / Tous les projets / Mes projets" mais je ne sais pas si ça marcherait au niveau technique d'avoir un bouton qui glisse sur 3 choix possibles.

Sinon ce que tu proposes peut aussi fonctionner. C'est juste l'idée de voir en haut et bien visible "Tous les projets" et n'afficher au final que Mes projets avec une petite case cochée pas forcément aussi visible.
C'est aussi parce que j'oublie souvent celle cochée par défaut de l'import des médias que je dis ça ;)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/386fa5a8-8827-4854-8cd0-0d90bfcb531e)

**Comment by louis-ev** [comment]
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/bdd6abaa-c855-45ee-a125-75fa6cd395a2)

On test comme ça ! en place

**Comment by jubonhomme** [comment]
A fermer ?
