### ISSUE TITLE
Ajout d'un indicateur pour dépassement dans un bloc

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#743]
Dans la V9 il y a un indicateur visuel si le texte dépasse la zone visible du bloc, c'est assez utile pour bien dimensionner le bloc et que le texte ne soit pas masqué.

Est-ce possible de retrouver ce type d'indication dans les blocs de texte de la V10 ?

Et aussi dans le bloc ajout de médias à télécharger.

**Comment by louis-ev** [comment]
Ok oui.
Est-ce que l'idéal ne serait pas que le bloc texte soit aussi haut que nécessaire pour accomoder tout le texte ? Et qu'on ne puisse pas régler sa hauteur (qui serait donc automatique) ? Je ne sais pas si techniquement j'arriverai à faire ça, mais ça vaut le coup d'évoquer la situation idéale :)

**Comment by jubonhomme** [comment]
Ça pourrait effectivement résoudre le problème. 
Si on change la largeur du bloc, la hauteur s'adapte automatiquement pour que le texte reste complet.
C'est le comportement sur Inkscape par exemple

**Comment by jubonhomme** [comment]
Et aussi de tldraw
voir ici :
https://test10.dodoc.fr/+espace/test-texte-hauteur/publications/texte?display=section

**Comment by jubonhomme** [comment]
Et pour le cas ou c'est une liste de fichiers sources à télécharger est-ce que ça ne pourrait fonctionner comme les médias dans un carrousel ?
A la place d'avoir un bloc qui contient une liste on aurait un bloc type "carrousel à la verticale" avec les fichiers sources et un + en vert en dessous pour ajouter d'autres sources.

**Comment by louis-ev** [comment]
Le plus simple serait un scroll vertical oui, après il faut comprendre qu'on peut scroller.
À tester oui !

**Comment by louis-ev** [comment]
Je reprends le picto "texte coupé" pour v10, et on verra pour la v10.1
