### ISSUE TITLE
Nommage du fichier PDF exporté

### ISSUE THREAD

**Issue by ThibM** [l-atelier-des-chercheurs/dodoc#745]
L'export PDF d'une publication crée un fichier nommé "publication-xxx.pdf". 
Pourrait-on envisager une option pour récupérer une information déjà renseignée (par exemple le titre du projet) ?

**Comment by louis-ev** [comment]
Mais oui ! Bien d'accord 👍

**Comment by louis-ev** [comment]
Implémenté ! Et en ligne sur ton instance
