### ISSUE TITLE
Masquer par défaut l'affichage de la liste des contributeurs d'un espace ou projet

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#746]
Est-il possible de masquer par défaut la liste des contributeurs et d'avoir un bouton pour l'afficher ?

Il faudrait garder uniquement les référents pour bien visualiser qui gère cet espace ou projet.
La liste des contributeurs peut être trèèèèsss looonngue et ça plombe l'affichage de l'espace ou du projet. Cette info est à mon avis peu importante. Soit je suis dans la liste et je vois tout de suite le bouton "créer" pour ajouter du contenu, soit je n'y suis pas et je navigue en visiteur et j'identifie les personnes référentes pour demander un accès si besoin.

Exemple :
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/b1775052-fbc5-40a2-a5df-e18ce12a7c9f)

**Comment by louis-ev** [comment]
<img width="1276" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/effcfcb8-74f8-45a8-be18-c7b71b937f8e">

Voilà la proposition. Juste les portaits, sur une ligne avec défilement horizontal si nécessaire.
Ajout des deux premières lettres comme avatar par défaut si pas d'image.

En ligne sur dodoc2-next et dodoc2-next-node

**Comment by jubonhomme** [comment]
J'ouvre à nouveau cette issue car l'affichage de la vignette bug si la liste des référents / contributeurs dépasse le cadre.
voir ici
https://dodoc10.reseau-canope.fr/+fablab-a-lecole

ou là 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0ef64fe9-9b69-4dad-ac1a-41554b9ecb75)

**Comment by louis-ev** [comment]
Arf :/ 
L'affichage "smartphone" se déclenche à cause de la longueur du bloc "référents" qui agrandit le bloc méta qui le contient… Pas simple de résoudre ça, à moins de le controler "à la mano". Je vais voir.
