### ISSUE TITLE
Coins arrondis 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#749]
Sur un carré ou une image avec le ratio d'origine, l'application des "coins arrondis" fonctionnent bien

Mais si on déforme le carré en rectangle (ou une image avec un recadrage) les coins arrondis sont aussi déformés. Même si on applique cette fonction après avoir fait la déformation.
Il faudrait appliquer la fonction en prenant en compte le nouveau format et non le format d'origine.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/3b8fff0d-b066-46a6-995c-7aa71002f54e)

**Comment by louis-ev** [comment]
Corrigé : 
<img width="1253" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/a2024e41-e613-4e10-9393-2c2af0f50346">

**Comment by jubonhomme** [comment]
Génial
