### ISSUE TITLE
Aperçu vidéo

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#754]
Un petit problème sur l'aperçu des vidéos.

Le format des vidéos dans la fenêtre des médias dans collecter est tout en hauteur. Il s'adapte quand on lance la lecture.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/ea8def93-dfc0-4c8d-9009-b88917db8458)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/a1fd4868-423b-4fa1-9c81-9e3e3e0f7b3a)

**Comment by louis-ev** [comment]
Corrigé ! Le player devrait toujours prendre toute la place disponible maintenant (en espérant que cela n'ait pas cassé l'incrustation dans une publication page à page, il y a pas mal de cas de figure possible qui sont difficiles à tester en même temps).
