### ISSUE TITLE
Ajout image de couverture, filtrer les autres médias

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#755]
Quand on veut ajouter une image de couverture dans un projet

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/77b1b1f0-f55d-4b27-801f-a8307ec2d4a1)

On peut naviguer dans les médias du projet, mais on peut aussi choisir un son par exemple... 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/1977ba8f-1852-4a23-a95b-64ae65963e24)

ce qui ne fonctionne pas, normal.

Il serait plus simple d'afficher uniquement les images pour ne pas avoir de message d'erreur à la fin si on choisit autre chose.
Mais peut-être que ça viendra avec les filtres de médias ?

C'est plus une note pour la suite qu'une priorité dans les modifications.

**Comment by louis-ev** [comment]
Ajouté ici : 9cd33e38d4367b0c0194756a3756cf8cd31b984a
En même temps que le filtre dans les médias (le sélecteur est améliorable mais fait l'affaire à court terme :) )
