### ISSUE TITLE
Déconnexion page auteur

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#756]
Si je clique sur une vignette auteur j'arrive sur une page auteur

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/cdef41a3-98be-4796-8b45-96e95ea96fb9)

Si ensuite je clique sur accueil ou le logo dodoc pour sortir de cette page, ça revient sur une page avec "se connecter"
Mais on n'est pas vraiment déconnecté puisqu'en rafraîchissant la page ça nous reconnecte bien directement.

**Comment by louis-ev** [comment]
À retester :)

**Comment by jubonhomme** [comment]
C'est ok 
Je ferme
