### ISSUE TITLE
Retouche image - taille image / zoom

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#757]
Je viens de mettre à jour dodoc à l'instant ;)
Très bonne nouvelle pour la retouche d'image !

Une première remarque sur cette première recette fabrication, l'image s'ouvre automatiquement en pleine largeur.
C'est très bien pour les formats en paysage mais pour le format vertical on ne voit pas toute l'image. 
Est-il possible d'avoir une fonction zoom ?
Est-ce qu'une image pourrait s'afficher automatiquement en plein écran : 
- comme actuellement pour les images horizontales
- avec une hauteur maxi de l'écran si verticales 

Je vois que la rotation est déjà dans les tuyaux ;)

Dernière remarque :
Est-ce qu'on pourrait avoir un bouton "Modifier l'image" dans le bandeau de la partie Collecter qui ouvrirait directement l'image dans Fabriquer ?

**Comment by jubonhomme** [comment]
Toujours sur le même sujet

Est-ce que par défaut la zone recadrée ne serait pas plus petite que l'image ? C'est surtout pour mieux identifier le cadre et les poignées.
Exemple sur cette image, si la zone est sur l'image on ne voit pas très bien les points.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/107dfcb4-b50a-42b1-b9bd-f83e7dd846c2)


Si en cliquant sur recadrer la zone par défaut est plus petite on identifie tout de suite le cadre et on déplace les poignées

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c535a365-676d-47e1-a54c-4b894a4449d5)

**Comment by jubonhomme** [comment]
Les poignées sont visibles et ne posent plus de problème.

Reste encore la gestion des images verticales qui ne sont pas évidentes à manipuler car il faut jouer en même temps sur la barre de défilement.

**Comment by jubonhomme** [comment]
Bon on avance... ça rentre dans la page sans scroller, mais c'est pas encore complètement utilisable ;)

https://test10.dodoc.fr/+espace/test-cartographie?projectpanes=%5B%7B%22type%22%3A%22make%22,%22size%22%3A100,%22make%22%3A%22modifier-une-image-hm0%22%7D%5D
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/afc56d28-c44c-4087-87ee-d60f125fb83e)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/2433213d-9376-4a3d-9544-206b44b18726)

**Comment by louis-ev** [comment]
Résolu !
bon par contre le soucis avec l'image étirée, c'est parce que sa taille correspond pas à son orientation (il y a une métadonnée qui indique qu'elle est pivotée, donc qu'il faut inverser largeur et hauteur

**Comment by jubonhomme** [comment]
Si ça optimise et l'affichage et le stockage je pense aussi que ça en vaut la peine.
Surtout que les images de smartphones sont maintenant assez lourdes avec les capteurs actuels.

**Comment by jubonhomme** [comment]
En lien avec #821

**Comment by louis-ev** [comment]
Je retente ce lien et ça m'a l'air résolu : https://test10.dodoc.fr/+espace/test-cartographie?projectpanes=%5B%7B%22type%22%3A%22make%22,%22size%22%3A100,%22make%22%3A%22modifier-une-image-hm0%22%7D%5D

Avez-vous une image sous la main @jubonhomme @FabLabEcoCentre que vous pourriez tester sur test10 ? Merci !

**Comment by jubonhomme** [comment]
J'ai essayé avec plusieurs images et je n'ai plus d'étirement... ça à l'air d'être bon cette fois.

On ferme ici et #821 ?

**Comment by catmdb** [comment]
Ça marche aussi de mon côté. Par contre pas les modifications de luminosité, contraste, saturation et flou.

**Comment by jubonhomme** [comment]
De mon côté aucun problème, ni sur mon dodoc en local ni sur test10.
Exemple ici
https://test10.dodoc.fr/+do-doc-10-espace-de-demo-et-test/creer-une-publication?projectpanes=%5B%7B%22type%22%3A%22make%22,%22size%22%3A100,%22make%22%3A%22retravailler-une-image-kop%22%7D%5D

**Comment by catmdb** [comment]
Je viens de ressayer dans ton projet julien, avec mon iPhone sans être connecté, ça ne marche pas. C'est parce que je ne suis pas connectée?

**Comment by louis-ev** [comment]
Je confirme que ça marche pas sur iOS, et que ça n'est très probablement pas lié au fait d'être connecté.
Il s'agit plutôt des fonctionnalités (avancées) que j'utilise pour les filtres.
Je regarde.

**Comment by louis-ev** [comment]
Pas pris en charge officiellement donc (ça marche pas aussi sur safari macOS, plus pratique pour tester).
<img width="822" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/97dfa20e-3b12-4bd9-b07a-5b02742dfed0">

Un polyfill qui a l'air au point : https://github.com/davidenke/context-filter-polyfill?tab=readme-ov-file
Je test

**Comment by louis-ev** [comment]
À jour sur test10, il faut parfois reboutiquer les règlages pour que ça s'active mais ça résoud le soucis à priori (chez moi en tout cas).

**Comment by jubonhomme** [comment]
Je viens tout juste de refaire un test et ça marche toujours de mon côté (Firefox/linux)

**Comment by catmdb** [comment]
Je confirme : all good !

**Comment by jubonhomme** [comment]
Je ferme
