### ISSUE TITLE
Bug suppression image recette page à page

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#759]
Si on supprime une image dans une recette page à page en passant par le menu du bandeau à gauche il y a une fenêtre pour confirmer la suppression. Très bien

Si on supprime avec le picto corbeille sur le bloc l'image reste affichée et s'efface quand on clique ailleurs mais sans demande de confirmation.

Les 2 fonctionnent différemment c'est un peu étrange.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/9c247eef-d14b-45c8-a158-af23f1c535fb)

**Comment by louis-ev** [comment]
Est-ce que c'est bien pertinent d'avoir le bouton suppression sur le média ? Il n'est pas sur les formes, et accessible aussi au clavier. Je partirai sur le masquer.
Et je m'interroge sur le cadenas, on devrait pas le placer dans ce petit menu en haut à droite ? dans le même style

**Comment by jubonhomme** [comment]
oui pour les deux.
Masquer le bouton et ne garder que le menu ou la touche suppr du clavier ça me va très bien et on a bien la confirmation de suppression.
Et oui si on place le cadenas en haut à droite

**Comment by jubonhomme** [comment]
je remonte cette issue,
Proposition : 
Enlever le bouton suppression du média qui est dans le bloc média
Déplacer le cadena du verrouillage en haut à droite du bloc

**Comment by jubonhomme** [comment]
avec la dernière mise à jour 24/10 et la réparation des blocs dans la publication page, le picto de la corbeille est présent dans le bloc quand on ajoute un média puis disparait après un premier clic ailleurs.
Il faudrait le supprimer dès le début si possible

**Comment by louis-ev** [comment]
On est bon non ?

**Comment by jubonhomme** [comment]
OUI !
