### ISSUE TITLE
Bug interface tactile sur "Recouper un son"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#760]
Dans la V10 et la recette Recouper un son, la sélection à la souris fonctionne bien sur ordi en surlignant sur la piste son.
Mais dans une interface tactile on ne peut que déplacer la barre rouge sur la piste son, la sélection d'un extrait ne peut pas se faire.
Il faudrait pouvoir sélectionner l'extrait en glissant le doigt sur la piste.

**Comment by louis-ev** [comment]
Argh :/
On arrive aux limites de Waveform Playlist…
J'ai transformé les affichages des valeurs en seconde pour qu'on puisse indiquer un chiffre, ça permet de sélectionner sans utiliser le spectrogramme 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/13d4ca4a-8ffe-4874-a547-3c3c14ce6879)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/6cb3c96d-a273-4f8a-bd9d-9d8181f48a24)

Faudra trouver mieux

**Comment by jubonhomme** [comment]
Je viens de voir cette issue 
https://github.com/naomiaro/waveform-playlist/issues/43

Je vais le relancer avec mon anglais approximatif ;)

**Comment by jubonhomme** [comment]
L'affichage en dessous des secondes fonctionne plutôt bien.
En testant un peu je vois qu'on peut mettre des temps négatifs et des temps bien supérieurs à la durée maxi de la piste.

Est-ce qu'on peut comme pour les time lapses mettre des limites possibles aux valeurs : de 0 à durée maxi de la piste.

**Comment by jubonhomme** [comment]
Je reviens sur cette issue pour la suite de l'intégration de waveform-playlist sans que ça bloque sur tablette.

En refaisant des tests sur ordi avec souris / ordi avec touchpad / tablette
et en comparant le fonctionnement de waveform et de tldraw (qui lui fonctionne très bien sur tactile comme sur ordi)

Si je prends ce qui fonctionne sur tldraw
sur ordi touchpad : 
- avec un doigt je déplace les objets ou j'encadre une zone de sélection
- avec deux doigts je déplace l'espace de travail

sur tablette (idem) : 
- avec un doigt je déplace les objets ou j'encadre une zone
- avec deux doigts je déplace l'espace de travail

Et sur waveform 
sur ordi touchpad (idem tldraw): 
- avec un doigt je déplace les objets ou j'encadre une zone de sélection
- avec deux doigts je déplace l'espace de travail

Mais sur tactile : 
**- avec un doigt je déplace déjà l'espace de travail**
- avec deux doigts je déplace la page entière

Ça pourrait donc très bien fonctionner sans trop se compliquer si sur tactile tout ne remontait pas d'un cran. Il faudrait "juste" que l'interaction à un doigt soit reprise comme sur le touchpad de l'ordi et demander 2 doigts pour déplacer l'espace de travail.

Les interactions d'une publication page à page par exemple fonctionnent aussi comme ça
1 doigt = objet
2 doigts = espace de travail

Pour recouper ou déplacer les pistes on aurait la même interaction sur ordi que sur tablette

**Comment by louis-ev** [comment]
> L'affichage en dessous des secondes fonctionne plutôt bien. En testant un peu je vois qu'on peut mettre des temps négatifs et des temps bien supérieurs à la durée maxi de la piste.
> 
> Est-ce qu'on peut comme pour les time lapses mettre des limites possibles aux valeurs : de 0 à durée maxi de la piste.
> 
> Je m'en suis rendu compte en mettant une valeur en oubliant le point 1167s au lieu de 11.67s et ça m'a planté quelques secondes en mode écran figé

Je corrige pour la v10.

Pour le dernier message pour la gestion du tactile, je laisse en attente pour la v10.1 (en espérant très fortement que waveform-playlist gère ça mieux d'ici là !).

**Comment by jubonhomme** [comment]
Peut-être une bonne piste de ce côté pour la gestion du tactile, par contre je ne comprends pas trop pourquoi c'est fermé alors que ça à l'air assez complet.
https://github.com/naomiaro/waveform-playlist/pull/228 

dont celui ci pour la sélection 
https://github.com/naomiaro/waveform-playlist/pull/228/commits/cf195fb637711dac7ce1ecdb9c0a9d91a70436c3

**Comment by jubonhomme** [comment]
Une bonne nouvelle, 
Emmanuel Zimmert vient d'ajouter suite à mon ticket les nouvelles fonctionnalités à Logimix : découper à l'intérieur d'une piste audio, scinder la piste sur une nouvelle ET la prise en charge du tactile sur waveform ... il ne me reste plus qu'a faire des tests demain sur un écran tactile

**Comment by louis-ev** [comment]
Je ne vois pas de maj côté waveform playlist, et je ne sais pas ou chercher – pas le temps pour la v10, je reporte.

**Comment by jubonhomme** [comment]
Pour le moment il n'y a plus de sélection directe sur le spectrogramme donc plus de bug tactile.
Je fermer cette issue.
Une des pistes serait d'utiliser wavesurfer pour le son qui gère correctement le tactile.
voir #535
