### ISSUE TITLE
Boutons un peu trop proches

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#761]
A chaque fois que l'on veut ajouter un contributeur dans un espace il faut passer par "Plus d'informations"...

Mais j'ai déjà plusieurs fois appuyé sur le bouton juste en dessous, en voulant aller vite. 
Et le bouton c'est TOUT supprimer :(
Heureusement il y a une demande de confirmation mais si on pouvait espacer un peu les deux ce serait plus sécure

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/1b5a3ce3-8259-4808-8a1c-82e4766b655d)

**Comment by louis-ev** [comment]
Très juste !
J'ai récemment expérimenté un bouton en menu déroulant : 
<img width="240" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/d34fe575-d819-4c68-b433-8bf781d1a346">
<img width="320" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/7b7a1418-d303-4d8c-8036-65cfb410212b">

Ce qui permet de ranger les options avancées sans encombré l'interface utilisateur.
Qu'en penses-tu ?

**Comment by jubonhomme** [comment]
Oui j'ai vu dans le bandeau des publications, je trouve que ça épure l'interface, un bouton qui regroupe des fonctions que l'on utilise pas forcément très souvent 
Très bien

**Comment by jubonhomme** [comment]
En voyant la future publication cartographie je pense qu'on pourrait gagner un peu d'espace en hauteur en regroupant dans le même bandeau les boutons de retour menu et de réglages.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c835e441-cd40-4a57-ac09-89f0708ebdc6)

**Comment by jubonhomme** [comment]
idem pour les récits et page à page
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/dbc38b41-5a96-41ed-b1df-a85193df66c9)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0cb73c6f-f78d-4714-a524-38e6608623bc)

**Comment by jubonhomme** [comment]
Très bien pour les deux !
Je ferme
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/17dcd0a7-e030-45f6-ad14-b021c735ae36)


![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/521497fa-d740-4220-9d74-b48943bdcd12)
