### ISSUE TITLE
Publier une version pour Yunohost

### ISSUE THREAD

**Issue by Nico7as** [l-atelier-des-chercheurs/dodoc#770]
Salut l'Atelier des Chercheurs, 

Pensez-vous qu'il serait possible de "packager" do⋅doc pour Yunohost ?

Do.doc y aurait parfaitement sa place, en particulier pour les écoles.

[Yunohost](https://yunohost.org/#/) est une distribution Linux orientée serveur, à l'administration simplifiée.
Elle se destine aux structures non-expertes, comme les associations, les écoles, ou les particuliers.

Elle propose un [catalogue d'application](https://apps.yunohost.org/catalog), à l'installation simplifiée.
Ces applications sont "packagée" spécifiquement pour cette distribution, basée sur Debian.
La préparation du paquet est présentée dans [ce guide](https://yunohost.org/fr/packaging_apps_intro)

Je sais que préparer un paquet demande du travail, et de la maintenance, et pour l'instant, je n'en ai pas les compétences.

Merci d'avance à celui ou celle qui se dévouera!!

**Comment by jubonhomme** [comment]
Bonjour,
Peut-être qu'en déposant une demande ici : https://apps.yunohost.org/wishlist ça motiverait quelqu'un qui sait packager pour Yunohost.
Mais je pense aussi que plus l'installation serveur sera simplifiée et plus des petites structures associatives ou écoles pourront créer leur propre instance de dodoc.

**Comment by louis-ev** [comment]
Chouette idée oui ! Un temps évoqué avec @aurelient pour Plateau (une variante sur la même base de code que dodoc), Aurélien tu/on en avait conclu quoi ? Je crois qu'il était délicat de gérer le stockage aussi, je ne sais plus trop pour tout dire…

**Comment by Nico7as** [comment]
@jubonhomme 
Je ne l'avais pas précisé, mais j'avais déjà fait une demande dans la liste de souhaits.

Je ne la vois pas, d'ailleurs. Elle est peut-être en instance de validation ?

**Comment by aurelient** [comment]
Bonjour, 
packager pour Yunohost n'est pas tout à fait trivial. Les montées de version dans la stack do.doc devraient aider (c'était un des freins), mais il y a d'autres problèmes qui arrivent notamment si on veut avoir une gestion des comptes "propre" avec SSO/LDAP.

@louis-ev un problème du stockage de Plateau était la volonté de gérer cas p2p et cas stockage centralisé. Je crois que de ce côté ça sera plus simple aujourd'hui avec la stack de do.doc relativement à jour et stable.

TLDR: maintenant que la stack do.doc est un peu stabilisée ça devrait être faisable, mais pour que ce soit fait proprement il faudrait investir dans la gestion de comptes générique dans do.doc ce qui a un coût en développement et en maintenance assez important.

**Comment by Nico7as** [comment]
J'ai parcouru l'introduction de la documentation consacrée au packaging pour Yunohost, et effectivement, cela semble complexe. Il disent néanmoins qu'ils ont simplifié le processus.

À l'heure des formats Snap ou Flatpak, le système de paquetage traditionnel peut paraitre désuet, surtout s'il est "exotique" comme pour Yunohost. Il garde néanmoins l'avantage de la légèreté.


Par contre, j'ai pas compris l'histoire des "comptes génériques"

PS: j'ai installé Do⋅doc en AppImage un des postes sous Ubuntu de ma classe, et on va s'en débrouiller pour le moment.
Mais YNH m'intéresse aussi pour d'autres apps.

**Comment by aurelient** [comment]
En gros la gestion des comptes utilisateurs est faite en interne à do.doc. Yunohost permet de partager des comptes entre services héberger et de gérer les accès à tel ou tel service pour les utilisateurs de l'instance. Toutefois cela se fait au moyen d'un outil standardisé : les annuaires LDAP. Do.doc ne s'appuie pas là dessus me semble t'il. Je ne pense pas que ce soit bloquant, mais je ne crois pas que ce soit très encouragé par Yunohost. Tout cela est à vérifier, il est possible que je dise des bétises ou que les choses aient évolué.

**Comment by louis-ev** [comment]
Bonjour et merci pour vos discussions. Je propose que ce chantier soit relancé après la publication de la v10 en version stable – j'essaye de mettre un coup de boost pour la publier avant la fin de l'année et je crains que cette issue reporte encore.
Une fois publiée (en version serveur et en AppImage notamment) il sera plus simple de refaire la documentation proprement et mettre à jour la branche principale du repo (+ nettoyage des branches obsolètes) – plus lisible et plus facile pour repartir de cette base là !

**Comment by Nico7as** [comment]
Salut Louis, 
Merci pour le retour ! 

Depuis la dernière fois, j'ai aussi commencé à m'intéresser à l'utilisation de Containeur, comme Docker, ou Podman.

Podman m'intéresse en particulier car c'est le système de conteneur par défaut de OpenMediaVault, une distribution Linux basée sur Debian, faite pour les NAS.

Le système de conteneur est plus universel que celui d'un empaquetage pour une distrib spécifique comme YNH.
Il y a peut-être quelque-chose à creuser aussi de ce côté là ... :-D mais dans un ticket séparé ;-)

**Comment by jubonhomme** [comment]
Avec un bon coup de main de la communauté de Yunohost ça avance !

Voir le sujet sur le forum avec une première version en test :
https://forum.latelier-des-chercheurs.fr/t/empaquetage-de-dodoc-pour-yunohost/548/10?

**Comment by louis-ev** [comment]
J'ai l'impression que c'est tout bon, et on a même un super tuto de heron1306 pour aider à l'installation !
https://forum.latelier-des-chercheurs.fr/t/intastaller-dodoc-avec-yunohost-methode-la-moins-geek/561
Je ferme.
