### ISSUE TITLE
Bug image instance

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#771]
Je viens de mettre à jour dodoc ce soir et j'ai fait du ménage dans mes instances de test pour repartir sur une version toute propre.

J'ai bien accès à l'administration de l'instance en me connectant avec le compte admin et dodoc comme mot de passe.
Je peux modifier le titre de l'instance, le dossier de stockage et plein d'autres choses.
Par contre l'import d'une image pour mettre sur la page d'accueil ou comme favicon plante systématiquement. 
J'ai un message d'erreur en rouge [Object Object]
et dans le terminal j'ai ça 
API2 • _restrictToContributors – Folder opened to any contributors or admins
~ FILE • Failed to handle form / {"code":"ERR_INVALID_ARG_TYPE"}
~ API2 • Failed to upload file: Cannot destructure property 'originalFilename' of '(intermediate value)' as it is undefined.

**Comment by jubonhomme** [comment]
Je viens de mettre à jour à l'instant et ce n'est pas seulement les images de l'instance mais aussi lorsqu'on importe une image d'espace ou de projet.
Si on ajoute une image déjà présente dans "collecter" d'un projet ça marche.
Mais si on utilise importer ça ne marche pas.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/e267fe6a-4243-4cfe-9ee8-a7a7f5b996f4)

**Comment by jubonhomme** [comment]
L'ajout direct avec l'import fonctionne maintenant, mais je réouvre pour l'ajout avec "prendre une photo" qui affiche un écran noir

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/2c9b1232-4bae-40de-9f07-ec1b01ef125a)

**Comment by louis-ev** [comment]
Effectivement.
Corrigé !
