### ISSUE TITLE
Amélioration de la visibilité des boutons de navigation des médias "collecter"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#772]
Retour d'aujourd'hui

Les boutons pour naviguer dans la bibliothèque de médias ne sont pas assez visibles
Comme en plus il n'y a pas de raccourcis avec les flèches du clavier, on passe souvent par la fermeture du média pour en ouvrir un autre. 
Il faudrait que les boutons gauche / droite soient plus visibles et que la zone de sélection soit plus grande

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/d1b102b0-76f5-421c-a97c-52f0196c329c)

**Comment by louis-ev** [comment]
(j'ai fermé mais tu peux rouvrir si besoin :) )

**Comment by jubonhomme** [comment]
Sur un fond uni on les voit un peu mais sur une image plein cadre et plein de couleur ça n'est pas très visible.
Même la flèche de droite sur le blanc il faut la voir...
Quand on sait ça va mais pour ceux qui découvrent c'est pas très net.

Un exemple sur thingiverse
En pleine page
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/68dd29a2-f367-4416-bd95-dcc20ba31b4a)

Et avec cerclage
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/32329ff1-e0ca-46ae-b828-23f70631b28b)
