### ISSUE TITLE
Ajout de la géolocalisation dans capter photo / vidéo / son

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#774]
Lorsqu'on utilise un smartphone ou une tablette on peut allumer le gps et avoir dans les exif du média la géolocalisation.
Si on ajoute ce média avec l'import dans "collecter" puis sur une publication cartographique dans dodoc, le média se positionne automatiquement sur la carte au bon endroit.

Est-il possible d'avoir ce comportement à partir de l'outil "Capter" dans dodoc10 ?
Depuis une tablette ou un smartphone, j'ouvre dodoc, je vais dans un projet, j'ouvre capter et je prends une photo / vidéo / son
Si j'ajoute ce média dans une publication carto il se positionne directement au bon endroit.
Si je le souhaite je peux changer la position et l'enregistrer.

Idéalement on pourrait choisir si on veut utiliser la géolocalisation ou non dans les paramètres de la capture, là où il y a le choix du format de l'image ...

**Comment by louis-ev** [comment]
J'avance dessus en ce moment.
Je m'interroge sur le bon emplacement. À vrai dire l'idéal me semble être de l'avoir 2 fois : une fois à côté du menu règlages (pour gagner un peu en visibilité), et une fois au moment de la validation du média.
Je test et je te/vous dis.

**Comment by louis-ev** [comment]
à tester !

**Comment by louis-ev** [comment]
<img width="433" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/f4fd1029-6ecd-4a2c-87e9-9445f3ff1d91">

**Comment by jubonhomme** [comment]
Top !
Il faudra juste préciser que les services de carto sont accessibles si il y a une connexion internet pour les fonds de cartes.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/109a8ee0-4729-410f-bd11-41f7f64efbe1)


![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/dc51d85f-fcb6-458f-bcb0-56f88c0d5910)

**Comment by jubonhomme** [comment]
Pour la 10.1

Ajouter un picto 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/b1de84c1-bce3-45ca-8550-b8da482ee616)
pour indiquer que le média a une localisation dans la vue générale en liste / tuile
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/468a98c1-a429-4885-9f5d-731901cbc1d2)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4771d8a1-0323-4acc-9cd8-2c4faa433d41)

**Comment by jubonhomme** [comment]
Je passe en V10.1 pour la suite

**Comment by louis-ev** [comment]
Haha c'était en place il ya quelques mois et j'ai fais sauter, ça semblait anecdotique. Maintenant qu'on peut ajouter à la capture et modifier après coup, ça parait plus central. j'améliore la vue tableau en même temps : 

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/34d35b25-f78b-4d7a-8397-b493f7c1121d)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/8e8bbedc-36f7-4d13-8606-c607285365c9)

>  Il faudra juste préciser que les services de carto sont accessibles si il y a une connexion internet pour les fonds de cartes.
Tu penses à un petit message "Cette fonctionnalité utilise internet et les servers du projet Open Street Map" ? On doit cocher une case pour dire "accepter" avant l'ouverture ?

**Comment by jubonhomme** [comment]
L'idée c'est de faire comprendre que c'est pour trouver le lieu sur la carte qu'on a besoin d'internet mais que la localisation, une fois qu'elle est renseignée, n'a pas besoin d'une connexion permanente... si j'ai bien compris ;)

Quand on fait une recherche si on a pas de connexion il y a un message d'erreur : Error! No internet connection?
Mais on ne sait pas forcément pourquoi la carte ne s'affiche pas si on ne lance pas une recherche.

Donc je dirais qu'au lieu de cocher une case pour accepter, on peut juste mettre un message : 
"Pour afficher le fond de carte OpenStreetMap une connexion internet est nécessaire."

Dans la majorité des cas les utilisateurs auront une connexion (dodoc serveurs) ou ordi sur wifi et c'est donc transparent pour les utilisateurs, pas trop de question à se poser. Et on affiche juste pourquoi on ne voit pas le fond si on n'a pas d'internet pour signaler ce point à l'utilisateur. Mais la localisation fonctionnera quand même.

**Comment by jubonhomme** [comment]
Je ferme ici tout est en place
