### ISSUE TITLE
Affichage image aérienne comme fond de carte 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#775]
Peut-être une piste pour un fond image aérienne de l'IGN avec Openlayers (celui qui est utilisé par uMap)

https://geoservices.ign.fr/documentation/services/utilisation-web/affichage-wmts/openlayers-et-wmts

https://geoservices.ign.fr/documentation/services/utilisation-web/extension-pour-openlayers

**Comment by louis-ev** [comment]
C'est risqué d'embarquer une clé : si elle est révoquée, alors ça marchera plus pour tous les utilisateurs qui utilisent une version de dodoc qui l'embarque.
On peut cependant imaginer qu'il soit possible d'indiquer (par exemple dans les réglages de la carte) une clé spécifique, généré par un utilisateur de son côté. La seule limite c'est que la clé est communiquée à tous les utilisateurs du même dodoc et aussi à toutes les personnes qui consulteront des publications exportées de ce dodoc. Mais c'est un peu inévitable de toute façon.

**Comment by louis-ev** [comment]
Résolu en utilisant la clé decouverte : https://geoservices.ign.fr/services-web-decouverte
À tester :)
