### ISSUE TITLE
Bug affichage page à page

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#776]
Bug depuis la modification de la fenêtre des Réglages

La fenêtre des réglages est assez courte
Et quand on ouvre une page l'affichage plante et disparait

Dans les 3 publications (récit / page / carto) la fenêtre Réglage reste ouverte même si on passe sur "options" ou "Partager" et ça masque les deux. 
Il faudrait que ça referme le volet Réglages quand on clique sur Options ou Partager

**Comment by louis-ev** [comment]
Résolu le soucis de mise en page et le panneau réglage qui se referme, merci de l'info.
