### ISSUE TITLE
Bug Ajout d'une épingle en passant pas la recherche sur la carte

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#785]
SI je recherche un lieu sur la carte et que je le sélectionne, une fenêtre popup s'ouvre pour proposer l'ajout d'un texte ou d'un média à cet endroit.
Mais dès qu'on clique sur texte ou média on revient à l'endroit de la dernière création d'épingle.
Il faudrait qu'on reste sur la localisation de la recherche sans que ça revienne au précédent point.

**Comment by louis-ev** [comment]
Résolu
