### ISSUE TITLE
Epingle masquée par le texte / média sur la carte

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#786]
Si on ouvre un texte ou un média l'épingle est masquée par la fenêtre popup
ça pourrait être bien de l'afficher dans la fenêtre pour continuer à faire le lien entre la fenêtre et le panneau de droite
Pas forcément la mettre au premier plan sinon on masque le point mais plutôt reprendre l'info dans la fenêtre en haut à gauche. Un peu comme dans le panneau à droite

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/29d46e0a-6621-4e22-b2cf-de0daf193539)

**Comment by louis-ev** [comment]
Ou décaler la popup un peu plus haut, pour qu’on continue à voir l'épingle ?

**Comment by jubonhomme** [comment]
ok pour décaler plus haut
C'est la solution sur umap par exemple
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/79554f93-12ca-4fd1-824b-bdba4b4efa31)

**Comment by jubonhomme** [comment]
Top !
