### ISSUE TITLE
Bouton menu paramètre chapitre sur carte

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#788]
J'ai eu du mal à retrouver le bouton de menu des chapitres pour modifier les épingles.
Ne pas faire un bandeau sur toute la hauteur est une bonne chose car ça prenait beaucoup de place sur la page.
Mais l'emplacement en bas de la carte n'est pas très visible. 
Comme la création des chapitres se passe en haut dans le panneau de droite, je pense qu'on pourrait avoir le menu dépliant des paramètres en haut à droite dans la fenêtre de la carte. 
On le garde dans la carte pour bien montrer qu'un chapitre = une vue 
Mais on le place à côté de la vue des chapitres

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/41249235-143d-4e2f-b581-c756bbac2307)

**Comment by louis-ev** [comment]
Proposition : 
<img width="1840" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/8810ae15-9c17-4bb6-8778-2428602d62eb">

Tiens je remarque que le picto pour rechercher ressemble pas à ce que j'ai – c'est géré en interne par ol-geocoder 
https://github.com/Dominique92/ol-geocoder/

Il faudrait améliorer tout ça, homogénéiser les espaces et les survols, etc. Pas urgent urgent :)

**Comment by jubonhomme** [comment]
Ok je trouve ça mieux !
et le picto pour passer en plein écran au même endroit que pour les médias c'est bien vu

Je ferme
