### ISSUE TITLE
Impression publication cartographie

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#793]
Quand on clique sur imprimer la carte le premier aperçu n'est pas complet.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/17ca04c7-87e9-47a3-ba82-753e2d757ea3)

ça fonctionne si on choisit un autre format et qu'on revient sur le premier format. 

C'est juste sur le premier aperçu que ça bug

**Comment by louis-ev** [comment]
Tu peux retester maintenant ? Je n'arrive pas à reproduire ce soucis sur Chrome et Firefox.

**Comment by jubonhomme** [comment]
Oui j'ai toujours le même bug

J'ouvre une recette carto, je clique sur imprimer et l'affichage place une petite carte sur la page.

**Comment by louis-ev** [comment]
Ajout d'un petit délai de 500ms à l'ouverture pour laisser le temps à la carte de se re-rendre, dis-moi si c'est mieux ?

**Comment by jubonhomme** [comment]
Oui c'est tout bon
Je ferme
