### ISSUE TITLE
Changement de fond de carte

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#795]
Lors du changement de fond de carte d'un calque l'affichage revient à chaque fois au centrage de la carte et au niveau de zoom de référence.
Quand on veut juste vérifier une zone à l'aide de la photo aérienne et qu'on revient au fond OSM il faut retrouver la zone à chaque étape.

Il faudrait pouvoir changer le fond du calque sans que ça modifie la zone affichée

**Comment by louis-ev** [comment]
C'était le comportement que j'avais prévu mais bug dans le code :)
Corrigé !
