### ISSUE TITLE
Bug Confirmation pour sortir du mode "animation"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#799]
Si je suis dans "capter" sur une animation et que je clique sur le bouton "retour" en bas à gauche pour sortir de l'animation, la fenêtre se grise mais le message qui demande une confirmation est sous la fenêtre principale et n'est pas visible.
Il ne réapparaît entièrement que si on sort du projet.

**Comment by louis-ev** [comment]
Yes. Je corrige.

Il y a aussi 2 prévisualisations : une sur la page capture avec le bouton Lire, et une après avoir cliqué sur Assembler, en cliquant sur le bouton lecture vert. Je propose que cliquer sur Assembler lance directement la création du stopmotion, qui s'ajoutera automatiquement à la bibliothèque et sera aussi lisible dans la fenêtre (avec un bouton "annuler" qui le supprimer et permet de revenir à l'édition, et un bouton "valider" qui réinitialise la vue stopmotion ?)

**Comment by louis-ev** [comment]
Résolu soucis du bouton retour : j'ai supprimé la demande de confirmation (vu que de toute façon le stopmotion s'enregistre).

**Comment by louis-ev** [comment]
Bon j'ai un peu de mal à faire sauter cette fenêtre encore sans avoir pu tester en live auprès d'utilisateurs – @jubonhomme tu es vraiment sur que ça marcherait de lancer la compilation au bouton Assembler et de fermer le stopmotion direct ? Il faudrait peut etre mettre un petit message, une fenêtre modale qui indique que l'export se fait et propose une visu ?
Ou alors v10.1 ?
pour la v10 on fait quoi ?

**Comment by jubonhomme** [comment]
Je viens de mettre à jour et tester.
Le comportement actuel me va bien.
Le bouton lecture dans le mode animation est très utile pour visualiser au fur et à mesure ce qu'on fait avec la possibilité de choisir un nombre d'image / s et le tout sans sortir du mode prise de vue avec la pelure etc... Il n'était pas présent sur la V9 et c'est vraiment mieux. Avant on devrait cliquer sur Créer à chaque fois et revenir dans le mode prise de vue, pas très pratique et ça prenait du temps qd il y avait beaucoup d'images.

Le clic sur assembler qui ouvre une deuxième vue en mode lecture et qui met bien en évidence le nombre d'images par seconde est aussi très bien. Ça permet de refaire une vraie prévisualisation avec différente vitesse avant de lancer l'assemblage. Mais on est dans une vue épurée de contrôle en vue de faire le montage final et non plus dans un mode prise de vue. Donc très bien à mon avis. Et ensuite un clic sur enregistrer pour confirmer le choix de monter le film.  
Ce système en deux temps avec deux vues différentes me va bien, c'est un peu le mode "capter et fabriquer" = deux en un

Le bouton ouvrir dans la fenêtre popup qui bascule directement dans collecter (comme pour la découpe d'une vidéo) est bien aussi, on sort de capter pour visualiser la production.

Donc je dirais qu'on peut fermer ici pour le moment
