### ISSUE TITLE
Bug Incrustation fond vert - image de fond

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#801]
L'incrustation fond vert (ou autre couleur) fonctionne si on incruste une couleur mais pas avec une image en fond.

J'ai l'impression que le lien vers le dossier ou sont stockées les images est cassé. Impossible d'ouvrir le dossier du projet et si on ajoute une image par "importer" on voit bien l'image dans le bandeau incrustation mais rien en fond.

**Comment by louis-ev** [comment]
Après diagnostique j'ai tout cassé en réutilisant ce composant pour sélection une image de couverture pour un espace et un projet. Tout à fait normal. Nécessite un temps assez important pour résoudre le soucis pour que ça marche partout, ça sera pour plus tard… je désactive en attendant…

**Comment by jubonhomme** [comment]
Je viens de retrouver ce fil... donc ça n'a pas l'air aussi simple que je ne l'imaginais

**Comment by louis-ev** [comment]
Rétabli sur la branche next. Mais uniquement en utilisant une image du projet – il doit être possible de remettre en important une image sans avoir à la mettre d'abord dans le projet mais j'ai pas encore pu me pencher sur la doc. Si ça te parait pas indispensable, je te laisse ferme, sinon tu peux laisser ouvert pour pas oublier :)

**Comment by jubonhomme** [comment]
Perso je trouve l'option plus simple et plus claire que la version précédente. 
Concernant l'image qui doit forcément provenir du projet, je ne trouve pas ça gênant, on peut toujours cliquer sur importer pour ajouter une nouvelle image une fois la fenêtre modale ouverte.
On peut même choisir une image d'un autre projet.
Top !

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/65ed70f5-254f-4a93-938b-b46b301d29ef)

Par contre j'observe un bug qui fige l'image de la vidéo.
Pour reproduire : 
J'active l'option incrustation fond vert, je décoche la première case "couleur" -> l'image se fige
si je désactive l'option fond vert -> image en live OK
si je reactive l'option fond vert -> toujours figé
si je change de couleur ça reste figé
si je désactive / réactive après changement de couleur et en laissant la case couleur cochée ça remarche.

Proposition : Ne pas pouvoir décocher la première case "couleur" pour que ça reste toujours actif dès qu'on active fond vert.
Je ne vois pas l'intérêt de pouvoir décocher cette case si l'option fond vert est active.

**Comment by jubonhomme** [comment]
Je remonte ce bug... ça doit pas être grand chose à corriger et on ferme ;)

**Comment by jubonhomme** [comment]
Il faudrait juste faire sauter la case à cocher "couleur" qui est juste sous le bouton pour activer l'incrustation fond vert pour ne pas que ça fige l'image, cette option ne sert à rien il me semble.
J'active l'incrustation fond vert et je dois pouvoir choisir une couleur ou cliquer sur l'écran pour sélectionner une couleur dans la capture.
