### ISSUE TITLE
Fond blanc pour les SVG 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#802]
Le fond noir actuel pour les fichiers SVG rend peu lisible les dessins vectoriels dans la partie Collecter.

Est-ce possible d'avoir un fond blanc pour ce type de fichier avec des transparences ?

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/88abba9f-3be9-4ac2-8dab-00638a162034)

**Comment by louis-ev** [comment]
Effectivement, problématique.
Et si on reprends le style pour les PDF ?

<img width="1728" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/414ff936-3c10-4a14-8352-9de3858a5bb9">
<img width="1728" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/4206d3af-76b7-4d7c-aca7-d995f26381ee">

**Comment by jubonhomme** [comment]
oui

**Comment by louis-ev** [comment]
Au fait j'ai déplacé les flèches aussi, pour qu'elles soient toujours sur le média (y compris en mobile). Mieux ?

**Comment by jubonhomme** [comment]
oui j'ai vu hier les flèches TOP !
