### ISSUE TITLE
changer le remplissage des apercus de média / panneau Collecter

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#805]
Je m'interroge sur la présentation "plein pot" des apercus ici : 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/3d9903e3-9ed9-4951-98cb-85d3a0a51931)

Visuellement c'est moins chargé, mais on voit plus l'ensemble de l'apercu (qui est rogné). Ne serait-ce pas plus facile de se repérer et retrouver les contenus importés comme ça ? 

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/173d7eff-e284-4c5d-87fa-adb6a7b2e970)

**Comment by jubonhomme** [comment]
C'est vrai qu'on voit moins le format quand c'est plein cadre mais visuellement c'est plus beau et c'est un affichage assez classique de bibliothèque de médias.
Perso je garderai comme c'est maintenant en plein cadre.  
Surtout que ce composant est repris en petit pour l'ajout de médias dans une publication donc c'est bien de voir plein cadre.

**Comment by louis-ev** [comment]
Je comprends oui. Et si on réservait ça au mode "aperçu tuile grande" ? 

<img width="893" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/e754e6d4-9c3c-4d65-afdb-a629ec41219b">

**Comment by jubonhomme** [comment]
Donc oui !
