### ISSUE TITLE
Import image vignette dans Espace "depuis le projet"

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#807]
Quand on veut ajouter une image en vignette d'un Espace on peut aussi ajouter avec "depuis le projet" ,

Si on importe une image dans le projet on voit que ça charge mais on ne voit pas l'image apparaitre dans les médias disponibles.
Si on sort de l'espace et qu'on revient l'image y est bien.

**Comment by louis-ev** [comment]
J'ai pas compris. Après validation, l'image est pas chargée directement ? Il faut quitter/revenir sur l'espace pour la voir ?
Je n'ai pas ce soucis en local, tu l'as en ligne ? Si oui, comment le reproduire ?
Merci

**Comment by jubonhomme** [comment]
A voir ici, j'ai utilisé test10.dodoc.fr

**Comment by louis-ev** [comment]
Il me semble que c'est normal : tu importes un PDF, alors que tu dois choisir un média "image". Du coup il est bien ajouté mais invisible (car le filtre "image" l'empêche d'apparaître).

Faut-il interdire l'importation de médias qui ne sont pas des images à cet endroit ? Ou interdire l'importation dans collecter quand il s'agit de couverture (il y a l'option "importer une image" qui apparait en haut de toute façon) ?

**Comment by jubonhomme** [comment]
Non c'est tout bon, c'est moi qui me suis planté...
Je ferme
