### ISSUE TITLE
Traduction apparait au deuxième clic

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#811]
Voir sur la capture, la traduction en fr n'apparait qu'au deuxième clic. 
En premier c'est en anglais puis en fr, ça revient en anglais puis en fr etc...

Et si tu peux aussi ajouter un s pour les secondes dans l'affichage sous le graph

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/dd14842e-4f5a-4152-8738-66508fc8631d)

**Comment by louis-ev** [comment]
C'était juste pas traduit :) si le texte est en minuscule avec des _ au lieu d'espaces, c'est l'identifiant et pas la trad.
Je propose les trad suivantes : 
```
      fr: {
        start_egal_to_end: "Le début est identique à la fin",
        end_before_start: "La fin est avant le début",
        export_trim_video: "Exporter la vidéo recoupée",
      },
      en: {
        start_egal_to_end: "Start is equal to end",
        end_before_start: "End is before start",
        export_trim_audio: "Export trimmed video",
      },
```
