### ISSUE TITLE
recette son + vidéo - pourcentage

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#815]
La recette fonctionne bien, c'est juste le pourcentage quand on génère qui fonctionne étrangement

Exemple sur cette recette : 
https://test10.dodoc.fr/+espace/test-son-video?projectpanes=%5B%7B%22type%22%3A%22make%22,%22size%22%3A100,%22make%22%3A%22son-sur-une-video-fjy%22%7D%5D

le début se passe bien ça monte doucement puis ça accélère jusqu'à 1100 % et ça redescend  jusquà 599 %.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/b040c698-00c3-477e-b66a-e18545e0bc85)

Pas d'urgence mais juste pour ne pas oublier

**Comment by louis-ev** [comment]
Ah oui ? hahaha c'était effectivement pas prévu :)
ffmpeg reporte assez bizarrement le décompte, on re-regarde pour la 10.1 !

**Comment by jubonhomme** [comment]
Après un nouveau test ça semble résolu 
Je ferme ici et on ouvrira à nouveau si besoin
