### ISSUE TITLE
Superposition boutons et player audio sur vue verticale

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#816]
La vue haut / bas des médias dans collecter est vraiment mieux quand le format d'écran est vertical.

Juste un petit problème avec les boutons avant / après qui se superposent au player audio

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c4b736ab-e3e8-4088-b861-906c4b096afc)

**Comment by jubonhomme** [comment]
Le plus simple est peut-être de juste décaler le player pour qu'il ne soit pas au milieu mais par exemple à 1/3 en bas de la fenêtre

**Comment by louis-ev** [comment]
J'aime pas quand c'est pas aligné :)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/6034971d-5209-4342-92a8-fcc80f3b1bb4)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/be91f3cc-3326-400d-ad12-54fba2fc7ee0)
