### ISSUE TITLE
revoir filtres projets

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#819]
Remonter **Disciplines** et **Publics cibles** : 

<img width="299" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/178d7adb-dbe5-4d55-83cc-ba59cf0f6ad5">

Afficher les X premiers, puis un bouton "afficher tout" ?

Pouvoir rechercher dans les mots-clés / machines / etc.

**Comment by louis-ev** [comment]
Retirer "événements"

**Comment by louis-ev** [comment]
Organiser les mots-clés par fréquence ?

**Comment by jubonhomme** [comment]
Ça me parait complexe d'organiser les mots clés par fréquence car on va avoir beaucoup de mal à retrouver un mot sans devoir tout lire. L'avantage de l'ordre alphabétique est quand même intéressant.

Je pense aussi qu'un champ de recherche est nécessaire, dès qu'il y a un certain nombre de mots clés ça devient difficile.

Est-ce qu'un champ de recherche pourrait filtrer les mots clés des différentes catégories en une seule fois.

Exemple : 
Dans le champ de recherche je tape : jeu mathématiques cycle 2

-> L'affichage donne  : 
jeu jeux Jeux
mathématique
cycle 2

**Comment by FabLabEcoCentre** [comment]
Pour les machines et matériaux, est-il possible d'en ajouter soi-même ?

Je constate que cela se passe au niveau des fichiers "TagsSuggestionsList.js", "175.js.map" et "175.js"

Est-ce qu'on peut simplement en ajouter en direct dedans, comme un bourrin ? ;p
Selon moi, le plus simple serait qu'un ajout manuel soit enregistrer d'une manière ou d'une autre dans la BDD (avec les risques de multiplicité que cela comporte) car ajd c'est trop limitant et ça pousse justement à des multiples par erreur de frappe ou quoi du fait de la non proposition :'(

**Comment by jubonhomme** [comment]
On avait déjà échangé sur ces questions avec @louis-ev  mais impossible de retrouver ça dans le forum ou sur git.

Voici dans mes souvenir quelques points évoqués : 
Si on veut pouvoir importer / exporter des projets d'un dodoc à un autre il serait pratique d'avoir des listes communes de métadonnées. 
Mais si on affiche un trop grand nombre de possibilités, on risque aussi de perdre les utilisateurs et surtout les jeunes élèves.

L'auto complétion me parait une bonne chose. 
La possibilité pour un admin de plateforme de masquer une partie de la liste serait intéressant. 

Ou autre proposition serait d'avoir une liste commune et des "templates dodoc" réglables au niveau admin : 
je suis dans une école je coche liste pour école (proposition de machine simplifié, mais liste importante de filtre par niveau / discipline ...), je suis dans un fablab je coche liste pour fablab (plus complète au niveau matériel mais épuré sur d'autres points), je veux ma propre liste je coche liste personnalisée et je choisis en sélectionnant dans la liste commune ce que je souhaite voir dans la liste déroulante et je peux ajouter des entrées.

**Comment by jubonhomme** [comment]
Suite a un échange aujourd'hui avec Philippe au sujet des métadonnées des projets voici quelques pistes et exemples.

Une suggestion (afficher les mots clés / auto complétion) au niveau des mots clés serait vraiment utile pour éviter d'avoir les erreurs de saisie, un trop grand nombre de propositions avec différentes écritures du même mot, des créations de mots clés qui sont déjà utilisés dans d'autres champs (machines / matériaux / disciplines...)

Une recherche complète sur les différents champs et pas seulement sur les titres.
Exemple de Esup Pod qui utilise[ Elastic search ](https://www.elastic.co/fr/elasticsearch/)
https://podeduc.apps.education.fr/search/?q=fablab

Avoir un thésaurus commun avec d'autres plateformes (éducation / fablab..) permettrait d'utiliser plus simplement les métadonnées si elles sont communes.

**Comment by louis-ev** [comment]
Je ferme cette issue, la dernière branche implémente tout ça.
@jubonhomme si tu veux recréer une issue pour ces améliorations (suggestion mots-clés ?). Et on classifie 10 ou 10.1 :)
