### ISSUE TITLE
Modifier une image : déformation de l'image si prise avec téléphone

### ISSUE THREAD

**Issue by FabLabEcoCentre** [l-atelier-des-chercheurs/dodoc#821]
Hello

J'ai l'impression que les images prises avec un téléphone sont systématiquement converties vers un format paysage rigide. Cela amène à des déformations mineures lorsque la photo a bien été prise en paysage mais sur un format similaire, mais surtout à des déformations énormes pour les photos en portrait.
Ci dessous un exemple :

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/100687849/272751f4-fda7-4a6d-a98e-c7db4bc52fac)

**Comment by louis-ev** [comment]
Le soucis ici est lié au fait que le smartphone stocke les pixels dans le sens du capteur, et ajoute dans une métadonnée le sens d'affichage de l'image.
Le moteur de chargement du recadrage ici est pas très malin, il lit pas les métadonnées. Il faudrait. Je note.

**Comment by jubonhomme** [comment]
A fermer ?

**Comment by jubonhomme** [comment]
Je ferme et on re ouvre si besoin
