### ISSUE TITLE
Récit : bug quand on duplique un contenu 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#825]
protocole pour reproduire le bug
- dans récit, ajouter un bloc texte 
- écrire du texte dedans
- cliquer sur le bouton _dupliquer_ 
- supprimer le bloc qui vient de se dupliquer
- on se retrouve avec le bloc de texte d'origine
- cliquer à nouveau sur le bouton dupliquer
- bug : le contenu se duplique 2 fois (2 blocs)

**Comment by louis-ev** [comment]
Euh j'ai pas ça ? 
@jubonhomme est-ce que je peux te demander de tester aussi ?

**Comment by jubonhomme** [comment]
Oui j'arrive à reproduire le bug de Sara
Bloc texte 1 je duplique 
Je supprime bloc texte 2 qui est généré
Je reduplique le bloc 1
J'ai la création d'un bloc 3 et 4

**Comment by louis-ev** [comment]
Hello ! 
Y a eu pas mal d'améliorations sur la duplication et la gestion des blocs textes collaboratifs, je viens de tester (duplication / modification suppression de pleins de blocs textes en chaine et rapidement) et pas de soucis.
Vous pouvez tester / fermer ?

**Comment by louis-ev** [comment]
Plutôt, je ferme et je vous laisse rouvrir si besoin :)
