### ISSUE TITLE
Récit : séléction d'un élement ferme le bloc quand la souris sort du bloc 

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#826]
Dans un bloc texte, si je veux sélectionner un élément (un titre par exemple pour changer la typo) et que ma souris sort du bloc pendant la sélection ça ferme le bloc ( et c’est assez énervant…)

**Comment by louis-ev** [comment]
Je retire ce comportement – pour quitter le mode édition d'un média dans une publication, il faut soit cliquer sur le ✔️ , soit changer de chapitre, soit lancer l'édition d'un autre média. Si ça te manque on tentera autre chose :)
