### ISSUE TITLE
Récit : Bug page blanche à l'exportation d'un pdf

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#830]
Si j’exporte un récit, j’ai une page blanche entre chacun de mes chapitres

**Comment by louis-ev** [comment]
Pas le cas ici. J'ai une page blanche si j'arrive tout en bas de la page précédente éventuellement.
Tu peux retester plus précisément ?

**Comment by louis-ev** [comment]
Je ferme, rouvrir si nécessaire :)
