### ISSUE TITLE
Bug: importer / exporter un projet

### ISSUE THREAD

**Issue by sarahgarcin** [l-atelier-des-chercheurs/dodoc#834]
Exporter, dézipper, rezipper et réimporter un projet = ça ne marche pas

**Comment by louis-ev** [comment]
Ok mais… c'est un problème tu penses ?
J'y arrive en compressant non pas le dossier créé à la décompresser mais tous les contenus (command + A / compresser, ce qui créer un Archive.zip sur macos. Mais ensuite le soucis ce sont les fichiers créés par macos __MACOSX ajoutés à l'archive.

C'est peut-être pas plus mal au final : il vaut mieux que les utilisateurs n'ouvrent pas le ZIP, il y a un gros risque de corruption du dossier. S'il reste en .zip, pas de risque.

**Comment by sarahgarcin** [comment]
Non ce n'est pas un problème, le tout c'est d'expliquer le processus quelque part.
Par contre, on a pas testé entre instances différentes, mais je vois pas pourquoi ça ne marcherait pas

**Comment by jubonhomme** [comment]
J'ai pu tester entre deux instances sur serveur /serveur  mais aussi entre serveur / local et local / serveur.
Tout est bien transféré tant qu'on bascule le dossier .zip sans y toucher.

**Comment by louis-ev** [comment]
À la réflexion ça doit pas être bien compliqué d'ignorer les fichiers insérés par macOS/linux/windows et de prendre en charge le zip même s'il a été fait sur le dossier à la main (exemple : plutôt que de télécharger un zip en passant par dodoc, je créer un zip en passant par l'explorateur de fichier en cliquant sur le dossier entier).

Sarah tu aurais une référence pour quoi ignorer ?
Est-ce que si j'ouvre chaque fichier .meta.txt et que je les copie ainsi que le $media_filename qui est indiqué dedans c'est bon ?
Ou alors ne prendre aucun fichier caché ? Plus simple à faire.

**Comment by louis-ev** [comment]
Oui en fait ça devrait pas être bien compliqué :)

**Comment by sarahgarcin** [comment]
Ok cool ! :)
Oui prendre aucun fichier caché ça me semble une bonne piste.
Qu'est-ce qu'il se passerait si quelqu'un ajoute une image au dossier par exemple ?

**Comment by louis-ev** [comment]
Rien : dodoc scan les fichiers qui terminent par .meta.txt uniquement et lis dedans la propriété $media_filename pour connaître le fichier source en lien.

**Comment by louis-ev** [comment]
Tu me fais penser que ça serait pas mal d'avoir une doc développeur ou utilisateur avancé qui raconte comment les dossiers sont lus et comment les données circulent.

**Comment by louis-ev** [comment]
Je change la logique au téléchargement : plutôt que de mettre tous les contenus directement à la racine dans le zip, je les place dans un sous-dossier du nom du dossier dans `projects` dans le zip. Pour être sur qu'au dezip, ça créer bien un dossier avec le bon nom et pas tous les contenus directement à la source.
Ça permettra aussi d'homogénéiser les ZIP entre ceux provenant de la fonctionnalité "télécharger" et ceux créés en naviguant dans le dossier de contenu, et en cliquant droit sur un dossier de projet "Compresser".

**Comment by jubonhomme** [comment]
A fermer ?
