### ISSUE TITLE
enregistrement audio : bon format de fichier ?

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#839]
D'après 
https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/audio-recording.html#L205

l'enregistrement avec recordRTC produirait du MP3. à vérifier

**Comment by paulinegourlet** [comment]
J'ajoute ici : convertir le wma (illisible pour l'instant)

**Comment by louis-ev** [comment]
Il semble que l'enregistrement en wav puisse contenir du mp3, je ferme :)
