### ISSUE TITLE
Bibliothèque -> pouvoir filtrer les médias par auteur

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#840]

**Comment by louis-ev** [comment]
En place pour les exports "fabrications" et "publications", à tester !

**Comment by jubonhomme** [comment]
Je vois bien comment on peut ajouter un auteur ou en enlever. Par contre je ne vois pas la possibilité de filtrer les médias par auteurs.. j'ai loupé une étape ?

**Comment by louis-ev** [comment]
En place dans la bibliothèque : 

<img width="223" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/6faf5474-e7bd-4cee-8ca6-09895ecde464">
<img width="239" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/156969e2-c937-47c7-99d2-325f6c81e137">
