### ISSUE TITLE
Flou sur image

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#843]
Pouvoir gérer une zone à flouter plutôt que toute l'image (notamment utile pour visages / conformité RGPD)

**Comment by jubonhomme** [comment]
Doublon avec #326 ?

**Comment by paulinegourlet** [comment]
Tout à fait ! Heureusement que tu veilles — ça fait partie d'une liste longue comme le bras discutée au dernier point ADC mais dont bcp des issues étaient en fait déjà ouvertes...
