### ISSUE TITLE
Récit/Carte -> scroll compliqué

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#844]
Difficile de scroller vers le bas quand on est avec le bandeau projet, la barre des quatre tâches et les deux panneaux cartes et récit. Soit ça dézoom dans la carte, soit ça scroll dans le récit. Il faudrait une zone plus grande où le scroll n'est pas actif ?

**Comment by louis-ev** [comment]
Normalement au click dans la zone sous le menu des 4 panneaux, ça te fait scroller vers le bas pour bien caler la publi.
Que proposes-tu ?

**Comment by louis-ev** [comment]
Je ferme, rouvrir si besoin.
