### ISSUE TITLE
Récit -> disparition de l'adresse d'un lien avec l'affichage mosaïque

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#849]
<img width="980" alt="Capture d’écran 2023-11-22 à 16 59 52" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/7995654/de008e69-fb46-4add-ab3d-7ad4b6d5d3bd">
<img width="970" alt="Capture d’écran 2023-11-22 à 17 00 49" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/7995654/55fc4e69-6178-403e-81cd-0d133969ea3b">
<img width="955" alt="Capture d’écran 2023-11-22 à 17 00 59" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/7995654/ed415b20-ae9d-486f-827f-16de38f46d0e">

Je ne récupère l'adresse que si je clique sur l'aperçu du lien et que je drag le coin en bas à droite...
Et comme l'embed marche pas, je ne sais pas du tout ce que je suis censé comprendre de ce média (ni même si c'est un lien, une image ou autre...)

**Comment by louis-ev** [comment]
Est-ce qu'il faudrait un bouton pour afficher/masquer le lien ? Ou on le met sur une seule ligne avec une ellipse, en bas du cadre en superposition ?

**Comment by louis-ev** [comment]
@paulinegourlet tu peux retester ?

**Comment by louis-ev** [comment]
Je ferme :)
