### ISSUE TITLE
Bouton "accéder à la copie" après duplication d'une publication non valide

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#851]
Quand on duplique une publication (récit ou page à page) on a une dernière fenêtre pour accéder à la copie
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/54334609-9244-4824-8ae9-55001353f887)

Mais le bouton n'est pas actif

**Comment by louis-ev** [comment]
À tester. Je reload "pour de vrai" la page du coup, plus simplement une mise à jour des composants. C'est peut-être pas la meilleure solution cela dit, je met un todo pour plus tard.

**Comment by jubonhomme** [comment]
Testé ça fonctionne
Je ferme
