### ISSUE TITLE
la gestion des mots de passe

### ISSUE THREAD

**Issue by spiderwan** [l-atelier-des-chercheurs/dodoc#856]
Problème des mots de passe qui s'enregistrent, c'est un problème, car l'élève qui passent après peut visualiser le mot de passe d'un autre élève ou d'un autre utilisateur passé avant, même si ordinateur est éteint entre les deux, même l'administrateur.

exemple : 
Gabriel se connecte mais il voit qu'un mot de passe est déjà enregistré, 

![capture-decran-2023-12-04-162946](https://github.com/l-atelier-des-chercheurs/dodoc/assets/73277691/98a2f120-a0db-4d8e-abc0-e2e589a0177b)

il le révèle pour voir si c'est bien le sien, et il voit alors le mot de passe d'un élève qui sans doute passé avant lui ?? il le révèle et comme aujourd'hui gros bazar entre eux .....
![capture-decran-2023-12-04-18152201](https://github.com/l-atelier-des-chercheurs/dodoc/assets/73277691/09b51448-1222-457d-80cb-8437513222ff)

**Comment by jubonhomme** [comment]
Salut Erwan,

À voir les captures d'écran tu n'es pas sur la dernière mise à jour de dodoc. 
@louis-ev a corrigé un grand nombre de chose ces derniers temps... peut-être qu'en faisant une simple mise à jour ça pourrait déjà régler une partie des issues.

**Comment by louis-ev** [comment]
Je confirme, bien qu'ici il me semble que le soucis vient du navigateur et pas du code de dodoc (qui n'enregistre pas le mot de passe en clair, celui-ci ne connaît qu'une version cryptée indéchiffrable).

Je pense que l'utilisateur précédent a cliqué sur "Enregistrer" sur le menu suivant, qui s'affiche lorsqu'on s'identifie.

<img width="553" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/a0ff6ca8-2f7c-4b7a-a949-6b699e7dd071">

Ce que je peux corriger, c'est que le mot de passe soit bien associé au compte et pas à "Aucun nom d'utilisateur" comme indiqué dans le menu dans le screenshot – qui fait que le mot de passe d'un autre compte ressort là où il ne devrait pas.
Du coup Gabriel aurait uniquement comme suggestion le mdp de Gabriel. Ce serait déjà mieux. Désolé pour ce bug, merci pour l'info :)

Par contre si Gabriel veut tester tous les comptes pour voir s'ils ont enregistré leur mdp sur le navigateur, à priori il pourra le faire. Mais ça sera moins visible/tentant, c'est sur :)

**Comment by louis-ev** [comment]
J'ai amélioré l'enregistrement pour que le nom soit bien associé au mot de passe, mais je ne peux pas empêcher le mot de passe d'être révélé si un utilisateur a cliqué sur "Enregistrer" pour son mot de passe…

<img width="305" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/b9d4fd55-dc19-4cbd-bcf1-440c8cc747f6">

Je peux supprimer la fonctionnalité "révéler le mot de passe" mais ça changera rien au fait qu'on pourra se connecter en tant qu'un autre compte – juste pas le lire…

Qu'en pensez-vous ?

**Comment by jubonhomme** [comment]
Je suis bien content moi de pouvoir afficher le mot de passe quand je le tape parce que souvent d'un clavier à l'autre il m'arrive de faire des erreurs de frappes.
Donc je veux bien qu'on laisse le bouton révéler.
Si on ne veut pas que dodoc garde les mots de passe on peut aussi paramétrer le navigateur pour en jamais enregistrer sur ce site.

Un autre retour sur une sujet assez proche : est-ce que la fenêtre de connexion pourrait se fermer uniquement quand on clique sur un bouton fermer ou se connecter mais pas quand on clique à l'extérieur ?
Quand on a un bon nombre de comptes, la popup qui s'ouvre automatiquement pour proposer les comptes recouvre presque toute la fenêtre de connexion, et si on clique à l'extérieur pour récupérer la vue de la fenêtre ça la ferme.  Sur ma machine, je dois cliquer juste en bas de cette fenêtre pour la refaire passer au dessus et fermer les propositions mais ce n'est pas pratique.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/7301967e-9756-481a-a000-2bb06a8e45b8)

**Comment by louis-ev** [comment]
Hmm je vois ce que tu veux dire mais du coup ça change le comportement
d’une seule fenêtre par rapport à toutes les autres…
J’ai déplacé les suggestions pour qu’elles arrivent au dessus du champ de
texte et on peut aussi ne pas centrer cette fenêtre pour que ça « saute »
moins, peut être que ça serait suffisant ? Mais c’est clair que les
suggestions du navigateur sont gênantes…

**Comment by jubonhomme** [comment]
Je viens de mettre à jour et ça fonctionne très bien pour moi !
Merci

**Comment by spiderwan** [comment]
A priori avec la mise à jour faite, plus difficile de trouver de mot de passe d'un autre élèves même si enregistré.
Merci

**Comment by jubonhomme** [comment]
A fermer ?
