### ISSUE TITLE
la légende des médias

### ISSUE THREAD

**Issue by spiderwan** [l-atelier-des-chercheurs/dodoc#858]
Il est possible de mettre un légende sur un média , mais il n'y a plus la possibilité ( idéalement optionnelle) de la faire apparaitre sous le média une fois intégrée dans une publication.

**Comment by louis-ev** [comment]
Vous pensez que ça devrait être possible côté page à page ? 
Comme dans la v9, la légende "pendouille" du média ?

<img width="239" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/e2b35a63-e24a-4f69-ba23-ff77b470446f">

**Comment by jubonhomme** [comment]
Si on ajoute une légende dans Collecter et qu'on la récupère directement avec l'ajout d"un média dans la publication récit et carto je trouverais normal de la voir aussi dans le page à page
Donc oui pour simplifier les comportements entre les publications.

**Comment by spiderwan** [comment]
Oui le comportement de la V9 interressant , peut être juste en plus avec une option pour afficher ou non. Car concrêtement on peut vouloir laisser une légende pour mémoire  destiné aux contributeurs, ou une légende que l'on veut aficher.
Ici la légende dnas les écoles sert à inviter les élèves à systématiquement signaler la source de leur média si récupéré sur le net , la légende "obligatoire" les éduque au droit à l'image, aux règles rgpd .....
Mettre une légende avec un bout de texte à ajuster correctement dans le page à page est laborieux.

**Comment by spiderwan** [comment]
Un peu sur le même sujet, la fonction qui permettait, directement du média dans la publication, de pouvoir revenir à son édition était vraiment utile, permettant d'intervenir dessus sans  pour autant sortir de la publication.

**Comment by louis-ev** [comment]
C'est en place, à tester sur https://test10.dodoc.fr/ :
- les médias des page à page peuvent avoir une légende (réglable sur la page ou dans le menu à gauche)
- il est possible de la modifier / supprimer
- les modules textes ne peuvent plus avoir de légende (on l'avait statué sur la v9, j'ai repris°
- ajout d'un bouton "modifier la source"

**Comment by jubonhomme** [comment]
Super !

Une ou deux remarques en complément 
- la légende du média en proposition est affichée en majuscule, peux-tu reprendre la version identique à l'originale (si maj -> maj / si min -> min) ?
- je trouverais bien d'avoir un cadre discret comme pour le bloc média au dessus pour bien identifier ce bloc "légende" et bien relier les 2 propositions
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/864fcc56-4b8c-4026-9eec-8a1a5af9d8a9)

- l'indication pour le Markdown est bien mais ça ne parle pas à tous.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/b99d8bf6-a9ca-481f-8958-7a06727670cb)

Est-ce qu'on pourrait ajouter une aide qui s'ouvrirait à partir d'un bouton si on veut des infos sur la syntaxe à utiliser ?
Exemple sur CodiMD si on clique sur un petit bouton 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c4431b2e-9a92-41f9-8bbd-eae06cf4fc2d)


ça ouvre ce pense bête (pas obligé d'être aussi complet)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/d7dc9c9d-555d-43d0-91c1-93fcc0c2d47c)

**Comment by spiderwan** [comment]
test effectué, la légende ajouté via le bandeau à gauche fonctionne bien et est comprehensible.
bouton vers la source ok, super , mais si on écrit une légende par ici, ce n'est pas elle qui est affichée.

Donc finalement une image peut être légendée pour une info "privée" propre au média ( via modifier la source)  et être légendée pour être affichée dans la publication ( via le bandeau de gauche lorsque l'on est dans la publication.

propositions de mise en valeur et d'une aide aux codes CodiMD super.

**Comment by louis-ev** [comment]
Ok merci :)
Je rouvre et met 10.1 pour pas qu'on oublie ! J'aurai pas le temps avant je pense
