### ISSUE TITLE
Accès aux médias des autres projets

### ISSUE THREAD

**Issue by spiderwan** [l-atelier-des-chercheurs/dodoc#859]
Lorsque l'on place un média dans une publication, un menu déroulant invite à pouvoir aller piocher dans un autre projet dont on aurait j'imagine l'accès, mais cela ne marche pas.
![01](https://github.com/l-atelier-des-chercheurs/dodoc/assets/73277691/0736fc4b-f8ac-4237-a68c-7ba06f5dfcda)

**Comment by louis-ev** [comment]
Implémenté il y a quelques semaines, il faut que je mette à jour ton instance :)
