### ISSUE TITLE
Exportation ou lien direct du publication - la page blanche

### ISSUE THREAD

**Issue by spiderwan** [l-atelier-des-chercheurs/dodoc#860]
Il arrive que l'exporation PDF d'un document, ou même le lien direct, aboutissent à une publication visible avec son titre mais vide ....

**Comment by louis-ev** [comment]
Je reprends le message que j'ai mis sur le forum, je veux bien ton avis ! 

> Pour le partage, effectivement si on instance est protégée par un mdp général, aucun contenu ne peut être visualisé par ceux qui n’ont pas le mdp. Il faut que j’intègre un système déclaratif.
>
>Je vous propose, dans le cas ou je souhaite partager une publi en mode « ouvert à tous »,
>
> -   j’ouvre la publication dans dodoc en étant connecté en tant que contributeur d’un projet, et je coche une case « partager un lien public vers cette publication ». Cette information est enregistrée et peut être modifiée par tous ceux qui peuvent modifier la publi (tous les référents et contributeurs du projet)
> -    ça me donne le lien que tu as indiqué ici
> -    je peux transmettre ce lien à qui je veux, l’accès se fera sans mot de passe mais sans possibilité de modifier les contenus par les visiteurs
> -   si je le souhaite, je peux annuler ce lien pour qu’il ne charge plus la publi automatiquement et affiche la fenêtre « mot de passe général », si j’ai changé d’avis ou ajouté du contenu perso/sensible à ma publi
>
> Qu’en pensez-vous ?
> Est-ce suffisamment puissant/permissif ?

**Comment by spiderwan** [comment]
Oui bonne idée, le but étant tout de même en exportant c'est de pouvoir partager le résultat de son travail sans pour autant l'avoir achevé ni en donner un accès. Ok

**Comment by louis-ev** [comment]
Soucis export PDF ? Voir l'autre issue https://github.com/l-atelier-des-chercheurs/dodoc/issues/861 
(l'export PDF et la prévisualisation image d'une publi utilisent le même code)

Donc pour l'export PDF normalement on est tout bon.
Par contre pour le partage, la règle ci-dessus pourrait s'appliquer (c'est pas encore en place).

**Comment by Spiderwan01** [comment]
Toutes ces questions d'accès et de partage ne sont pas simples, on en prend pleinement conscience vraiment lorsque l'on est confronté à la situation.
Actuellement, c'est mon cas ayant des publications que je souhaite partager, mais pas forcément en direction de gens à qui je veux donner le mot de passe de la plateforme de ma classe ( comme sur la V9) tout en conservant la protection RGPD du reste et des auteurs, avec une facilité de partage en format html ou via une version pdf ( nouveau média partagé)

Pour m'y retrouver, j'ai essayé de revoir l'ensemble des besoins dans un cadre d'usage en classe avec élèves.

J'ai mis  cela sous la forme de carte mentale :
Je vous fais partager cela en format ouvert :

https://www.canva.com/design/DAF8e74_dlM/3rZtnwofbFTzKKJTb6YYOw/edit?utm_content=DAF8e74_dlM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/159693804/58691118-5083-4a07-818a-12f86230c055)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/159693804/f44b9020-4e50-4d52-bd54-d48f8aae444d)


![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/159693804/28c1b8e5-bb86-4032-aa89-fd32762ca15b)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/159693804/d3e1b3e2-1739-47eb-bf7b-0ccb1b9e52ce)

**Comment by louis-ev** [comment]
Waouh sacré travail !
Quelle conclusion ? c'est trop complex à ton avis ? Il faudrait simplifier ?
Ou avec le systèeme de partage de publi sur instance protégée par mdp, on est bon ?

**Comment by louis-ev** [comment]
Je ferme, n'hésite pas à rouvrir si besoin :)
