### ISSUE TITLE
personnalisation des vignettes

### ISSUE THREAD

**Issue by spiderwan** [l-atelier-des-chercheurs/dodoc#861]
Y a t'il un  type de contenu dans une publication pour conduit à  générer sa vignette ?
car pour le moment même en forçant, de mon côté elle ne génère pas.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/73277691/f98ca3db-c2ce-4cb6-b812-0adcc8c10e1c)

**Comment by louis-ev** [comment]
Bizarre, ça marche effectivement pas chez toi mais partout ailleurs…

**Comment by jubonhomme** [comment]
De mon côté aucun problème sur ce module.
Ça ne pourrait pas venir du module qui créé les vignettes pdf et aperçus qui serait désactivé ?  
"no--optional" ou un truc du genre

**Comment by louis-ev** [comment]
J'y ai pensé mais c'est moi qui gère l'instance de @spiderwan et j'ai pas eu de soucis à l'installation :D

**Comment by louis-ev** [comment]
Il manquait un paquet : 
`sudo apt-get install -y libgbm1`

J'ai amélioré le log qui s'affiche avec `npm run dev` pour bien l'afficher. Ça devrait afficher ça (je le met au cas ou qqun utilise la recherche dans github) : 

```
~ EXPORTER • err for puppeteer Error: Failed to launch the browser process!
/home/ubuntu/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

**Comment by louis-ev** [comment]
Bon par contre on a un autre soucis maintenant, que j'avais déjà constaté sur d'autres installations qui utilisent des mots de passe généraux :
<img width="321" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/592853cf-6b50-4202-8526-7ad64a647c9f">

L'aperçu se fait "trop" vite, le mot de passe n'a pas encore été entré dans le champ automatiquement…

**Comment by louis-ev** [comment]
Ok on devrait être bon !
0c1fe1b132ebdab1a2107cbf7e001fe9ad53dbba

**Comment by louis-ev** [comment]
N'hésitez pas à rouvrir si soucis sur ça :)

**Comment by spiderwan** [comment]
tout fonctionne à présent  , merci
