### ISSUE TITLE
Ajout dans la liste des Machines

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#864]
Suite à une discussion du jour :
Est-ce qu'on peut ajouter "Tablette" , "Webcam" et "Microphone" dans la liste des machines utilisées pour un projet ?
Exemple pour une station météo, on affiche les données sur une tablette tactile.
Les webcams (ou caméra) sont aussi utilisées dans certains projets pour lire de code QR ou faire des captations.
Idem pour les microphones (ou micro)

Au pire pour webcam et micro on peut toujours sélectionner "Capteurs" qui est déjà dans la liste

**Comment by JeFabrique-MaterielPeda** [comment]
Est-ce qu'on ne pourrait pas plutôt proposer une entrée prédictive (auto-complete si la machine existe déjà dans la base), qui permettra d'enrichir la base de données de façon contributive et évitera les doublons dus à des différentes orthographes ?

**Comment by jubonhomme** [comment]
C'est déjà le cas pour les matériaux et machines. Dès que l'on commence à taper un mot les propositions s'affichent en direct en dessous. 
Mais justement ces propositions ne s'affichent que si elles sont déjà dans la liste en dur dans dodoc.
L'idée serait d'avoir une liste un peu commune entre les différentes instances en dur à l'installation avec la possibilité pour l'admin de la compléter (ou la simplifier) suivant la coloration et le public de son instance. 
L'autre solution serait d'avoir un projet de démo / présentation à l'installation (comme dans la V9) dans lequel on ajoute toutes les machines / matériaux / mots clés que l'on souhaite proposer.
Ce projet pourrait même être masqué et accessible que pour l'admin.

Une chose qui manque aussi c'est l'autocomplétion pour les mots-clés qui eux ne possèdent pas de liste de base et donc de suggestion.

**Comment by jubonhomme** [comment]
Les listes de machines / mots clés / matériaux sont directement paramétrables dans la partie admin de dodoc

![image](https://github.com/user-attachments/assets/e8303bb2-7fc7-4c75-9aa6-0f3f2f9a9b9f)

![image](https://github.com/user-attachments/assets/b7049225-d0f8-47e7-9402-5039b54c8dfd)
