### ISSUE TITLE
Fenêtre Langue

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#865]
Il faudrait réduire un peu la largeur de la liste déroulante pour éviter d'avoir une barre de scroll en bas de la fenêtre à cause du bouton éditer.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/2b1fe456-cc33-4a20-9ad5-2b9acf552358)

**Comment by jubonhomme** [comment]
https://github.com/l-atelier-des-chercheurs/dodoc/commit/35e29e9de85d12f697e5873979af3da7554d37e0
Ok !

**Comment by louis-ev** [comment]
<img width="547" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/1a7fb9c8-99eb-48d5-91b7-250e76792ac4">
