### ISSUE TITLE
Collecter : Volet d'information des médias

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#866]
Pour être plus lisible il faudrait peut-être revoir un peu la place des éléments dans le volet de droite des médias
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/94ee969d-215d-4200-8e9f-f668fceb343d)

Le bouton "options" est très souvent utilisé pour supprimer / convertir / télécharger des médias. Il se retrouve un peu au milieu du volet alors qu'on le trouve tout en haut dans les publications. On pourrait essayer de le remonter en haut sur la même ligne que Média N° 

Le panneau "informations" qui se déplie se trouve tout en bas alors qu'il est en premier dans le volet des métadonnées pour un Projet.
Je le remettrais bien aussi en premier juste sous le nom du fichier

Un peu comme ça 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/eecc8d46-6c53-48c1-bace-0a82f911ac6c)

**Comment by jubonhomme** [comment]
Merci pour ces modifications.
j'ouvre à nouveau juste pour une chose.
Est-ce possible de remonter d'un cran le bouton option pour qu'il ne soit pas sur la même ligne que le nom de fichier ?
Le bouton se déplace à chaque fois juste après le nom et comme le nom des fichiers n'est jamais de la même taille, il se déplace toujours. 
Si tu peux le placer juste au dessus de cette ligne pour qu'il soit au niveau de "Média / Favoris"  ça éviterait qu'il ne se déplace.

Si c'est trop complexe je te laisse refermer ici.

**Comment by louis-ev** [comment]
Oui, c'est pas parfait encore.
Il y a ce problème et aussi la superposition avec les boutons pour replier la barre et fermer la fenêtre :  
<img width="296" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/0938ff85-272d-4402-94dd-190568eb4f77">

**Comment by louis-ev** [comment]
Je propose, pour résoudre tout ça : 

<img width="739" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/5c1764fb-3ec8-44ff-a502-49164e756008">
<img width="454" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/4d3811cc-5077-4444-9183-49c979f7ecbd">

(le petit _Informations_ flotte et n'est pas aligné, je résoudrai plus tard)

Sur mobile la croix suit le scroll : 
<img width="373" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/294af2af-8577-4fe1-ab9e-4929256ad234">
<img width="376" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/16bff49e-cbdf-4cfe-99d6-d7c44758bdb9">

**Comment by jubonhomme** [comment]
Top !
