### ISSUE TITLE
Partage publications

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#867]
Suite à un retour d'une collègue qui souhaitait avoir accès au pdf d'une publication.

Si je partage une publication Récit par exemple :
https://dodoc10.reseau-canope.fr/+creation-de-ressources-pour-la-formation/vectorisation-et-decoupe-numerique/publications/vectorisation-et-decoupe-numerique?display=section&section=section-1700728456679.meta.txt

Je n'ai accès qu'à la publication en ligne.
Est-ce qu'il serait possible de conserver l'affichage du bouton "Partager" sur cette page de la publication pour les simples lecteurs afin qu'ils puissent avoir le lien à copier / le code QR à utiliser directement ou imprimer / la possibilité de générer un pdf et le télécharger directement sans l'envoyer dans "Collecter".

**Comment by louis-ev** [comment]
C'est pas prévu, le menu disparaît pour laisser la place à la publication pleine page.
Pourquoi pas remettre un bouton "partager" qui ouvre le menu code QR, dans une emplacement bien pensé (et spécifique à chaque gabarit ?), oui.
Pour le PDF, si on pouvait éviter de le générer à chaque visiteur ça serait quand même pas mal – donc soit c'est une manip de l'auteur de la publi qui le génère et l'ajoute à la publi qqpart, soit le PDF est mis "en cache" pour être généré qu'au premier téléchargement. Pourquoi pas plus tard mais pas gérable en v10 je pense…

**Comment by jubonhomme** [comment]
Effectivement je n'avais pas en tête que faire un pdf côté utilisateur redemanderait à chaque fois de générer le doc, oui il faut donc éviter.
Et c'est aussi assez simple de générer le pdf côté contributeur / référent et de l'ajouter en téléchargement dans la publication ou comme fichier à télécharger dans le projet directement.
On garde ce fonctionnement, ok pour passer l'info.

Par contre si on peut avoir la popup avec le code QR/url pour partager facilement sur un autre appareil directement dans la publication ça pourrait simplifier.

**Comment by jubonhomme** [comment]
C'est actif sur la nouvelle version, on peut partager directement le code QR dans la fenêtre de la publication.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/25f1cba0-527a-4db2-ad8d-bf222a4529f4)
