### ISSUE TITLE
revoir interface données méta d'un projet

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#870]
Voici quelques idées concernant l'évolution de la page des projets (branche ui_projets)

Pour conserver le fonctionnement entre les espaces et les projets, je propose un bouton Options pour la page d'accueil de l'espace 
ça évitera aussi de cliquer sans le vouloir sur "supprimer" alors qu'on veut juste cliquer sur plus d'informations pour ajouter un contributeur

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/8840ac6f-6097-480d-9622-8507c1b43f91)

Pour la page projet :

L'idée de ne pas aligner toutes les métadonnées sur la droite est bien vu, on ne voyait pas souvent les blocs du bas qui étaient masqués par défaut.
Mais en voyant le bandeau horizontal je trouve que ça prend quand même bcp de place pour assez peu d'info. 
Et ça masque les publications qui se retrouvent en dessous du premier écran.

Quelques propositions pour épurer la page. 
Supprimer les blocs "mots clés" "Machines et matériaux" du dessous et les remplacer directement par un crayon à l'endroit ou ils apparaissent sous le titre du projet.
Les niveaux et compétences pourraient aussi revenir sous les mots clés
Si on clique sur le "crayon" ça ouvre le champ pour ajouter des mots clés ou des machines à cet endroit.

Les référents et contributeurs pourraient aussi revenir dans la partie à droite de la vignette comme sur les espaces.

Il resterait la date à afficher quelque part.

Le bloc de fichiers à télécharger pourrait être encore à droite comme c'est une liste de fichiers

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/1d9d667f-c5fe-4e8e-a6cb-a4ebd395115b)

**Comment by louis-ev** [comment]
J'ai ajouté ce bouton options pour les espaces : 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/5e4a22dc-e662-44c1-8ed9-5dd5dd987bdc)

Pour le reste, je propose de garder ouverte cette issue et d'en reparler pour la v10.1, il y a certainement des choses à creuser (peut-être une fenêtre d'édition plus pratique pour le remplissage des données "avancées" d'un projet, et présenter les données synthétiques si renseignées qqpart sur cet écran) mais pour le moment ça fonctionne et c'est lisible.

**Comment by jubonhomme** [comment]
Point d'étape, voici la comparaison entre l'ancienne version avec les métadonnées dans un volet à droite et la nouvelle avec le bandeau en dessous

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4c69c536-df9f-4247-87d0-1c3d588c34a3)

Il n'y a plus de doublon dans l'affichage des infos. 
Toutes les infos sont visibles et affichées par défaut. 

Pour la 10.1...
Il faudrait gagner un peu de hauteur pour faire remonter un peu les publications

**Comment by jubonhomme** [comment]
Les modales permettent maintenant de remplir facilement les métadonnées du projets même sur petit écran de téléphone.
L'affichage est responsive et lisible. 
Les métadonnées sont facilement identifiables

C'est adopté !

Je ferme ici aussi
