### ISSUE TITLE
Affichage Bloc Niveaux de compétence

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#874]
Pour simplifier l'affichage de ce bloc dans le projet on pourrait reprendre l'affichage de la tuile

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/77d15484-76f3-40ce-9a88-50ed4cd5940c)

 au lieu de 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/20cd4dd7-ec95-4077-abc2-e05781be8143)

**Comment by louis-ev** [comment]
Merci pour le retour, c'est effectivement très logique / pertinent…
Pas si simple car le composant avec le sélecteur a rien à voir avec les mots-clés (bien que l'affichage le suggère sur la vue Projets, pour homogénéiser l'interface).

**Comment by jubonhomme** [comment]
Oui très bien pour l'affichage des tags avec les couleurs, ça fonctionne bien et on retrouve directement le lien avec les vignettes.

Par contre c'est le seul bloc où on a encore besoin de scroller pour voir l'ensemble des infos, alors que l'affichage est en partie avec des doublons pour l'info.
Est-ce qu'il y a un moyen "simple et rapide" sans modifier le composant de n'afficher que les tags avec un crayon vert comme pour le bloc juste à côté ?
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/ee3ba553-23e0-4f4a-9d0c-007ad358e18e)

**Comment by jubonhomme** [comment]
Avec les nouvelles modales l'affichage est parfait !

![image](https://github.com/user-attachments/assets/1d1d7728-730e-40a1-a32f-9f77d7a0e703)
![image](https://github.com/user-attachments/assets/53608e20-39ac-40da-bca8-6fcb542bf488)
