### ISSUE TITLE
Visibilité épingles

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#876]
Une fois qu'on a épinglé un projet on voit assez bien l'épingle.
Par contre on ne voit pas très bien l'épingle avant de l'activer quand on a que le contour, surtout si la vignette est une image avec du détail.

Il faudrait la rendre plus visible  : couleur ? remplissage ? 

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c83fcf1c-2601-4833-98c5-a8974ae1ca09)

**Comment by louis-ev** [comment]
C'est revu en utilisant un code graphique déjà présent, fond blanc semi-transparent :
<img width="394" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/2e6ac7ae-e603-4bcd-9cd3-f192ed9df43b">
<img width="395" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/1ff897fc-6437-4e7c-b515-4fc0006648ca">

Si l'épingle est juste une indication, pas de fond blanc : 
<img width="387" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/0a4a583f-e795-4151-82d8-4ffd5e6958c0">
