### ISSUE TITLE
bouton option / partage 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#877]
Est-ce qu'on pourrait conserver la même taille de police pour le texte des menus déroulants ?
Le titre du bouton est assez grand mais les textes en dessous sont petits... pour mes yeux

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/3d166d36-4f74-4808-86f8-5896bbc0a182)

**Comment by louis-ev** [comment]
J'ai repris les menus déroulants, normalement la taille des éléments est toujours la même.
Tu peux retester ?

**Comment by jubonhomme** [comment]
Oui maintenant c'est la même taille partout... mais en petit
J'aurais préféré tout de la même taille que le titre du bouton, même si ça prend un peu plus de place ça serait plus lisible

**Comment by jubonhomme** [comment]
Exemple sur le bouton options des médias, il y a encore Télécharger un peu plus gros -> je préfère cette taille

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/214f9d40-3647-4ec0-b221-72d6c721432c)

**Comment by jubonhomme** [comment]
Par contre ici on pourrait un peu grossir le texte sous le code QR, il y a un peu de place et c'est petit pour l'instant
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/321b2751-42f8-4d88-92fe-2b2d85f38c15)

**Comment by louis-ev** [comment]
Est-ce plus lisible comme ça (notamment pour des enfants de primaire) ? 
Quitte à changer :) 

<img width="224" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/d0dd9738-d2d3-4eda-a0ad-3e52084bdbf8">

<img width="503" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/4d45df5a-8ca4-4d5b-b48c-286f5b1b9c50">

**Comment by jubonhomme** [comment]
Oui très bien comme ça... et c'est plus pour moi que pour les enfants qui ont encore de bons yeux ;)
