### ISSUE TITLE
Picto téléchargement fichier

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#884]
Je trouve que le picto actuel pour les fichiers en téléchargement dans les fichiers sources n'est pas vraiment identifiable comme étant le bouton pour déclencher le téléchargement. 
Surtout quand la ligne est assez longue on ne va pas forcément passer la souris dessus.
Dans le bloc des métadonnées c'est la ligne entière qui sert de bouton. 
J'aime bien l'idée du bouton à droite mais je pense qu'on pourrait grossir un peu le picto pour le rendre plus évident. Un peu comme celui dans le titre du bloc fichier des métadonnées c'est pas mal au niveau taille.

Ou sinon comme celui pour télécharger les projets.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/a9479720-9abf-4f7d-9ac4-47b997a5afcd)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/9d44a79f-b477-4c47-8fbc-40fea28db4c2)

**Comment by louis-ev** [comment]
Amélioration : 
<img width="336" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/ececd70e-ecbd-4bd9-a7e9-e289a1c11941">

On n'a pas de controle sur le nom des fichiers. C'est un problème non ? Il faudrait pouvoir les renommer ?

**Comment by jubonhomme** [comment]
Très bien pour ce bloc des fichiers à télécharger dans les métadonnées du projet.

Mais je voulais surtout parler du bloc dans un récit comme ici, le problème c'est que seul le petit picto au bout de la ligne déclenche un téléchargement. Tout le reste de la ligne n'active pas ça.
Est-ce qu'on pourrait avoir le même fonctionnement dans les deux blocs ? Celui des métadonnées est très bien !
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/b0bf1e21-7db1-471f-8126-6979c56c6b4e)

Et pour le renommage des fichiers... oui dans l'idéal ce serait pratique de les renommer.
Par exemple pour les fichiers issues de la capture dans dodoc avec des noms assez long et peu identifiables : image-1710025019111-za2.jpeg

**Comment by louis-ev** [comment]
Ha je comprends ! à tester.
Le renommage, on garde pour 10.1, il faudrait creuser le sujet (créer un champ titre dans la modale d'un média ? ou c'est spécifique à la publi ?)

**Comment by jubonhomme** [comment]
Top !
Je ferme ici et on ouvrira un nouveau sujet sur les noms de fichiers / titres
