### ISSUE TITLE
Liste médias dans publication page à page

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#887]
Retour aujourd'hui d'un collègue suite à une animation avec des élèves qui utilisaient une publication page à page en synchrone.
En ajoutant les médias dans la publication, les médias se superposent tous au même niveau en haut à gauche de la page. Les premiers médias ajoutés sont alors masqués sous les suivants et disparaissent de la vue, les élèves ne retrouvaient plus les médias ajoutés en premier. 

Peut-être qu'en rendant un peu plus visible la liste des médias ça permettrait de déplier la liste et de voir les médias et simplement de les sélectionner en cliquant dans cette liste.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/8245f05c-d966-4cf4-a6ee-13bc9b1db3df)

Proposition : 
Mettre en couleur le nombre de médias pour le rendre plus visible un peu comme dans le bloc des métadonnées. 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/6ff23e8c-ce32-4ad3-9b2d-afedde482872)
Et pour simplifier le dépliage repliage et uniformiser le fonctionnement, est-ce qu'on pourrait reprendre ce qui existe dans le volet de "collecter" 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4f056f63-7c0b-44d3-8f40-226b84f6ed46)

ça donnerait quelque chose comme ça

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/dc10b163-93f7-4b42-bb1e-1d70f1a1648d)

**Comment by louis-ev** [comment]
Bonne idée !

<img width="313" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/90457ff8-704b-42de-9327-df60b6dcd0c1">

Je laisse ouvert et je met pour la 10.1 pour reprendre ce panneau, pas très bien structure.

<img width="315" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/011524f4-4d5c-4fce-bb38-77629ebda6d2">

**Comment by jubonhomme** [comment]
C'est déjà plus visible ;)

Par contre je vois que les formes sont comptabilisées mais n'apparaissent pas dans la liste

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/446e884d-fda1-4a4b-86fe-dfcb377d9ef0)

**Comment by jubonhomme** [comment]
C'est bon, tout y est !
![image](https://github.com/user-attachments/assets/efadd805-133b-4b81-a99c-649f4bc46963)
