### ISSUE TITLE
Carte en plein écran - bouton zoom et recherche

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#890]
Si on passe une publication cartographie en plein écran les boutons de zoom et de recherche ne sont plus visibles.

Est-ce que c'est voulu ?
Je trouverais plus logique de les conserver même dans ce mode
![Capture d’écran de 2024-02-27 20-52-18](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/58429b0e-3bb7-4868-b675-40a305d5c0dc)

**Comment by louis-ev** [comment]
Non, c'est pas voulu…
En fait j'arrivais pas à avoir la souplesse que je voulais pour créer la barre de bouton, donc c'est pas openlayers qui gère ces boutons mais vue.js
Donc quand on passe en plein écran openlayers, ils n'y sont pas.
Je vais voir si on peut adapter le comportement du plein écran.

**Comment by louis-ev** [comment]
Corrigé ! J'adore OpenLayers

**Comment by jubonhomme** [comment]
j'imagine que c'est pas aussi simple que de mettre vue.js au dessus et openlayers en dessous ;)
