### ISSUE TITLE
Affichage médias sons dans une cartographie

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#891]
Les boutons "informations" et "fermer" sont bien identifiables et fonctionnent bien pour des médias images ou vidéos.
Par contre pour les médias sons les boutons se retrouvent un peu tous les uns sur les autres.
Est-ce que pour les sons il ne faudrait pas ajouter une ligne au dessus et en dessous du player pour ne pas avoir de chevauchement ?
Ou bien allonger un peu le bandeau du player son pour avoir la place des différents boutons, comme pour les vidéos, le bouton "informations" par exemple se situe après le volume et n'est pas au dessus

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/a8ccada8-3b6b-4f5c-9dd1-9e20c8a2a740)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/418347c5-ac40-4538-94c1-dc3e0cfac7e7)

**Comment by louis-ev** [comment]
Je tente de bouger un peu tout pour trouver de la place et éviter les superpositions indésirables : 
<img width="340" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/d23f032d-5abf-487f-89fa-0aad5fea97c8">

<img width="407" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/0c16a486-b803-492e-85a3-a45e0e0a2349">

On a malgré tout la superposition "règlage du volume" et "bouton info/crédits", à résoudre (même si c'est pas trop trop grave pour le moment je trouve)

**Comment by jubonhomme** [comment]
Ce n'est pas possible de mettre le player dans une box un peu plus grande ?

**Comment by louis-ev** [comment]
Je tente un petit padding à droite : 

<img width="446" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/38206bea-0576-4cb4-9f26-4403727bcb60">
<img width="497" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/28642519-784d-4877-b1a2-ba7a522d6802">

Et sur la carte : 
<img width="354" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/8e779906-8787-4262-b667-62c03054e75e">
