### ISSUE TITLE
Exporter en image une publication page à page

### ISSUE THREAD

**Issue by JeFabrique-MaterielPeda** [l-atelier-des-chercheurs/dodoc#899]
Tps: peux servir à ajouter une forme sur les visages des photos/flouter des visages et exporter dans un récit

**Comment by louis-ev** [comment]
À tester !

<img width="763" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/
c2cc7863-25f7-4c83-ae24-1bf17d40366a">

<img width="873" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/d103001f-ae4c-46dc-9776-8ae5720a8b47">

<img width="829" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/ce10e446-a770-434b-b90c-c7d9d838395a">

<img width="797" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/b6b62287-f67b-4475-9734-aea7c62f7b8f">

**Comment by jubonhomme** [comment]
Ça fonctionne bien pour l'export en image.

Mais tant qu'on y est... j'en profite pour demander deux autres petites modifications : 
- est-ce qu'on pourrait avoir la vignette AVANT de faire l'export pour visualiser la page que l'on exporte.
La vignette de la vue dans l'ensemble des pages de la publication irait très bien ;)

- est-ce qu'on pourrait proposer par défaut la page sur laquelle on est comme page à exporter et pas la page 1 ?

Donc si je suis sur la page 3 de ma publication et que je clique sur Partager / Exporter et que je sélectionne image, ça affiche par défaut la vignette de la page 3 et ça propose page 3 à exporter, je peux choisir une autre page si je veux et la vignette s'actualise en présentant la vignette de la page, je clique sur créer et la suite est identique à la version actuelle

**Comment by louis-ev** [comment]
> est-ce qu'on pourrait proposer par défaut la page sur laquelle on est comme page à exporter et pas la page 1 ?

Bonne idée, c'est en place !

> est-ce qu'on pourrait avoir la vignette AVANT de faire l'export pour visualiser la page que l'on exporte.
La vignette de la vue dans l'ensemble des pages de la publication irait très bien ;)

Pas simple du tout, ça complexifierait beaucoup le code (au delà du travail que ça me demande) donc dans l'immédiat non…
