### ISSUE TITLE
RECIT /AMÉLIORATION/ Meilleure gestion des interligne entre les +. 

### ISSUE THREAD

**Issue by JeFabrique-MaterielPeda** [l-atelier-des-chercheurs/dodoc#902]
Espace entre éléments trop important et pas gérable pour l’instant.

**Comment by louis-ev** [comment]
à retester 

<img width="563" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/411c6b75-8c12-42ce-88f8-e3caadf3a992">
![Uploading image.png…]()

**Comment by jubonhomme** [comment]
A fermer ?
