### ISSUE TITLE
En-tête markdown> remplacer par un mini editeur V10.1

### ISSUE THREAD

**Issue by JeFabrique-MaterielPeda** [l-atelier-des-chercheurs/dodoc#908]

**Comment by louis-ev** [comment]
Remplacement de l'éditeur "markdown" basique/pas simple à prendre en main par un éditeur quill simplifié, non collaboratif : en cours, à tester sur les descriptions d'espace.

**Comment by louis-ev** [comment]
C'est en place partout. Vous pouvez tester ?

**Comment by jubonhomme** [comment]
ça marche très bien de mon côté

On pourrait peut-être l'ouvrir dans une modale pour la saisie, par exemple dans la description d'un projet c'est pas très grand quand on a le clavier numérique sur un téléphone. 
Idem quand on choisit "autre licence" dans la modale de licence du projet (là on la place) ça referme la modale et ça ouvre l'éditeur de texte dans le bloc licence. Avec une modale qui s'ouvre pour saisir la nouvelle licence on aurait plus de place

**Comment by jubonhomme** [comment]
Je remonte cette issue, si jamais ça passe comme ça on peut fermer

**Comment by jubonhomme** [comment]
Il y a une modale pour la description du projet qui fonctionne mieux que le simple champ.
Par contre la description de l'espace n'a pas de modale.
On pourrait l'ajouter aussi pour ce champ ?

**Comment by louis-ev** [comment]
Oui, c'était pour tester d'abord là :)
Dès que c'est validé, je déploie partout ou y a ce petit éditeur (aussi dans les options méta).

@jubonhomme tu pourrais tester des cas de figure un peu particuliers, genre j'édite le contenu du champ, mais je ferme la modale sans enregistrer – ça devrait ouvrir une modale de confirmation de non-enregistrement comme sur la v9. Merci !

**Comment by jubonhomme** [comment]
Testé et approuvé ;)

**Comment by louis-ev** [comment]
J'ai remplacé partout ou ça me semblait nécessaire, à voir si on remplace aussi pour les champs crédits/légendes aussi, c'est possible et facile.
