### ISSUE TITLE
Picto fermeture du filtre En cours / finalisé / Privé

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#913]
Quand on filtre avec le bouton en cours / finalisé / Privé il n'y a pas de picto pour fermer ce filtre comme pour les autres tags.
ça fonctionne quand même mais c'est moins évident que pour les autres
Je trouverais ça plus logique de le mettre aussi sur ce bouton quand le filtre est actif.

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/e1ed0ef6-7ef8-4520-a580-8a7c7de8065e)

**Comment by jubonhomme** [comment]
J'ouvre ici à nouveau.
Il y a bien le picto pour fermer par contre j'ai un problème de couleur.
Le bouton "en cours" fonctionne bien

Par contre pour les deux autres dès qu'on passe au survol pour sélectionner ou l'enlever des filtres les boutons sont presque tout blanc et donc très peu lisibles

**Comment by louis-ev** [comment]
Merci :) Les détails sont importants !
En place : 

<img width="716" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/b5e27584-818a-465d-86c8-b2ffb798c1ec">

<img width="529" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/2442d642-3a0c-4345-8a6c-54f63beaa9dd">
