### ISSUE TITLE
[UX] Verrou superposé  bloque le début du texte dans page à page

### ISSUE THREAD

**Issue by JeFabrique-MaterielPeda** [l-atelier-des-chercheurs/dodoc#926]
![sélection texte page à page dodoc](https://github.com/l-atelier-des-chercheurs/dodoc/assets/152091642/5f4c9e19-8504-4f46-9d27-e0436696ea46)

Cette après-midi, en voulant copier le roadmap page page d'Erwan dans récit, j'ai crisé quand je n'arrivais qu'à la 3e tentative de changer le numéro d'entête de mon titre: le verrou empêche d'éditer rapidement le texte: il faudrait le mettre à droite au bout de la ligne, non?

**Comment by jubonhomme** [comment]
Normalement il est en bas maintenant ;)
Depuis aujourd'hui il me semble
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/6dbef19b-9fe6-41c8-b015-ab766dc071ba)
