### ISSUE TITLE
remplacer/prévenir pour les éléments qui nécessitent le web

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#928]
Certains pictos sont chargés depuis le web : 
`<sl-icon`
Les tabs admin aussi
`<sl-tab`

Mettre un message pour OSM / carto

**Comment by louis-ev** [comment]
Ne reste que OSM. On fait quoi ?

**Comment by jubonhomme** [comment]
Pour l"instant on peut juste mettre un message sur la carte si pas de fond disponible car hors connexion. 

Et si on peut pour la suite charger une tuile ou deux dans le projet pour les avoir hors connexion... mais cas assez rare à mon avis car une tablette en extérieure est forcément sur un wifi pour dodoc

**Comment by louis-ev** [comment]
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/c625aa75-373e-4713-bb75-d49e52f44511)

> Failed loading the baselayer, are you connected to the internet?
(en anglais)

Ça balance un message pour chaque tuile, donc ça en envoit un bon paquet. On fera mieux en 10.1, je crois que ça fait le taf là :)

**Comment by louis-ev** [comment]
(si besoin les trad sont dans les fichiers de langue habituels, n'hésite(z) pas à proposer mieux)
