### ISSUE TITLE
bouton ? 

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#933]
Remettre un bouton « ? » dans la barre en haut qui ouvre une modale avec un petit texte/credits, et un lien vers le forum pour orienter si bugs/retours/envie de contribuer.

**Comment by louis-ev** [comment]
Comment gérer les crédits ? indiquer les noms des contributeurs réguliers/principaux ? @jubonhomme @JeFabrique-MaterielPeda etc. ?

**Comment by louis-ev** [comment]
En cours : 

<img width="262" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/4d4e5e74-9eb0-4419-833c-1424983adccd">

ouvre 

<img width="555" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/f5c3a524-d661-450c-8893-cf6dc89953af">

<img width="579" alt="image" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/55fb07e9-5399-48d0-88ef-c46209edccd5">

Si vous souhaitez être ajoutés à la liste en bas, indiquez le ici ou en m'envoyant un mail : info@latelier-des-chercheurs.fr

**Comment by louis-ev** [comment]
Est-ce que cette fenêtre fonctionne bien ? Vous validez ? Je ferme ?

**Comment by jubonhomme** [comment]
C'est bon pour moi
