### ISSUE TITLE
Bug : Déplacement d'un espace à l'autre

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#934]
J'ai essayé de déplacer ce projet d'un espace à un autre mais ça ne fonctionne pas.
https://test10.dodoc.fr/+espace/test-horloge
J'ai bien les droits dans l'autre espace.
Je voulais le déplacer ici :
https://test10.dodoc.fr/+do-doc-10-espace-de-demo-et-test

J'arrive à le dupliquer dans le même espace mais pas à le déplacer.
Une idée ?

**Comment by jubonhomme** [comment]
J'ai le même problème pour déplacer une publication

**Comment by louis-ev** [comment]
Pas de message d'erreur ? Ça n'affiche rien ?
J'ai réussi à le faire…

**Comment by louis-ev** [comment]
Tu l'as fais depuis ton compte admin ?

**Comment by jubonhomme** [comment]
Oui depuis un compte admin...

**Comment by jubonhomme** [comment]
J'ai pas réussi à reproduire... ça marche maintenant ;)
je ferme donc ici
