### ISSUE TITLE
Bug Montage vidéo linux electron

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#942]
Quand je fais un montage avec la session local electron linux le compteur s'affole
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/919f445d-362a-4158-a14e-48aaf1ad695f)

Le montage est bien créer mais le compteur continu de tourner en boucle

**Comment by jubonhomme** [comment]
Une deuxième remarque sur l'export, la vidéo finale est exportée dans "collecter"  même si on ne clique pas sur le bouton "enregistrer dans le projet"

**Comment by louis-ev** [comment]
Pour le compteur, c'est lié aux données qu'envoi ffmpeg à la compilation – parfois des valeurs qui n'ont aucun sens. J'ai ajouté de quoi filtrer.

> Une deuxième remarque sur l'export, la vidéo finale est exportée dans "collecter" même si on ne clique pas sur le bouton "enregistrer dans le projet"

C'est voulu ! Une fois la tâche démarrée (certaines recettes de fabrication, la création de PDF ou images à partir de page à page et récit, la création d'un stopmotion, la conversion d'une image/vidéo), le résultat sera automatiquement ajouté à la bibliothèque du projet même si l'utilisateur qui l'a lancé s'est déconnecté. Ça me semblait indispensable pour permettre des tâches au long cours sans prendre le risque que le résultat parte à la poubelle à cause d'une connexion instable (par exemple).

Idéallement, la personne qui lance la tâche devrait avoir accès à un petit tableau de bord pour suivre l'avancement, l'arrêter en cours de route, ou consulter le résultat à la fin. Je pense qu'on pourrait ajouter une contrainte aux non-admins : une seule tâche peut être lancée à la fois. J'ai déjà entamé ce chantier mais pas terminé, ça sera pour la v10.1 je pense
