### ISSUE TITLE
Bug bouton import collecter

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#945]
Le bouton import fonctionne bien au clic

Par contre le glisser / déposer sur le bouton ne marche plus trop. Avant ça fonctionnait à chaque fois mais maintenant c'est soit inactif, soit ça ouvre un message d'erreur soit ça marche quelques rares fois.
Voir ici une capture vidéo
https://test10.dodoc.fr/+espace/crash-test?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100%7D%5D

**Comment by jubonhomme** [comment]
Je viens de vérifier en passant par le navigateur sur la version en local.
Dans le navigateur aucun problème.

ça viendrait donc de electron ?

**Comment by louis-ev** [comment]
Je vois ce que tu veux dire.
Soucis maj electron, sur et certain.
Chez moi le drag/drop fonctionne plutôt bien.
Argh c'est le pire, ça marche qqpart et pas ailleurs…
Je sais pas quoi te dire, j'ai pas de piste et il faut qu'on sorte la v10. Ça passera peut-être en 10.1 sinon ça sortira jamais

**Comment by jubonhomme** [comment]
SI ça marche sur MacOS et Win ? c'est déjà ça.
C'est pas indispensable non plus d'avoir le glisser déposer si le bouton fonctionne. 
Pour charger les images de tablettes ou téléphones (cas le plus fréquent que j'utilise) on passe toujours par le bouton et une version web. 
Donc oui on peut laisser comme ça et ça attendra la V10.1

**Comment by louis-ev** [comment]
Il me semble avoir réparé ça avant la sortie de la v10. Tu peux confirmer @jubonhomme ? Merci !
