### ISSUE TITLE
Suppression médias collecter

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#946]
Quand on sélectionne plusieurs médias (sélectionner tout par exemple) et qu'on supprime, l'affichage clignote.

On dirait que dodoc ouvre chaque média avant de le supprimer.
Est-ce que ça n'irait pas plus vite de supprimer sans ouvrir chaque média ?

**Comment by louis-ev** [comment]
Effectivement, un bug corrigé de plus :)
