### ISSUE TITLE
Permettre modif de l'aspect des titres de chapitre (récit)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/dodoc#949]
<img width="782" alt="Capture d’écran 2024-04-11 à 10 15 34" src="https://github.com/l-atelier-des-chercheurs/dodoc/assets/7995654/10f7e0f2-9dfc-4cc2-a369-65179e5015cf">

(ici on est obligé d'avoir les deux, car les étudiants veulent garder le fil d'ariane en haut mais veulent un autre aspect visuel)

**Comment by louis-ev** [comment]
Hmm ok. Est-ce qu'on donne la possibilité de masquer le titre grand, ou de pouvoir choisir sa typo ? 
Un truc comme ça ?
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/07a9e678-3069-4e0b-8afd-2c828b985165)

**Comment by louis-ev** [comment]
Quelles option(s) ? J'ai un doute sur bold/ital/lien

**Comment by JeFabrique-MaterielPeda** [comment]
Bonne idée la possibilité de choisir la Typo et Bold /Ital. Le lien par contre, pour uin titre, je n'en vois pas l'utilité...

**Comment by paulinegourlet** [comment]
La contrainte sur la taille est pas géniale. 
Pour moi : 
- option 1 : on laisse toutes les options d'édition de texte (comme n'importe quel autre texte)
- option 2 (si la 1 ne convient pas) : on permet de cacher le titre du chapitre (qui est contraint dans son apparence) -> le seul point positif de cette option est que tu peux nommer différemment ton fil d'ariane et ton chapitre (ça peut être bien quand tu as un long titre ou que tu veux jouer sur un fil d'ariane custom)

**Comment by louis-ev** [comment]
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/10d69c8f-4ae9-471d-bf8f-6afb3b45459a)

**Comment by jubonhomme** [comment]
voir #827 
Doublon ?
