### ISSUE TITLE
Doubler une vidéo en live

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#950]
Revoir l'interface pour permettre l'enregistrement "en direct" d'une piste sonore pour une vidéo.
Exemple : j'ai fais un stopmotion, je veux faire la voix off. Dans fabriquer je choisis la vidéo, puis je click sur "enregistrer", ça lance la lecture de la vidéo (sans le son) tout en enregistrant le niveau sonore.

@olerun

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/8a064c83-1038-4d71-a3c2-b165ca73e031)

**Comment by louis-ev** [comment]
On pourrait séquencer mieux la création de cette recette : 

1. choisissez la vidéo à utiliser (on part du principe qu'elle a déjà été réalisée, soit dans Capter soit importée dans Collecter)

2. une fois la vidéo ajoutée, elle se positionne au milieu en haut de page

3. on affiche deux boutons en dessous : **Importer un son pour doubler la vidéo** / **Enregistrer le doublage en direct**
(aide pour nommage de boutons !)

Puis le bouton créer

**Comment by JeFabrique-MaterielPeda** [comment]
Bonne idée! Si on peut s'assurer que la vidéo créer est enregistrée en temporaire quelque part, ou sous forme de script enregistré, pour ne pas risquer de la perdre en cas de crash, bref pour ne pas avoir à refaire les deux manips si déconnexion ou autre...
Pour 10.1 ou tu veux le faire avant le release?

**Comment by jubonhomme** [comment]
Au détour d'un fil de discussion je viens de découvrir cette application qui tourne dans un navigateur en local.
C'est basique et très simple comme dodoc.
On sélectionne une vidéo que l'on peut visionner.
Un bouton en haut permet de lancer l'enregistrement sonore.
Si on clique dessus ça relance la vidéo au début et lance l'enregistrement du son.
Voir ici
https://pragmatice.net/pragmaprodu/pragmadoublage/app/index.php?prof#production

Pour tester il suffit de décompresser l'archive ici 
https://pragmatice.net/pragmaprodu/pragmadoublage/pragmamp3-video_archive.zip

![image](https://github.com/user-attachments/assets/2517d6b6-541a-4e64-b422-66c90ff819ee)

**Comment by louis-ev** [comment]
Mais oui et ça marche super bien ! Très simple, efficace :)

**Comment by jubonhomme** [comment]
On peut aussi tester en ligne ici
https://pragmatice.net/pragmaprodu/pragmadoublage/app/index.php

**Comment by jubonhomme** [comment]
Tu penses qu'on pourrait l'avoir pour cette version 11 ou c'est plus complexe / long à ajouter ?

**Comment by jubonhomme** [comment]
Pour une V2 : 
- Je préfèrerais que la capture du son se coupe automatiquement à la fin de la lecture de la vidéo. Sinon on obtient une vidéo avec un son blanc à la fin si on coupe avant ou une image fixe sur la vidéo si on coupe après. Pas trop gênant si c'est juste une vidéo mais si on veut ensuite faire un montage vidéo + vidéo à partir de séquences doublées on va avoir des problèmes dans les transitions.

- la fenêtre de capture du son pourrait être moins haute. Ce n'est pas important sur un écran large mais si on le fait sur un écran vertical de téléphone avec les deux blocs en vertical on ne peut pas voir la vidéo ET lancer l'enregistrement (sauf si on utilise le retardateur)

![image](https://github.com/user-attachments/assets/68f14900-ae36-4730-8071-cf90696c04c2)

**Comment by louis-ev** [comment]
En place, et optionnel : 
<img width="959" alt="image" src="https://github.com/user-attachments/assets/43c5d3df-1e73-474e-ac38-1f94152dc2ab" />

**Comment by jubonhomme** [comment]
Il reste juste un petit souci d'affichage du compte à rebours dans la fenêtre du son, j'imagine que ce n'est pas possible de déporter l'affichage du compte à rebours dans la fenêtre de la vidéo ?

![image](https://github.com/user-attachments/assets/2dd36c73-fbea-4575-8662-5b8d5621aed7)

**Comment by jubonhomme** [comment]
Tout y est !
Merci pour cette super nouveauté qui va bien faciliter la création de vidéo en stop motion
