### ISSUE TITLE
Liste de suggestions

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#951]
Si j'ajoute un mot clé déjà présent dans la liste j'ai bien un message en rouge qui m'indique que ce mot est déjà dans la liste mais je peux l'ajouter quand même.
Est-ce qu'il est possible de refuser son ajout s'il est déjà présent ?

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/436a802f-1b85-4250-bdd3-40fcffcffb92)

**Comment by louis-ev** [comment]
Ha oui tiens ! 
J'ai trouvé un autre bug : on peut ajouter un mot-clé vide :)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/d09453fa-9822-4332-b634-51ac40c87b48)

**Comment by louis-ev** [comment]
Corrigé.
Que fait-on pour les mots-clés avec capitales/minuscules ? 

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/85424ca7-ff6e-4cda-b54a-20154a44aded)

**Comment by jubonhomme** [comment]
Je garderais les deux possibles mais si je tape "Pl" j'ai la suggestion des deux : Ploup et ploup
Donc les deux mots clés sont distincts mais la suggestion ne tient pas compte de la casse
Qu'en penses-tu ?

**Comment by louis-ev** [comment]
C'est le comportement actuel non ? ça me va :)
