### ISSUE TITLE
taille média page à page à l'import

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#956]
Soucis dimensionnement à l'arrivée

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/8c1d5098-7f9e-4757-aaca-5d1ef9bfef3a)

**Comment by louis-ev** [comment]
Soucis pre / post additional meta dans module creator

      if (this.pre_addtl_meta)
        Object.assign(additional_meta, this.pre_addtl_meta);
      if (addtl_meta) Object.assign(additional_meta, addtl_meta);
      if (this.post_addtl_meta)
        Object.assign(additional_meta, this.post_addtl_meta);

Délicat à résoudre. Ça dépend du niveau de zoom.

**Comment by louis-ev** [comment]
Résolu sur next et donc sur https://test11.dodoc.fr/
@jubonhomme tu pourras tester quand/si tu as le temps stp ? Merci !

**Comment by jubonhomme** [comment]
Je viens de mettre à jour la V11 et ça marche bien de mon côté aussi.
