### ISSUE TITLE
(bug- dodoc windows 10.0.9) Erreur importer projet 

### ISSUE THREAD

**Issue by JeFabrique-MaterielPeda** [l-atelier-des-chercheurs/dodoc#957]
Bravo pour le release! Champagne !

Toute excitée, j'ai installé sur mon PC, et j'ai voulu  créer mon instance locale et tester l'import de projets en ligne (fabriquedu et dodoctest). Voici le message:
![Importer projet fail](https://github.com/l-atelier-des-chercheurs/dodoc/assets/152091642/616607a5-8d94-4c03-865e-f0bb2d7eafc8)
Pourtant ça marchait sur Raspberry en 10.0.7 ! Est-ce une spécificité Windows ?

J'ai essayé plusieurs projets, plusieurs tailles, provenant de différentes versions dodoc en ligne y compris la dernière sur test dodoc, rien n'y fait !

**Comment by jubonhomme** [comment]
Je viens de mettre à jour ma version linux en local avec electron et ça marche bien pour importer un projet.
Est-ce que l'installation s'est bien faite en créant un nouveau dossier dodoc ?

**Comment by louis-ev** [comment]
Hmm est-ce que tu essayes d'importer vers un Windows des projets créés sur des Linux ? Il est bien possible que le soucis provienne des retours chariots dans les fichiers meta…

**Comment by louis-ev** [comment]
@JeFabrique-MaterielPeda tu pourrais mettre ici un ZIP qui pose problème et qui n'est pas trop lourd ?

**Comment by JeFabrique-MaterielPeda** [comment]
> Hmm est-ce que tu essayes d'importer vers un Windows des projets créés sur des Linux ? Il est bien possible que le soucis provienne des retours chariots dans les fichiers meta…

J'essaye de mettre des projets de la plateforme en ligne fabriquedu et de celle de test 10. Quelque soit le projet, no luck, même message. Ça fonctionnait avant c'est sur (on l'a testé après FabLab dehors)

**Comment by JeFabrique-MaterielPeda** [comment]
> @JeFabrique-MaterielPeda tu pourrais mettre ici un ZIP qui pose problème et qui n'est pas trop lourd ?

[le-chuchoteur.zip](https://github.com/l-atelier-des-chercheurs/dodoc/files/14978922/le-chuchoteur.zip)

**Comment by jubonhomme** [comment]
J'arrive à importer ton projet sur mon dodoc local linux

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/8801cac5-4b08-4faf-a488-f207ca2aa892)

**Comment by JeFabrique-MaterielPeda** [comment]
Donc c'est avec la V Windows le pb

**Comment by jubonhomme** [comment]
C'est pas encore une histoire de \\ dans l'arborescence ?

**Comment by louis-ev** [comment]
Ok, donc ce que j'en comprends, c'est que l'import Windows ne marche jamais !

**Comment by jubonhomme** [comment]
j'ai l'impression oui, sur un serveur ou sur linux l'import marche bien mais je n'ai pas de win pour tester

**Comment by louis-ev** [comment]
> C'est pas encore une histoire de \ dans l'arborescence ?

Probablement oui.

Je pense ici : 
```
      const directory = await unzipper.Open.file(path_to_temp_file);

      // two cases : either all medias are at root ('meta.txt' and so on)
      // or they are in a subfolder
      let subfolder_name = false;
      let meta_file = directory.files.find((f) => f.path === "meta.txt");

      if (!meta_file) {
        meta_file = directory.files.find((f) => {
          const path_splits = f.path.split(path.sep);
          if (path_splits.length === 2 && path_splits[1] === "meta.txt") {
            subfolder_name = path_splits[0];
            return true;
          }
          return false;
        });
      }
```

Il n'arrive pas à localiser de fichier meta.txt de référence, probablement lié au chemin oui.
Mais je n'ai pas accès à un Windows avant jeudi ou vendredi pour creuser, donc ça devra attendre (sauf si quelqu'un veut se lancer, ça se passe dans le fichier `core2/folder.js`, ligne 171 :)

**Comment by louis-ev** [comment]
Résolu sur la branche `main`, à tester !

**Comment by jubonhomme** [comment]
Je regarde demain sur un ordi windows !

**Comment by jubonhomme** [comment]
Je n'ai pas réussi à remettre à jour la version installée sur windows depuis git.
Est-ce que tu aurais une version à jour pour win à télécharger que je teste sur un poste en local ?

**Comment by louis-ev** [comment]
Euh attends c'est un gros soucis ça... tu n'arrives pas à basculer sur main ? Tu peux me dire où ça coince ? 
J'ai pas de .exe sous la main je peux en builder un mais autant résoudre ton soucis non ?

**Comment by louis-ev** [comment]
Julien a testé, ça a l'air tout bon chez lui aussi. Je ferme donc.
