### ISSUE TITLE
Cartographie HS

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#958]
La cartographie est HS depuis ce soir avec la dernière mise à jour en local sous linux
J'ai un écran vide sur la page côté carte, les fonds de carte et les surcouches ne s'affichent plus.
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/0d7d09d2-c26d-44b2-8be5-1dda1b5681c2)

**Comment by louis-ev** [comment]
Merci pour l'info, j'ai introduis un bug hier. Résolu.
