### ISSUE TITLE
Export du récit d'une publication cartographique en pdf

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#971]
Pour le moment il est possible d'exporter la partie carte d'une publication cartographique en format png.

J'aurais besoin dans certains cas de pouvoir exporter la partie récit en pdf de cette recette cartographique.
Si on utilise les mêmes paramètres que pour une recette récit classique ça m'ira très bien.

**Comment by louis-ev** [comment]
On pourrait imaginer que la carte prenne la première page d'un chapitre, et que le récit se déploie ensuite sur les pages suivantes par exemple ?

Ça ferait : 

- Chapitre 1 (ou son titre)
- Sa carte avec les points numérotés en pleine page
- Le récit avec les numéros qui correspondent, sur plusieurs pages

- Chapitre 2
- Sa carte
- Le récit

etc.

?

**Comment by louis-ev** [comment]
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/bd64f39e-1f0a-4c79-8533-06092c5377e0)

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/1948417/2af16a3f-e9b8-4bc3-9860-7cc86e411990)

En cours, à tester sur next

**Comment by louis-ev** [comment]
Ha ? export qui n'a pas laissé le temps au fond de carte de se charger ?
En créant une nouvelle carto, ça refait le soucis ? C'est systématique ?

Le niveau de zoom est calculé pour afficher l'ensemble des points en même temps. SI y a qu'un point, zoom par défaut.

**Comment by jubonhomme** [comment]
Après une nouvelle série de tests tout fonctionne parfaitement.

Je ferme ici et on ouvrira une autre issue si on rencontre un problème
