### ISSUE TITLE
gestion des versions dans un bloc texte > éviter l'accumulation des archives

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#976]
Actuellement, quand le bloc s'auto enregistre (quand un utilisateur n'a pas appuyé sur une touche depuis au moins 2 secondes) ou est enregistré, une copie de la version précédente est conservée dans un sous-dossier _archive dans la publication correspondante. On peut ensuite restaurer cette version grâce à l'interface dédiée.

Il n'y a pas de mécanisme pour faire le tri et éviter que des milliers de versions soient constitués. C'est pas très grave (ça pèse très peu) mais c'est embêtant quand on manipule les fichiers/dossiers, par exemple au moment d'un transfert d'un serveur à un autre (en FTP). Chaque fichier ajoute du temps, et le transfert est bcp plus long qu'il ne devrait.

L'idéal serait de trouver une logique pratique pour archiver/supprimer. Il pourrait y avoir un bouton "supprimer les anciennes versions", mais il faut penser à aller appuyer dessus pour chaque bloc texte – pas idéal.

Des propositions : 

- on garde que les X dernières versions. Très simple à développer, mais pas génial. Par exemple, si on garde les 10 dernières, au bout d'une ou deux minutes on aura plus accès à la version de la veille, potentiellement. Si on garde les 100 dernières, on résouts pas vraiment le soucis…

- on ne garde qu'une version par jour, celle réalisée le plus tard ce jour là (ou une logique un peu plus complexe dans le genre). Cela nécessite de lire toutes les versions régulièrement (quand ?) pour faire ce nettoyage. À voir si c'est logique, cela signifie que les versions visibles un jour ne le seront plus le lendemain potentiellement.

- on arrête de stocker les versions dans le dossier des contenus /Documents/dodoc, et on conserve cette information plutôt dans un cache spécifique à cette instance, dans l'appli. Tant qu'on utilise le même dodoc (version appli ou version serveur) on aura accès à toutes les versions, mais si on télécharge un projet pour l'importer ailleurs ou si on en créer une copie, les versions ne viennent pas avec, juste le bloc texte à un instant T.

Qu'en pensez-vous ?

**Comment by catmdb** [comment]
La 3e option sans hésiter

**Comment by louis-ev** [comment]
Je pense juste à une limite : lorsqu’on supprime un projet ou un espace et qu'il est du coup déplacé vers un sous-dossier `_bin` (si on a pas activé le réglage *Supprimer définitivement les contenus*), alors ça supprimera les archives. Si on imagine un processus pour permettre à un admin de le restaurer après coup, cette approche `/Documents/dodoc/archives` signifie qu'on ne récupérera pas les archives.

Est-ce un soucis ?

**Comment by jubonhomme** [comment]
Si déjà on peut restaurer la dernière version du projet ou espace à partir de _bin je trouve ça très bien. 

On aurait deux niveaux : 
- pour un projet existant on a accès aux archives pour retrouver d'anciennes versions
- pour un projet supprimer on peut restaurer la dernière version

je trouve ça très bien, tout en gardant les avantages que tu évoques plus haut avec un dossier spécifique archive qui n'est pas un sous dossier dans chaque projet.

**Comment by louis-ev** [comment]
Yes.
Effectivement il y a un chantier "restaurer" à mettre en place.
La modification des archives est en place sur next.
À noter : on perds l'accès aux archives existantes – on ne peut plus remonter aux versions précédentes. Je n'ai pas mis en place un système de récupération des archives.

**Comment by louis-ev** [comment]
Tout ça est en place.

**Comment by Spiderwan01** [comment]
En en effet , je trouve interressant cette dernière approche : 
Si déjà on peut restaurer la dernière version du projet ou espace à partir de _bin je trouve ça très bien.

On aurait deux niveaux :

    pour un projet existant on a accès aux archives pour retrouver d'anciennes versions
    pour un projet supprimer on peut restaurer la dernière version

Mais il est vrai qu'il y a besoi nd'un outil d'aide à la gestion des versions antérieures.

Je uis en plein dedans là donc plus facile de me rendre compte 👍 
un élève a détruit un chapitre sur une publi en mode récit.
J'ai super besoin de la retrouver.

Je me retrouve donc dans les archives via une balade sur le serveur, dans lesquels il faut naviguer pour retrouver l'archive de la bonne publication sachant que le nom du répertoire semble resté celui donné à la création de la publi mais que depuis le publi a pu changer plusieurs fois de nom pour par exemple améliorer sa gestion dans celle des mulplication d'un même projet.

ensuite plusieurs textes ( j'ai compris correspondant à des blocs texte initialement présents dans la publi) et donc à l'interieur de chaque dossier, des versions, dans le premier que j'ouvre  338 !
je sens que ça va être long :)

je considère que comme elle sont dans l'ordre chronologique, je remonte les versions par la plus récente pour trouver la bonne.

Bon là petit panique, en me demadnant comment j'avais retrouver les données texte rapidement ... 
![image](https://github.com/user-attachments/assets/d2ef1e44-ab3a-46b4-a704-424877b6da8e)

et là j'avoue que j'ai du mal à capter comment je peux le réinjecter dans lerépertorie de la publication en cours , sans son ficheir meta associé, sachant que je voie que dans document/dodoc/spaces/... publication     il y a aussi des répertoires d'archives.

oui un outil d'aide à la gestion des archives et la manière de les réintroduire sera utile.. :)

**Comment by Spiderwan01** [comment]
Là je m'en suis sortie de façon peu conventionnelle j'imagine car peu expérimenté, en réinjectant mes fichiers texte récupérés dans un éditeur html et en copiant collant le texte acompagné  de la mise en forme ....

**Comment by louis-ev** [comment]
> Là je m'en suis sortie de façon peu conventionnelle j'imagine car peu expérimenté, en réinjectant mes fichiers texte récupérés dans un éditeur html et en copiant collant le texte acompagné de la mise en forme ....

Très bonne technique mais effectivement, il y a plus simple !

Par exemple, pour une version appli : 

1. tu recréer un bloc texte vide dans ta publi, ce qui créer un fichier text-1727070560202.txt et un fichier text-1727070560202.txt.meta.txt côté stockage dans `dodoc/spaces/mon-espace/projects/mon-project/publications/ma-publication/`

2. tu fermes dodoc

3. tu copies le nom du fichier text-1727070560202.txt, tu supprimes ce fichier

4. tu copie/colle le fichier d'archive que tu veux restaurer à l'emplacement du fichier ci-dessus (par exemple, 17310[…].txt) et tu le renommes en text-1727070560202.txt

5. tu rouvre dodoc, et il chargera le contenu sans soucis

Pour une version en ligne… je ne vois pas de solution à vrai dire… il faudrait pouvoir injecter le HTML, mais c'est n'est pas permis/possible. Je ne sais pas quoi te proposer là-dessus.

Merci pour la doc de ton raisonnement et tes tentatives ! Il faudrait effectivement mieux gérer le versioning, mais la contrainte du stockage dans des dossiers et fichiers ajoute une lourdeur importante qu'on aurait pas avec une base de donnée non-lisible en clair, mais optimisée pour ça.

**Comment by Spiderwan01** [comment]
Merci pour explication méthode plus interressante. A défaut que d'autres solutions soit possible, il nous faudrait formaliser et partager la méthode dans une future FAQ.
