### ISSUE TITLE
Indiquer le nombre de pages d'un document PDF dans collecter

### ISSUE THREAD

**Issue by louis-ev** [l-atelier-des-chercheurs/dodoc#978]
Pourrait remplacer l'indication PDF. Indiquer "3 pages" sur la tuile ?

**Comment by louis-ev** [comment]
@jubonhomme qu'en penses-tu ?
La dépendance qui fournit ça fait 33mo. Ça a du sens pour une fonctionnalité comme ça ?

**Comment by louis-ev** [comment]
(rectification, en fait ce paquet appelle pdf.js qui fournit cette info)

**Comment by jubonhomme** [comment]
je ne pense pas avoir bien compris la question...
On a déjà le nombre de page dans collecter 
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/c02ac089-2fb5-4e24-acc0-c46d19f623ee)

Par contre je viens de voir que les 2 boutons pour fermer le média ou replier le volet de droite se trouve au dessus des boutons du player de pdf.
Voir ici en vidéo
https://test11.dodoc.fr/+hello-test/test-11?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100,%22focus%22%3A%22video-1719672986387-z6p.webm.meta.txt%22%7D%5D

**Comment by louis-ev** [comment]
L'idée était de récupérer le nombre de page à l'importation pour afficher cette info sur la petite tuile à la place de "PDF" (un peu comme indiquer la durée d'une vidéo et pas l'indication "VIDÉO")

**Comment by jubonhomme** [comment]
L'indication "pdf" me suffit mais si tu trouves ça utile pourquoi pas.

**Comment by louis-ev** [comment]
Pas réussi à sortir l'info en passant par iframe.contentDocument dans la fenêtre d'aperçu d'un pdf (qui permet de générer une image d'aperçu), du coup je ferme et si la demande revient on rouvrira.
