### ISSUE TITLE
Affichage crayon média page à page 

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#982]
Un petit bug d'affichage avec une vidéo pour reproduire sur test11.dodoc.fr
dans cette publication

https://test11.dodoc.fr/+hello-test/test-11?projectpanes=%5B%7B%22type%22%3A%22collect%22,%22size%22%3A100,%22focus%22%3A%22video-1720037688854-qaw.webm.meta.txt%22%7D%5D

**Comment by louis-ev** [comment]
À tester
