### ISSUE TITLE
Ajouter un bouton pour récupérer simplement l'URL d'un média dans collecter

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#985]
Dans la V9 de dodoc on pouvait voir l'URL d'un média pour le partager directement en pleine page (standalone) ou le partager dans l'interface complète de dodoc (bouton glissière)

Depuis la V10, le partage se fait uniquement dans le volet Publier.
On peut récupérer l'URL d'un média en utilisant le lien du bouton Télécharger. 
Cette URL reste accessible à toutes personnes qui ont ce lien mais ce volet collecter reste accessible uniquement aux contributeurs. Mais c'est une fonction cachée et peu connue / utilisable

L'idée est donc d'avoir un nouveau bouton "Partager" dans Option (comme pour les publications)
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/4b79fdd5-60fd-403a-a125-3cb78e28b528)
Si on clique sur ce bouton partager on retrouverait la même fenêtre que le partage d'une publication
Avec en entête : 
Partager un lien vers ce média

![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/25c9c9a7-ee7c-41f7-aeb3-83b22c57bf64)

**Comment by louis-ev** [comment]
Yes !
Question : est-ce qu'on affiche la légende/les crédits si ils existent ? Ou on est vraiment sur le fichier brut ?

**Comment by louis-ev** [comment]
Autre question : que fait-on si le média appartient à un projet privé ? On l'affiche quand même, en partant du principe que si on a l'url, c'est qu'on nous l'a envoyé, ou on ne l'affiche pas car le contenu est privé ? Sauf erreur, nous avons statué que les publications dont le statut est "public" appartenant à un projet privé sont visibles à tous, avec l'url.

**Comment by jubonhomme** [comment]
Je dirais que oui.
C'est une démarche active de partager le lien ou un code QR.
Si le projet est privé il faut forcément être contributeur pour voir ce qu'il y a dedans et donc personne ne peut y accéder sans une action volontaire ni remonter le fil dans l'URL pour accéder au reste.
Par contre un lien d'une publication ou d'un média peut être partagé directement à partir d'une URL ou un code QR

**Comment by JeFabrique-MaterielPeda** [comment]
> brut ?

Les légendes et crédits c'est pas mal pour la lisibilité il me semble. Et en respect des droits

**Comment by jubonhomme** [comment]
oui je trouve aussi que ça reste discret avec simplement le picto i en bas du média et si on l'incruste dans une activité H5P ou autre on retrouve les données

**Comment by jubonhomme** [comment]
On a donc maintenant la possibilité de partager un lien direct vers un média à partir de "options"/"Partager"
![image](https://github.com/l-atelier-des-chercheurs/dodoc/assets/29262866/ea2df16d-8707-44b0-85fd-bfbce1488385)

Ce lien ou code QR permet d'afficher en pleine page dans un navigateur le média sans passer obligatoirement par une publication.
Ce lien permet de gérer correctement l'affichage dans le navigateur.

Mais ce lien n'est pas utilisable pour embarquer ce média dans d'autres applications externes comme H5P, uMap...

Pour ne pas charger les menus, on pourrait garder cette fenêtre dans Options / partager et afficher une nouvelle possibilité avec un bouton radio en plus : 
Lien pour intégrer ce média dans un outil externe H5P, uMap...

**Comment by louis-ev** [comment]
Ajouté !
