### ISSUE TITLE
Catégories et mots-clés suggérés

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#989]
Je ne trouve plus comme ajouter une catégorie de tags dans l'administration.

Soit ça a disparu soit c'est moi qui ne regarde pas au bon endroit

**Comment by louis-ev** [comment]
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/4656ba46-13e2-4941-af29-cc2090d621c6">

Ici ?

**Comment by jubonhomme** [comment]
Oui pardon je n'ai pas été très clair.
J'ai bien cette fenêtre mais je ne vois pas comment ajouter une nouvelle catégorie
![image](https://github.com/user-attachments/assets/b4641653-43b0-451d-928e-25e1731b6dec)

Et la suppression d'une catégorie existante ne fonctionne pas.
Quand je clique sur supprimer cette catégorie ça n'a pas d'effet même en relançant dodoc.

**Comment by louis-ev** [comment]
Eh bien on ne peut pas ajouter de catégories outre celles-ci, ce qui est (normalement)assez logique. On ne peut pas encore créer de catégories personnalisées. 
Bon clairement l'interface est pas géniale.

J'avais cassé la suppression des dossiers, c'est remis !

**Comment by jubonhomme** [comment]
ok
Je ne sais pas pourquoi j'ai imaginé qu'on pouvait créer des catégories... 
Je ferme donc cette issue ;)
