### ISSUE TITLE
L'export d'un récit en pdf coupe les images

### ISSUE THREAD

**Issue by gheleguen** [l-atelier-des-chercheurs/dodoc#990]
Bonjour, 
J'utilise dodoc. 10.0.13-dev sur la branche next-node. 
Lorsque je cherche à exporter un récit en pdf, j'obtiens un pdf ca c'est cool mais les images sont coupés. 
Voyez plutôt : 
![Capture d’écran du 2024-07-15 11-12-49](https://github.com/user-attachments/assets/ca6ed0fe-65df-437d-adea-d00b57ded990)

Merci pour votre travail dodoc est formidable ;-)
Guillaume

**Comment by louis-ev** [comment]
Il s'agit de quoi comme images ? Plusieurs répartis dans des mosaïques ? Possible de reproduire le soucis sur test10.dodoc.fR et d'indiquer ici l'emplacement de la publi ? Nettement plus simple pour reproduire le bug et le résoudre !

**Comment by gheleguen** [comment]
Yes pas de soucis, je peux faire ca. J'ai créer un compte sur le dodoc de test. Peux tu m'attribuer le droit de crer un espace et un projet ?

**Comment by gheleguen** [comment]
Hello,
Oui j'ai essayé de le reproduire sur dodoc test mais l'export pdf ne fonctionne pas. 
Ca me fait ca tu as raison uniquement sur les images quand elles sont cote a cote. Je n'ai encore jamais vue ca pour des images entières : 
![Capture d’écran du 2024-07-15 11-47-31](https://github.com/user-attachments/assets/59165784-e74e-4540-bc81-2c6b2fdc9f54)
Merci à toi

**Comment by louis-ev** [comment]
Résolu pour la v11 / sur next.
Les images, grilles d'image et carrousel ne seront plus coupés lors d'une nouvelle page : ils passeront à la page suivante.
