### ISSUE TITLE
bouton validation modification localisation

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#992]
J'ai cliqué plusieurs fois sur ce petit bouton bleu après avoir modifier la localisation avant de me rappeler que le bouton de validation est en bas ;)
Comme le bouton modifier est en haut à gauche, il est assez trompeur ce picto bleu avec une coche... qui est juste là pour inciter à cliquer et ça hop ça replie la fenêtre et on recommence la modif... jusqu'à ce qu'on voit le bouton enregistrer tout en bas.
C'est pas super important mais si on pouvait rapprocher dans un sens ou dans l'autre les boutons modifier et enregistrer je trouverais ça plus clair

![image](https://github.com/user-attachments/assets/31560e92-b563-46f1-a8c4-e0cea82ed496)

**Comment by louis-ev** [comment]
Je vois très bien, ça marche. À retester sur next. 
J'ai ajouté aussi un déplacement pour centre le point qu'on vient de cliquer – too much ? ça le fait partout maintenant, potentiellement utile pour bien avoir la fenêtre de création de médias par la carte bien visible / en entier.

**Comment by jubonhomme** [comment]
Très bien comme ça, pour la validation qui remonte bien visible et le centrage de la carte qui permet aussi un zoom plus facile.

Hop je ferme ici !
