### ISSUE TITLE
bug affichage ?

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#993]
J'ai mis à jour à l'instant et je vois un détourage ovale des différents ratio, bug d'affichage ou vrai détourage ovale ?
![image](https://github.com/user-attachments/assets/ee63e01a-be80-4415-b852-d2c85e366463)

**Comment by louis-ev** [comment]
Ça a toujours été comme ça ? C'est un petit soucis graphique, facile à résoudre :)
![image](https://github.com/user-attachments/assets/cbde90d3-2e6d-4cd9-ba12-dd5569f1685e)

**Comment by jubonhomme** [comment]
j'avais déjà vu ça à un endroit et tu avais corrigé il me semble... mais je ne m'en souviens plus bien

**Comment by louis-ev** [comment]
Corrigé. Plus simple et plus propre.

<img width="957" alt="image" src="https://github.com/user-attachments/assets/bea7c880-e3d9-4470-b9b3-80dcae68ce98">
