### ISSUE TITLE
Chevauchement boutons tableau / déplacement

### ISSUE THREAD

**Issue by jubonhomme** [l-atelier-des-chercheurs/dodoc#999]
Dans un récit on peut maintenant ajouter des tableaux.
Mais les boutons d'ajout/suppression de colonnes sont quelques fois masqués par le bouton (main) de déplacement.
Est-ce qu'il est possible d'éviter ce chevauchement pour toujours avoir accès aux +/- pour les colonnes ?

![image](https://github.com/user-attachments/assets/9be9280e-553b-4d87-9c33-194a22fb395c)

**Comment by louis-ev** [comment]
Ajout d'un petit espace (le carré légèrement rouge sous la main) qui permet de rajouter de la marge à droite des boutons.

<img width="352" alt="image" src="https://github.com/user-attachments/assets/e42d9842-0384-4bd0-b3d3-6aa1d9592256">
